### ISSUE TITLE
out参数导致接口混淆

### ISSUE THREAD

**Issue by tianye910208** [Tencent/xLua#100]
public static bool Raycast(Ray ray);
public static bool Raycast(Ray ray, out RaycastHit hitInfo);

在lua里调用 ret,hit = Raycast(ray) 无法区分两个函数
生成的导出代码里出现了相同的判定条件

                if(__gen_param_count == 1&& translator.Assignable<UnityEngine.Ray>(L, 1)) 
                {
                    UnityEngine.Ray ray;translator.Get(L, 1, out ray);
                    
                        bool __cl_gen_ret = UnityEngine.Physics.Raycast( ray );
                        LuaAPI.lua_pushboolean(L, __cl_gen_ret);
                    
                    
                    
                    return 1;
                }

                if(__gen_param_count == 1&& translator.Assignable<UnityEngine.Ray>(L, 1)) 
                {
                    UnityEngine.Ray ray;translator.Get(L, 1, out ray);
                    UnityEngine.RaycastHit hitInfo;
                    
                        bool __cl_gen_ret = UnityEngine.Physics.Raycast( ray, out hitInfo );
                        LuaAPI.lua_pushboolean(L, __cl_gen_ret);
                    translator.Push(L, hitInfo);
                        
                    
                    
                    
                    return 2;
                }

**Comment by chexiongsheng** [comment]
类型丰富程度不一样，重载无论如何都完善不了，应付了out还有别的，比如lua只有一种数字类型，当c#那通过int和short来区分重载的时候，要怎么判断呢？
发生这种情况，建议通过自行封装来解决，静态函数的直接封装个另外名字的，如果是成员方法则通过Extension method来封装。

**Comment by tianye910208** [comment]
xlua在导出的时候应该对这种情况提示一下，至少不要生成无用代码

**Comment by tianye910208** [comment]
另外提一下，在调用的时候out是否可以用type类型占位，而不要直接省略掉？

**Comment by chexiongsheng** [comment]
嗯，无用代码和提示确实值得斟酌。

**Comment by chexiongsheng** [comment]
我个人觉得这情况反生的概率并不高，发生了让写代码的自行封装并没有太大的困扰。
而为一个无论如何都无法完善的特性增加系统复杂度并不值得。这复杂度除了实现本身之外，对于使用者的要理解的内容也变多了。
提示是可以考虑的，不过按经验往往也会被忽略。
