### ISSUE TITLE
plugin.js:74 missing function: luaopen_rapidjson

### ISSUE THREAD

**Issue by LazyPlanet** [Tencent/xLua#1001]
Xlua 用了rapidjson 导出webgl后出现找不到？请问是不是需要重新编个库，这个库要用xlua哪个平台下的？谢谢。

missing function: luaopen_rapidjson(env: Windows,mg,1.05.2204264; lib: 2.24.6)
printErr @ plugin.js:74
_luaopen_rapidjson @ webgl.wasm.framework.unityweb.js:2
(anonymous) @ 090865fa:0x1762eba
dynCall_iii @ 090865fa:0x1fe27a0
(anonymous) @ webgl.wasm.framework.unityweb.js:2
invoke_iii @ webgl.wasm.framework.unityweb.js:2
(anonymous) @ 090865fa:0x1762e89
(anonymous) @ 090865fa:0x1fc82af
(anonymous) @ 090865fa:0x1f79754
(anonymous) @ 090865fa:0x1fbf1b9
(anonymous) @ 090865fa:0x1f79754
(anonymous) @ 090865fa:0x1f7c9db
(anonymous) @ 090865fa:0x1fbf1c2
(anonymous) @ 090865fa:0x1f79754
(anonymous) @ 090865fa:0x1f7c9db
(anonymous) @ 090865fa:0x1fbf1c2
(anonymous) @ 090865fa:0x1f79754
(anonymous) @ 090865fa:0x1f7c9db
(anonymous) @ 090865fa:0x1fbf1c2
(anonymous) @ 090865fa:0x1f79754
(anonymous) @ 090865fa:0x1f7c9db
(anonymous) @ 090865fa:0x1fbf1c2
(anonymous) @ 090865fa:0x1f79754
(anonymous) @ 090865fa:0x1f7c9db
(anonymous) @ 090865fa:0x1f88db9
dynCall_vii @ 090865fa:0x1fe2d52
(anonymous) @ webgl.wasm.framework.unityweb.js:2
invoke_vii @ webgl.wasm.framework.unityweb.js:2
(anonymous) @ 090865fa:0x1f83f99
(anonymous) @ 090865fa:0x1fc1f77
(anonymous) @ 090865fa:0x176332a
(anonymous) @ 090865fa:0x1765134
(anonymous) @ 090865fa:0x17650b9
(anonymous) @ 090865fa:0x16c21d0
(anonymous) @ 090865fa:0x16c1f21
(anonymous) @ 090865fa:0x1642f8c
(anonymous) @ 090865fa:0x15d5539
dynCall_iiii @ 090865fa:0x1fe2825
(anonymous) @ webgl.wasm.framework.unityweb.js:2
invoke_iiii @ webgl.wasm.framework.unityweb.js:2
(anonymous) @ 090865fa:0x15d5271
(anonymous) @ 090865fa:0x15b2318
(anonymous) @ 090865fa:0x2ceec1
(anonymous) @ 090865fa:0x2ceb91
(anonymous) @ 090865fa:0x505ce2
(anonymous) @ 090865fa:0x505bc6
(anonymous) @ 090865fa:0x5084f6
(anonymous) @ 090865fa:0x507439
(anonymous) @ 090865fa:0x3fa869
(anonymous) @ 090865fa:0x506e7d
(anonymous) @ 090865fa:0x2eea7d
(anonymous) @ 090865fa:0x2ee978
(anonymous) @ 090865fa:0x4ac2e6
(anonymous) @ 090865fa:0x4aaa69
(anonymous) @ 090865fa:0x4aae24
(anonymous) @ 090865fa:0x4aa33e
(anonymous) @ 090865fa:0x522947
(anonymous) @ 090865fa:0x52253c
(anonymous) @ 090865fa:0x5223ca
(anonymous) @ 090865fa:0x521c9d
(anonymous) @ 090865fa:0x5213ca
(anonymous) @ 090865fa:0x50fd82
_main @ 090865fa:0x50f850
(anonymous) @ webgl.wasm.framework.unityweb.js:2
callMain @ webgl.wasm.framework.unityweb.js:2
doRun @ webgl.wasm.framework.unityweb.js:2
run @ webgl.wasm.framework.unityweb.js:2
runCaller @ webgl.wasm.framework.unityweb.js:2
removeRunDependency @ webgl.wasm.framework.unityweb.js:2
value @ plugin.js:74
(anonymous) @ plugin.js:74
L @ plugin.js:71
(anonymous) @ plugin.js:71
t.<computed> @ plugin.js:71
o @ plugin.js:74
(anonymous) @ VM35 WAGameSubContext.js:2
n @ VM35 WAGameSubContext.js:2
Promise.then (async)
a @ VM35 WAGameSubContext.js:2
e.exports @ VM35 WAGameSubContext.js:2
re @ VM35 WAGameSubContext.js:2
then @ VM35 WAGameSubContext.js:2
u @ plugin.js:74
(anonymous) @ plugin.js:74
$ @ VM35 WAGameSubContext.js:2
Ln @ plugin.js:74
i.startCompileAnimation @ plugin.js:74
(anonymous) @ plugin.js:74
L @ plugin.js:71
(anonymous) @ plugin.js:71
t.<computed> @ plugin.js:71
(anonymous) @ plugin.js:74
$ @ VM35 WAGameSubContext.js:2
Fn @ plugin.js:74
value @ plugin.js:74
(anonymous) @ plugin.js:74
f @ VM35 WAGameSubContext.js:2
(anonymous) @ VM35 WAGameSubContext.js:2
(anonymous) @ VM35 WAGameSubContext.js:2
(anonymous) @ VM35 WAGameSubContext.js:2
setTimeout (async)
(anonymous) @ VM35 WAGameSubContext.js:2
globalThis.setTimeout @ VM35 WAGameSubContext.js:2
(anonymous) @ plugin.js:74
(anonymous) @ VM35 WAGameSubContext.js:2
n @ VM35 WAGameSubContext.js:2
Promise.then (async)
a @ VM35 WAGameSubContext.js:2
e.exports @ VM35 WAGameSubContext.js:2
re @ VM35 WAGameSubContext.js:2
ue @ VM35 WAGameSubContext.js:2
(anonymous) @ VM35 WAGameSubContext.js:2
success @ plugin.js:74
t @ VM34 WAGameSubContext.js:2
t.length.u.<computed> @ VM15 WAGame.js:2
u @ VM15 WAGame.js:2
(anonymous) @ VM15 WAGame.js:2
a @ VM15 WAGame.js:2
(anonymous) @ VM15 WAGame.js:2
qi @ VM15 WAGame.js:2
(anonymous) @ VM15 WAGame.js:2
(anonymous) @ VM12 asdebug.js:1
C @ VM12 asdebug.js:1
(anonymous) @ VM12 asdebug.js:1
g @ VM12 asdebug.js:1
f @ VM12 asdebug.js:1
(anonymous) @ VM12 asdebug.js:1
_ws.onmessage @ VM12 asdebug.js:1
Show 47 more frames
plugin.js:74 -1
plugin.js:74 -1(env: Windows,mg,1.05.2204264; lib: 2.24.6)
printErr @ plugin.js:74
abort @ webgl.wasm.framework.unityweb.js:2
_luaopen_rapidjson @ webgl.wasm.framework.unityweb.js:2
(anonymous) @ 090865fa:0x1762eba
dynCall_iii @ 090865fa:0x1fe27a0
(anonymous) @ webgl.wasm.framework.unityweb.js:2
invoke_iii @ webgl.wasm.framework.unityweb.js:2
(anonymous) @ 090865fa:0x1762e89
(anonymous) @ 090865fa:0x1fc82af
(anonymous) @ 090865fa:0x1f79754
(anonymous) @ 090865fa:0x1fbf1b9
(anonymous) @ 090865fa:0x1f79754
(anonymous) @ 090865fa:0x1f7c9db
(anonymous) @ 090865fa:0x1fbf1c2
(anonymous) @ 090865fa:0x1f79754
(anonymous) @ 090865fa:0x1f7c9db
(anonymous) @ 090865fa:0x1fbf1c2
(anonymous) @ 090865fa:0x1f79754
(anonymous) @ 090865fa:0x1f7c9db
(anonymous) @ 090865fa:0x1fbf1c2
(anonymous) @ 090865fa:0x1f79754
(anonymous) @ 090865fa:0x1f7c9db
(anonymous) @ 090865fa:0x1fbf1c2
(anonymous) @ 090865fa:0x1f79754
(anonymous) @ 090865fa:0x1f7c9db
(anonymous) @ 090865fa:0x1f88db9
dynCall_vii @ 090865fa:0x1fe2d52
(anonymous) @ webgl.wasm.framework.unityweb.js:2
invoke_vii @ webgl.wasm.framework.unityweb.js:2
(anonymous) @ 090865fa:0x1f83f99
(anonymous) @ 090865fa:0x1fc1f77
(anonymous) @ 090865fa:0x176332a
(anonymous) @ 090865fa:0x1765134
(anonymous) @ 090865fa:0x17650b9
(anonymous) @ 090865fa:0x16c21d0
(anonymous) @ 090865fa:0x16c1f21
(anonymous) @ 090865fa:0x1642f8c
(anonymous) @ 090865fa:0x15d5539
dynCall_iiii @ 090865fa:0x1fe2825
(anonymous) @ webgl.wasm.framework.unityweb.js:2
invoke_iiii @ webgl.wasm.framework.unityweb.js:2
(anonymous) @ 090865fa:0x15d5271
(anonymous) @ 090865fa:0x15b2318
(anonymous) @ 090865fa:0x2ceec1
(anonymous) @ 090865fa:0x2ceb91
(anonymous) @ 090865fa:0x505ce2
(anonymous) @ 090865fa:0x505bc6
(anonymous) @ 090865fa:0x5084f6
(anonymous) @ 090865fa:0x507439
(anonymous) @ 090865fa:0x3fa869
(anonymous) @ 090865fa:0x506e7d
(anonymous) @ 090865fa:0x2eea7d
(anonymous) @ 090865fa:0x2ee978
(anonymous) @ 090865fa:0x4ac2e6
(anonymous) @ 090865fa:0x4aaa69
(anonymous) @ 090865fa:0x4aae24
(anonymous) @ 090865fa:0x4aa33e
(anonymous) @ 090865fa:0x522947
(anonymous) @ 090865fa:0x52253c
(anonymous) @ 090865fa:0x5223ca
(anonymous) @ 090865fa:0x521c9d
(anonymous) @ 090865fa:0x5213ca
(anonymous) @ 090865fa:0x50fd82
_main @ 090865fa:0x50f850
(anonymous) @ webgl.wasm.framework.unityweb.js:2
callMain @ webgl.wasm.framework.unityweb.js:2
doRun @ webgl.wasm.framework.unityweb.js:2
run @ webgl.wasm.framework.unityweb.js:2
runCaller @ webgl.wasm.framework.unityweb.js:2
removeRunDependency @ webgl.wasm.framework.unityweb.js:2
value @ plugin.js:74
(anonymous) @ plugin.js:74
L @ plugin.js:71
(anonymous) @ plugin.js:71
t.<computed> @ plugin.js:71
o @ plugin.js:74
(anonymous) @ VM35 WAGameSubContext.js:2
n @ VM35 WAGameSubContext.js:2
Promise.then (async)
a @ VM35 WAGameSubContext.js:2
e.exports @ VM35 WAGameSubContext.js:2
re @ VM35 WAGameSubContext.js:2
then @ VM35 WAGameSubContext.js:2
u @ plugin.js:74
(anonymous) @ plugin.js:74
$ @ VM35 WAGameSubContext.js:2
Ln @ plugin.js:74
i.startCompileAnimation @ plugin.js:74
(anonymous) @ plugin.js:74
L @ plugin.js:71
(anonymous) @ plugin.js:71
t.<computed> @ plugin.js:71
(anonymous) @ plugin.js:74
$ @ VM35 WAGameSubContext.js:2
Fn @ plugin.js:74
value @ plugin.js:74
(anonymous) @ plugin.js:74
f @ VM35 WAGameSubContext.js:2
(anonymous) @ VM35 WAGameSubContext.js:2
(anonymous) @ VM35 WAGameSubContext.js:2
(anonymous) @ VM35 WAGameSubContext.js:2
setTimeout (async)
(anonymous) @ VM35 WAGameSubContext.js:2
globalThis.setTimeout @ VM35 WAGameSubContext.js:2
(anonymous) @ plugin.js:74
(anonymous) @ VM35 WAGameSubContext.js:2
n @ VM35 WAGameSubContext.js:2
Promise.then (async)
a @ VM35 WAGameSubContext.js:2
e.exports @ VM35 WAGameSubContext.js:2
re @ VM35 WAGameSubContext.js:2
ue @ VM35 WAGameSubContext.js:2
(anonymous) @ VM35 WAGameSubContext.js:2
success @ plugin.js:74
t @ VM34 WAGameSubContext.js:2
t.length.u.<computed> @ VM15 WAGame.js:2
u @ VM15 WAGame.js:2
(anonymous) @ VM15 WAGame.js:2
a @ VM15 WAGame.js:2
(anonymous) @ VM15 WAGame.js:2
qi @ VM15 WAGame.js:2
(anonymous) @ VM15 WAGame.js:2
(anonymous) @ VM12 asdebug.js:1
C @ VM12 asdebug.js:1
(anonymous) @ VM12 asdebug.js:1
g @ VM12 asdebug.js:1
f @ VM12 asdebug.js:1
(anonymous) @ VM12 asdebug.js:1
_ws.onmessage @ VM12 asdebug.js:1
Show 48 more frames
plugin.js:74 exception thrown: Error: WXUncaughtException,Error: WXUncaughtException
    at currentStackTrace (http://127.0.0.1:40582/game/unity-sdk/util.js:66:17)
    at Object.WXUncaughtException (http://127.0.0.1:40582/game/unity-sdk/util.js:70:15)
    at abort (http://127.0.0.1:40582/game/webgl.wasm.framework.unityweb.js:2:740)
    at _luaopen_rapidjson (http://127.0.0.1:40582/game/webgl.wasm.framework.unityweb.js:2:376552)
    at <anonymous>:wasm-function[72787]:0x1762eba
    at dynCall_iii (<anonymous>:wasm-function[110357]:0x1fe27a0)
    at Object.dynCall_iii

**Comment by chexiongsheng** [comment]
要把rapidjson相关代码放到WebGLPlugins目录
rapidjson代码可以在这里找到：
https://github.com/chexiongsheng/build_xlua_with_libs

**Comment by LazyPlanet** [comment]
你好，感谢回复。
我要使用哪个库进行编译呢？我没看见[make_win64_lua53.bat] 类似这样的脚本，比如 make_webgl_lua53.bat的脚本哈？安卓和PC平台都知道怎么编，webgl用哪个呢？谢谢大佬。

**Comment by LazyPlanet** [comment]
@chexiongsheng

**Comment by ubanck** [comment]
@LazyPlanet 大佬，我想知道你那个编译要求ANDROID_TOOLCHAIN_NAME的 问题，还出现了没有

**Comment by ubanck** [comment]
@LazyPlanet 
尴尬，我也是发现，全换成高版本就完事儿了

**Comment by chengyimingvb** [comment]
> 要把rapidjson相关代码放到WebGLPlugins目录 rapidjson代码可以在这里找到： https://github.com/chexiongsheng/build_xlua_with_libs

大佬，编译WebGL后，报错：missing function: luaopen_pb 咋整，拉取了你的项目也会报这个错误

**Comment by wuhang326** [comment]
> > 要把rapidjson相关代码放到WebGLPlugins目录 rapidjson代码可以在这里找到： https://github.com/chexiongsheng/build_xlua_with_libs
> 
> 大佬，编译WebGL后，报错：missing function: luaopen_pb 咋整，拉取了你的项目也会报这个错误

请问下 你这个问题解决了吗  我一样的问题 missing function: luaopen_sproto_core
