### ISSUE TITLE
List <> return error

### ISSUE THREAD

**Issue by leechen2020** [Tencent/xLua#101]
![array](https://cloud.githubusercontent.com/assets/8110601/22873205/ce05c8d2-f201-11e6-89d7-e307e4380b93.png)

![array01](https://cloud.githubusercontent.com/assets/8110601/22873207/d357100c-f201-11e6-8b02-97a28aa42ab6.png)

![error](https://cloud.githubusercontent.com/assets/8110601/22873210/d4ef76e8-f201-11e6-8d12-5c2bb1c3ffa6.png)

LuaException: error loading module Main from CustomLoader, Main:4: syntax error near 't'
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	[string "chunk"]:1: in main chunk
XLua.LuaEnv.ThrowExceptionFromError (Int32 oldTop) (at Assets/Packages/XLua/Src/LuaEnv.cs:366)

**Comment by chexiongsheng** [comment]
“syntax error”，语法错误啊
你那local写错了，凡事提示语法错误，自己解决啊，你这几行代码帮你看下问题不大，要多了没法看。

**Comment by leechen2020** [comment]
sorry My miss!!

**Comment by leechen2020** [comment]
another problem!!
![error2](https://cloud.githubusercontent.com/assets/8110601/22873424/683f1fc4-f203-11e6-8d0e-68a494ff9e09.png)

**Comment by chexiongsheng** [comment]
提示不是很明确了没？下标越界，C#的数组下标从0开始。

**Comment by leechen2020** [comment]
谢谢。

**Comment by Phantomphyre** [comment]
#81
