### ISSUE TITLE
最新release版xluajit运行demo 调用到lua_newstate这里就崩溃了，不用jit版本的没事

### ISSUE THREAD

**Issue by wangpengzhao** [Tencent/xLua#1011]
崩溃日志：
Obtained 28 stack frames
0x00007ffd94e32f27 (xlua) lua_newstate
0x00007ffd94e27c60 (xlua) luaL_newstate
0x00000272f1bfed3e (Mono JIT Code) (wrapper managed-to-native) XLua.LuaDLL.Lua:luaL_newstate ()
0x00000272f1c6cea3 (Mono JIT Code) [LuaEnv.cs:81] XLua.LuaEnv:.ctor () 
0x00000272f1c6c69b (Mono JIT Code) [Helloworld.cs:19] XLuaTest.Helloworld:Start () 
0x00000272e2267648 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
0x00007ffd76ca02f4 (mono-2.0-bdwgc) [mini-runtime.c:3445] mono_jit_runtime_invoke 
0x00007ffd76bdeb34 (mono-2.0-bdwgc) [object.c:3066] do_runtime_invoke 
0x00007ffd76bdeccc (mono-2.0-bdwgc) [object.c:3113] mono_runtime_invoke 
0x00007ff70ae7b8c4 (Unity) scripting_method_invoke
0x00007ff70ae763c4 (Unity) ScriptingInvocation::Invoke
0x00007ff70ae4a6cd (Unity) MonoBehaviour::InvokeMethodOrCoroutineChecked
0x00007ff70ae4a7fb (Unity) MonoBehaviour::InvokeMethodOrCoroutineChecked
0x00007ff70ae44d62 (Unity) MonoBehaviour::DelayedStartCall
0x00007ff70a928264 (Unity) DelayedCallManager::Update
0x00007ff70ab3d259 (Unity) `InitPlayerLoopCallbacks'::`2'::EarlyUpdateScriptRunDelayedStartupFrameRegistrator::Forward
0x00007ff70ab24dfc (Unity) ExecutePlayerLoop
0x00007ff70ab24ed3 (Unity) ExecutePlayerLoop
0x00007ff70ab2ac90 (Unity) PlayerLoop
0x00007ff70baa3dbf (Unity) PlayerLoopController::UpdateScene
0x00007ff70ba8f079 (Unity) PlayerLoopController::EnterPlayMode
0x00007ff70ba9eb7a (Unity) PlayerLoopController::SetIsPlaying
0x00007ff70baa2250 (Unity) Application::TickTimer
0x00007ff70bf06faa (Unity) MainMessageLoop
0x00007ff70bf0bdb4 (Unity) WinMain
0x00007ff70d262bee (Unity) __scrt_common_main_seh
0x00007ffdf1f27034 (KERNEL32) BaseThreadInitThunk
0x00007ffdf2442651 (ntdll) RtlUserThreadStart

运行demo里的helloworld就崩溃，请问这个是什么原因怎么解决

**Comment by myyunsong** [comment]
我也需要相同的问题，请问怎样解决?
