### ISSUE TITLE
Unity2022.1打包WebGL失败

### ISSUE THREAD

**Issue by chaoslife** [Tencent/xLua#1015]
原来项目是19.4上是正常的，转到22上出WebGL包，出现以下错误 ：

`
Building Library\Bee\artifacts\WebGL\GameAssembly\master_WebGL_wasm\e4yq_xlua_webgl.o failed with output:
In file included from Assets/com.onesight.xframework/Assets/Lua/Plugins/WebGL/xlua_webgl.cpp:31:
C:\Chaos\SVN\Test\TF\Framework\Assets\com.onesight.xframework\Assets\Lua\WebGLPlugins\lundump.c:237:33: warning: adding 'int' to a string does not append to the string [-Wstring-plus-int]
  checkliteral(S, LUA_SIGNATURE + 1, "not a");  /* 1st char already checked */
                  ~~~~~~~~~~~~~~^~~
C:\Chaos\SVN\Test\TF\Framework\Assets\com.onesight.xframework\Assets\Lua\WebGLPlugins\lundump.c:237:33: note: use array indexing to silence this warning
  checkliteral(S, LUA_SIGNATURE + 1, "not a");  /* 1st char already checked */
                                ^
                  &             [  ]
In file included from Assets/com.onesight.xframework/Assets/Lua/Plugins/WebGL/xlua_webgl.cpp:35:
C:\Chaos\SVN\Test\TF\Framework\Assets\com.onesight.xframework\Assets\Lua\WebGLPlugins\i64lib.c:409:34: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
        snprintf(temp, sizeof(temp), "%"PRIu64, n);
                                        ^
                                         
1 warning and 1 error generated.
emcc2: error: '"C:/Program Files/Unity/Hub/Editor/2022.1.19f1c1/Editor/Data/PlaybackEngines/WebGLSupport/BuildTools/Emscripten/llvm\clang++.exe" -target wasm32-unknown-emscripten -DEMSCRIPTEN -fno-inline-functions -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -D__EMSCRIPTEN_major__=2 -D__EMSCRIPTEN_minor__=0 -D__EMSCRIPTEN_tiny__=19 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-function-declaration -Xclang -iwithsysroot/include/SDL "--sysroot=C:\Program Files\Unity\Hub\Editor\2022.1.19f1c1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\cache\sysroot" -Xclang -iwithsysroot/include\compat -D__webgl__ -Wno-c++11-extensions -Wno-nonportable-include-path -ffunction-sections -fno-unwind-tables -fomit-frame-pointer -fno-threadsafe-statics -std=c++11 -Wno-#warnings -Wswitch -Wno-trigraphs -Wno-tautological-compare -Wno-invalid-offsetof -Wno-implicitly-unsigned-literal -Wno-integer-overflow -Wno-shift-negative-value -Wno-unknown-attributes -Wno-implicit-function-declaration -Wno-null-conversion -Wno-missing-declarations -Wno-unused-value -Wno-pragma-once-outside-header -fvisibility=hidden -fexceptions -fno-rtti -fno-strict-overflow -ffunction-sections -fdata-sections -fmessage-length=0 -pipe -DBASELIB_INLINE_NAMESPACE=il2cpp_baselib -DIL2CPP_MONO_DEBUGGER_DISABLED -DRUNTIME_IL2CPP -DHAVE_BDWGC_GC -DUNITY_WEBGL=1 -DNDEBUG -I. -IC:/Chaos/SVN/Test/TF/Framework/Library/Bee/artifacts/WebGL/il2cppOutput/cpp "-IC:/Program Files/Unity/Hub/Editor/2022.1.19f1c1/Editor/Data/il2cpp/libil2cpp/pch" "-IC:/Program Files/Unity/Hub/Editor/2022.1.19f1c1/Editor/Data/il2cpp/libil2cpp" "-IC:/Program Files/Unity/Hub/Editor/2022.1.19f1c1/Editor/Data/il2cpp/external/baselib/Include" "-IC:/Program Files/Unity/Hub/Editor/2022.1.19f1c1/Editor/Data/il2cpp/external/baselib/Platforms/WebGL/Include" -Oz -fcolor-diagnostics -fdiagnostics-absolute-paths -UGC_THREADS -UUSE_MMAP -UUSE_MUNMAP -c -xc++ Assets/com.onesight.xframework/Assets/Lua/Plugins/WebGL/xlua_webgl.cpp -o Library/Bee/artifacts/WebGL/GameAssembly/master_WebGL_wasm/e4yq_xlua_webgl.o' failed (1)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

`

请问这个应该怎么解决

**Comment by FirstAutoMain** [comment]
error: invalid suffix on literal; C++11 requires a space between literal and identifier
在中间加个空格试试
409行	
snprintf(temp, sizeof(temp), "%"PRIu64, n);
snprintf(temp, sizeof(temp), "%" PRIu64, n);

**Comment by chaoslife** [comment]
> error: invalid suffix on literal; C++11 requires a space between literal and identifier 在中间加个空格试试 409行 snprintf(temp, sizeof(temp), "%"PRIu64, n); snprintf(temp, sizeof(temp), "%" PRIu64, n);

嗯嗯，加了这个错没了，又出来新的错了

Building Library\Bee\artifacts\WebGL\build\debug_WebGL_wasm\build.js failed with output:
wasm-ld: error: duplicate symbol: main
>>> defined in C:\\Users\\Chaos\\AppData\\Local\\Temp\\tmpy9pl4z7sGameAssembly.a(yw7e_luac.o)
>>> defined in C:\\Users\\Chaos\\AppData\\Local\\Temp\\tmp_h04c9_qWebGLSupport_CoreModule_Dynamic.a(PlatformDependent_WebGL_Source_2_6xdlo.o)

这个同名main怎么解决呢

**Comment by FirstAutoMain** [comment]
> 

改名或删除呗

**Comment by chaoslife** [comment]
> > 
> 
> 改名或删除呗

![image](https://user-images.githubusercontent.com/2386021/199930450-e301fdaa-0d04-4ae0-be7b-577c18820e54.png)

改luac.c的mani这工程量有点大了吧

**Comment by chaoslife** [comment]
另一个main是 Unity.CoreModule里的

**Comment by FirstAutoMain** [comment]
> 另一个main是 Unity.CoreModule里的

看一下报错的上下文，可能与平台有关

**Comment by chaoslife** [comment]
> > 另一个main是 Unity.CoreModule里的
> 
> 看一下报错的上下文，可能与平台有关

Building Library\Bee\artifacts\WebGL\build\debug_WebGL_wasm\build.js failed with output:
wasm-ld: error: duplicate symbol: main
>>> defined in C:\\Users\\Chaos\\AppData\\Local\\Temp\\tmp2f2gajo9GameAssembly.a(yw7e_luac.o)
>>> defined in C:\\Users\\Chaos\\AppData\\Local\\Temp\\tmp4453qfapWebGLSupport_CoreModule_Dynamic.a(PlatformDependent_WebGL_Source_2_6xdlo.o)
emcc2: error: '"C:/Program Files/Unity/Hub/Editor/2022.1.20f1c1/Editor/Data/PlaybackEngines/WebGLSupport/BuildTools/Emscripten/llvm\wasm-ld.exe" @C:\Users\Chaos\AppData\Local\Temp\emscripten__hg852ex.rsp.utf-8' failed (1)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

这是所有的LOG了

**Comment by FirstAutoMain** [comment]
> 

你是不是把lua的源码拽到工程里了

**Comment by chaoslife** [comment]
> 

原来 我是把WebGLPlugins文件夹放在PackageManager的一个包中的，在2019.4是没有问题的，能正常出包

现在我把WebGLPlugins文件夹移出去了，再打包报了其它问题了


Building Library\Bee\artifacts\WebGL\build\debug_WebGL_wasm\build.js failed with output:
Traceback (most recent call last):
  File "C:\Program Files\Unity\Hub\Editor\2022.1.20f1c1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\emcc2.py", line 3571, in <module>
    sys.exit(main(sys.argv))
  File "C:\Program Files\Unity\Hub\Editor\2022.1.20f1c1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\emcc2.py", line 3564, in main
    ret = run(args)
  File "C:\Program Files\Unity\Hub\Editor\2022.1.20f1c1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\emcc2.py", line 1082, in run
    phase_post_link(options, wasm_target, wasm_target, target)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\contextlib.py", line 74, in inner
  File "C:\Program Files\Unity\Hub\Editor\2022.1.20f1c1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\emcc2.py", line 2400, in phase_post_link
    phase_emscript(options, in_wasm, wasm_target, memfile)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\contextlib.py", line 74, in inner
  File "C:\Program Files\Unity\Hub\Editor\2022.1.20f1c1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\emcc2.py", line 2428, in phase_emscript
    emscripten.run(in_wasm, wasm_target, final_js, memfile)
  File "C:\Program Files\Unity\Hub\Editor\2022.1.20f1c1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\emscripten.py", line 830, in run
    emscript(in_wasm, out_wasm, outfile_js, memfile, shared.DEBUG)
  File "C:\Program Files\Unity\Hub\Editor\2022.1.20f1c1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\emscripten.py", line 308, in emscript
    glue, forwarded_data = compile_settings()
  File "C:\Program Files\Unity\Hub\Editor\2022.1.20f1c1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\emscripten.py", line 178, in compile_settings
    cwd=path_from_root('src'), env=env)
  File "C:\Program Files\Unity\Hub\Editor\2022.1.20f1c1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\tools\shared.py", line 216, in run_js_tool
    return check_call(command, *args, **kw).stdout
  File "C:\Program Files\Unity\Hub\Editor\2022.1.20f1c1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\tools\shared.py", line 202, in check_call
    return run_process(cmd, *args, **kw)
  File "C:\Program Files\Unity\Hub\Editor\2022.1.20f1c1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emscripten\tools\shared.py", line 97, in run_process
    ret = subprocess.run(cmd, check=check, input=input, *args, **kw)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 474, in run
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 926, in communicate
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 54661: illegal multibyte sequence
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by FirstAutoMain** [comment]
> 

你这报错是编码错误啊，和放哪没关系吧

**Comment by MemoChen** [comment]
> 

请问解决了吗， 我也遇到这个问题，就很奇怪，搜了很多方式都解决不了

**Comment by Gaobobo-C** [comment]
找到WebGLPlugins/lundump.c 第237行，代码代码改成下面这样就可以了
checkliteral(S, &LUA_SIGNATURE[1], "not a");

报错提示是由于在 "LUA_SIGNATURE + 1" 这一表达式中进行了字符指针和整数的相加操作，这样的操作可能会导致错误，因为这不是合法的操作。这个警告意味着编译器认为您可能意图执行一个不确定的操作。解决这个问题的方法是，您可能需要明确地将 LUA_SIGNATURE 的指针与整数进行相加，然后传递给 checkliteral 函数。这可以通过使用数组索引来实现。
