### ISSUE TITLE
rapidjson 数组转成string为{}

### ISSUE THREAD

**Issue by LazyPlanet** [Tencent/xLua#1017]
![微信图片_20221028174755](https://user-images.githubusercontent.com/15156350/198570369-76e367a9-f581-4add-a8fe-7774ad2f5232.png)
大佬好，我现在在xlua里面repuList转成json的时候变成了：
"repuList":{}
是不是这个大小有限制呢？也不是必现，偶尔就不行了。

**Comment by chexiongsheng** [comment]
官版xLua不包含rapidjson。
即使个人这个repo：https://github.com/chexiongsheng/build_xlua_with_libs , 也仅仅提供的是这几个库的集成，这几个库的用法和维护请联系相应维护的组织/个人。

**Comment by LazyPlanet** [comment]
好的，抱歉。
里面不能有metatalbe，有这个就无法转换了。
