### ISSUE TITLE
Generate Code 报错问题

### ISSUE THREAD

**Issue by shishu123cn** [Tencent/xLua#102]
can not find delegate for BossHomePanel.GetBossInfo! try re-genertate code.

指向的那段代码是这样的 `private List<BossInfo> GetBossInfo(int pageType)`

**Comment by chexiongsheng** [comment]
重新执行下Generate Code也不行么？
另外，是哪个版本呢？master？

**Comment by shishu123cn** [comment]
嗯，Clear 了后 重新执行下也不行，用的是老版本还没更新过，我一会更新下试试

**Comment by shishu123cn** [comment]
嗯，更新到最新的版本后就可以了，还有我看了下日志，那个新加的HOTFIX_SYMBOLS_DISABLE这个宏是干嘛的。文档里面有说明吧。

**Comment by chexiongsheng** [comment]
有说明，如果你一切正常，不用关注这宏

**Comment by shishu123cn** [comment]
哦，好的，谢了
