### ISSUE TITLE
Unity2021.3生成Screen.MoveMainWindowTo方法报错。黑名单无效

### ISSUE THREAD

**Issue by hbpp** [Tencent/xLua#1028]
在Unity2021.3.x版本中生成Wrap时，会报错
`Assets\ClientCode\ThirdParty\XLua\Gen\UnityEngineScreenWrap.cs(214,103): error CS1615: Argument 1 may not be passed with the 'ref' keyword`
![image](https://user-images.githubusercontent.com/1718996/211480078-3a45f1b7-d16d-4fb5-ac24-d6ba64261da3.png)
![image](https://user-images.githubusercontent.com/1718996/211480145-3730872c-0ca2-462d-8fd5-ae6143538c57.png)

黑名加入了该方法，但还是会生成
`public static class BlackListConfig
{
    //黑名单
    [XLua.BlackList]
    public static List<List<string>> BlackList = new List<List<string>>()  {
                new List<string>(){"UnityEngine.Screen", "MoveMainWindowTo"},
            };`

**Comment by LazyPlanet** [comment]
大佬，怎么解决的？

**Comment by hbpp** [comment]
> 

new List<string>(){ "UnityEngine.Screen", "MoveMainWindowTo", "UnityEngine.DisplayInfo&", "UnityEngine.Vector2Int" },

**Comment by hbpp** [comment]
> 大佬，怎么解决的？

在blacklist里加入

**Comment by LazyPlanet** [comment]
UnityEngine.DisplayInfo&
应用竟然是这么写的，学习了，谢谢大佬。

**Comment by TDIT-haha** [comment]
那如果是out _DisplayInfo,在blacklist中该怎么写呢？
