### ISSUE TITLE
请问 黑名单如何过滤重载的构造函数？

### ISSUE THREAD

**Issue by git-SteamedBun** [Tencent/xLua#1029]
请问 黑名单如何过滤重载的构造函数？

**Comment by git-SteamedBun** [comment]
![微信截图_20230111155737](https://user-images.githubusercontent.com/42927066/211749902-d1ab8b1b-1bde-4a6c-9ac4-2e22b8b5d3a3.png)
我想将图中的两个构造函数过滤，要如何写到黑名单中？一般函数是（类型，函数名，参数类型）的形式，构造函数要如何表示呢？

**Comment by chexiongsheng** [comment]
名字是".ctor"，你可以通过反射获取methodbase后，打印一下Name确认下。
参数和普通方法一样。
