### ISSUE TITLE
LuaException:  attempt to index a nil value (local 'self')

### ISSUE THREAD

**Issue by leechen2020** [Tencent/xLua#103]
Help me~~~~~

----      c# code 

[LuaCallCSharp]
class A {
LuaEnv luaEnv = new LuaEnv();
luaTable = luaEnv.NewTable();

var meta = luaEnv.NewTable();
meta.Set("__index", luaEnv.Global);
luaTable.SetMetaTable(meta);
meta.Dispose();     

scriptEnv.Set("self", this);

....

public void TestCSFunc()
{
    Debug.Log("TestFunc()");
}

}

----      First Lua Code 'Test.lua.txt'

require 'test2'
....

function Main()
    Lua2Func()
end

----      Second Lua code2 : 'Test2.lua.txt'

function Lua2Func()
    self:TestCSFunc()
end

**Editor Run...  So.. Error!!!**
LuaException:  ... attempt to index a nil value (local 'self')

Help!!!!

**Comment by chexiongsheng** [comment]
env不会传递到第二个文件。

**Comment by leechen2020** [comment]
谢谢。

**Comment by VDerGoW** [comment]
> env不会传递到第二个文件。

文档里面说更建议使用 require 来调用lua脚本，那请问要怎么才能在被require的lua脚本中访问从C#端设置进去的env呢？
