### ISSUE TITLE
Unity新项目在只导入Xlua的情况下打包webgl报错

### ISSUE THREAD

**Issue by ShiroNeko07** [Tencent/xLua#1034]
现版本2020.2.6f1
网上有类似的错误，但是对方解决方案是更新插件版本，出现这个问题貌似是库文件冲突了，请问各位有什么解决方案吗？
Failed running "C:/Program Files/Unity2020_2/Editor/Data/PlaybackEngines/WebGLSupport\BuildTools\Emscripten_Win\python\2.7.5.3_64bit\python.exe" -E "C:/Program Files/Unity2020_2/Editor/Data/PlaybackEngines/WebGLSupport\BuildTools\Emscripten\emcc" @"D:\UnityProject\BestHttp2\Assets\..\Temp\emcc_arguments.resp"

stdout:
stderr:error: Linking globals named 'main': symbol multiply defined!ERROR:root:Failed to run llvm optimizations: 
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by chexiongsheng** [comment]
提示不是挺明确了么？多个main函数。
如果是官方的xlua，没有main函数。

**Comment by ShiroNeko07** [comment]
@chexiongsheng 我看在Xlua下的WebGLPlugins内的lua.c中就包含main函数，当我试图隐藏这个函数后还会有其他重名函数的情况。

**Comment by chexiongsheng** [comment]
> @chexiongsheng 我看在Xlua下的WebGLPlugins内的lua.c中就包含main函数，当我试图隐藏这个函数后还会有其他重名函数的情况。

lua.c没使用。

使用了哪些文件是看这：https://github.com/Tencent/xLua/blob/master/Assets/Plugins/WebGL/xlua_webgl.cpp
