### ISSUE TITLE
如果允许创意工坊物品中使用xLua来实现游戏的额外功能，考虑到安全性问题，有哪些库或者函数应当被禁用？

### ISSUE THREAD

**Issue by q2398003522** [Tencent/xLua#1035]
想让玩家能够使用创意工坊来自定义部分游戏的功能，但可能会出现安全性问题，想问下有哪些库或者函数应当禁用，即能够防止用户在创意工坊xLua脚本文件中使用恶意代码。
目前看到xLua的loslib.c中已经禁用了`os.execute`。

**Comment by chexiongsheng** [comment]
文件读写之类吧。
但lua本身的禁用，还是能调用c#的，xlua没有限制c# api调用的功能。blacklist也是不生产静态wrap代码而已，仍然可以反射调用。
