### ISSUE TITLE
请问xlua.genaccessor的传参是什么情况

### ISSUE THREAD

**Issue by Liar0** [Tencent/xLua#1039]
xlua.genaccessor(0, 8)

![image](https://user-images.githubusercontent.com/48144699/219951545-08656065-5d5d-4632-9acb-785950229cde.png)
也没有找到具体的参考方案

**Comment by chexiongsheng** [comment]
参数1是字段偏移
参数2是字段类型
字段类型定义看这里：https://github.com/Tencent/xLua/blob/d60930196e8a3ab1936251d5a99432df2d783f10/build/xlua.c#L1099
