### ISSUE TITLE
unity3d 4.7.2 编译出错

### ISSUE THREAD

**Issue by hanchong22** [Tencent/xLua#104]
Assets/XLua/Src/LuaEnv.cs(294,55): error CS1502: The best overloaded method match for `XLua.ObjectPool.Check(int, int, Func<object,bool>, System.Collections.Generic.Dictionary<object,int>)' has some invalid arguments

**Comment by chexiongsheng** [comment]
我机器是4.7.2f1，能编译通过

**Comment by hanchong22** [comment]
原来是项目中已经另外一个lua解析代码了，有相同名称的类。
