### ISSUE TITLE
hotfix中調用跟Transform有關的操作都會報錯

### ISSUE THREAD

**Issue by chris312319** [Tencent/xLua#1040]
例如
`player.transform.position = player.transform.position + UnityEngine.Vector3(0,10 * UnityEngine.Time.deltaTime,0)`
在一個lua虛擬機可以正常運行
但在hotfix修改函數的時候卻會報錯
而且所有跟transform有關的都會報錯
例如
`CS.UnityEngine.GameObject.Find("Player").transform.Translate(CS.UnityEngine.Vector3(1,1,1))`會報錯LuaException: invalid arguments to UnityEngine.Transform.Translate!
`obj.transform.position = CS.UnityEngine.Vector3(1,1,1)`會報錯LuaException: c# exception:System.Exception: invalid userdata for UnityEngine.Vector3
還有很多種情況也都試了 
只有
`obj.transform.position = {x = 1,y=2,z=3}`這種可以運行
請問是hotfix時對transform相關屬性的操作有甚麼限制嗎

**Comment by chexiongsheng** [comment]
不会对transform有什么特殊。unity的任意类型都不特殊。也没听说有你描述的问题。

**Comment by chris312319** [comment]
> 不会对transform有什么特殊。unity的任意类型都不特殊。也没听说有你描述的问题。

沒事了 後來發現是兩個lua虛擬機有相同的local變數名稱導致的衝突
