### ISSUE TITLE
ExampleConfig.cs

### ISSUE THREAD

**Issue by jiangjiali** [Tencent/xLua#1047]
ExampleConfig.cs 这个文件，生成Wrap时，出现 

The type name 'ClusterSerialization' could not be found in the namespace 'UnityEngine'. This type has been forwarded to assembly 'UnityEngine.ClusterRendererModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' Enable the built in package 'Cluster Renderer' in the Package Manager window to fix this error.

**Comment by becomingrusty** [comment]
请问是怎么解决的

**Comment by andy380743909** [comment]
同样碰到这个问题了，怎么都找不到这个类。我只能手动把这个生成的类相关的代码和文件都删了，编译能通过就行了

**Comment by jiangjiali** [comment]
> 同样碰到这个问题了，怎么都找不到这个类。我只能手动把这个生成的类相关的代码和文件都删了，编译能通过就行了

你使用deepseek问问这个错误问题，试试。
