### ISSUE TITLE
luajit_v2.1.16_ndkr21b_with_win.tgz

### ISSUE THREAD

**Issue by jiangjiali** [Tencent/xLua#1049]
这个版本，在windows下，一点运行就挂掉。

**Comment by jiangjiali** [comment]
[v2.1.16_ndkr21b_with_win](https://github.com/Tencent/xLua/releases/tag/v2.1.16_ndkr21b_with_win)
源码包的插件 运行正常。

**Comment by ruandh** [comment]
源码版本的不是luajit的吧，应该是luajit版本有问题

**Comment by chexiongsheng** [comment]
xlua的编译是用github acton去自动化编译。
之前用window2016编译出来没啥问题，但后面github不提供window2016虚拟机了，在新的虚拟机编译出来的luajit版本可能有问题。建议自己在本地编译。

**Comment by ruandh** [comment]
好的 多谢大佬
