### ISSUE TITLE
热更新的时候，如果不用lua重新整个c#类，能否往c#类里面添加一个函数

### ISSUE THREAD

**Issue by chenqiu1988** [Tencent/xLua#105]
看demo都是要么重写类，要么重写函数，有时候需要热更新添加功能，但是又不想把c#全部转为lua，有无办法再不用重写整个c#类的情况下，用lua插入一个函数，

**Comment by chexiongsheng** [comment]
你加来干嘛呢？别的C#又不会引用

**Comment by chenqiu1988** [comment]
用了一个和服务器通信的库,框架比较死,用了反射的机制去调用对应C#类的函数,我如果后面加功能,他可能会自动调到对应的函数去,因此我考虑,需要在这个类中插入对应的函数实现,当然如果你有更好的做法也可以给我推荐推荐

**Comment by chexiongsheng** [comment]
不行
据我所知，C#没法在运行时动态在已有类加函数。

**Comment by chenqiu1988** [comment]
实在不行 我把就能把交互模块 用lua重写一遍  就是代价有点大.......
