### ISSUE TITLE
关于xlua后台收集设备信息，为未公开收集使用规则

### ISSUE THREAD

**Issue by magicskysword** [Tencent/xLua#1053]
https://github.com/Tencent/xLua/commit/9e431cbf36e04c8f276bf06ba75ab110d8d62f97
该提交既没有在Readme里写明会发送设备信息和Unity信息。也没有在Unity里弹出对应提示窗口，为未公开收集使用规则。这违反了相关的隐私保护政策。

**Comment by jiangjialiv** [comment]
在什么地方修改呢？

**Comment by magicskysword** [comment]
> 在什么地方修改呢？

删除 Assets/XLua/Src/Editor/Report.cs 文件即可

**Comment by magicskysword** [comment]
https://github.com/Tencent/xLua/commit/ad548a68fc203d2efd1e771660a888a64921af25
因为已经添加了相关说明，此Issue关闭。
