### ISSUE TITLE
编译优化

### ISSUE THREAD

**Issue by jiangjiali** [Tencent/xLua#1054]
在CMakeLists.txt文件中加入编译器指定，编译出来的安卓版本so文件，小很多。
#c++ standard
if (NOT DEFINED CXX_STD)
	set (CXX_STD 14)
endif()
message(STATUS "CXX_STD=${CXX_STD}")
set(CMAKE_CXX_STANDARD ${CXX_STD})
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

**Comment by jiangjialiv** [comment]
经过策划，无效。
