### ISSUE TITLE
用文件的方式加载lua，不能得到文件末位的返回值（LuaTable）

### ISSUE THREAD

**Issue by naponean** [Tencent/xLua#106]
如果lua的文件(例如f.txt)的末位返回一个table，在C#这么怎么才能拿到这个LuaTable？LuaEnv.DoString("require 'f'")返回为null，这个文件确实执行了，但收不到返回值。

**Comment by chexiongsheng** [comment]
群上已经答复

**Comment by roclau0102** [comment]
> 群上已经答复

请问群上的答复是什么，能否把答复贴在这里留个记录？

**Comment by roclau0102** [comment]
> 群上已经答复

请问群上的答复是什么，能否把答复贴在这里留个记录？

**Comment by chexiongsheng** [comment]
@roclau0102 
DoString("return require 'f'")
