### ISSUE TITLE
Is it possible to restrict call of C" namespace in Lua?

### ISSUE THREAD

**Issue by mrpierrot** [Tencent/xLua#1065]
Hi !
I would like forbidden access to namespace like "CS.UnityEngine" or "CS.System.IO.File" in lua script. 
Better : I would have by default no CS namespace granted and just add the namespace that could be usefull (Disable all namespaces and add exceptions)
Can be possible ? I don't find anything for ths in the doc. But Perhaps I missed something.
Thank you.

**Comment by chexiongsheng** [comment]
You can write a filter here: https://github.com/Tencent/xLua/blob/master/Assets/XLua/Src/LuaEnv.cs#L473

**Comment by mrpierrot** [comment]
Thank you for this answer.
It could be cool but I think that not solve my problem. 
I want to create mods with xlua. And for security reason, I must to restrict namespace like CS.System.IO.File. 
If I do it in the lua scripts like you show me : I think an user can bypass the restriction by calling directly xlua.import_type.
But I think your answer give me a clue. And I need to rewrite this function : https://github.com/Tencent/xLua/blob/0d1e3eb78b8f7560e9bfb74790fea83e5d2fc37e/Assets/XLua/Src/StaticLuaCallbacks.cs#L849

Thank you :-)

**Comment by Philofallever** [comment]
> Thank you for this answer. It could be cool but I think that not solve my problem. I want to create mods with xlua. And for security reason, I must to restrict namespace like CS.System.IO.File. If I do it in the lua scripts like you show me : I think an user can bypass the restriction by calling directly xlua.import_type. But I think your answer give me a clue. And I need to rewrite this function :
> 
> https://github.com/Tencent/xLua/blob/0d1e3eb78b8f7560e9bfb74790fea83e5d2fc37e/Assets/XLua/Src/StaticLuaCallbacks.cs#L849
> 
> Thank you :-)

There is a  better way that set a Lua env for your mods, and  only  import necessary function in mods Lua env. it's easy to implement.
