### ISSUE TITLE
error CS0117: 'Type' does not contain a definition for 'MakeGenericSignatureType'

### ISSUE THREAD

**Issue by wangshucheng** [Tencent/xLua#1066]
Unity 2021.3.23f1c1
xlua v2.1.15

```
// System_TypeWrap.cs

Utils.EndObjectRegister(type, L, translator, null, null,null, null, null);
Utils.BeginClassRegister(type, L, __CreateInstance, 17, 1, 0);
Utils.RegisterFunc(L, Utils.CLS_IDX, "GetTypeHandle", _m_GetTypeHandle_xlua_st_);
Utils.RegisterFunc(L, Utils.CLS_IDX, "GetTypeArray", _m_GetTypeArray_xlua_st_);
Utils.RegisterFunc(L, Utils.CLS_IDX, "GetTypeCode", _m_GetTypeCode_xlua_st_);
Utils.RegisterFunc(L, Utils.CLS_IDX, "GetTypeFromCLSID", _m_GetTypeFromCLSID_xlua_st_);
Utils.RegisterFunc(L, Utils.CLS_IDX, "GetTypeFromProgID", _m_GetTypeFromProgID_xlua_st_);
Utils.RegisterFunc(L, Utils.CLS_IDX, "MakeGenericSignatureType", _m_MakeGenericSignatureType_xlua_st_);
...

[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
static int _m_MakeGenericSignatureType_xlua_st_(RealStatePtr L)
{
try {
        ObjectTranslator translator = ObjectTranslatorPool.Instance.Find(L);
        {
            System.Type _genericTypeDefinition = (System.Type)translator.GetObject(L, 1, typeof(System.Type));
            System.Type[] _typeArguments = translator.GetParams<System.Type>(L, 2);
            
                var gen_ret = System.Type.MakeGenericSignatureType( _genericTypeDefinition, _typeArguments );
                translator.Push(L, gen_ret);

            return 1;
        }
        
    } catch(System.Exception gen_e) {
        return LuaAPI.luaL_error(L, "c# exception:" + gen_e);
    }
}
```
Type不知道为什么生成出了MakeGenericSignatureType，Type里并没有找到这个方法的

我尝试使用blacklist也屏蔽不了

        if (memberInfo.DeclaringType.IsGenericType && memberInfo.DeclaringType.GetGenericTypeDefinition() == typeof(Type))
        {
            if (memberInfo.MemberType == MemberTypes.Method)
            {
                var methodInfo = memberInfo as MethodInfo;
                if (methodInfo.Name == "MakeGenericSignatureType" && methodInfo.GetParameters().Length == 2)
                {
                    return true;
                }
            }
        }

**Comment by myyunsong** [comment]
我也遇到了一样的问题，请问你怎么解决的

**Comment by Leon-lr** [comment]
type的这个函数不是泛型的，memberInfo.DeclaringType.IsGenericType这里就不会进来

        if (memberInfo.DeclaringType  == typeof(Type))
        {
            if (memberInfo.MemberType == MemberTypes.Method)
            {
                var methodInfo = memberInfo as MethodInfo;
                if (methodInfo.Name == "MakeGenericSignatureType" && methodInfo.GetParameters().Length == 2)
                {
                    return true;
                }
            }
        }

这样就行了
