### ISSUE TITLE
Build xLua with lua-5.4.6 failed.

### ISSUE THREAD

**Issue by lunoctis** [Tencent/xLua#1073]
build/memory_leak_checker.c
line 153: `setclLvalue(L, L->top, cl);`
need change to `setclLvalue(L, L->top.p, cl);`

**Comment by liuyi13-cpu** [comment]
setclLvalue2s(L, L->top.p, cl);

**Comment by liuyi13-cpu** [comment]
setclLvalue2s(L, L->top.p, cl);

**Comment by chexiongsheng** [comment]
https://github.com/Tencent/xLua/commit/4d01bb25f4bf6ca05dc5921ffcb97ca4d9f416bf
