### ISSUE TITLE
Failed to load 'Assets/Plugins/x86_64/xlua.dll' with error '拒绝访问。

### ISSUE THREAD

**Issue by bandok123** [Tencent/xLua#109]
unity 5.4.4f
Failed to load 'Assets/Plugins/x86_64/xlua.dll' with error '拒绝访问。

**Comment by chexiongsheng** [comment]
重启Unity，还不行重启windows

**Comment by bandok123** [comment]
@chexiongsheng 都试过了，还是不行，有没有什么特殊设置

**Comment by chexiongsheng** [comment]
没有，都是拷贝进去就可以了

**Comment by bandok123** [comment]
@chexiongsheng 我是直接pull这个工程，然后用unity打开了，然后运行hello world就提示错误

**Comment by bandok123** [comment]
new了一个新工程，把东西都拷贝过去，就好了，谢谢了

**Comment by chexiongsheng** [comment]
群里头有人碰到过，说是vs的问题。清除掉工程下生成的东西就好了，你也可以加下官方群。
