### ISSUE TITLE
Unity2022.3 打PC包的时候，会报错UnityEngine.Material类的的一些接口不存，但是接口是有的

### ISSUE THREAD

**Issue by surpassSelf** [Tencent/xLua#1094]
Assets\XLua\Gen\UnityEngine_MaterialWrap.cs(1238,57): error CS1061: 'Material' does not contain a definition for 'IsChildOf' and no accessible extension method 'IsChildOf' accepting a first argument of type 'Material' could be found (are you missing a using directive or an assembly reference?)
Assets\XLua\Gen\UnityEngine_MaterialWrap.cs(1266,39): error CS1061: 'Material' does not contain a definition for 'RevertAllPropertyOverrides' and no accessible extension method 'RevertAllPropertyOverrides' accepting a first argument of type 'Material' could be found (are you missing a using directive or an assembly reference?)
Assets\XLua\Gen\UnityEngine_MaterialWrap.cs(1296,57): error CS1061: 'Material' does not contain a definition for 'IsPropertyOverriden' and no accessible extension method 'IsPropertyOverriden' accepting a first argument of type 'Material' could be found (are you missing a using directive or an assembly reference?)
Assets\XLua\Gen\UnityEngine_MaterialWrap.cs(1307,57): error CS1061: 'Material' does not contain a definition for 'IsPropertyOverriden' and no accessible extension method 'IsPropertyOverriden' accepting a first argument of type 'Material' could be found (are you missing a using directive or an assembly reference?)

**Comment by wyjxp** [comment]
给报错的方法加黑名单

**Comment by chrisfox23** [comment]
我也遇到这样的问题，如果加黑名单的话也不是办法，太多了。

**Comment by surpassSelf** [comment]
只能将这几个方法加到BlackList了，翻了Unity2022的文档，这些方法是EditorOnly的，不能在运行时使用。

**Comment by ouyangluqi** [comment]
// material
new List<string>(){ "UnityEngine.Material", "IsChildOf", "UnityEngine.Material"},
new List<string>(){ "UnityEngine.Material", "RevertAllPropertyOverrides"},
new List<string>(){ "UnityEngine.Material", "IsPropertyOverriden", "System.String"},
new List<string>(){ "UnityEngine.Material", "IsPropertyOverriden", "System.Int32"},
new List<string>(){ "UnityEngine.Material", "IsPropertyLocked", "System.String"},
new List<string>(){ "UnityEngine.Material", "IsPropertyLocked", "System.Int32"},
new List<string>(){ "UnityEngine.Material", "IsPropertyLockedByAncestor", "System.String"},
new List<string>(){ "UnityEngine.Material", "IsPropertyLockedByAncestor", "System.Int32"},
new List<string>(){ "UnityEngine.Material", "SetPropertyLock", "System.Int32", "System.Boolean"},
new List<string>(){ "UnityEngine.Material", "SetPropertyLock", "System.String", "System.Boolean"},
new List<string>(){ "UnityEngine.Material", "ApplyPropertyOverride", "UnityEngine.Material", "System.String"},
new List<string>(){ "UnityEngine.Material", "ApplyPropertyOverride", "UnityEngine.Material", "System.String", "System.Boolean"},
new List<string>(){ "UnityEngine.Material", "ApplyPropertyOverride", "UnityEngine.Material", "System.Int32", "System.Boolean"},
new List<string>(){ "UnityEngine.Material", "RevertPropertyOverride", "System.String"},
new List<string>(){ "UnityEngine.Material", "RevertPropertyOverride", "System.Int32"},
new List<string>(){ "UnityEngine.Material", "parent"},
new List<string>(){ "UnityEngine.Material", "isVariant"},

添加到BlackList
