### ISSUE TITLE
请问只能在Unity下用吗

### ISSUE THREAD

**Issue by gitlsl** [Tencent/xLua#11]
比如我一个 c#写的 桌面 exe  能不能用这个 xlua 热更新算法？

**Comment by chexiongsheng** [comment]
设计时就考虑了在非Unity环境下使用，和Unity耦合不大。
c#写的，甚至只要是.net的都可以用。

**Comment by chexiongsheng** [comment]
但目前还没剥离出来。

**Comment by huomm23** [comment]
非常棒 支持你们！期望能把xlua发展成多平台通用的浇水框架， 在性能和质量上有充分的数据和保障。

**Comment by gitlsl** [comment]
@chexiongsheng    最好能公布下roadmap   这样大家看起来也方便

**Comment by chexiongsheng** [comment]
@gitlsl 这个暂时没有具体计划。

**Comment by chexiongsheng** [comment]
@gitlsl @huomm23 非Unity环境下的支持已经开发完毕，下次发版本就会同时发一个通用版本。

**Comment by Domain** [comment]
> @gitlsl @huomm23 非Unity环境下的支持已经开发完毕，下次发版本就会同时发一个通用版本。

有没有文档说明一下，非unity环境怎么使用啊？

**Comment by chexiongsheng** [comment]
> > @gitlsl @huomm23 非Unity环境下的支持已经开发完毕，下次发版本就会同时发一个通用版本。
> 
> 有没有文档说明一下，非unity环境怎么使用啊？

https://github.com/Tencent/xLua/tree/master/General
