### ISSUE TITLE
通过u3d的Il2CPP发布成ios后HotFix无法找到C# 类中的成员

### ISSUE THREAD

**Issue by hanchong22** [Tencent/xLua#110]
这个问题怎么解决？是否不能使用Il2CPP？

**Comment by chexiongsheng** [comment]
可以，应该是你build的时候没打开宏

**Comment by hanchong22** [comment]
找到原因了，原来是因为C#中如果用引用的方式传递string类型的参数（比如function(int a,ref string b)这样的方式）则不能标记为Hotfix，否则会出错。

**Comment by chexiongsheng** [comment]
@hanchong22 这种标记为hotix的话，仅在打包ios的时候会出错？还是都会出错？你的xLua版本是？

**Comment by chexiongsheng** [comment]
我们的预期是所有类型的参数都支持的

**Comment by hanchong22** [comment]
会在生成il2cpp的时候出错

**Comment by chexiongsheng** [comment]
报啥错？发来看看？

**Comment by hanchong22** [comment]
IL2CPP error for method 'System.String obj.FighterAppear::GetAnimFileName(ObjPart,obj.ObjAnimType,System.String,System.String&)' in assembly '/Users/hanchong/Desktop/tianzi/wholeclient2/Temp/StagingArea/Data/Managed/Assembly-CSharp.dll'
Additional information: Build a development build for more information. Cannot cast from source type to destination type.
这也许是unity3d本的错误，我是unity3d版本是4.7.1f1 for mac

**Comment by hanchong22** [comment]
@chexiongsheng 这个错误并不是单纯的string&这样的语法导致的，我重新在一个新项目中试过了是没有问题的，具体原因我再分析一样。

**Comment by chexiongsheng** [comment]
好的，谢谢了！

**Comment by chexiongsheng** [comment]
@hanchong22 后面有查找到具体的原因么？

**Comment by hanchong22** [comment]
@chexiongsheng  没找出原因，在旧项目中一直存在此问题，但在新项目中没有此问题。

**Comment by chexiongsheng** [comment]
那先关闭吧，后面发现规律再提
