### ISSUE TITLE
unity编译后出现了一个warning

### ISSUE THREAD

**Issue by shishu123cn** [Tencent/xLua#111]
code has not been genrate, may be not work in phone!
UnityEngine.Debug:LogWarning(Object)
CSObjectWrapEditor.Startup:Update() (at Assets/XLua/Src/Editor/Generator.cs:1252)
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

这个警告我一直没看明白。请教下

**Comment by chexiongsheng** [comment]
xlua的特色之一是unity编辑器下不用生成代码。
这个warning是提醒你发布到的时候记得执行下生成代码。

**Comment by shishu123cn** [comment]
就是说这个警告我不用管是吧，我以为我哪个代码有问题呢。

**Comment by chexiongsheng** [comment]
代码没问题，但要管，别发布到手机时报错，那就真的执行不了了。

**Comment by shishu123cn** [comment]
嗯，好的
