### ISSUE TITLE
内存泄漏严重

### ISSUE THREAD

**Issue by quaerere** [Tencent/xLua#1116]
通过lua profiler分析，发现xlua util.lua.txt这个里面逻辑内存泄漏严重
![image](https://github.com/Tencent/xLua/assets/7693562/02c77291-850b-470e-a09e-1d4c2778bd30)
![image](https://github.com/Tencent/xLua/assets/7693562/27ab6188-1efb-433d-b0ee-c730000debff)

**Comment by Philofallever** [comment]
业务代码问题吧, 这儿没干什么

**Comment by quaerere** [comment]
不是，我换了新的这个lua这个文件的时候 这个方法，这块就没有了，不过另外有个每帧访问transform.rotation的泄漏还是有

**Comment by Philofallever** [comment]
你自己研究吧 这儿只是协程 具体分配什么内存和你们业务逻辑关系很大, 要是有这么严重的问题其他人早提出来了
