### ISSUE TITLE
使用luasocket库，require（“mime.core”）失败

### ISSUE THREAD

**Issue by hejie332** [Tencent/xLua#112]
已经扩展库里已经内置了luasocket，我按如下添加了，还是报错

AddBuildin("mime.core", StaticLuaCallbacks.LoadMimeCore);

 [MonoPInvokeCallback(typeof(LuaCSFunction))]
 internal static int LoadMimeCore(RealStatePtr L)
  {
       return LuaAPI.luaopen_mime_core(L);
  }

 [DllImport(LUADLL, CallingConvention = CallingConvention.Cdecl)]
        public static extern int luaopen_mime_core(IntPtr L);

报错信息
EntryPointNotFoundException: luaopen_mime_core
XLua.StaticLuaCallbacks.LoadMimeCore (IntPtr L) (at Assets/XLua/Src/StaticLuaCallbacks.cs:480)
(wrapper native-to-managed) XLua.StaticLuaCallbacks:LoadMimeCore (intptr)
XLua.LuaEnv.DoString (System.String chunk, System.String chunkName, XLua.LuaTable env) (at Assets/XLua/Src/LuaEnv.cs:213)

请问是什么问题呢？
谢谢！！

**Comment by chexiongsheng** [comment]
EntryPointNotFoundException表明没有那c函数，代表你从编译到copy库到Plugins的某个环节没成功。

**Comment by hejie332** [comment]
luasocket库，xlua已经内置了，按理说我不需要重新编译库，替换plugins对应的库

我已经找到问题了
不过我不是很理解为什么会这样，我是按如下修改：
mime.c文件的
MIME_API int luaopen_mime_core(lua_State *L)
{
....
}
修改成
LUA_API int luaopen_mime_core(lua_State *L)
｛
...
｝

重新生成库到plugins里就可以了......

**Comment by chexiongsheng** [comment]
你查看下MIME_API

**Comment by hejie332** [comment]
哦，我明白了，感谢~

**Comment by tianjiegs1986** [comment]
非常想知道最后是怎么解决的，需要改MIME_API 为 LUA_API 吗？如果不改的话应该如何调用呢？现在lua中直接require "mime.core"是会报找不到的的，如果可以的话请说明一下

**Comment by chexiongsheng** [comment]
> 非常想知道最后是怎么解决的，需要改MIME_API 为 LUA_API 吗？如果不改的话应该如何调用呢？现在lua中直接require "mime.core"是会报找不到的的，如果可以的话请说明一下

你的报错和楼主一样么？
