### ISSUE TITLE
鸿蒙平台导出包报错

### ISSUE THREAD

**Issue by QinMoXX** [Tencent/xLua#1125]
DllNotFoundException: Unable to load DLL 'xlua'. Tried the load the following dynamic libraries: Unable to load dynamic library 'xlua' because of 'Failed to open the requested dynamic library (0x06000000) dlerror() = Error loading shared library xlua: No such file or directory
找不到xlua库文件，考虑到还没有鸿蒙平台专用构建，测试使用安卓平台的替换也仍然出现该报错！
是否是因为平台原因需要对应平台构建工具

**Comment by chexiongsheng** [comment]
鸿蒙得下其sdk构建，puerts那我加了，xlua我有空加吧。

**Comment by chexiongsheng** [comment]
https://github.com/Tencent/xLua/releases/tag/v2.1.16_with_ohos
