### ISSUE TITLE
Unity2022.3.17发布WebGL后运行报错

### ISSUE THREAD

**Issue by Gaobobo-C** [Tencent/xLua#1131]
运行时浏览器报错
LuaException: [string "LuaTestScript"]:17: attempt to perform arithmetic on a nil value (field 'up')
stack traceback:
	[string "LuaTestScript"]:17: in function <[string "LuaTestScript"]:16>
  at XLua.LuaEnv.ThrowExceptionFromError (System.Int32 oldTop) [0x00000] in <00000000000000000000000000000000>:0 

所有文件一个不落都导入了，直接打开下载的包也试过了，发布WebGL时报错问题解决了，运行时浏览器报这个错，请问该怎么解决？

**Comment by Gaobobo-C** [comment]
![jietu](https://github.com/Tencent/xLua/assets/41881329/257eeea3-2292-4710-abb1-11cee0989e88)

**Comment by chexiongsheng** [comment]
代码剪裁
