### ISSUE TITLE
webgl平台下如何自定义异步加载loader

### ISSUE THREAD

**Issue by wyjxp** [Tencent/xLua#1135]
![2b3a7e6a03cfbb13f64581776074a5e8](https://github.com/Tencent/xLua/assets/31341515/3796f385-320e-4fa5-8006-bb50209ecf4b)
webgl平台只支持异步加载，不是很理解要如何做到同步加载lua文件后返回bytes，教程里面没写，可以给一个详细的案例代码吗？

**Comment by chexiongsheng** [comment]
lua的require本身就要求是同步的。
异步你不能用require，得自己写一个

**Comment by wyjxp** [comment]
感谢作者回复，还没有水平自己写哈哈，目前处理为webgl平台下在启动游戏时缓存所有lua代码，require时直接用缓存中的。
