### ISSUE TITLE
Support English version for documents

### ISSUE THREAD

**Issue by kokichi88** [Tencent/xLua#114]
Would you like to support english version for all documents and tutorials? It's really helpful

**Comment by chexiongsheng** [comment]
We will provide later. Before we provide this, you can had a look at the excamples:
https://github.com/Tencent/xLua/tree/master/Assets/XLua/Examples
https://github.com/Tencent/xLua/tree/master/Assets/XLua/Tutorial

**Comment by Game-Hacker** [comment]
Thank you.
