### ISSUE TITLE
如何将枚举值转换为其基础类型？

### ISSUE THREAD

**Issue by svermeulen** [Tencent/xLua#1143]
我从文档中看到枚举类型有一个 __CastFrom 方法,但是反方向呢?我有一个枚举值,想要它的原始值(在这个例子中是 int)。我无法弄清楚如何在 Lua 中获得它。我看到它是一个用户数据值,但没有看到任何获取原始值的方法。

**Comment by Philofallever** [comment]
CS.System.Convert.ToInt32(enumValue)
