### ISSUE TITLE
能请教一下，为什么把lua_setfiled给屏蔽掉？？

### ISSUE THREAD

**Issue by lybmccree** [Tencent/xLua#1146]
如果我想在cs层往luaState塞一个自定义table，然后需要对这个table 进行setfiled，然后再把函数塞进去，应该怎么做呢？tolua可以操作，但是xlua就屏蔽掉接口。

**Comment by chexiongsheng** [comment]
luaState概念上是一个携程/用户态线程。携程不能往里面做什么“塞table”操作。
你说的应该是往虚拟机的全局table那加个table。这可以通过luaEnv.Global实现。

**Comment by lybmccree** [comment]
> luaState概念上是一个携程/用户态线程。携程不能往里面做什么“塞table”操作。 你说的应该是往虚拟机的全局table那加个table。这可以通过luaEnv.Global实现。

对的，就是往虚拟机里面全局table塞一个key tolua可以LuaDLL.lua_setfield(L, idx, key);设置一个成员变量，
举例子_G["network"] = {[“funcName”] = function() end}
我拿到一个 network 的表， 但也无法 使用LuaAPI.lua_setfiled()，因为这个接口没有。
求大佬再指导指导

**Comment by chexiongsheng** [comment]
都封装好更简单的接口可以直接用，你为啥要直接访问lua的接口？
什么接口看我上个回复

**Comment by lybmccree** [comment]
> 都封装好更简单的接口可以直接用，你为啥要直接访问lua的接口？ 什么接口看我上个回复

tolua转xlua，有些业务本来是直接操作lua栈塞到虚拟机，类似以前C++跟lua交互那种，用到了LuaAPI.lua_setfiled跟getfiled，遇到困难
