### ISSUE TITLE
请问可以把xlua用的lua虚拟机编译成webgl插件(.bc文件)在unity plugin用么？

### ISSUE THREAD

**Issue by zdykiller** [Tencent/xLua#1147]
看unity文档提及webgl可以通过emscripten预先编译成.bc文件来导入
https://docs.unity3d.com/6000.0/Documentation/Manual/webgl-native-plugins-with-emscripten.html
相比c源码放到unity plugin目录下，直接放.bc 感觉方便维护一些
我对这部分的编译不了解，想问下可以实现xlua编译成 .bc 文件放到unity plugin目录来用么？

**Comment by chexiongsheng** [comment]
默认也是一个c文件编译成一个bc文件，放一堆bc文件和放一堆c文件有区别吗？

**Comment by zdykiller** [comment]
谢谢，我理解错了。我原本理解的是能类似生成dll文件那样，把所有c文件编译成一个完整bc。
