### ISSUE TITLE
xLua use zerobrane studio 调试的工作原理?

### ISSUE THREAD

**Issue by leechen2020** [Tencent/xLua#115]
你好.

 Zerobrane Studio连接，如何调试？

请告诉我们更多。

**Comment by chexiongsheng** [comment]
Zerobrane Studio是开源的，可以看它的代码：https://github.com/pkulchenko/ZeroBraneStudio

**Comment by leechen2020** [comment]
你会知道如何联动或偏好的方法。

require("mobdebug").start()

Unity3d Run =>

Console Window Message : 
Debugger connection unexpectedly closed 
stack traceback:
        [C]: in function 'error'
	mobdebug:578: in hook '?'
        [string "Test"]:6: in main chunk

我很欣赏你的解决方法。

**Comment by chexiongsheng** [comment]
看下网上关于Zerobrane的调试的文章，其实是通用的。调试器其实和虚拟机打交道。
在xlua唯一需要注意的是，如果你用CustomLoader，要把真实路径通过ref参数返回。这点在faq，以及api文档都有。

**Comment by leechen2020** [comment]
谢谢。

**Comment by chexiongsheng** [comment]
加QQ群了没？N多群友都已经在用Zerobrane调试。

**Comment by leechen2020** [comment]
QQ 帐户 : 3410332849 
谢谢。

**Comment by leechen2020** [comment]
QQ  使用它做得很好

此外还存在疑问。

使用'require'的 xLua这样zerobrane似乎有所不同。

stack traceback:
	[C]: in function 'require' 
.../text.lua:2: in main chunk 

它配备了消息。

你怎么知道，如果你需要解决

**Comment by chexiongsheng** [comment]
我似乎不是很懂你在说啥。。sorry

**Comment by gitlsl** [comment]
@chexiongsheng   可能是一个谷歌翻译的老外？

**Comment by wang-yichun** [comment]
nice, 可用
