### ISSUE TITLE
UnityEngine.QualitySettings中的GetAllRenderPipelineAssetsForPlatform添加到BlackList后依然生成

### ISSUE THREAD

**Issue by linkliu** [Tencent/xLua#1155]
我已经把这个方法添加到黑名单中了，可是在点击生成后，生成的桥接代码中依然有这个方法
如下图
![微信图片_20240820125129](https://github.com/user-attachments/assets/e501b1fe-198e-4b4e-92e3-38dfd5653428)

看了一下源码，发现：
![image](https://github.com/user-attachments/assets/979cb3f1-14cd-4f4e-87aa-ca49ad19bff2)
对于 `typeof(List<RenderPipelineAsset>).FullName` 这个类型，
发现两者的值并不相等，如下图
![image](https://github.com/user-attachments/assets/2e92f0b0-6365-418c-8bd8-c4f6c7564f40)
请问这个问题改如何解决呢，

**Comment by linkliu** [comment]
第一张图有问题，我用vim的时候不小心删掉了方法名，正确的应该像下面这个图
![image](https://github.com/user-attachments/assets/8193cde8-85fd-4805-94b5-4cbb6a48ec1a)

**Comment by linkliu** [comment]
暂时可以用下面的方式解决
`new List<string>(){"UnityEngine.QualitySettings", "GetAllRenderPipelineAssetsForPlatform", typeof(string).FullName, "System.Collections.Generic.List`1[UnityEngine.Rendering.RenderPipelineAsset]&"}`

**Comment by chexiongsheng** [comment]
你这类型都不一样啊。引用类型你应该调用一下MakeByRefType 然后再FullName

**Comment by linkliu** [comment]
> 你这类型都不一样啊。引用类型你应该调用一下MakeByRefType 然后再FullName

好的，非常感谢，可以了
