### ISSUE TITLE
xlua里按照签名调用，需要传参的时候，到底如何传参，这个是最最最基础的一个功能呀

### ISSUE THREAD

**Issue by TQCasey** [Tencent/xLua#1161]
xlua里按照签名调用，需要传参的时候，到底如何传参

比如 UnityPlayerActivity 里 
public static int addFunc (int a,int b) {
     return a + b;
}

在xlua 里
local clazz = CS.UnityEngine.AndroidJNI.FindClass('com/unity3d/player/UnityPlayerActivity')
local method = CS.UnityEngine.AndroidJNI.GetStaticMethodID(clazz, 'addFunc', '(II)I')
local result = CS.UnityEngine.AndroidJNI.CallStaticIntMethod(clazz, method,  {2,3})
print('Java Result: ' .. tostring(result))

怎么都不对，到底是如何传参的，可以给一个demo么，这个是最最最基础的一个功能呀

**Comment by chexiongsheng** [comment]
最最最基础的一个功能为啥只有你在问呢？
你的错误可以在文档中找到原因，我不想直接告诉你。
这确实是最最最基础的一个功能。

**Comment by TQCasey** [comment]
首先，文档非常凌乱
其次，我仔细翻了文档，并没有找出从lua传递多参数到java 函数的方法

我也是个老开发者，我是初次学习u3d，开发者本来就是很忙的，能理解，但是如果文档不太详尽，会让使用者手足无措，我不认为我找的地方不对，我甚至 各种AI都试验过，仔细对照文档（我能找到的部分）并不对，因此我才提了issue。

**Comment by TQCasey** [comment]
我用过很多很多的sdk，很多时候所谓的doc，你甚至只要给一行 sample code，仅一行就可以代替所有文字

**Comment by chexiongsheng** [comment]
首先这就一普通c# api，按普通c# api即可。
我不可能对世上任意c# api都给出例子。
就像你看加法书，只会讲多位加法的步骤，外加几个例子，不可能对2位加2位，3位加2位，3位加3位.。。。都给个例子。
之前没人在这问过你说的这个API怎么调，正如没人质疑小学数学书为啥没有某特定位数的加法的例子。

**Comment by TQCasey** [comment]
如果只是简单的 C# add 函数，我根本就不需要提issue了
首先 函数 C# 里的原型是 public static int CallStaticIntMethod(IntPtr clazz, IntPtr methodID, jvalue[] args);
但是并没有doc写明，如果传递 jvalue ，目前是jvalue，如果是  ByteBuffer 或者 是  byte [] 这类参数如何传递，正视提出的issue，而不是在这里挖苦提issue的人

**Comment by TQCasey** [comment]
如果你很忙，那你就慢回复，如果不像回复，那就无视也可以，没有必要嘲讽，应该是思考为什么这么一个所谓的基础功能，还会有人问，是不是doc不完整，别人看doc就能会，就不需要提issue ，这样不是也能减少你的烦恼不是么？

**Comment by chexiongsheng** [comment]
你的意思是如果有一天有人问了数学书为啥没有5位数加5位数的例子，编写数学书的就得反省是不是自己写的不全了？

首先你用了三个最，这不也是嘲讽么？意思是最最最基础的功能都没做好？

**Comment by TQCasey** [comment]
如果一个文档连常用的使用都需要提issue来解决，我优先会考虑我的文档是不是没写好，按照你的逻辑，如果一个问题，只有一个人问，在你的逻辑里就认为这个是一个基本的问题，那这个项目真的是高贵啊？其次，你的类比错误，我不认为这个是一个堪比5位数和5位数的一个加法的一个基础使用，最后，如果你认为三个最是嘲讽，那我道歉，但是如果是我，接受嘲讽的同时，我一定会把这个问题解决，想清楚到底是什么问题，情绪化是情绪化，问题是问题，如果你不想解决，那就直接无视，让别人知道的可以帮忙，而不是粗暴的直接close，同时我也会自己去debug，毕竟有src code ，但是我非常不理解，一个对我而言没有解决的问题，会被粗暴的close，这个非常不好的行为。

**Comment by chexiongsheng** [comment]
> 如果只是简单的 C# add 函数，我根本就不需要提issue了 首先 函数 C# 里的原型是 public static int CallStaticIntMethod(IntPtr clazz, IntPtr methodID, jvalue[] args); 但是并没有doc写明，如何传递 jvalue，经过我的验证，是传递一个table ，目前是jvalue，如果是 ByteBuffer 或者 是 byte [] 这类参数如何传递，正视提出的issue，而不是在这里挖苦提issue的人

一个类型除了基本类型，就class或struct。你问如何传递jvalue（这个是个struct），已经有struct的示例的情况下问jvalue怎么处理和对着加法书问5位数和5位数加法怎么算有什么区别？

**Comment by TQCasey** [comment]
那你尽管可以：
1.如果觉得这太弱智，那直接无视
2.丢一句：参考 struct 

而不是跟我这里长篇大论的，参考 struct ，就几个字，如果我看了你的这几个字，就马上解决了，或者我自己debug src code出来了，那我自己也就close这个issue了，虽然我在提问后自己debug出来了，但是我非常不理解，既然你们这么忙，为什么还要这么费时的去和我这里说，有时间在这里撕，没时间回答我问的这个你所谓的”弱智的“问题

**Comment by TQCasey** [comment]
因为这个东西是你写的，我自己开发过很多sdk，也做了很多框架，我也经常会想当然的觉得这个很简单的，甚至觉得很弱智，因为你会觉得既然我给了加法，那乘法，减法，你自然就会，因为add就能推导出乘法，减法，别人问你，你自然会觉得肯定是没看文档，我在公司经常碰到这种无厘头问题，我都麻了，但是别人使用的人就不一定，为什么有测试，因为自己找自己的bug，很难找出corner case ,这不就是一个道理么

**Comment by chexiongsheng** [comment]
> 因为这个东西是你写的，我自己开发过很多sdk，也做了很多框架，我也经常会想当然的觉得这个很简单的，甚至觉得很弱智，因为你会觉得既然我给了加法，那乘法，减法，你自然就会，因为add就能推导出乘法，减法，别人问你，你自然会觉得肯定是没看文档，我在公司经常碰到这种无厘头问题，我都麻了，但是别人使用的人就不一定，为什么有测试，因为自己找自己的bug，很难找出corner case ,这不就是一个道理么

“C#除了基本类型，就class或struct”这时sdk的事情吗？

**Comment by chexiongsheng** [comment]
> 因为这个东西是你写的，我自己开发过很多sdk，也做了很多框架，我也经常会想当然的觉得这个很简单的，甚至觉得很弱智，因为你会觉得既然我给了加法，那乘法，减法，你自然就会，因为add就能推导出乘法，减法，别人问你，你自然会觉得肯定是没看文档，我在公司经常碰到这种无厘头问题，我都麻了，但是别人使用的人就不一定，为什么有测试，因为自己找自己的bug，很难找出corner case ,这不就是一个道理么

什么加法推导乘法。struct和jvalue的关系就是加法和加法的一个特例的关系。

**Comment by TQCasey** [comment]
那这样，你既然觉得这个问题很弱智，你如果有时间，你可以做一个问卷，让一个u3d的开发者翻译一段 jni 的，带参数那种，就是将 lua的tabel转成 Java的ByteBuffer,  就丢开发群里，那按照你的意思100个人，应该99个人应该就能答出来吧，1个人应该是我，是吧，那这么自信的话，不妨试一试，如果没时间那就算了 

local data = { 0x01,0x02,0x03, ....}

**Comment by TQCasey** [comment]
还有我回复三个最，是因为我自己做开发多年，头一遭使用u3d，结果问了一个你觉得很弱智的问题，就这么一直撕，是我的话，我就丢一句 "参考struct” ，而不是长篇大论给我撕
