### ISSUE TITLE
如何 Use xLua Debug 

### ISSUE THREAD

**Issue by leechen2020** [Tencent/xLua#118]
是否有一个实时调试？
使用Unity3d有或在Visual Studio中启用？

调试工具或者调试工具

Lua Script Debugging

**Comment by chexiongsheng** [comment]
调试其实和xLua关系不大，主要是调试器和lua虚拟机打交道。
xLua需要注意的是，如果用CustomLoader，需要把调试器能识别的路径重filepath参数传出。
zerobrane studio和luastudio都有成功的案例。
以zerobrane studio为例，需要在zerobrane studio开启debug server，然后lua里头
require("mobdebug").start()

更详细的信息请参见各IDE的帮助文档。
