### ISSUE TITLE
请问能够描述下这个开源项目的中长期规划吗？

### ISSUE THREAD

**Issue by huomm23** [Tencent/xLua#12]
请问能够描述下这个开源项目的中长期规划吗？  主要是发展计划、 未来在结构上和目标平台的考虑、开源后tencent投入的资源、以及一些期望等等？

**Comment by chexiongsheng** [comment]
就xLua本身的话，开源后前几个月还是专注于C#和Lua间交互这块。在阳光下把这个核心给做好。如果届时核心没多少问题了，会考虑一些周边模块的启动。

**Comment by ahhuang** [comment]
@huomm23 应该是在考虑是否在正式项目中使用，怕项目太监了。

**Comment by chexiongsheng** [comment]
@ahhuang 腾讯出钱养程序员专门开发维护，太监的可能性比业余搞搞的小多了吧？腾讯也不至于缺钱到要省那么一两个人力。

**Comment by chexiongsheng** [comment]
@ahhuang 你看我回得多么快，是吧，o(∩_∩)o 哈哈
