### ISSUE TITLE
在Lua中传给C#callback函数，会导致LuaEnv最后Dispose时报异常

### ISSUE THREAD

**Issue by xysz0824** [Tencent/xLua#120]
InvalidOperationException: try to dispose a LuaEnv with C# callback!

经测试发现只有在不Gen代码的情况下会出现

**Comment by chexiongsheng** [comment]
刚刚解决，请看，https://github.com/Tencent/xLua/commit/ffa91e9776c79a809bed4e0eed344599122f8460
