### ISSUE TITLE
内存泄漏bug？

### ISSUE THREAD

**Issue by Lu-Kye** [Tencent/xLua#121]
```lua
LuaCallCS.obj1 = {} -- Issue: lua table to csharp object will cause a lot of memory ??
function LuaCallCS:TestObject()
    self.csharpTestCase:TestObject(self.obj1)
end
```
```csharp
// Class 有 LuaCallCSharp attribute
public void TestObject(object obj)
{
 }
```
调用lua TestObject 1000次以上 lua memory.total() 一下子多了几千KB
是我使用姿势问题？还是？
(我有其他TestNumber等类似方法没有发现这个问题)

**Comment by chexiongsheng** [comment]
需要定期调用下LuaEnv.Tick()

**Comment by chexiongsheng** [comment]
当然，你这用例里头执行1000次后，调用LuaEnv.Tick()，lua内存也不一定降，因为可能lua虚拟机没跑完一趟GC，这个你可以调用下lua的强制全量GC，在查下memory。

**Comment by Lu-Kye** [comment]
First of all, thanks for your answer.
   
我的测试中有使用一个单例Update调用LuaEnv.Tick()。
昨天我只在OSX环境下测试，今天早上在Windows下测试了下，我还是有这个问题。
   
# 我的困惑在于:
* 我有其他的类似测试代码 都没有发现问题
* 当我把TestObject的obj参数改为csharp对象则没有发现这个问题, 当我把obj改为{}, 则会产生内存突然增加到6000+KB, 之前是300+KB. 同时我试过只测试除TestObject之外的方法，内存一直比较正常。
# 以下是我的主要测试代码:
```lua
-- Elapsed time at first time is more than next times.
-- Elapsed time is calculated by repeating 100000 times. 

LuaCallCS = Class("LuaCallCS", XLuaTestCase) 

-- Elapsed milliseconds about 0.0019
-- 0B GC
function LuaCallCS:TestNumber()
    self.csharpTestCase:TestNumber(10);
end

-- Elapsed milliseconds about 0.0061
-- 0B GC
-- LuaCallCS.obj1 = CS.UnityEngine.GameObject() -- No Issue
LuaCallCS.obj1 = {} -- Issue: lua table to csharp object will cause a lot of memory ??
function LuaCallCS:TestObject()
    self.csharpTestCase:TestObject(self.obj1)
end

-- Elapsed milliseconds about 0.0019
-- 0B GC
function LuaCallCS:TestOutRef()
    local a, b
    a, b = self.csharpTestCase:TestOutRef(a)
    -- Log.Debug("a "..tostring(a).."b "..tostring(b))
end

-- Elapsed milliseconds about 0.0019
-- 0B GC
LuaCallCS.obj2 = {}
function LuaCallCS:TestOverload()
    self.csharpTestCase:OverloadA(1)
    -- self.csharpTestCase:OverloadB(self.obj2)
end
```
```csharp
using XLua;
using UnityEngine;

namespace XLuaExamples
{
    [LuaCallCSharp]
    public class LuaCallCS : XLuaTestCaseForLua<LuaCallCS>
    { 
        protected override string LuaFile { get { return "LuaCallCS"; } }
        
        public void TestNumber(int num)
        {
        }

        public void TestObject(object obj)
        {
        }

        public void TestOutRef(ref int a, out int b)
        {
            a = 1;
            b = 2;
        }

        public void TestOverload() {}
        public void OverloadA(int a)
        {
            // Debug.Log(string.Format("int a = {0}", a));
        }
        public void OverloadB(LuaTable a)
        {
            // Debug.Log(string.Format("LuaTable a = {0}", a.ToString()));
        }
    }
}
```

**Comment by chexiongsheng** [comment]
在你这场景下在Update上调用Tick是没啥用的吧。你查内存时，Update又没调用。
首先你要明白机理：lua的table传到C#，会有个代理对象，LuaTable，这个C#对象释放了，才有可能是否lua的table，由于C#的GC是在另外一个线程做，所以所有lua方案都改为异步释放，在xlua里是那个Tick函数里头做，还有即使Tick把对lua的引用释放了，你查内存也不一定降了，lua要跑完一个完整gc才释放内存。

你这类性能测试要检查内存要这么做：

```csharp
//你原先的测试代码

//C# gc
System.GC.Collect();
System.GC.WaitForPendingFinalizers();
//Tick异步释放
luaenv.Tick()
//强制跑完一趟lua gc
luaenv.FullGc()

//你原先的查内存代码

```


实际运行中，一定时间内调用Tick还是有保障。

**Comment by Lu-Kye** [comment]
我理解你的意思了，不过我目前的测试方法是这样：
  我只想看lua测调用c#函数 是否会产生多余的lua虚拟机内存，所以我是在保证我测试代码中的对象都有被持久持有引用之后，再去通过lua虚拟机内存前后的差距去判断是否产生了额外的内存。(是否我这样的思路是有问题?)
  然后我主要产生这个问题的原因是 我有很多其他类似的测试 但只有Object这个发现内存前后产生了巨大的差距，其他都是OB offset，而且我有用OnGUI一直显示LuaEnv.Memory, 发现一直不降下去。
  还有就是 我在lua侧，使用memory.snapshot()观察了TestObject调用100000次前后的差别，第一行REGISTRY Level1的Size差距十分大。
snapshot截图如下:
![wechatimg426](https://cloud.githubusercontent.com/assets/5763734/23930798/91add2ec-0969-11e7-844d-0b7065b67d7a.jpeg)

**Comment by chexiongsheng** [comment]
是这样的，当且仅当C#测的LuaTable被GC释放，而且Tick调用了，才会释放lua对应的table，目前保持引用的方式就是REGISTRY上加个ref。

**Comment by Lu-Kye** [comment]
我试了一下，把csharp中的LuaTable = null 之后强制释放内存 确实可以了。 谢谢~

**Comment by Lu-Kye** [comment]
我看了下ObjectCasters::getLuaTable, 您说的加上ref 是否是LuaAPI.luaL_ref?

**Comment by chexiongsheng** [comment]
是的

**Comment by Lu-Kye** [comment]
我看了下 LuaBase里 在Dispose里是有luaL_unref的, 而我的代码 
```csharp 
TestObject(object obj) {}
```
理论上应该在函数退出的时候，之前getLuaTable实例化的LuaTable 应该会Dispose, unref
那不是应该说 lua里面的 REGISTRY 同时也会释放么？ 还是我理解错误。 表示好奇~

**Comment by chexiongsheng** [comment]
理解错误。
在你这种情况，Dispose是C#GC调用的，啥时候调是GC算法决定。
还有GC调用了Dispose也没用，还需要经过Tick异步释放（这才真正unref）。

这个应该是第三遍说了，你显然没仔细看我的回复。

**Comment by Lu-Kye** [comment]
我之前有说啊。。。我在Update里一直有调用Tick, 而我不是根据当前那一帧的执行结果来说这个问题的。我主要是发现我经过了很长时间 Memory一直还是不降下去，我打断点 发现Dispose, unref也调用了 我理解下来应该是释放了的，所以感到困惑。

**Comment by chexiongsheng** [comment]
unref后REGISTRY那应该是没了，但memory不一定会释放，lua的自动gc机制是在发生新分配空间的操作后，才会执行一个gc step。
换句话，如果你一直没有lua的执行，或者lua的执行没有内存分配，memory是不会降的。

**Comment by Lu-Kye** [comment]
哦哦 是这样啊，了解了。 非常感谢~

**Comment by Lu-Kye** [comment]
我最后发现 我把csharp的代码改成这样, 就达到了我的预期.
```csharp
        public void TestObject(object obj)
        {
            using (LuaTable table = obj as LuaTable)
            {
            }
        }
```
LuaBase在析构的时候是Dispose(false)的，是否有什么深意？
(我是不是很烦....)

**Comment by Lu-Kye** [comment]
最后发现csharp如下实现，可以达到我的预期:
```csharp
public void TestObject(object obj)
{
    // If obj is LuaTable 
    using (LuaTable table = obj as LuaTable)
    {
    }
}
```
非常感谢作者解惑~
