### ISSUE TITLE
项目中只有确认的底层 不需要标记 HotFix 而其它的都需要的的情况怎么处理？

### ISSUE THREAD

**Issue by Jihuihu** [Tencent/xLua#122]
你好：
  我在使用时的疑问，项目中往往只有部分很底层的代码确认不会使用HotFix 绝大多数的代码都需要HotFix 那就需要对每一个CS 标记[HotFix]？ 还是说我的思路有问题？

**Comment by chexiongsheng** [comment]
目前xlua的所有配置都支持三种形式。
1、直接打标签；
2、一个字段列表；
3、一个返回列表的属性；
其中第三种就是写个返回List的函数，这个函数是怎么写由你，这个列表列的类型都相当于打了标签。第三种比较适合你这种情况。
详情请看看配置的介绍文档。

**Comment by chexiongsheng** [comment]
思路是正确的，有较大可能要改的地方都要配上

**Comment by Jihuihu** [comment]
非常感谢 么么哒！
