### ISSUE TITLE
mac下编译安卓显示 Could not find neither Android NDK nor Android standalone toolchain

### ISSUE THREAD

**Issue by drashnane** [Tencent/xLua#123]
我是用brew安装的android-ndk，路径在/usr/local/opt/android-ndk，我执行export ANDROID_NDK=/usr/local/opt/android-ndk后再执行make_android_lua53.sh还是显示Could not find neither Android NDK nor Android standalone toolchain

**Comment by chexiongsheng** [comment]
脚本第一行设置了ndk你要改脚本

**Comment by drashnane** [comment]
找到了多谢！

**Comment by drashnane** [comment]
您好，抱歉再问一下，又显示：
CMake Error at cmake/android.toolchain.cmake:538 (FILE):
  file STRINGS file
  "/Users/cf/android-ndk-r13b/toolchains/arm-linux-androideabi-clang3.6/setup.mk"

我用

**Comment by chexiongsheng** [comment]
其实我都是在linux下编android
据说mac下要用r10版本的ndk

**Comment by drashnane** [comment]
我再下一个r10好了
