### ISSUE TITLE
Tutorial/LuaCallCSharp has exception when exit.

### ISSUE THREAD

**Issue by limiy** [Tencent/xLua#124]
Tutorial/LuaCallCSharp ， in Editor，  when exit Play mode， throw an exception "InvalidOperationException: try to dispose a LuaEnv with C# callback!". Which can be located at LuaEnv.cs:386

**Comment by chexiongsheng** [comment]
fixed in https://github.com/Tencent/xLua/commit/c75de8cc99e18a49307071240b2049bb4b47c103

**Comment by lfs1023** [comment]
热修复后，UNITY停止运行时报错：
InvalidOperationException: try to dispose a LuaEnv with C# callback!
XLua.LuaEnv.Dispose (Boolean dispose) (at Assets/WMPlatform/XLua/XLua/Src/LuaEnv.cs:387)
XLua.LuaEnv.Dispose () (at Assets/WMPlatform/XLua/XLua/Src/LuaEnv.cs:370)

升级文档：
CHANGELOG.txt +9、对已经Dispose的LuaEnv的访问做保护；Dispose时检查callback是否已经都释放，没释放的话报错；

已下载最新版本，请问怎么释放文档中说的这个callback？

**Comment by chexiongsheng** [comment]
https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/faq.md#调用luaenvdispose时报try-to-dispose-a-luaenv-with-c-callback错是什么原因
