### ISSUE TITLE
关于可为空的值类型 在lua中的使用

### ISSUE THREAD

**Issue by Jihuihu** [Tencent/xLua#129]
大牛你好，我当前的项目 协议使用的是FlatBuffer 它生成的CS类型是可谓空的值类型 Nullable 在调用的时候会报错，我不是很明白 问题出在哪里 文档中没有发现相关的描述 大牛有什么建议吗？ 我做了一个简易的代码演示 如下：
CS中 
[LuaCallCSharp]
public struct TestNullable
{
    public int Num;
    public string Name;
}

public class ByFile : MonoBehaviour {
    LuaEnv luaenv = null;

    public static string TestMsg = "Msg``````````";
    public static Nullable<TestNullable> m_TestNullable;

    // Use this for initialization
    void Start()
    {
        luaenv = new LuaEnv();
        m_TestNullable = new TestNullable();
        if (m_TestNullable.HasValue)
        {
            Debug.Log("CS number: " + m_TestNullable.Value.Num);
            Debug.Log("CS name: " + m_TestNullable.Value.Name);
        }
        luaenv.DoString("require 'byfile'");
    }
｝

Lua中
print(''..CS.ByFile.TestMsg);
-- 输出的是 “Msg``````````”
print('m_TestNullable toString:'..tostring(CS.ByFile.m_TestNullable));
-- 输出的是 “LUA: m_TestNullable toString:TestNullable: 0”
print('m_TestNullable Value toString:'..tostring(CS.ByFile.m_TestNullable.Value));
输出 “LUA: m_TestNullable Value toString:nil”

此时Value为nil 请问怎么访问对应的值？

**Comment by Jihuihu** [comment]
抱歉 上面的例子写错

**Comment by chexiongsheng** [comment]
在lua访问nullable不用加Value
~~~lua
print('m_TestNullable.Num:'..CS.ByFile.m_TestNullable.Num);
~~~

**Comment by Jihuihu** [comment]
非常 感谢 我试试

**Comment by Jihuihu** [comment]
确认OK 非常感谢
