### ISSUE TITLE
热补丁的问题

### ISSUE THREAD

**Issue by aidanni** [Tencent/xLua#13]
在运行hotfixtest例子的时候，按下按钮报了如下的错误，求教如何解决

LuaException: xlua.access, no field __Hitfix0_Update
stack traceback:
	[C]: in field 'access'
	[string "Init"]:86: in field 'hotfix'
	[string "chunk"]:3: in main chunk
XLua.LuaEnv.ThrowExceptionFromError (Int32 oldTop) (at Assets/XLua/Src/LuaEnv.cs:360)
XLua.LuaEnv.DoString (System.String chunk, System.String chunkName, XLua.LuaTable env) (at Assets/XLua/Src/LuaEnv.cs:212)
HotfixTest.OnGUI () (at Assets/XLua/Examples/08_Hotfix/HotfixTest.cs:29)

**Comment by aidanni** [comment]
HOTFIX_ENABLE宏（在Unity3D的File->Build Setting->Scripting Define Symbols下添加）

**Comment by chexiongsheng** [comment]
这有类似的issue，你看看有帮助不？https://github.com/Tencent/xLua/issues/8

**Comment by aidanni** [comment]
没有finished，但是在开头报了一个黄错，可能是cecil版本的问题或者unity版本的问题，我的unity版本是5.3.4
can not find delegate for HotfixTest..ctor! try re-genertate code.
UnityEngine.Debug:LogWarning(Object)
XLua.Hotfix:InjectMethod(AssemblyDefinition, MethodDefinition, Int32, FieldReference) (at Assets/XLua/Src/Editor/Hotfix.cs:235)
XLua.Hotfix:HotfixInject() (at Assets/XLua/Src/Editor/Hotfix.cs:171)

**Comment by chexiongsheng** [comment]
@aidanni “can not find delegate”这个好解决，你执行下XLua/Generate Code

**Comment by chexiongsheng** [comment]
然后等hotfix inject finish!打印再运行

**Comment by aidanni** [comment]
目前来看无任何黄错了＝。＝但是还是没有出现finished，请教下如何排查未出现hotfix inject finish!错误可能

**Comment by chexiongsheng** [comment]
执行了XLua/Generate Code么？

**Comment by chexiongsheng** [comment]
另外hotfix inject finish!是由编译触发的，是不是之前出错后没修改过代码？

**Comment by aidanni** [comment]
问题解决！可能出错之后改了代码自己忘记了＝。＝
mac上的Mono.Cecil.dll不太好找，可能和unity版本有关
其他按照文档来做就可以了！
