### ISSUE TITLE
生成的Wrap，重载的顺序不对

### ISSUE THREAD

**Issue by heroboy** [Tencent/xLua#130]
从GenericMethod示例开始：
C#:
```c#
public class Foo
{
    #region Supported methods

    public void Test1<T>(T a) where T : Foo1Parent
    {
		Debug.Log(string.Format("Test1<{0}> x={1}", typeof(T), a.x));
    }
	public void Test1(int val)
	{
		Debug.Log("this is Test1(int),val = " + val);
	}

	public void Test1(object obj)
	{
		Debug.Log("this is Test1(object),obj = " + obj);
	}

	public void Test1(string str)
	{
		Debug.Log("this is Test1(string),str = " + str);
	}
	public void Test1(LuaTable lt)
	{
		Debug.Log("this is Test1(LuaTable), lt = ");
	}
}
```
lua:
```
foo:Test1({A=1})
```
在FooWrap.cs中，应该优先判断`Test1(LuaTable)`，而实际上被转换成了`Foo1Parent`。

**Comment by xiluoyouqd** [comment]
The namespace `global::' already contains a definition for `XLuaTest'

**Comment by chexiongsheng** [comment]
重载要做到完全和C#一致，一是代价大，复杂的重载算法，在静态语言是可以接受的，因为都是在编译器做，但动态语言的话，要在运行期做就太费了，二是因为类型丰富程度不一样，也做不到，比如c#有各种数字类型，lua就一种，在lua调用obj:foo(1)，在C#的int和short你选哪个呢？
也有机制能让你调用到你想要的方法，比如成员函数，你可以用Extension method为其中一个起个别名。

**Comment by heroboy** [comment]
你说得对。所以我的题目就是“顺序”，我觉得应该生成更好的“顺序”。例如，在这个例子中，LuaTable，LuaBase一类的参数应该优先判断，因为这种函数就是为了获取lua的类型的值。更进一步的话，对于有可能有歧义的重载在生成的时候给出警告。

**Comment by chexiongsheng** [comment]
现在不宜做这样的调整了，xLua虽然开源不久，但内部使用一年多了，有项目已经按照现有的顺序写代码（排后面的用Extension method封装），修改会导致这些应用出问题。
