### ISSUE TITLE
Dictionary`2[System.String,System.String]使用正常，但是Dictionary`2[System.String,UnityEngine.Vector3]使用报错

### ISSUE THREAD

**Issue by lfs1023** [Tencent/xLua#135]
Dictionary`2[System.String,System.String]使用正常，但是Dictionary`2[System.String,UnityEngine.Vector3]使用报错，提示没有此类型，自己定义的类型放进去也会报错。测试过程如下：

定义：local DicStringString = CS.System.Collections.Generic["Dictionary`2[System.String,System.String]"]
使用：local dic = DicStringVector3()
正常！

定义：local DicStringVector3 = CS.System.Collections.Generic["Dictionary`2[System.String,UnityEngine.Vector3]"]
使用：local dic = DicStringVector3()
报错：No such type: System.Collections.Generic.Dictionary`2[System.String,UnityEngine.Vector3]

**Comment by lfs1023** [comment]
尝试在加了LuaCallCSharp白名单列表中加入了：
list.Add(typeof(Dictionary<string, Vector3>));

Gen目录下已经生成：
SystemCollectionsGenericDictionary2SystemStringUnityEngineVector3Wrap

仍然提示No such type

**Comment by lfs1023** [comment]
上面的文本，因为web页面问题，有些地方把方括号给我搞丢了，我的语法是正确的。

**Comment by lfs1023** [comment]
上面的文本，因为web页面问题，有些地方把方括号给我搞丢了，我的语法是正确的。

**Comment by chexiongsheng** [comment]
除mscorlib，Assembly-CSharp程序集之外的类型都不支持，你可以用C#的反射来创建
~~~lua
local dic = CS.System.Activator.CreateInstance(CS.System.Type.GetType('System.Collections.Generic.Dictionary`2[[System.String, mscorlib],[UnityEngine.Vector3, UnityEngine]],mscorlib'))
dic:Add('a', CS.UnityEngine.Vector3(1, 2, 3))
print(dic:TryGetValue('a'))
~~~
