### ISSUE TITLE
全平台编译报错：Error:Exception! System.InvalidOperationException: Operation is not valid due to the current state of the object.

### ISSUE THREAD

**Issue by lfs1023** [Tencent/xLua#137]
全平台编译报错：
Error:Exception! System.InvalidOperationException: Operation is not valid due to the current state of the object.

我使用了自定义编译工具，编译前修改了宏定义，引起Application.isCompiling为true
期望效果是，等待Application.isCompiling为false，然后再编译

很多项目都会自定义编译工具，一般都会修改宏定义，希望XLUA框架上能考虑这个问题。。

**Comment by chexiongsheng** [comment]
我这没这样的环境，所以也不知道怎么改，怎么调试。
很简单的话，你自行修改下就可以了。

**Comment by lfs1023** [comment]
OK
