### ISSUE TITLE
System.Action,在安卓手机上报错,pc上正常

### ISSUE THREAD

**Issue by chenqiu1988** [Tencent/xLua#138]
我已经把	 typeof(Action<object>), type(Action) 加进了csharpcalllua, 在编辑器里面测试没有问题,打包到安卓之后,报以下错,请问一般是什么原因呢?
InvalidCastException: This delegate must add to CSharpCallLua: System.Action

**Comment by chexiongsheng** [comment]
手机打包前要执行生成代码。

**Comment by chenqiu1988** [comment]
可能是我没有生成代码的问题 我用了NGUI  代码里面各种宏定义 其中有的用了unity_editor 和!MOBILE等区分函数 切换到Android build  导致生成代码各种报错 必须一个个去解决 所以我就没有生成代码 这种报错情况 有无什么快捷的方案解决类似问题

**Comment by chexiongsheng** [comment]
就得一个个解决，或者向以及解决的人那要一份。。我印象中github就有人做好了放上去的，你看看

**Comment by chenqiu1988** [comment]
我已经一个个加入了blacklist,解决了,谢谢,要是能根据平台生成代码就更完美了
