### ISSUE TITLE
lua 传给c# 一个指针，是否可以自定义包装函数？

### ISSUE THREAD

**Issue by daaoling** [Tencent/xLua#141]
lua 传给c# 一个指针，是否可以自定义包装函数？ 
可能我描述不是很明白,比如
lua
   lua_push(msg) (msg = char*)
c# 
  lua_push(type msg) 这个type是啥娃？

后来我看了一下xlua的底层

        private object getIntptr(RealStatePtr L, int idx, object target)
        {
            return LuaAPI.lua_touserdata(L, idx);
        }

这里面如果这个指针是c给lua, 然后lua给c#的话 不是意味着不是userdata了嘛？

**Comment by chexiongsheng** [comment]
C给lua，一般都是以ligthuserdata给，也是userdata，lua_touserdata也能转成指针。
前半段不明白你问什么。

**Comment by daaoling** [comment]
哦 是这样的 本地c库传一个指针给lua， 我想在c#层拿到这个指针，并且这个指针是作为函数的参数传入的.

**Comment by chexiongsheng** [comment]
可以，就上个回复

**Comment by daaoling** [comment]
恩 主要是checktype push之类的一些底层可能需要扩展下, 算了, 我看下底层代码吧。
