### ISSUE TITLE
luajit-ios 的编译问题

### ISSUE THREAD

**Issue by mzxnzzk** [Tencent/xLua#142]
使用新的工程编译Luajit-ios，打包出来的xlua.a有warning libluajit.a armv7/armv7s has no symbol,这时候打包出来的libxlua.a大小为550k左右，发布到xcode下，存在链接错误，找不到xlua相关的接口（数十个error）；
使用release（2.1.6） 版本的luajit打包的libxlua.a，大小为1.3M左右，发布到xcode下，仍然存在链接错误(1个error,
Apple Mach-O Linker(ld) Error
Linker command failed with exit code 1 (use -v to see invocation))
使用lua53版本的libxlua.a，直接替换掉xcode项目中的.a，可以正常发布和运行，表现正常

**Comment by chexiongsheng** [comment]
550k那个so应该是luajit没编译成功导致，你留意第一个错误。我的环境是可以正常编译的。

至于release版本，luajit版本尚不支持bitcode，你把xcode的编译选项关闭这个选项就能通过。

**Comment by mzxnzzk** [comment]
550k那个.so编译时只有warning（类似libluajit.a armv7/armv7s has no symbol）没有error，但打出来只有550k左右；换了两台mac编译都是一样的表现，环境搭建应该只需要CMAKE和XCODE吧？还是说需要一些其它支持

**Comment by chexiongsheng** [comment]
应该还要gcc吧，通过xcode安装的。

**Comment by mzxnzzk** [comment]
gcc也是有的

**Comment by mzxnzzk** [comment]
lua53版本的可以正常编译和使用的

**Comment by chexiongsheng** [comment]
lua53的编译是全走cmake。
luajit版本是先调用luajit的编译编译libluajit.a，然后用cmake编译xlua相关代码，然后用libtool合并成一个lib，你看看问题出在哪一步，如果是最后一步其实是可以省略的，你libluajit.a和libxlua.a都拷贝过去就可以了。

**Comment by mzxnzzk** [comment]
最后链接我那里出了点问题，使用自动化脚本在libtool合并那里出错了，已经解决了，谢了

**Comment by yiyucyp** [comment]
> 最后链接我那里出了点问题，使用自动化脚本在libtool合并那里出错了，已经解决了，谢了

怎么解决的能说下吗

**Comment by bab409866** [comment]
> 550k那个so应该是luajit没编译成功导致，你留意第一个错误。我的环境是可以正常编译的。
> 
> 至于release版本，luajit版本尚不支持bitcode，你把xcode的编译选项关闭这个选项就能通过。

你好，请问到是否到现在，release版本的 luajit版本是否还是不支持bitcode。
那么在正式项目中使用时，选择luajit的debug版本会有哪些潜在的弊端。
