### ISSUE TITLE
关于使用LuaTable.Get<T>方法时的问题

### ISSUE THREAD

**Issue by iNeverSleeeeep** [Tencent/xLua#146]
在lua中有类型为userdata的全局变量O。而这个userdata的结构是在c++的环境中定义的。O包含一个getName()方法
声明以下接口
```
        [CSharpCallLua]
        public interface IObj
        {
            string getName();
        }
```
这样，如果我直接用*Global.Get\<IObj\>("O")*，返回的指针为空。这种情况，我有可能在c#侧添加什么代码，来实现在C#层对于变量*O*的引用吗？

**Comment by chexiongsheng** [comment]
要引用比较简单，Global.Get<IntPtr>你就能拿到这个指针。

**Comment by iNeverSleeeeep** [comment]
我想通过像xlua自带的那种方式绑定，可以实现吗？
如果能实现的话能给个大概思路吗？

**Comment by iNeverSleeeeep** [comment]
我有一个想法。不知道能不能行得通。
lua的函数调用我的理解是一个function和一个self确定。
这样 如果是一个不能识别的userdata，我在调用它的方法的时候，就把IntPtr和函数名压到栈里，然后调用一下pcall是不是就可以了？

**Comment by chexiongsheng** [comment]
用table+metatable封装给C#，C#用interface调用

**Comment by iNeverSleeeeep** [comment]
好办法
