### ISSUE TITLE
unity5.5.3 ios运行时闪退

### ISSUE THREAD

**Issue by lfs1023** [Tencent/xLua#147]
#0	0x00000001018dba90 in il2cpp::icalls::mscorlib::System::Object::GetType(Il2CppObject*) at /Users/builduser/buildslave/unity/build/Tools/il2cpp/il2cpp/libil2cpp/icalls/mscorlib/System/Object.cpp:24
#1	0x00000001007281f8 in ::OverloadMethodWrap_Init_m1302647323(OverloadMethodWrap_t1422847581 *, ObjectCheckers_t3937197 *, ObjectCasters_t3695619658 *, const MethodInfo *) at /Users/weimei/Desktop/WMHD/P02_Tags/Product/xxios/Classes/Native/Bulk_Assembly-CSharp_34.cpp:359819
#2	0x0000000100726ec4 in ::MethodWrapsCache__GenMethodWrap_m4289822449(MethodWrapsCache_t4056581618 *, Type_t *, String_t *, Il2CppObject *, const MethodInfo *) at /Users/weimei/Desktop/WMHD/P02_Tags/Product/xxios/Classes/Native/Bulk_Assembly-CSharp_34.cpp:338589
#3	0x000000010074aeec in ::Utils_makeReflectionWrap_m2424205106(Il2CppObject *, IntPtr_t, Type_t *, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, lua_CSFunction_t10472361 **, lua_CSFunction_t10472361 **, bool, const MethodInfo *) at /Users/weimei/Desktop/WMHD/P02_Tags/Product/xxios/Classes/Native/Bulk_Assembly-CSharp_35.cpp:11055
#4	0x000000010074bfe0 in ::Utils_ReflectionWrap_m4083470672(Il2CppObject *, IntPtr_t, Type_t *, const MethodInfo *) at /Users/weimei/Desktop/WMHD/P02_Tags/Product/xxios/Classes/Native/Bulk_Assembly-CSharp_35.cpp:11709
#5	0x000000010072f9dc in ::ObjectTranslator_TryDelayWrapLoader_m786891116(ObjectTranslator_t2220652049 *, IntPtr_t, Type_t *, const MethodInfo *) at /Users/weimei/Desktop/WMHD/P02_Tags/Product/xxios/Classes/Native/Bulk_Assembly-CSharp_34.cpp:344757
#6	0x0000000100742324 in ::StaticLuaCallbacks_ImportType_m3914329362(Il2CppObject *, IntPtr_t, const MethodInfo *) at /Users/weimei/Desktop/WMHD/P02_Tags/Product/xxios/Classes/Native/Bulk_Assembly-CSharp_35.cpp:4473
#7	0x0000000100742548 in ::ReversePInvokeWrapper_StaticLuaCallbacks_ImportType_m3914329362(intptr_t) at /Users/weimei/Desktop/WMHD/P02_Tags/Product/xxios/Classes/Native/Bulk_Assembly-CSharp_35.cpp:4554
#8	0x0000000101af0324 in csharp_function_wrap ()
#9	0x0000000101accbfc in luaD_precall ()
#10	0x0000000101ae7a50 in luaV_execute ()
#11	0x0000000101acd054 in luaD_call ()
#12	0x0000000101ae2b5c in luaT_callTM ()
#13	0x0000000101ae7a28 in luaV_execute ()
#14	0x0000000101acd0e0 in luaD_callnoyield ()
#15	0x0000000101acc458 in luaD_rawrunprotected ()
#16	0x0000000101acd69c in luaD_pcall ()
#17	0x0000000101ac293c in lua_pcallk ()
#18	0x0000000100629c9c in Lua_lua_pcall_m2257336719 [inlined] at /Users/weimei/Desktop/WMHD/P02_Tags/Product/xxios/Classes/Native/Bulk_Assembly-CSharp_34.cpp:332561
#19	0x0000000100629c88 in ::DelegateBridge___Gen_Delegate_Imp26_m1260279622(DelegateBridge_t3830961628 *, Il2CppObject *, const MethodInfo *) at /Users/weimei/Desktop/WMHD/P02_Tags/Product/xxios/Classes/Native/Bulk_Assembly-CSharp_34.cpp:127381
#20	0x000000010022e0c0 in ::U3CCreateTcpClientU3Ec__AnonStorey8_U3CU3Em__0_m3122276119(U3CCreateTcpClientU3Ec__AnonStorey8_t1524651749 *, const MethodInfo *) at /Users/weimei/Desktop/WMHD/P02_Tags/Product/xxios/Classes/Native/Bulk_Assembly-CSharp_14.cpp:30135
#21	0x000000010081d768 in ::EDTcpClientManager_FixedUpdate_m1269088710(EDTcpClientManager_t3720283190 *, const MethodInfo *) at /Users/weimei/Desktop/WMHD/P02_Tags/Product/xxios/Classes/Native/Bulk_Assembly-CSharp_8.cpp:7803
#22	0x0000000100fa73e0 in RuntimeInvoker_Void_t1841601450(MethodInfo const*, void*, void**) at /Users/weimei/Desktop/WMHD/P02_Tags/Product/xxios/Classes/Native/Il2CppInvokerTable.cpp:861
#23	0x0000000101913cf0 in il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppException**) ()
#24	0x000000010137a3cc in ::Invoke() at /Users/builduser/buildslave/unity/build/Runtime/Scripting/Backend/ScriptingInvocation.cpp:288
#25	0x000000010145a88c in Invoke [inlined] at /Users/builduser/buildslave/unity/build/Runtime/Scripting/Backend/ScriptingInvocation.h:80
#26	0x000000010145a878 in CallMethodIfAvailable [inlined] at /Users/builduser/buildslave/unity/build/Runtime/Mono/MonoBehaviour.cpp:462
#27	0x000000010145a838 in ::CallUpdateMethod() at /Users/builduser/buildslave/unity/build/Runtime/Mono/MonoBehaviour.cpp:560
#28	0x0000000101179dfc in UpdateBehaviour [inlined] at /Users/builduser/buildslave/unity/build/Runtime/GameCode/Behaviour.cpp:191
#29	0x0000000101179df0 in ::CommonUpdate<FixedBehaviourManager>() at /Users/builduser/buildslave/unity/build/Runtime/GameCode/Behaviour.cpp:153
#30	0x0000000101288704 in ::PlayerLoop() at /Users/builduser/buildslave/unity/build/Runtime/Misc/PlayerLoop.cpp:154
#31	0x00000001014b8570 in ::UnityPlayerLoopImpl() at /Users/builduser/buildslave/unity/build/PlatformDependent/iPhonePlayer/LibEntryPoint.mm:218
#32	0x00000001000c5210 in ::UnityRepaint() at /Users/weimei/Desktop/WMHD/P02_Tags/Product/xxios/Classes/UnityAppController+Rendering.mm:266
#33	0x00000001000c50fc in ::-[UnityAppController(Rendering) repaintDisplayLink]() at /Users/weimei/Desktop/WMHD/P02_Tags/Product/xxios/Classes/UnityAppController+Rendering.mm:79
#34	0x0000000105a504fc in __clang_call_terminate ()
#35	0x00000001945da600 in CA::Display::DisplayLinkItem::dispatch(unsigned long long) ()
#36	0x00000001945da4b0 in CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) ()
#37	0x0000000191637dd4 in IODispatchCalloutFromCFMessage ()
#38	0x0000000191361958 in __CFMachPortPerform ()
#39	0x0000000191379adc in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ ()
#40	0x000000019137927c in __CFRunLoopDoSource1 ()
#41	0x0000000191376d90 in __CFRunLoopRun ()
#42	0x00000001912a6d94 in CFRunLoopRunSpecific ()
#43	0x0000000192d10074 in GSEventRunModal ()
#44	0x000000019755f130 in UIApplicationMain ()
#45	0x00000001000bef1c in main at /Users/weimei/Desktop/WMHD/P02_Tags/Product/xxios/Classes/main.mm:32
#46	0x00000001902b559c in start ()

**Comment by lfs1023** [comment]
4月18日下载的最新xlua版本

**Comment by chexiongsheng** [comment]
这是反射调用，你看看反射调用的是哪个类的哪个函数。
然后按同样的函数声明写个测试例子看看是不是会crash。
重现了就发这里我定位下。

当然，规避也简单，你打印到这个类后，把它加到LuaCallCSharp。

**Comment by chexiongsheng** [comment]
如果你放到LuaCallCSharp后不crash的话，也可以把函数声明发到这

**Comment by lfs1023** [comment]
嗯 正在调试看哪行代码

**Comment by chexiongsheng** [comment]
OverloadMethodWrap.Init函数

**Comment by lfs1023** [comment]
前面几百行代码都没问题，运行到这行报错的：
resIcon:GetComponent("Image").sprite = CS.Common.GetSprite(data.iconName)

GetSprite函数：
public static Sprite GetSprite(string sprite){
        string spritPath = "BuildOut/Sprite/" + sprite +".prefab";
        GameObject goSprite = ResourceLoader.inst.LoadSync(spritPath) as GameObject;
		if(goSprite == null){
			Debug.LogError("ERROR! Sprite预置加载失败！路径："+ spritPath);
			return null;
		}else{
			return goSprite.GetComponent<SpriteRenderer>().sprite;
		}
    }

**Comment by lfs1023** [comment]
安卓、pc、Mac 都没有问题

**Comment by chexiongsheng** [comment]
不科学啊，这没啥特别的。
你把Common加到LuaCallCSharp试试

**Comment by lfs1023** [comment]
加了LuaCallCSharp就不闪退了，我现在就还在研究为什么只有IOS有问题

**Comment by lfs1023** [comment]
local coms = prefabEffect:GetComponentsInChildren(typeof(CS.UnityEngine.ParticleSystem))
            if coms.Length~=0 then
                for i = 0,coms.Length-1 do
                    local ps = coms[i]
                    local mm = ps.main
                    mm.startDelay = CS.UnityEngine.ParticleSystem.MinMaxCurve(0)
                end
            end
类似的问题是上面这段代码，找不到startDelay，提示：no such field

**Comment by chexiongsheng** [comment]
这个应该是被il2cpp剪裁了，你要把那个类加到LuaCallCSharp或者ReflectionUse。

**Comment by chexiongsheng** [comment]
但你第一个错误比较奇怪，是调用GetType的时候崩的，Init调GetType表示那个函数有默认值。但你GetSprite根本没有默认值。

**Comment by chexiongsheng** [comment]
你可以在OverloadMethodWrap的Init那加个日志么，看崩的时候处理哪个类的哪个函数

**Comment by lfs1023** [comment]
裁剪那个我明白了，之前看文档提过，后来很久没遇到过问题就忘了。
那我想想办法做个白名单，把所有类型都加到LuaCallCSharp或者ReflectionUse。

我加个日志看看，有结果了回复你。

**Comment by lfs1023** [comment]
生成代码报错：
1. gen wrap file fail! err=TemplateCommon:207: attempt to index a function value (local 't')

2. Assets/XLua/Gen/XLuaGenAutoRegister.cs(473,19): error CS0673: System.Void cannot be used from C#. Consider using `void'

代码很多，所有代码都可能被热修复，所以只能通过白名单的方式来加Reflectionuse，请问有没有比较好的加白名单的方式呢？ 我已经尝试了一晚上了，实在没办法了。。

**Comment by lfs1023** [comment]
//避免代码裁剪
    [ReflectionUse]
    public static List<Type> ReflectionUse
    {
        get
        {
            List<Type> lst = (from type in Assembly.Load("Assembly-CSharp").GetTypes()
                    where ( true)
                    select type).ToList();
            return lst;
        }
    }

**Comment by lfs1023** [comment]
今天来开机重启unity，又打了几次包，去掉luacallcsharp以后也没有闪退了。。
上周五无论怎么打包都闪退来着。。

**Comment by lfs1023** [comment]
哦，原来是因为我今天用的ipad，ipad不闪退，iphone仍然闪退

**Comment by chexiongsheng** [comment]
那你帮忙看下是初始化哪个函数crash的。调用GetSprite不一定是GetSprite的问题，第一次调第一个函数，会把整个类的所有函数都加载。

**Comment by lfs1023** [comment]
CALL Init, targetType:Common, method:xxx
CALL Init, targetType:Common, method:yyy
CALL Init, targetType:Common, method:zzz
CALL Init, targetType:Common, method:...
CALL Init, targetType:Common, method:UnityEngine.MonoBehaviour AddChild[MonoBehaviour]
运行到这里闪退！！！

addchild方法定义如下，应该喝范型有关？
public static T AddChild<T>(GameObject parent, string path, int siblingIndex=-1, string goName="", bool isSetSizeZero = true) where T : MonoBehaviour
{
    ...
}

但是前面还有个方法，直接被跳过了，没有打印：
public static T TryGetValue<T>(Dictionary<string,object> dic, string key, object defaultValue = null)
{
   ...
}

**Comment by lfs1023** [comment]
看起来是因为写了个：where T : MonoBehaviour

**Comment by lfs1023** [comment]
CALL Init, targetType:Common, method:UnityEngine.Component GetOrAddComponent[Component](UnityEngine.GameObject)

这个也没有引起闪退，也有where t，定义如下：

public static T GetOrAddComponent<T>(GameObject go) where T : Component
{
       ...
}

**Comment by YaoYilin** [comment]
public static T GetOrAddComponent<T>(GameObject go)where T : MonoBehaviour 应该这么写吧？

**Comment by chexiongsheng** [comment]
栈显示是和默认值有关

**Comment by lfs1023** [comment]
public static T AddChild < T > (GameObject parent, string path, int siblingIndex=-1, string goName="", bool isSetSizeZero = true) where T : MonoBehaviour

这是函数声明，刚刚发的，有部分字符因为github的问题没显示出来

**Comment by chexiongsheng** [comment]
我这没重现，同样的声明。

**Comment by chexiongsheng** [comment]
也可能是机器，unity版本之类的原因。
你那最好能够搞个能重现的最小demo

**Comment by lfs1023** [comment]
嗯，我尝试搞个最小demo出来

**Comment by lfs1023** [comment]
不闪退的机器：所有安卓、所有pc、ipad(系统8.4.1)
闪退的机器：测试过的所有iphone（6台iphone，各种型号和系统版本）

**Comment by chexiongsheng** [comment]
好的，多谢，有劳

**Comment by lfs1023** [comment]
这段代码：
ParticleSystem ps = particleSystem;
ParticleSystem.MainModule mm = ps.main;
mm.startDelay = new ParticleSystem.MinMaxCurve(0f);

翻译成lua后：
local mm = ps.main
mm.startDelay = CS.UnityEngine.ParticleSystem.MinMaxCurve(0)

报错：
LuaException: cannot set startDelay, no such field

白名单如下：
[LuaCallCSharp]
public static List < Type >  LuaCallCSharp {
get
{
         List<Type> list =   
         Assembly.Load("UnityEngine.UI").GetExportedTypes()
         )Where(type => !type.IsGenericTypeDefinition)
        .Where(type => !type.IsNested)
        .Where(type => !isExcluded(type)).ToList();

	list.Add (typeof(ParticleSystem));
	list.Add (typeof(ParticleSystem.MainModule));

        return list;
     }
}

请问：
Lua怎么才能识别到startDelay这个field？

**Comment by chexiongsheng** [comment]
确实有这个字段的话，保证不被剪裁即可（这个字段所在的类加到LuaCallCSharp或者ReflectionUse）

**Comment by lfs1023** [comment]
这个类是UnityEngine.ParticleSystem的，我无法在源码中加入LuaCallCSharp
所以用了上述白名单

**Comment by chexiongsheng** [comment]
那个闪退问题，有整出一个能重新的小工程么？
