### ISSUE TITLE
error CS0122: `Mono.Cecil.MethodReference.ContainsGenericParameter' is inaccessible due to its protection level

### ISSUE THREAD

**Issue by staare-zx** [Tencent/xLua#15]
Unity4.7.2下，Editor\Data\Managed下只有Mono.Cecil.dll一个文件，没有Mono.Cecil.Pdb.dll，Mono.Cecil.Mdb.dll。而且复制Mono.Cecil.dll到Editor目录后报错：Assets/XLua/Src/Editor/Hotfix.cs(171,72): error CS0122: `Mono.Cecil.MethodReference.ContainsGenericParameter' is inaccessible due to its protection level

**Comment by yxriyin** [comment]
I found the same problem

**Comment by chexiongsheng** [comment]
对于老版本的cecil这个property是internal的，已经做了兼容，请pull下。 @staare-zx @yxriyin

**Comment by yxriyin** [comment]
现在已经好了 不过unity4木有Mono.Cecil.Pdb.dll，Mono.Cecil.Mdb.dll，所以开启HOTFIX_DEBUG_SYMBOLS也还是无法调试的样子，这个有办法吗

**Comment by chexiongsheng** [comment]
@yxriyin 找下和其配套的Mono.Cecil.Pdb.dll，Mono.Cecil.Mdb.dll？或者换个Unity版本？或者从别的版本的Unity拷贝一整套过来试试？

**Comment by yxriyin** [comment]
@chexiongsheng 可以了 非常感谢 我拷贝了一份5.1下面的两个文件过来
