### ISSUE TITLE
Mac下编译安卓 出现： Could not find toolchain file: ../cmake/android.toolchain.cmake

### ISSUE THREAD

**Issue by LazyPlanet** [Tencent/xLua#150]
脚本里面改了
export ANDROID_NDK=/Users/lazy/Library/Android/ndk/
然后执行脚本，出现如下状态：
localhost:build lazy$ sh make_android_lua53.sh 
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.8/Modules/CMakeDetermineSystem.cmake:94 (message):
  Could not find toolchain file: ../cmake/android.toolchain.cmake
Call Stack (most recent call first):
  CMakeLists.txt:17 (project)

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
make: *** No targets specified and no makefile found.  Stop.
cp: build_v7a/libxlua.so: No such file or directory
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.8/Modules/CMakeDetermineSystem.cmake:94 (message):
  Could not find toolchain file: ../cmake/android.toolchain.cmake
Call Stack (most recent call first):
  CMakeLists.txt:17 (project)

**Comment by LazyPlanet** [comment]
版本：android-ndk-r14b-darwin-x86_64.zip

**Comment by chexiongsheng** [comment]
我没在mac下编android，据成功的童鞋反馈，用r10版本才能成功

**Comment by yuanlairubi2016** [comment]
Mac r10e 好像也不行了
但是：下面这个可以编译过
export ANDROID_NDK=/Users/xxxxx/Library/Android/sdk/ndk/20.0.5594570
chmod 777 make_android_lua53.sh
./make_android_lua53.sh
