### ISSUE TITLE
LINUX64: To configure the toolchain set CMake variable ANDROID_TOOLCHAIN_NAME to one

### ISSUE THREAD

**Issue by LazyPlanet** [Tencent/xLua#151]
1 export ANDROID_NDK=~/android-ndk-r14b
  2 export ANDROID_TOOLCHAIN_NAME=x86_64-4.9
  3 echo $ANDROID_NDK
  4 echo $ANDROID_TOOLCHAIN_NAME

[game@iZ2zeerthpe64c45eu5v7eZ build]$ sh make_android_lua53.sh 
/home/game/android-ndk-r14b
x86_64-4.9
CMake Error at cmake/android.toolchain.cmake:739 (message):
  Specified toolchain "arm-linux-androideabi-clang3.6" is missing in your NDK
  or broken.  Please verify that your NDK is working or select another
  compiler toolchain.

  To configure the toolchain set CMake variable ANDROID_TOOLCHAIN_NAME to one
  of the following values:

    * aarch64-linux-android-4.9
    * arm-linux-androideabi-4.9
    * mips64el-linux-android-4.9
    * mipsel-linux-android-4.9
    * x86-4.9
    * x86_64-4.9

Call Stack (most recent call first):
  /usr/local/share/cmake-3.8/Modules/CMakeDetermineSystem.cmake:85 (include)
  CMakeLists.txt:17 (project)

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
gmake: *** No targets specified and no makefile found.  Stop.
cp: cannot stat `build_v7a/libxlua.so': No such file or directory
CMake Error at cmake/android.toolchain.cmake:739 (message):
  Specified toolchain "x86-clang3.5" is missing in your NDK or broken.
  Please verify that your NDK is working or select another compiler
  toolchain.

  To configure the toolchain set CMake variable ANDROID_TOOLCHAIN_NAME to one
  of the following values:

    * aarch64-linux-android-4.9
    * arm-linux-androideabi-4.9
    * mips64el-linux-android-4.9
    * mipsel-linux-android-4.9
    * x86-4.9
    * x86_64-4.9

Call Stack (most recent call first):
  /usr/local/share/cmake-3.8/Modules/CMakeDetermineSystem.cmake:85 (include)
  CMakeLists.txt:17 (project)

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
gmake: *** No targets specified and no makefile found.  Stop.
cp: cannot stat `build_x86/libxlua.so': No such file or directory

**Comment by Jayatubi** [comment]
https://developer.android.com/ndk/downloads/older_releases.html
https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip

**Comment by LazyPlanet** [comment]
@Jayatubi  多谢兄弟，只有r10版本没有问题，LINUX完美解决。非常非常感谢。

**Comment by cco203040** [comment]
cs nb

**Comment by cco203040** [comment]
zm zns

**Comment by lvchy** [comment]
用了 r10e ,还是有这个问题 。
