### ISSUE TITLE
我从服务器上down下来的lua代码，本地pc运行没问题，手机报错

### ISSUE THREAD

**Issue by momo25** [Tencent/xLua#154]
LuaException: xlua.access, no field __Hitfix0_ShowCellView

**Comment by momo25** [comment]
查了资料说是需要配置类型，我还是不懂要配置什么类型。例子 文档 我都没找到，求普及

**Comment by chexiongsheng** [comment]
手机平台要定义HOTFIX_ENABLE

**Comment by momo25** [comment]
定义了

**Comment by momo25** [comment]
我把lua放在本地 是没问题的   down下来的  我本地点下注入就可以运行 ，但是我打包到手机上就不能运行

**Comment by momo25** [comment]
为什么都是说宏定义没定义，没有点注入，cecil没copy  肯定不是这种啊   我本地lua已经测试过了，就是down下来的不行
