### ISSUE TITLE
关于代码被剪裁,请问具体会剪裁哪些代码,有详细文档么

### ISSUE THREAD

**Issue by w1ng** [Tencent/xLua#155]
情况是这样,最近打包代码到iOS上去真机测试的时候,发现一些`UnityEngine`的类的一些方法都找不到,例如`UnityEngine.PlayerPrefs`的`SetInt`,`UnityEngine.AssetBundle`的`LoadAsset`,目前用到的系统类我都已经直接对typeof(UnityEngine.xxxxxx)加了`LuaCallCSharp`,然而在Lua端打印`UnityEngine.PlayerPrefs`这种的时候,却发现只有几个方法,其中就没有我需要调用的那个,从而导致报错; 后面解决的办法是我写了个类似黑名单一样的List,前面加上了`LuaCallCharp`

    [LuaCallCSharp]  
    public static List<List<string>> WhiteList = new List<List<string>> () {
    		new List<string> (){"UnityEngine.PlayerPrefs","SetInt"},
    };

 因为`UnityEngine`的类太多了,也不知道以后到底会用到哪些,上线之后就没法再添加并导出代码了,觉得这样手动加不大对劲,请教一下这种情况应该怎么去处理

**Comment by chexiongsheng** [comment]
WhiteList是你自己写代码支持的？xlua没这个功能，你这个配置会被无视。

“整个类”加到LuaCallCSharp或者ReflectionUse，打包前“执行了代码生成”，就不会被剪裁。你加了LuaCallCSharp仍然被剪裁，应该是你加了后没重新生成代码，或者生成的时候没编译完毕，或者unity有换成导致没读到新的配置。

剪裁是il2cpp的行为，请参照相关文档。（按我测的大多数版本：业务代码不剪裁，业务代码引用到的引擎及c#系统api不剪裁。）
