### ISSUE TITLE
设备上就报错 LuaException: xlua.access, no field __Hitfix0_ Editor 正常

### ISSUE THREAD

**Issue by iMemento** [Tencent/xLua#158]
请问在UnityEditor里hotfix可以执行，到设备上就报错 LuaException: xlua.access, no field __Hitfix0_

我没有添加 HOTFIX_DEBUG_SYMBOLS 宏是因为这个原因么？

**Comment by iMemento** [comment]
HOTFIX_ENABLE;HOTFIX_DEBUG_SYMBOLS都 加过了也不行

**Comment by trarck** [comment]
这个怎么fix的？
