### ISSUE TITLE
使用后包的大小影响有多少？

### ISSUE THREAD

**Issue by WinterfellsSummer** [Tencent/xLua#16]
使用别的lua插件带来一个麻烦的问题就是包大小增大了很多，不知道xlua有没有什么好的解决办法？

**Comment by chexiongsheng** [comment]
xLua有luajit和lua版本，lua版本会小一点。
另外，性能不高的地方用反射，xLua的好处是反射和生成代码的支持程度是一样的，可以随意切换，而且如果标识了ReflectionUse后，会自动帮你防止代码剪裁。

**Comment by WinterfellsSummer** [comment]
同时加了luacallcsharp和hotfix标签，是生成两份代码吗
