### ISSUE TITLE
升级到了最新版本，lua代码中无法使用C#传送进来的hashtable对象

### ISSUE THREAD

**Issue by hanchong22** [Tencent/xLua#160]
以前在lua中这样访问 hashtable[key] 是可以正确获得value的，但将xlua升级到最新版本后这样取得的一直是nil

**Comment by chexiongsheng** [comment]
看下faq：https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/faq.md#thisstring-field或者thisobject-field操作符重载为什么在lua无法访问比如dictionarystring-xxx-dictionaryobject-xxx在lua中无法通过dicabc或者dicabc检索值

简单来说，string为key时，你只能用TryGetValue。

**Comment by hanchong22** [comment]
@chexiongsheng  我扩展了hashtable的方法：  public static int TryGetValue(this Hashtable ht,string key)，但在lua中这样使用
local _value = base_effect_values.TryGetValue(v)
报以下错误：
MyExpception.HandleException, e:XLua.LuaException: [string "chunk"]:16: attempt to call a nil value (field 'TryGetValue')

**Comment by chexiongsheng** [comment]
扩展方法看看扩展相关的faq，基本上你同时加上LuaCallCSharp和ReflectionUse就ok了。

另外，你用的是点，应该用:访问扩展方法。虽然这和报错没关系。

**Comment by hanchong22** [comment]
@chexiongsheng 可以了，谢谢
