### ISSUE TITLE
编译lua-rapidjson失败

### ISSUE THREAD

**Issue by Andrew-L** [Tencent/xLua#162]
CMakeLists.txt修改如下：
#begin rapidjson
set (RAPIDJSON_SRC lua-rapidjson/src/rapidjson.cpp)

set_property(
    SOURCE ${RAPIDJSON_SRC}
    APPEND
    PROPERTY COMPILE_DEFINITIONS
    LUA_LIB
)
list(APPEND THIRDPART_INC  lua-rapidjson/rapidjson/include)
set (THIRDPART_SRC ${THIRDPART_SRC} ${RAPIDJSON_SRC})
#end rapidjson

编译报错：
xLua/build/lua-rapidjson/src/values.hpp:225:10: error: calling a private
      constructor of class 'rapidjson::GenericValue<rapidjson::UTF8<char>,
      rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >'
                return details::toValue(L, idx, 0, allocator);
                       ^

**Comment by chexiongsheng** [comment]
参考下这里：https://github.com/chexiongsheng/build_xlua_with_libs
