### ISSUE TITLE
LuaJIT, Unity and PS4

### ISSUE THREAD

**Issue by CerosWare** [Tencent/xLua#164]
Hello:

I'm new to this. I compiled LuaJIT for PS4, and it built a **libluajit_ps4.a** file. I put it in the Plugins folder next to the **xlua.dll** file, but it doesn't seem to work, Am I missing some kind of link?

-Alejandro Guardado

**Comment by chexiongsheng** [comment]
complie c file in https://github.com/Tencent/xLua/blob/master/build/ and static link to libluajit_ps4.a. The suffix maybe not dll, it diffrence according to platform, for example, dll in window, so in android, a in ios...
it should be place in the right place, for example, "Assets/Plugins/x86_64" for window x64.

**Comment by CerosWare** [comment]
Hi:

I compiled the project and did a static link with LuaJIT, but after placing the files on the Plugins folder, it didn't work. This is the code I used:

`@set LJCOMPILE="%SCE_ORBIS_SDK_DIR%\host_tools\bin\orbis-clang" -c -Wall`
`@set LJLIB="%SCE_ORBIS_SDK_DIR%\host_tools\bin\orbis-ar" rcus`
`@set LJLINK=link /nologo`
`@set LJCOMPILE=%LJCOMPILE% -O2`
`@set TARGETLIB=libxlua.a`
`@set LUAJITPS4=libluajit_ps4.a`
`del %TARGETLIB%`

`@echo *******************************************************`
`@echo *** XLua COMPILING ***`
`@echo ******************************************************* `

`for %%f in (*.c) do (`
`  %LJCOMPILE% %%f`
`  @if errorlevel 1 goto :BAD`
`)`

`@echo *******************************************************`
`@echo *** XLua LINKING ***`
`@echo ******************************************************* `

`for %%f in (*.obj) do (`
`  %LJLINK% %%f %LUAJITPS4%`
`  @if errorlevel 1 goto :BAD`
`)`

`@echo *******************************************************`
`@echo *** XLua BUILDING AND CLEANING ***`
`@echo ******************************************************* `

`%LJLIB% %TARGETLIB% *.obj`
`@del *.obj`
`@echo === Successfully built XLua for PS4 ===`

`@goto :END`

`:BAD`
`@echo.`
`@echo *******************************************************`
`@echo *** XLua FAILED ***`
`@echo *******************************************************`
`@goto :END`

`:END`

**Comment by CerosWare** [comment]
Just as a note, I added all neccesary .h files on the src folder, and xLua compiles correctly (or it looks like it does)

**Comment by chexiongsheng** [comment]
What error report?

**Comment by chexiongsheng** [comment]
Compile to a .so file.
