### ISSUE TITLE
热更新问题

### ISSUE THREAD

**Issue by wzhfantastic** [Tencent/xLua#17]
热更新某个c#类的成员函数，如何在lua中访问该类的私有变量？

**Comment by chexiongsheng** [comment]
用反射，可以在C#那封装一下，简化了接口再给lua用

**Comment by wzhfantastic** [comment]
@chexiongsheng 
唔 
如果我的c#代码已经发布出去了，没有配置ReflectionUse，是不是可能无法使用反射？

我尝试了使用LuaCallSharp生成封装代码，但是热更新的lua代码中仍然访问不到类的成员变量，这是什么原因呢？

**Comment by chexiongsheng** [comment]
没配ReflectionUse，就可能被剪裁。

你那问题比较大可能是那个成员变量不是public的，或者大小写错误。检查下看看？

**Comment by wzhfantastic** [comment]
@chexiongsheng 
贴下代码了

----------c#-------------
[XLua.LuaCallCSharp]
[XLua.Hotfix(XLua.HotfixFlag.Stateful)]
public class CustomStatefulTest : MonoBehaviour{
    public int tick = 0;

    void Update () {
        ++tick;
    }
}

----------lua----------
xlua.hotfix(CS.CustomStatefulTest, {
	['.ctor'] = function(csobj)
        return {haha = 0}
    end;

    Update = function(self)
        print(self.tick)
    end
} )

**Comment by chexiongsheng** [comment]
如果你执行过Generate code，新加属性要重新执行下Generate code

**Comment by wzhfantastic** [comment]
在c# wrap文件里貌似注册了
Utils.RegisterFunc(L, Utils.GETTER_IDX, "tick", get_tick);
Utils.RegisterFunc(L, Utils.SETTER_IDX, "tick", set_tick);

**Comment by chexiongsheng** [comment]
Stateful方式传的是你构造函数返回的table，请看相应的文档。
你去掉Stateful就可以了。

**Comment by wzhfantastic** [comment]
唔唔 确实没仔细看文档 谢谢！
但是文档上有一句话没理解：
**Stateless比较适合无状态的类，有状态的话，你得通过反射去操作私有成员**
如果我同时标记stateless和LuaCallCSharp，会生成wrap，这时候访问变量还是反射吗？

**Comment by chexiongsheng** [comment]
私有变量只能走反射。
你生成了代码，公有的就走生成代码。

**Comment by wzhfantastic** [comment]
哦 这样啊 谢谢啦！
