### ISSUE TITLE
可以增加通用版本的使用说明吗

### ISSUE THREAD

**Issue by gitlsl** [Tencent/xLua#170]
现在的2份文档  xlua教程  xlua配置  都是对ut的，一个不懂UT的XLUA新手 看起来就会比较困难了，可否考虑出个通用版本的教程，覆盖 `相互调用`，`打补丁`这些核心的即可，相信对新手会有很大的帮助

**Comment by chexiongsheng** [comment]
是应该有的。我会逐渐完善文档，另外也会优化通用版本的易用性，比如通用版本用emit可以省掉生成代码这一步，但性能可以保持和生成代码一个水平线甚至更好。
开源其实不应该就我一个人在做，其实你们也可以帮忙完善这一块，欢迎大家给我提PR。
“相互调用”你看看教程，应该是通用的。

**Comment by gitlsl** [comment]
是的，开源就是要大家一起来完善，有机会我也分享一下我的学习经验，“相互调用” 我已经走通了，打补丁还在看，下次发布通用版记得`xlua.dll`哈

**Comment by chexiongsheng** [comment]
你是用在哪里？

**Comment by gitlsl** [comment]
我的目标是客户端运行wpf程序，每次更新都要下载整个dll并重启应用，下载是想定时从服务器获取xlua的补丁，免重启热更新自己？
