### ISSUE TITLE
xlua可以在 webGL上跑么，如果不能需要做哪些工作呢？

### ISSUE THREAD

**Issue by tangyiyang** [Tencent/xLua#175]
另外，xlua详细的工作原理有介绍文档么，lot of thanks! :)

**Comment by chexiongsheng** [comment]
webgl要求native plugin放源码，应该xLua的lua53版本比较容易做到，但暂时没规划支持，你可以先尝试下。
基本原理：http://gad.qq.com/article/detail/7156091
更深入看源码

**Comment by tangyiyang** [comment]
@chexiongsheng 感谢，我先看一下文档。:)
