### ISSUE TITLE
Is there any way to build iOS simulator app?

### ISSUE THREAD

**Issue by chenzaichun** [Tencent/xLua#178]
I found that there no simulator arch included in the libxlua.a, is there any way to include the i386 x86_64 for simulator?

**Comment by Jayatubi** [comment]
try the xlua.bundle

**Comment by chexiongsheng** [comment]
you can change the IOS_PLATFORM to "SIMULATOR" in CMakeLists.txt by adding:
set( IOS_PLATFORM "SIMULATOR")

and re-compile the libxlua.a
