### ISSUE TITLE
文档中有误

### ISSUE THREAD

**Issue by Mapz** [Tencent/xLua#18]
> OSX命令行 cp /Applications/Unity/Unity.app/Contents/Managed/Mono.Cecil.* Project/Assets/XLua/Src/Editor/

此处应该为

> OSX命令行 cp /Applications/Unity/Unity.app/Contents//FrameWorks/Managed/Mono.Cecil.* Project/Assets/XLua/Src/Editor/

**Comment by wzhfantastic** [comment]
这应该和unity版本有关吧

**Comment by chexiongsheng** [comment]
我在5.4.1f1是这么操作的，所以我也注明了是参考，要么我再注明下版本不同，命令行可能不同。
