### ISSUE TITLE
LuaEnv.Dispose时机问题

### ISSUE THREAD

**Issue by littlesome** [Tencent/xLua#187]
发现在卸载场景后（通过切换到一个空场景实现），调用LuaEnv.Dispose出现 “try to dispose a LuaEnv with C# callback!” 异常

发现过了一会儿，LuaBase的析构才会执行到，估计是这两行并不能确保GC完全
```C#
System.GC.Collect();
System.GC.WaitForPendingFinalizers();
```
或者Unity有什么机制在延迟销毁对象（不是很确定）

Dispose依赖于GC的实现感觉也不是很合理，能否提供一个AutoDispose这样的接口，标记这个LuaEnv为不可用，等检测到没有delegate_bridges剩余之后再自动lua_close呢？

**Comment by littlesome** [comment]
目前是这么临时解决的，继承一个LuaEnv，每帧TryDispose

```C#
    class LuaEnvEx : LuaEnv
    {
        public bool TryDispose()
        {
            if (translator == null)
                return true;

            Tick();

            if (!translator.AllDelegateBridgeReleased())
                return false;

            Dispose();

            return true;
        }
    }
```

**Comment by chexiongsheng** [comment]
你这问题是不是因为UnityEngine.Object.Destory到帧结束才解引用导致的？
http://answers.unity3d.com/questions/18651/difference-between-destroy-and-destroyimmediate-.html
你尝试在下一帧再Distroy看看？

**Comment by littlesome** [comment]
本想搞个小场景重现一下，结果小场景根本就没有这个问题，很尴尬。。。
目前排查会比较花时间，遇到类似问题的朋友可以尝试那个临时方案，这个issue就先关闭了
我这边继续排查，等有结果再在后面回复
