### ISSUE TITLE
Unity2017的代码生成问题

### ISSUE THREAD

**Issue by cnlas** [Tencent/xLua#188]
2017新加入的PlayableExtensions是在Struct上添加的扩展方法，如果进行导出，会有以下的问题：

Generator.cs里判定扩展方法的处理函数IsSupportedExtensionMethod里有这么一段
`if (parameterConstraints.Length == 0 || !parameterConstraints[0].IsAssignableFrom(extendedType))`
前面这部分parameterConstraints是通过 parameterType.GetGenericParameterConstraints()获得的，会把所有struct识别为“System.ValueType” 然后extendedType只要是struct都认为可以IsAssignableFrom
这就导致了Unity2017 因为新的PlayableExtensions生成了大量错误的代码。

这里增加一行
`if (parameterConstraints.Length > 1 && parameterConstraints[0] == typeof(System.ValueType) && !parameterConstraints[1].IsAssignableFrom(extendedType))  return false;`忽略第一个ValueType可以解决多生成代码的问题。
解决了上面的问题之后，还剩下一个问题，就是按照模板生成时，被识别为System.ValueType的struct不能作为非空对象用于生成的接口，需要按照上面的方法跳过ValueType，这样会被识别为UnityEngine.Playables.IPlayable，还是可空对象，可能需要修改模板lua代码特殊处理转换成UnityEngine.Playables.Playable的Struct。但是这样总感觉很别扭。不知道作者有没有什么优雅和通用些的修改方法。

测试方法：
在2017下导出UnityEngine.Playables.PlayableExtensions 和 UnityEngine.WheelHit
测试后面一个问题再导出一个AnimationClipPlayable

**Comment by chexiongsheng** [comment]
你用的是2.1.8么？你合入下这个commit试试：https://github.com/Tencent/xLua/commit/1b17ac0885be451f276741573533d2f70f19845a

**Comment by cnlas** [comment]
在2.1.8发现的问题，然后用的master最新代码问题还存在，1b17ac0这个commit解决了普通的Method，这个问题是Extension导致的，出错的代码在master最新的214行附近

**Comment by cnlas** [comment]
确认这个commit已修复：0a3c99d46f2ede522ed63e1fcb0beb3c14d779f2
感谢作者
