### ISSUE TITLE
关于在XLua介绍.ppt中性能测试

### ISSUE THREAD

**Issue by SachinKung** [Tencent/xLua#19]
1. 介绍下这个测试环境和机型
2. 这里的[max]列表示什么, xlua的数组1表示什么,

![qq20170104150348](https://cloud.githubusercontent.com/assets/7629149/21635216/549ccfce-d297-11e6-8ff7-54a800f05f91.png)

**Comment by chexiongsheng** [comment]
max是三者最高值，单位是每秒调用次数
1代表max * 1，换言之是最高值
0.15是max * 0.15
测试机型：Android是荣耀6+，IOS是iphone5c

这文档上的数据比较老了，有时间时重测一个版本，把测试结果和测试程序都公布出去。

**Comment by chexiongsheng** [comment]
当时版本没lua53的支持，都是luajit。
现在lua53和luajit还是有区别的。
