### ISSUE TITLE
lua协程中UnityWebRequest 调用send 方法后，后面的代码不再执行

### ISSUE THREAD

**Issue by AnCG7** [Tencent/xLua#192]
`local util = require 'xlua.util'
local yield_return = (require 'ScriptSrc/Core/CSCoroutine').yield_return
function Hotfix:Start()
	local co=coroutine.create(function ()self:HotfixCheckHandler() end);
	coroutine.resume(co)
end
function Hotfix:HotfixCheckHandler()
	local request = SH.CSU.Network.UnityWebRequest.Get("http://www.baidu.com");
	yield_return(request.Send());
	print("test invoke");
	--yield_return(CS.UnityEngine.WaitForSeconds(3))
        if (request.isDone) then
		if (request.isNetworkError) then
			print(request.error);
		else
                        print(“success”);
`

说明一下
1.我使用的是unity2017.1.0f3 UnityWebRequest 和之前的unity5.x 表面上没有太大变化
2.我将lua脚本和MonoBehaviour绑定，Hotfix:Start()方法会在 MonoBehaviour的Start方法调用的时候被调用
3.ScriptSrc/Core/CSCoroutine.lua 和 demo工程内的cs_coroutine.lua.txt 是一样的只是改了个名字
4.为了方便调用 SH.CSU.Network=CS.UnityEngine.Networking;
5.当前使用的是xlua的最新版，我刚更新过
问题：
1.当使用unity自带的UnityWebRequest发起网络请求的时候调用request.Send() 程序lua脚本就不再向下执行
2.我和WWW类请求的demo一样，已经在LuaCallCSharp列表中配置，WaitForSeconds ，WWW都正常
`               typeof(WaitForSeconds),
                typeof(WaitForEndOfFrame),
                typeof(WaitForFixedUpdate),
                typeof(WaitUntil),
                typeof(WaitWhile),
                typeof(AsyncOperation),
                typeof(ResourceRequest),`
3.我将yield_return(request.Send());直接去掉yield_return的调用来查看问题，改为直接调用request.Send()，之后的代码依旧没有执行
请问该如何处理，还是我忘记配置了什么

**Comment by chexiongsheng** [comment]
可能是异常了，关于协程中异常为啥不报错，看FAQ最后一条。

**Comment by AnCG7** [comment]
因为lua这边代码提示不好，大面积的代码我是通过C#写完之后，再直接改为lua脚本的。所以出现上述问题，大部分是因为方法访问 改用":" 我却用了“.” 来表示 导致异常，昨天我快郁闷死了，抱歉了，我犯了个很傻的问题
