### ISSUE TITLE
什么时候用冒号什么时候用.          UNITY 被XLUA转换后的API哪里看

### ISSUE THREAD

**Issue by HHHHHHHHHHHHHHHHHHHHHCS** [Tencent/xLua#195]
gameObject.GetComponent<Button>().onClick.AddListener(null);----------->C#
self:GetComponent("Button").onClick:AddListener()--------------->xlua

什么时候用  冒号，什么时候又用  点    呢？    这个 很晕   ...

**Comment by chexiongsheng** [comment]
用冒号还是点是个lua语法问题，请找下lua资料学习。

没有啥转换的api，把xLua教程看一遍，弄懂规律。https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/XLua%E6%95%99%E7%A8%8B.doc

**Comment by HHHHHHHHHHHHHHHHHHHHHCS** [comment]
谢谢
