### ISSUE TITLE
很多情况下 Lua 代码错误都抛 Unknown Lua Error 

### ISSUE THREAD

**Issue by pillar** [Tencent/xLua#196]
异常函数 ThrowExceptionFromError 中，很多时候 object err = translator.GetObject(L, -1) 的 err 是 null , 导致查找 Lua 代码错误很麻烦。我希望可以打印出完整的错误提示信息。其他人有遇到过吗？还是设置问题。另外，xlua 有调试工具吗？

**Comment by chexiongsheng** [comment]
之前没听过反馈。
你贴下能重现的代码？

**Comment by pillar** [comment]
不会意思，是因为我重写了 debug.traceback 导致的，注释掉就正常了，不会意思。我关了。
