### ISSUE TITLE
System.Linq extension method

### ISSUE THREAD

**Issue by yassir-ouali** [Tencent/xLua#198]
Hello everyone,
we  are testing xLua functionality to decide if we gonna use it in our project, I'm injecting a simple array to lua (string[] myArray) and I can print and access all its default methods and attributes such as myArray.Length, my issue is, I want to call an extension method of IEnumerable available with Linq(myArray.Contains(..)) but it didn't work so far, 
I tried to add to the config : 
[LuaCallCSharp]
    public static List<Type> LuaCallCSharp = new List<Type>()
    {
        typeof(System.Linq.Enumerable)
    };

unfortunately nothing changed !

**Comment by yassir-ouali** [comment]
@chexiongsheng do you have any idea ?

**Comment by chexiongsheng** [comment]
unity project?

**Comment by yassir-ouali** [comment]
yes it's a unity project

**Comment by chexiongsheng** [comment]
it may not work.
because in some os, such as ios, jit not work, so we can't instance the generic method(type) on the fly.

**Comment by yassir-ouali** [comment]
So it's not working because its a generic method, not because it's an extension ?

**Comment by chexiongsheng** [comment]
extension method that not a generic method is support.
extension method that is a generic method is partially support: the generic parameter must with a ref type constraints. 
so some usefull lib such as DOTween is support in xLua.
the normal extension method demo here:https://github.com/Tencent/xLua/blob/master/Assets/XLua/Tutorial/LuaCallCSharp/LuaCallCs.cs
the generic method support demo: https://github.com/Tencent/xLua/tree/master/Assets/XLua/Examples/09_GenericMethod

**Comment by yassir-ouali** [comment]
Okay thank you very much for your help !
