### ISSUE TITLE
关于win版本的luajit编译，报出缺少lua51.lib的错误

### ISSUE THREAD

**Issue by RainStar1989511** [Tencent/xLua#199]
在执行make_win64_luajit.bat的编译的时候，出现了错误信息
![3y9a2t tbp7 f_ 12lyy9](https://user-images.githubusercontent.com/17958662/29805423-543e5bda-8cbc-11e7-805b-928e7b3d0b5c.png)
应该是说在src中缺少一个lua51.lib的文件，然后查看cmakelists.txt看到
![xi3 rl8r a2s0bk i x7qs](https://user-images.githubusercontent.com/17958662/29805469-8c43b4da-8cbc-11e7-8ee0-89156d804e69.png)
也有写着需要这个lua51.lib文件。

请问是什么原因？是不是在网上找一个lua51.lib放进去，再编译就行了？

**Comment by chexiongsheng** [comment]
make_win64_luajit.bat前面一段是编译这个lib，你是那里出错了

**Comment by RainStar1989511** [comment]
你好，谢谢提醒。现在我使用vs2017的Developer Command Prompt for VS 2017来编译确实也生成了lib51.lib文件了。编译32位的luajit是编译成功了，但64位版本luajit还是出错了。
现在我的坏境配置是：
cmake-3.9.1-win64-x64   
vs2017

bat文件中，为了适应vs2017修改成这样(加粗就是改过的信息)，就是从新指向编译的bat的路径位置，但不知道有没有定位错误了，2017，VC编译器那里一共变成5个文件了vcvars32.bat , vcvars64.bat , vcvarsall.bat , vcvarsamd64_x86.bat , vcvarsx86_amd64.bat。编译32位的时候我是用了vcvars32.bat这个的，按理64位应该是用vcvars64.bat 就是了。

`@echo off
if exist "%VS150COMNTOOLS%" (
	set **VCVARS="%VS150COMNTOOLS%..\..\VC\Auxiliary\Build\"**
	goto build
	)  else (goto missing)


:build

**@set ENV64="%VCVARS%vcvars64.bat"**

call "%ENV64%"

echo Swtich to x64 build env
cd %~dp0\luajit-2.1.0b2\src
call msvcbuild_mt.bat static
cd ..\..

goto :buildxlua

:missing
echo Can't find Visual Studio 2017.
pause
goto :eof

:buildxlua
mkdir build_lj64 & pushd build_lj64
cmake -DUSING_LUAJIT=ON -G "Visual Studio 15 2017 Win64" ..
popd
cmake --build build_lj64 --config Release
md plugin_luajit\Plugins\x86_64
copy /Y build_lj64\Release\xlua.dll plugin_luajit\Plugins\x86_64\xlua.dll
pause`

这是错误信息
![rtba1 s3nogy7id _icum](https://user-images.githubusercontent.com/17958662/29811314-9d896d34-8cd5-11e7-928d-029fa56b0e59.png)

**Comment by chexiongsheng** [comment]
还是同样的原因，你先把cmake部分去掉，调通前面的。
ps一下，你安装个vs2015可能更快解决问题。

**Comment by RainStar1989511** [comment]
谢谢！！！解决了！vs2017 vc的Developer Command Prompt有32和64位2个版本，之前一直没看，一直用32位来编译，结果出来的lua51.lib文件是32位。今早发现，还有一个叫x64 Developer Command Prompt的命令提示工具，结果一次就通过了

**Comment by chexiongsheng** [comment]
@RainStar1989511 
Developer Command Prompt的32位和64位版本分别在哪个位置呢？
