### ISSUE TITLE
How can I find the source codes for plugin

### ISSUE THREAD

**Issue by colinchen1984** [Tencent/xLua#2]
At first , I wanna thank you guys for making such great tools which have blown my mind.
After took a glance at the project, I could't find the source codes or any links for plugin, so it's would be very great if u can offer a link to the source codes, or just a few keywords I can search it.
thanks again.

**Comment by chexiongsheng** [comment]
Plugin's source code is under the "build" directory (then "build" directory just under the project root).

**Comment by colinchen1984** [comment]
Shame on me
