### ISSUE TITLE
Example中HotFix2这个例子的最后一个测试报错

### ISSUE THREAD

**Issue by yxriyin** [Tencent/xLua#20]
calc.TestOut(100, out num, ref str, gameObject);
报：
LuaException: [string "chunk"]:4: test error
stack traceback:
	[C]: in function 'error'
	[string "chunk"]:4: in function <[string "chunk"]:2>
XLua.LuaEnv.ThrowExceptionFromError (Int32 oldTop) (at Assets/XLua/Src/LuaEnv.cs:360)
XLua.DelegateBridge.SystemInt32 (System.Object self, Int32 a, System.Double& b, System.String& c, System.Object go) (at Assets/XLua/Gen/DelegatesGensBridge.cs:565)
HotfixCalc.TestOut (Int32 a, System.Double& b, System.String& c, UnityEngine.GameObject go)
HotfixTest2.Start () (at Assets/XLua/Examples/08_Hotfix/HotfixTest2.cs:263)
版本unity4.6 其他都没问题

**Comment by chexiongsheng** [comment]
额，这是故意测试下在lua那抛异常能抛到C#那不。。
