### ISSUE TITLE
ReflectionUse is confusing

### ISSUE THREAD

**Issue by yassir-ouali** [Tencent/xLua#200]
Hello everyone,
I'm confused about using the ReflectionUse tag, it seems like in all of the cases I can use LuaCallCsharp and CsharpCallLua, so is there any particular case when it's necessary to use ReflectionUse tag.
Cheers

**Comment by yassir-ouali** [comment]
@chexiongsheng  please if you have any clarification, i tried to translate all  the Chinese documentation, but it wasn't clear for me !

**Comment by chexiongsheng** [comment]
ReflectionUse tag will gen a link.xml to avoid code strip, and using reflection to access c# from lua.
the advance of ReflectionUse is no gen code, so suitable for app is __TEXT sections sensitive, as we know, ios app has __TEXT sections size limit.
the disadvane of it is its perfroment.

i suggest api not calling frequently use ReflectionUse tag

**Comment by yassir-ouali** [comment]
Ok great that's clear enough, thank you very much !
