### ISSUE TITLE
请问. LuaCallCSharp  CSharpCallLua , 可不可以整个命名空间打标签的.

### ISSUE THREAD

**Issue by zhangdage** [Tencent/xLua#201]
如题.

**Comment by chexiongsheng** [comment]
用动态列表，可以任意你想的效果自动化批量配置
https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/configure.md

**Comment by zhangdage** [comment]
OK , 谢谢, 看文档不仔细,
