### ISSUE TITLE
注册全局函数

### ISSUE THREAD

**Issue by GardenG** [Tencent/xLua#204]
请问下如何注册Lua的全局函数，能在Lua下直接调用方法名即可调用C#绑定的函数？

**Comment by chexiongsheng** [comment]
先看首页链接的教程（最下面）

**Comment by GardenG** [comment]
感谢回复  不好意思，我只看到教程中C#访问全局的Lua函数，请问能明示吗？

**Comment by chexiongsheng** [comment]
foo = function() end
foo就是全局的了

max = math.max
本来不是全局的max是全局的了

不知道你想要啥
