### ISSUE TITLE
如何在lua中引入C++的动态链接库

### ISSUE THREAD

**Issue by xdestiny110** [Tencent/xLua#205]
我在Plugins中放入了一个名为`xxx.dll`的文件，lua脚本中用`local xxx = require("xxx")`进行引入
但运行时提示我找不到这个dll
我想问一下dll的搜索路径是哪些呢？在各个平台上是否有区别？
祝好

**Comment by chexiongsheng** [comment]
按这来：https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/XLua%E5%A2%9E%E5%8A%A0%E5%88%A0%E9%99%A4%E7%AC%AC%E4%B8%89%E6%96%B9lua%E5%BA%93.doc

**Comment by xdestiny110** [comment]
明白了，没发现有这个。Thx~

**Comment by xdestiny110** [comment]
多谢@chexiongsheng 的指点，已经整合完成，斗胆提几个意见...
1. [XLua增加删减第三方Lua库中](https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/XLua%E5%A2%9E%E5%8A%A0%E5%88%A0%E9%99%A4%E7%AC%AC%E4%B8%89%E6%96%B9lua%E5%BA%93.doc)有提到
>把xLua的C源码包解压到你Unity工程的Assets同级目录下  

这个应该不是必须的吧？最后需要的只是xlua.dll文件，应该不用放到特定的位置吧？

2. 现在添加第三方库需要手动修改`CMakeLists.txt`文件。如果是将`${THIRDPARTY_XXX}`这几个变量用`file(GLOB ...)`进行设置，只让用户设定第三方库源代码、头文件和链接库的路径会不会好一些？这样的话使用CMake-GUI或者命令行的时候只需要指定路径即可

3. 目前build里面只提供了在linux平台下进行编译的脚本文件。但如果有Android SDK的话，其实在Windows平台下也能使用CMake与Ninja进行编译。再提供一个相关的脚本我觉得比较方便。

初次接触项目，意见未必中肯，望海涵

**Comment by chexiongsheng** [comment]
1、只是给一个明确的指示，说放任意目录可能有的人会虚

2、有更好的做法，可以给我提PR，其实我cmake并不熟悉，都是现学现卖的；

3、android交叉编译是用网上找的tool_chain，这个说不支持window，如果你能让它支持，可以给我提PR，十分欢迎及感谢，o(∩_∩)o 哈哈
