### ISSUE TITLE
现在对c#生成lua的扩展方案了吗？关注xlua有半年了，非常有需求需要这个开发方案。

### ISSUE THREAD

**Issue by Githubxplabs** [Tencent/xLua#206]
现在对有c#生成lua的扩展方案了吗？关注xlua有半年了，非常有需求需要这个开发方案。

**Comment by chexiongsheng** [comment]
xlua本身没有。预研过，觉得可行的方案应该是类似il2cpp一样的il2lua方案，然而这方案已经和xlua没啥关系了：xlua是做C#和lua适配的，都没C#，还适配啥？

**Comment by chexiongsheng** [comment]
你可以关注下市面上的方案，貌似有能和xlua配合的。

**Comment by Githubxplabs** [comment]
想要的是全程都用C#开发，然后需要有热更新的需求的时候可以把需要热更新的C#代码转换成lua
下次更新新包的时候，全部转换成C#代码
想要的效果是这部分是可以自动做，而不是每次更新的时候需要手动写lua代码热更新

当然xlua已经很棒了
