### ISSUE TITLE
关于Android编译的问题

### ISSUE THREAD

**Issue by xdestiny110** [Tencent/xLua#207]
v2.1.9版本编译没有问题，但在`6aaa8b7`之后的提交编译全部报错
发现在`6aaa8b7`中将`inet_pton`改为了`inet_pton_w32`，并且宏定义指明只在WIN32下进行编译。这导致在Android下`options.c`的第277行会找不到对应的函数
我想确认一下现在的master在Android上编译是没有问题的吗？

**Comment by hlouis** [comment]
同样在 mac 上也会有编译问题
