### ISSUE TITLE
Loading script assembly "Library/ScriptAssemblies/Assembly-CSharp.dll" failed!

### ISSUE THREAD

**Issue by hadow** [Tencent/xLua#21]
AssemblyResolutionException: Failed to resolve assembly: 'UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
Mono.Cecil.BaseAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name, Mono.Cecil.ReaderParameters parameters)
Mono.Cecil.BaseAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name)
Mono.Cecil.DefaultAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name)
Mono.Cecil.MetadataResolver.Resolve (Mono.Cecil.TypeReference type)
Mono.Cecil.ModuleDefinition.Resolve (Mono.Cecil.TypeReference type)
Mono.Cecil.TypeReference.Resolve ()
Mono.Cecil.Mixin.CheckedResolve (Mono.Cecil.TypeReference self)
Mono.Cecil.MetadataBuilder.GetConstantType (Mono.Cecil.TypeReference constant_type, System.Object constant)
Mono.Cecil.MetadataBuilder.AddConstant (IConstantProvider owner, Mono.Cecil.TypeReference type)
Mono.Cecil.MetadataBuilder.AddParameter (UInt16 sequence, Mono.Cecil.ParameterDefinition parameter, Mono.Cecil.ParamTable table)
Mono.Cecil.MetadataBuilder.AddParameters (Mono.Cecil.MethodDefinition method)
Mono.Cecil.MetadataBuilder.AddMethod (Mono.Cecil.MethodDefinition method)
Mono.Cecil.MetadataBuilder.AddMethods (Mono.Cecil.TypeDefinition type)
Mono.Cecil.MetadataBuilder.AddType (Mono.Cecil.TypeDefinition type)
Mono.Cecil.MetadataBuilder.AddTypeDefs ()
Mono.Cecil.MetadataBuilder.BuildTypes ()
Mono.Cecil.MetadataBuilder.BuildModule ()
Mono.Cecil.MetadataBuilder.BuildMetadata ()
Mono.Cecil.ModuleWriter.<BuildMetadata>b__0 (Mono.Cecil.MetadataBuilder builder, Mono.Cecil.MetadataReader _)
Mono.Cecil.ModuleDefinition.Read[MetadataBuilder,MetadataBuilder] (Mono.Cecil.MetadataBuilder item, System.Func`3 read)
Mono.Cecil.ModuleWriter.BuildMetadata (Mono.Cecil.ModuleDefinition module, Mono.Cecil.MetadataBuilder metadata)
Mono.Cecil.ModuleWriter.WriteModuleTo (Mono.Cecil.ModuleDefinition module, System.IO.Stream stream, Mono.Cecil.WriterParameters parameters)
Mono.Cecil.ModuleDefinition.Write (System.IO.Stream stream, Mono.Cecil.WriterParameters parameters)
Mono.Cecil.ModuleDefinition.Write (System.String fileName, Mono.Cecil.WriterParameters parameters)
Mono.Cecil.AssemblyDefinition.Write (System.String fileName, Mono.Cecil.WriterParameters parameters)
XLua.Hotfix.HotfixInject () (at Assets/XLua/Src/Editor/Hotfix.cs:218)

**Comment by chexiongsheng** [comment]
哪个版本？直接运行例子还是加了[hotfix]到你们自定义的类呢？

**Comment by hadow** [comment]
@chexiongsheng 5.3.7p2 ，自定义的类

**Comment by chexiongsheng** [comment]
@hadow 麻烦发下自定义的类

**Comment by chexiongsheng** [comment]
@hadow 怎么联系？

**Comment by hadow** [comment]
using UnityEngine;
using System.Collections;
using XLua;
public class TestXLua : MonoBehaviour {

    [XLua.CSharpCallLua]
    public delegate double luaMax(double a, double b);

    XLua.LuaEnv luaenv = new XLua.LuaEnv();
    // Use this for initialization
    void Start () {
        
        var max = luaenv.Global.GetInPath<luaMax>("math.max");

        luaenv.DoString("CS.UnityEngine.Debug.Log('hello world')");
        Debug.Log("max:" + max(32, 12));
        //luaenv.Dispose();

	}
	
	// Update is called once per frame
	void Update () {
	
	}

    void OnGUI()
    {
        if(GUI.Button(new Rect(10, 100, 60, 15), "HotFix"))
        {
            luaenv.DoString(@"xlua.hotfix(CS.HotFixCalc,'Add',function(self,a,b)
                                        return a+b;                
                                         end               
                                    )");
        }

        if(GUI.Button(new Rect(50, 100, 60, 15), "Result"))
        {
            HotFixCalc fixCalc = new HotFixCalc();
            Debug.Log(fixCalc.Add(10, 50));
        }
    }
}


[Hotfix]
public class HotFixCalc
{
    public int Add(int a,int b)
    {
        return a - b;
    }
    public Vector3 Add(Vector3 a,Vector3 b)
    {
        return a - b;
    }
}

**Comment by hadow** [comment]
@chexiongsheng 我QQ396233160

**Comment by chexiongsheng** [comment]
@hadow 刚刚拿你发的代码试了没问题。。
你是神马版本的Unity？还有别的类标注了[Hotfix]么？

**Comment by hadow** [comment]
5.3.7p2  ，没有了，除了例子里面的

**Comment by chexiongsheng** [comment]
没加你那类是好的？
