### ISSUE TITLE
unity3d 2017.1.0f3 使用报错

### ISSUE THREAD

**Issue by Think-Jumper** [Tencent/xLua#212]
运行demo,helloworld,保持如下：
NullReferenceException: Object reference not set to an instance of an object
CSObjectWrapEditor.Generator..cctor () (at Assets/XLua/Src/Editor/Generator.cs:125)
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for CSObjectWrapEditor.Generator
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
UnityEditor.Build.BuildPipelineInterfaces+AttributeCallbackWrapper.OnProcessScene (Scene scene) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:91)
UnityEditor.Build.BuildPipelineInterfaces.OnSceneProcess (Scene scene, Boolean strict) (at C:/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:297)
UnityEditor.Build.BuildPipelineInterfaces:OnSceneProcess(Scene, Boolean)

生成代码菜单也报异常：
NullReferenceException: Object reference not set to an instance of an object
CSObjectWrapEditor.Generator..cctor () (at Assets/XLua/Src/Editor/Generator.cs:125)
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for CSObjectWrapEditor.Generator
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)

**Comment by Think-Jumper** [comment]
已自行解决，新手使用，不熟的情况下最好默认不打折扣导入demo的东西，让unity自己生成关联。

**Comment by Think-Jumper** [comment]
已自行解决，新手使用，不熟的情况下最好默认不打折扣导入demo的东西，让unity自己生成关联。

**Comment by CodeMasterYi** [comment]
所以到底是什么问题？

**Comment by chexiongsheng** [comment]
@CodeMasterYi 漏拷贝meta文件
