### ISSUE TITLE
打包apk运行后报错两个：

### ISSUE THREAD

**Issue by ea5y** [Tencent/xLua#217]
Unable to find AudioPluginOculusSpatializer
Unable to find libAudioPluginOculusSpatializer
调查发现，unity5.4以后unity自带oculus这个插件，我用的版本是unity5.6.2,但是我在api中找不到这两个类，想加黑名单也加不了。
然后我在AudioManager里面启用OculusSpatializeer插件，就只剩下面这个错误，剩下的这个错误，我怎么都解决不了，求帮助。

**Comment by chexiongsheng** [comment]
这和xlua没啥关系

**Comment by ea5y** [comment]
大佬不好意思啊，果然，我一个空项目打包也出这个提示，但是不影响运行，我unity5.6.2f1，感觉是unity的问题。
