### ISSUE TITLE
Example 关于第二个例子问题

### ISSUE THREAD

**Issue by Lemon-L** [Tencent/xLua#22]
luaEnv.DoString(luaScript.text, "LuaBehaviour", scriptEnv); 
换成 luaEnv.DoString("require 'LuaTestScript'", "LuaBehaviour", scriptEnv); 
lua文件已经放在Resoures目录下。
Error:
`LuaException: LuaTestScript.lua:15: attempt to index a nil value (global 'self')
stack traceback:
	LuaTestScript.lua:15: in function 'update'
XLua.LuaEnv.ThrowExceptionFromError (Int32 oldTop) (at Assets/xLua/Assets/XLua/Src/LuaEnv.cs:360)
XLuaGenDelegateImpl0.Invoke1 ()
LuaBehaviour.Update () (at Assets/xLua/Assets/XLua/Examples/02_U3DScripting/LuaBehaviour.cs:80)`

**Comment by chexiongsheng** [comment]
你为什么要放Resoures目录下呢，通过TextAsset直接引用的了。处理热更新的例子，全部例子都不用做任何事情，直接运行。
另外，你改了LuaBehaviour.cs？应该不会出现self为nil的情况呀？

**Comment by Lemon-L** [comment]
你好，是这样的，我看到XLua教程.doc 文档开头说，DoString("require 'byfile'") ,更建议这种方式， 我尝试了一下。
我只修改了LuaBehaviour.cs那一行代码。然后移动lua文件到Resources目录里，与第7个例子，相同的目录结构。

**Comment by chexiongsheng** [comment]
你看看LuaBehaviour.cs，这几行都存在吗？
scriptEnv = luaEnv.NewTable();

        LuaTable meta = luaEnv.NewTable();
        meta.Set("__index", luaEnv.Global);
        scriptEnv.SetMetaTable(meta);
        meta.Dispose();

        scriptEnv.Set("self", this);

**Comment by chexiongsheng** [comment]
哦，我知道了
luaEnv.DoString(luaScript.text, "LuaBehaviour", scriptEnv);
没传scriptEnv参数

**Comment by Lemon-L** [comment]
那几行代码都在的，我没有动其他代码，只换成了require方式。

**Comment by chexiongsheng** [comment]
要加后面两个参数
DoString("require 'byfile'"，"LuaBehaviour", scriptEnv )

**Comment by chexiongsheng** [comment]
scriptEnv不会自动设置给require的文件。。这个例子你不能通过require 方式，要require你得通过别的方式来传状态

**Comment by Lemon-L** [comment]
DoString("require 'byfile'"，"LuaBehaviour", scriptEnv ) 我第一条留言里已经改过了。
恩，有方式传状态吗，我在例子里并没有找到。
有相关xlua的qq群吗？

**Comment by chexiongsheng** [comment]
QQ群暂时还没有，建群了通知你

**Comment by Lemon-L** [comment]
好的，谢谢。

**Comment by chexiongsheng** [comment]
@lemon-li 刚建了QQ群：612705778

**Comment by delguoqing** [comment]
hi~方便问一下这个问题怎么解决么？
刚学lua，说得不对的话请见谅。

lua在加载一个新的模块的时候，其_ENV应该默认等于upvalue里面的_ENV。
那么在require一个模块的时候，这个模块的_ENV应该等于scriptEnv才对吧。
这算不算bug？

**Comment by chexiongsheng** [comment]
@delguoqing 算不算bug，你下载个原版的lua5.3试试就可以了，如果和原版的不一样，就是bug，否则不算。
