### ISSUE TITLE
[求助]General方案反射Hotfix失败

### ISSUE THREAD

**Issue by sisufo** [Tencent/xLua#221]
你好，

我的需求是，桌面应用可以通过动态读取lua脚本，替换出问题的代码达到hotfix的目的，您这个方案很棒，正是我所求的。

但是，现在遇到了一个问题，在执行XLuaTest这个示例工程时，XLua环境加载成功，调用Lua也没问题，
![image](https://user-images.githubusercontent.com/1243767/31542097-53fc4c3a-afd6-11e7-8747-6d30d69d0498.png)

但是到了Hotfix的时候就报错了，因为现有的文档都是Unity相关，所以一直没找到如何解决，下面是一些出错信息，麻烦帮看看，谢谢

出错的代码位置
![image](https://user-images.githubusercontent.com/1243767/31541674-0d6a1a50-afd5-11e7-8976-b25b012ba0c2.png)

出错的代码异常
```
xlua.access, no field __Hotfix0_Add
stack traceback:
	[C]: in field 'access'
	[string "Init"]:88: in field 'hotfix'
	[string "chunk"]:2: in main chunk
```

**Comment by chexiongsheng** [comment]
要用XLuaHotfixInject.exe注入那个exe。
你不需要用hotfix功能这个错误可以不管。

**Comment by sisufo** [comment]
感谢如此快速的回复
1. 大致感觉顺序应该是，使用Hotfix打标签->XLuaGenerate生成id_map->XLuaHotfixInject根据之前的东西修改assembly，最终实现hotfix，不知道对不对哈，因为没有跑通；
2. XLuaGenerate还是遇到了类似的问题，出错位置和信息如下，麻烦再帮看看
![image](https://user-images.githubusercontent.com/1243767/31593130-6773f204-b1f2-11e7-81be-3577d009d44f.png)
![image](https://user-images.githubusercontent.com/1243767/31593134-705b72de-b1f2-11e7-8b08-3ee5645e2c87.png)
~~~
c# exception:System.TypeAccessException: ������List`1Wrap59.Count62(IntPtr)�����Է������͡�System.Collections.Generic.List`1<<>f__AnonymousType6`2<CSObjectWrapEditor.Generator+MethodInfoSimulation,System.Collections.Generic.List`1<CSObjectWrapEditor.Generator+MethodInfoSimulation>>>��ʧ�ܡ�
   �� List`1Wrap59.Count62(IntPtr L)
stack traceback:
	[C]: in ?
	[C]: in metamethod '__index'
	TemplateCommon:144: in function 'ForEachCsList'
	[string "luatemplate"]:8: in main chunk
~~~

**Comment by chexiongsheng** [comment]
注入做了些改动，没测试Generate版本。。我看看

**Comment by chexiongsheng** [comment]
新修改引入个bug导致XLuaGenerate不可用。
XLuaGenerate是注入的前一步，而且和啥id_map没关。

**Comment by sisufo** [comment]
我的主要目的还是桌面开发传统winform客户端如何进行hotfix，github上的测试代码 XLuaTest 中的hotfix还是无法起作用，所以问了您之后说是，需要先进行 XLuaHotfixInject，但是尝试了多次还是无果

我的处理方法：
执行 `XLuaHotfixInject.exe XLuaTest.exe “”` （因为不知道search path 和 id_map_file_path 怎么填）

然后，就会报错

~~~
Error:Exception! System.InvalidOperationException: 序列不包含任何匹配元素
   在 System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   在 XLua.Hotfix.init(AssemblyDefinition assembly, IEnumerable`1 search_directorys) 位置 F:\xLua\Assets\XLua\Src\Editor\Hotfix.cs:行号 122
   在 XLua.Hotfix.HotfixInject(String inject_assembly_path, IEnumerable`1 search_directorys, String id_map_file_path, IEnumerable`1 cfg_check_types) 位置 F:\xLua\Assets\XLua\Src\Editor\Hotfix.cs:行号 473
~~~

看了代码，是要加载XLua.HotfixAttribute这些类型找不到，而这些类型只存在于 XLua.Mini.dll中，不在 XLuaTest.exe里，我就改了一些代码，从XLua.Mini.dll加载类型，然后再继续inject到 XLuaTest中，然后 又报错了

~~~
Error:Exception! System.ArgumentException: Member 'XLua.DelegateBridge' is declared in another module and needs to be imported
   在 Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
   在 Mono.Cecil.SignatureWriter.WriteTypeSignature(TypeReference type)
   在 Mono.Cecil.MetadataBuilder.AddField(FieldDefinition field)
   在 Mono.Cecil.MetadataBuilder.AddFields(TypeDefinition type)
   在 Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   在 Mono.Cecil.MetadataBuilder.AddTypeDefs()
   在 Mono.Cecil.MetadataBuilder.BuildTypes()
   在 Mono.Cecil.MetadataBuilder.BuildModule()
   在 Mono.Cecil.ModuleWriter.<BuildMetadata>b__0(MetadataBuilder builder, MetadataReader _)
   在 Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   在 Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   在 Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Stream stream, WriterParameters parameters)
   在 Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   在 Mono.Cecil.AssemblyDefinition.Write(String fileName)
   在 XLua.Hotfix.HotfixInject(String inject_assembly_path, String xlua_dll_path, IEnumerable`1 search_directorys, String id_map_file_path, IEnumerable`1 cfg_check_types) 位置 C:\Users\space\workspace\source\xLua\Assets\XLua\Src\Editor\Hotfix.cs:行号 513
~~~

现在感觉，有点误入歧途的感觉，求解惑；

万分感谢

**Comment by chexiongsheng** [comment]
@sisufo 要先基于XLua.Mini.dll编译好，然后用XLuaGenerate生成代码，然后再建新工程和生成代码，xlua源码一起编译，然后再XLuaHotfixInject。
看readme：https://github.com/Tencent/xLua/blob/master/General/README.md
或者看持续集成的配置，一个个命令都有：
https://github.com/Tencent/xLua/blob/master/.travis.yml

**Comment by sisufo** [comment]
@chexiongsheng  XLuaGenerate 不是可选的吗

**Comment by chexiongsheng** [comment]
@sisufo 你用hotfix就不是，包括刚刚发的readme，以及hotfix.md都明确说了。你得仔细看文档

**Comment by sisufo** [comment]
@chexiongsheng 请原谅，我把文档都看了好多遍了也没理解整个过程，现在看完代码现在有点感觉了。哈哈，过程如此曲折，我之前试过用generate，然后引入XLuaTestGenCode，但是，直接跑还是失败，原来是还需要inject XLuaTestGenCode的产出；刚试过了，成功了。我一直都在inject XLuaTest这个工程的产出。

不过会有另外一个问题，如果xlua要源码引入进行编译的话，对于一个工程如果有很多dll，怎么做到对所有dll都支持hotfix？比如，是不是能不用引入xlua源码，而只是引入dll就可以？不知道你们平时都是怎么在实际的工程里应用的

**Comment by chexiongsheng** [comment]
@sisufo unity借助其编辑器扩展倒是方便些，而通用版就没那么方便了。

放xlua源码的最大原因是生成代码和xlua核心代码必须得在同一个程序集。

**Comment by sisufo** [comment]
嗯，了解，和我理解的一样。现在起码知道整个过程怎么运作了。后面我看看再怎么整合一下，有进展再和你同步。

**Comment by Assxion** [comment]
@sisufo 老兄有进展么，我用XLuaGenerate进行生成代码，只有2.1.6版本可以成功

**Comment by sisufo** [comment]
@Assxion 生成代码没问题，只是不是不适用于我们
1. 对于非Unity的项目用起来会比较繁琐
2. 我们有多个dll，xlua没法进行部署，如果只是桌面应用的话，可以看看 [harmony](https://github.com/pardeike/Harmony) 这个方案
