### ISSUE TITLE
在lua那边好像能修改C#那边readonly的field

### ISSUE THREAD

**Issue by heroboy** [Tencent/xLua#224]
希望能抛出一个异常。

**Comment by chexiongsheng** [comment]
readonly做了个优化：既然不变，就不用每次都到C#那取，直接放到lua侧对应class的table里头，优化为table字段获取。
这的设置只是设置到lua侧的table，不会真的改了C#的readonly值。
当然，做了这个优化也可以做到异常，只是方案会复杂些，可能要动到一些底层设计，代价比较大。最近也没有时间。
暂时自己注意下可以接受不？或者你尝试帮忙改下，o(∩_∩)o 哈哈

**Comment by heroboy** [comment]
你说的优化，是已经做了吗？ 我看代码好像是没有做的：https://github.com/Tencent/xLua/blob/4f63d2acd0753163b0ab17e162081248d00fc6cd/Assets/XLua/Src/Utils.cs#L518

-----------------------

我想了一下，readonly不是static的，对每个对象这个值是不同的，不能做这个优化吧。

-----------------------

你觉得对于readonly的field应该是不在lua端设置这个setter呢（
 https://github.com/Tencent/xLua/blob/4f63d2acd0753163b0ab17e162081248d00fc6cd/Assets/XLua/Src/Utils.cs#L532
） ，还是应该在设置值的时候抛异常呢？（
https://github.com/Tencent/xLua/blob/4f63d2acd0753163b0ab17e162081248d00fc6cd/Assets/XLua/Src/Utils.cs#L164
）

**Comment by heroboy** [comment]
这是我现在的改动：
```csharp
static LuaCSFunction genFieldSetter(Type type, FieldInfo field)
{
	if (field.IsStatic)
	{
		。。。
	}
	else if (field.IsInitOnly)
	{
		return (L) =>
		{
			return LuaAPI.luaL_error(L, "Can't set readonly field: " + field.Name + " of type:" + type.FullName);
		};
	}
	else
	{
		。。。
	}
}
```

**Comment by chexiongsheng** [comment]
做了的，你定义一个readonly字段，然后在lua那rawget一下class对应的table看看。
要改的话，有好三个地方，分别对应反射，生成代码，以及emit。

**Comment by heroboy** [comment]
反射，生成代码我知道，但是什么时候会用到emit啊？

**Comment by chexiongsheng** [comment]
目前unity编辑器下或者非unity环境（比如原生mono，.net core等等）不生成代码就用emit

**Comment by heroboy** [comment]
有可能我的xlua比较老。在编辑器下，调用的都是反射的代码。而且我在CodeEmit里设置的断点都没有断下来。

现在的代码都是用emit了吗？

```csharp
public class SampleData
{
	public readonly int a = 123;
	public const int b = 999;
}
```
```lua
rawget(CS.SampleData, 'a') --反正这样返回的是nil
```

**Comment by heroboy** [comment]
哦，我知道了，我是生成过代码，但是这个类没有生成就用了反射。

**Comment by heroboy** [comment]
生成代码这里，readonly的好像已经去掉了。
https://github.com/Tencent/xLua/blob/4f63d2acd0753163b0ab17e162081248d00fc6cd/Assets/XLua/Src/Editor/Generator.cs#L367
