### ISSUE TITLE
windows下编译android失败

### ISSUE THREAD

**Issue by 1194451658** [Tencent/xLua#226]
你好，如题，我遇到了以下问题
![xlua](https://user-images.githubusercontent.com/4320428/31656326-db6f7806-b35d-11e7-88b5-9b7fdaefbb50.png)
----------------------------------------------------------
感觉是ndk那里出了问题。
不知道我这里哪里设置错误了，或者其他人有没有类似的问题。
如果可以能否告诉我，你们编译成功的开发环境都是什么版本。
----------------------------------------------------------
我的环境是：
android-ndk-r10e、visual studio2015、安装了Nsight Tegra、cmake版本3.4.3，编译xlua2.1.9。

**Comment by 1194451658** [comment]
多谢了

**Comment by 1194451658** [comment]
你好，我在linux下尝试了编译，但是还是没有成功。
我们的游戏项目需要接入一个修改过后的pbc，来支持protobuf-v3版本。所以还是想自己编译的。
由于对CMake不熟悉，细研究需要花费很多时间，所以还是请教问下，linux编译下的环境版本问题。
linux版本号，cmake版本号等。
PS：实际使用中的确遇到了很多问题，而且很解决起来很花时间。问下是否可以开启项目的wiki页，可以把一些问题例如，我这里遇到的自己编译的各种版本号问题，都记录到wiki上面。可以方便很多刚开始使用的新手。

**Comment by chexiongsheng** [comment]
linux是我们内部的，不过应该对linux版本没要求
$ cmake --version
cmake version 2.8.12.2

**Comment by xdestiny110** [comment]
@1194451658 要在windows上进行编译的话，cmake需要使用android  studio提供的cmake。cmake官网上的版本是不行的。对此我写过一个脚本pr上去过 #209。

**Comment by 1194451658** [comment]
谢谢了，我在linux下编译过去了。
windows编安卓太折腾了，感觉是CMake太折腾了。
我都感觉，都可以直接自己写NDK脚本，自己编译了
