### ISSUE TITLE
2017.2.0f3 Hoxfit Inject in Editor错误

### ISSUE THREAD

**Issue by kurong00** [Tencent/xLua#231]
点击Hoxfit Inject in Editor出现如下WARNING的提示是因为什么？
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319

Cannot determine the text encoding for the assembly location: 
XXX\Tools\XLuaHotfixInject.exe
Please add the correct encoding to MONO_EXTERNAL_ENCODINGS and try again.

**Comment by chexiongsheng** [comment]
那个exe是用.net3.5编译的，在5.5以上会报warning，一般没啥影响

**Comment by kurong00** [comment]
感谢！
