### ISSUE TITLE
iOS 模拟器下无法调用 xlua.c

### ISSUE THREAD

**Issue by bluexo** [Tencent/xLua#233]
在iOS模拟器下 new LuaEnv() 会报下面的错误：
```
dyld: lazy symbol binding failed: Symbol not found: _xlua_get_lib_version
```
Unity3D版本：2017.1.1 
MacOS版本：10.12 
xlua版本：2.1.10 用的最新的Release直接解压到Unity工程

**Comment by chexiongsheng** [comment]
库漏或者meta漏了

**Comment by chexiongsheng** [comment]
模拟器不支持，模拟器需要你自行编译库

**Comment by bluexo** [comment]
@chexiongsheng 需要编译成 MacOS 的库吗？

**Comment by chexiongsheng** [comment]
看这里：https://github.com/Tencent/xLua/blob/master/build/cmake/iOS.cmake#L105
试试设置IOS_PLATFORM为SIMULATOR看看

**Comment by cloudstlife** [comment]
@chexiongsheng 试试设置IOS_PLATFORM为SIMULATOR看看,是什么意思？

**Comment by cloudstlife** [comment]
@chexiongsheng 能说清楚点吗？

**Comment by chexiongsheng** [comment]
https://github.com/Tencent/xLua/blob/master/build/make_ios_lua53.sh
cmake -DIOS_PLATFORM=SIMULATOR -DCMAKE_TOOLCHAIN_FILE=../cmake/iOS.cmake  -GXcode ../
