### ISSUE TITLE
unity中如何用C# 开多线程，同时跑多个XLua虚拟机？

### ISSUE THREAD

**Issue by lichq5** [Tencent/xLua#234]
比如，我试了一下，在主线程里new了一个LuaEnv，执行LuaEnv.DoString函数，同时我在线程中也new了一个LuaEnv2，同样执行了LuaEnv2.DoString函数。但是线程里的DoString会报错：Load can only be called from the main thread.
Constructors and field initializers will be executed from the loading thread when loading a scene.
可能是我执行线程的方法有问题，在此请教一下各位大佬。

**Comment by chexiongsheng** [comment]
定义THREAD_SAFE宏。
建议升级到master版本

**Comment by lichq5** [comment]
能不能详细说一下，不太懂。谢谢！

**Comment by chexiongsheng** [comment]
网上搜索下unity怎么定义宏。
升级到最新的xlua版本

**Comment by lichq5** [comment]
@chexiongsheng  还是有个疑问，定义THREAD_SAFE宏具体是指做什么

**Comment by chexiongsheng** [comment]
搜索。。
这不是普及c#语法的地方。

**Comment by lichq5** [comment]
我不是问怎么定义一个宏。。
我是不太明白这个THREAD_SAFE的意义所在

**Comment by chexiongsheng** [comment]
互斥

**Comment by chexiongsheng** [comment]
搜索这个宏，看下就知道了

**Comment by lichq5** [comment]
好的，谢谢你。我知道了。
