### ISSUE TITLE
xLua在unity的分线程中调用会导致程序崩溃，为什么

### ISSUE THREAD

**Issue by lichq5** [Tencent/xLua#235]
具体的报错是：xlua.dll caused an Access Violation (0xc0000005)
  in module xlua.dll at 0033:33575141.
63% memory in use.
8085 MB physical memory [2962 MB free].
11541 MB paging file [2459 MB free].
134217728 MB user address space [134215579 MB free].
Read from location ffffffff caused an access violation.。
好像是说非法访问内存？？

**Comment by chexiongsheng** [comment]
多线程下加上THREAD_SAFE宏

**Comment by lichq5** [comment]
好的，加上THREAD_SAFE宏解决问题了，谢谢！
