### ISSUE TITLE
2017.2版本运行HotfixTest抛出AmbiguousMatchException

### ISSUE THREAD

**Issue by lingllting** [Tencent/xLua#238]
AmbiguousMatchException:'Void HotfixInject()' has more than one attribute of type 'UnityEditor.CallbackOrderAttribute'.
加入HOTFIX_ENABLE编译后（已添加dll）还会出现IOException: Sharing violation on path: XXX\Library\ScriptAssemblies\Assembly-CSharp.dll
运行是则出现：LuaException: xLua.access, no field__Hitfix0_Update,参考了之前closed的答案，没有帮助。

**Comment by lingllting** [comment]
我把Unity5.6.2f1版本Managed文件下的Mono.Cecil.dll拷到项目中，输入宏命令重新编译成功出现了hotfix inject finish. 问题解决！（AmbiguousMatchException仍然存在，但是不影响Hotfix）
 Unity2017.2f3Managed文件下没有Mono.Cecil.dll， 其他文件下的Mono.Cecil.dll均有BUG。

**Comment by chexiongsheng** [comment]
刚刚在2017.2试了没事？你确认是按教程来做么？
官方教程在这里：https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/hotfix.md
你按官方教程来是不需要什么Mono.Cecil.dll的
重要的事情说三遍，别定义INJECT_WITHOUT_TOOL，别定义INJECT_WITHOUT_TOOL，别定义INJECT_WITHOUT_TOOL
