### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object CSObjectWrapEditor.Generator..cctor () (at Assets/XLua/Src/Editor/Generator.cs:120)

### ISSUE THREAD

**Issue by leo8916** [Tencent/xLua#239]
Hotfix 按照教程一步步来
没想到第二步就进行不下去了。

NullReferenceException: Object reference not set to an instance of an object
CSObjectWrapEditor.Generator..cctor () (at Assets/XLua/Src/Editor/Generator.cs:120)
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for CSObjectWrapEditor.Generator

调试了下代码，ScriptableObject.CreateInstance 创建出的实例，里面的成员字段确实为null。
unity 5.3.7f1 iPhone平台，编辑器下。

**Comment by cn00** [comment]
报告一种情况: 中文注释编码引起的运行时错误,  看看有没有 [锟斤拷锟斤拷锟斤拷] 注释

**Comment by CodeMasterYi** [comment]
所以到底是什么问题？
