### ISSUE TITLE
General方案XLuaGenerate失败

### ISSUE THREAD

**Issue by Assxion** [Tencent/xLua#241]
操作步骤如下：
1.生成XLuaTestx.exe
2.执行XLuaGenerate.exe XLuaTestx.exe

如上流程产生大量异常

但是我如果是是使用2.1.6通用版本内的XLuaGenerate.exe则没有问题

**Comment by chexiongsheng** [comment]
修复过类似的问题，你更新到master，然后编译一份工具（含XLuaGenerate.exe）

**Comment by Assxion** [comment]
谢谢已经搞定了，不过通用版用起来真的是有点麻烦。
