### ISSUE TITLE
XLua/Hotfix Inject In Editor  在Unity 2017下面会报错

### ISSUE THREAD

**Issue by happyjiahan** [Tencent/xLua#242]
`			var mono_path = Path.Combine(Path.GetDirectoryName(typeof(UnityEngine.Debug).Module.FullyQualifiedName),
				"../MonoBleedingEdge/bin/mono");`

由于Unity 2017.2.0p1中 路径发生变化，上述路径已经找不到mono了，需要使用 ../../MonoBleedingEdge/bin/mono

不知道是否其他Unity2017的版本有没有问题，请测试修复。

**Comment by chexiongsheng** [comment]
window下的Unity 2017.2以及mac下的Unity 2017.1路径都没变。
mac下的Unity 2017.2没有下载来试

**Comment by happyjiahan** [comment]
对的，我是在Mac下面Unity 2017.2.0p1出现这个问题的

**Comment by ariganl** [comment]
你好，请问下，我lua放在Asserts/Resources目录下面，在PC端，使用lua我可以设置lua路径
var luaPath = string.Format("{0}/Resources/BTLuaProject/?.lua;", Application.dataPath);
luaEnv.DoString(string.Format("package.path='{0}'", luaPath), "LuaBehaviour set package path error", scriptEnv);
找到lua文件并执行，但在移动端并没有这个路径，请问下，我该怎么访问这个Resources目录

**Comment by sooryiamlate** [comment]
建议不同版本mono路径分出来。2017.2.0f3 on mac 同样有问题。
