### ISSUE TITLE
关于注册的self的问题

### ISSUE THREAD

**Issue by dingxiaowei** [Tencent/xLua#243]
void Awake()
        {
            luaEnv = GameEntry.XLuaManager.LuaEnv;
            scriptEnv = GameEntry.XLuaManager.LuaEnv.NewTable();
            LuaTable meta = GameEntry.XLuaManager.LuaEnv.NewTable();
            meta.Set("__index", luaEnv.Global);
            scriptEnv.SetMetaTable(meta);
            meta.Dispose();

            scriptEnv.Set("self", this);
            foreach (var injection in injections)
            {
                scriptEnv.Set(injection.name, injection.value);
            }

            if (!string.IsNullOrEmpty(FormLuaName))
            {
                luaEnv.DoString(string.Format("require'{0}'", FormLuaName), FormLuaName, scriptEnv);
            }

            Action luaAwake = scriptEnv.Get<Action>("awake");
            scriptEnv.Get("start", out luaStart);
            scriptEnv.Get("update", out luaUpdate);
            scriptEnv.Get("ondestroy", out luaOnDestroy);

            if (luaAwake != null)
            {
                luaAwake();
            }
        }

function start()
print("我是lua MenuPanel界面  调用lua里面的Start方法")
print(self)
end

在C#的Awake方法里面注册了self 但lua打印出来为nil

后来将lua改成txt 拖到TextAsset中 才可以打印出来了  自定义loader不可以这样操作么

**Comment by dingxiaowei** [comment]
已经解决 Editor下就用File.ReadAllBytes   AB模式就用txt后缀  结贴

**Comment by liqiang0508** [comment]
咋解决的啊 我也遇到 自定义loader 不能访问self

**Comment by liqiang0508** [comment]
> 已经解决 Editor下就用File.ReadAllBytes AB模式就用txt后缀 结贴
咋解决的啊 我也遇到 自定义loader 不能访问self
