### ISSUE TITLE
xlua general + .net core 2.0 中AppDomain.CurrentDomain.DefineDynamicAssembly缺失

### ISSUE THREAD

**Issue by devgl** [Tencent/xLua#244]
文件CodeEmit.cs 208行在.net core 2.0工程中运行抛出"MissingMethod"异常，原因是.net core2.0 API 中DefineDynamicAssembly被移到了AssemblyBuilder下，通过将 AppDomain.CurrentDomain 修改为 AssemblyBuilder可以解决这个问题。

**Comment by chexiongsheng** [comment]
暂时没时间去研究.net core
你可以先自行改下，这个issues打开着跟踪这事情，我到时有时间了再处理。
有发现别的.net core也劳烦帮忙提下

**Comment by geffzhang** [comment]
有计划支持.netcore吗

**Comment by chexiongsheng** [comment]
@geffzhang 我所知有人用在.netcore上，想这个问题反馈的api不兼容问题自行修改一些也可以
