### ISSUE TITLE
LuaCallCSharp System.IO.File报错

### ISSUE THREAD

**Issue by yihanjianduol** [Tencent/xLua#249]
unity2017.2
xlua v2.1.10 patch

![qq 20171204180916](https://user-images.githubusercontent.com/29097468/33547222-5ac40b40-d91e-11e7-8581-529698201bcf.png)

**Comment by chexiongsheng** [comment]
你看看是不是平台设置成webplayer了

**Comment by yihanjianduol** [comment]
没有啊，是standalone，你一说我还特地重新试了试，不过还是不行。。。

**Comment by yihanjianduol** [comment]
会不会是framework版本问题？File里面的API都对不上，F12过去根本就没有GetAccessControl这个方法。我暂时没空验证，只能猜测。。。

**Comment by chexiongsheng** [comment]
我试了可以
群也有人在用2017.2，甚至都发包了
可能你的2017.2有问题

**Comment by yihanjianduol** [comment]
好的。那我重装一下再看看，麻烦了！
