### ISSUE TITLE
mime库要怎么才能调用

### ISSUE THREAD

**Issue by lichq5** [Tencent/xLua#250]
请教一下，我看xlua的CMakeLists.txt在编译luasocket库的时候是有把mime.c文件加进去一起编译的，但是为什么在require 'mime.core'时会报错module 'mime.core' not found呢？还是说加载的库不对？

**Comment by Think-Jumper** [comment]
同问啊，我也遇到类似个情况，请问老兄你是怎么解决的？

**Comment by lichq5** [comment]
在close issue已经解决了这个问题，你去查一下吧 @Think-Jumper

**Comment by tianjiegs1986** [comment]
那个issue 关掉了但是看了还是不知道该怎么弄，如果不改c代码直接lua处理可以吗
