### ISSUE TITLE
你好，在打iphone包的时候，提示luadll.cs中引用dll的很多方法都不存在

### ISSUE THREAD

**Issue by ariganl** [Tencent/xLua#251]
undefined symbols for architecture arm64 “xlua_pack_decimal” referenced from : (_xlua_unpack_decimal_m1076337571) in Bulk_Assembly-CSharp_4.o
诸如这种的错误提示

安卓是没问题的，安卓和ios用的是同一个dll么，想问下，是不是缺少资源了

**Comment by chexiongsheng** [comment]
可能你漏了这个目录：https://github.com/Tencent/xLua/tree/master/Assets/Plugins/iOS

**Comment by ariganl** [comment]
确实。。
