### ISSUE TITLE
请问下关于移动端设置lua路径问题

### ISSUE THREAD

**Issue by ariganl** [Tencent/xLua#252]
你好，请问下，我lua脚本放在Asserts/Resources目录下面，在PC端，使用lua,我可以设置lua路径
var luaPath = string.Format("{0}/Resources/BTLuaProject/?.lua;", Application.dataPath);
luaEnv.DoString(string.Format("package.path='{0}'", luaPath), "LuaBehaviour set package path error", scriptEnv);
执行DoString("require 'Main'")可以找到Main.lua文件并执行，但在移动端并没有这个路径，请问下，我该怎么设置package.path呀

**Comment by chexiongsheng** [comment]
Resources不用设置package.path就可以访问。
