### ISSUE TITLE
DoString 跟 require 的安全域（作用域）问题

### ISSUE THREAD

**Issue by evapocket** [Tencent/xLua#254]
DoString的第三个参数可以设置独立的安全域（作用域），但是用 require 进来的一定是在默认的域Global里。
比如有 A.lua，B.lua，用DoString运行A.lua，在A.lua里require 'B.lua'，这样A.lua可以用B.lua里的全局变量，但B.lua不能用A.lua里的全局变量。
想问下是原本就这么设计的还是说有BUG？
PS：会有这样的想法是防止非常独立的模块间的相互影响，比如全局变量之类。

**Comment by chexiongsheng** [comment]
这个得问lua的作者了。这是lua的特性。

**Comment by evapocket** [comment]
哦，那看来只能不用 require，调用自己写的函数，全部用 DoString 了。
