### ISSUE TITLE
关于lua的日志输出

### ISSUE THREAD

**Issue by xdestiny110** [Tencent/xLua#255]
当在lua中发生异常并且没有捕获的时候，由unity打印出来的日志是类似这样的
```
12-11 18:08:37.760 18879-18906/? I/Unity: LuaException: 
```
有什么方法能够将日志等级由`Info`改为`Error`吗？

**Comment by chexiongsheng** [comment]
xlua没打日志。
xlua只是throw了个Exception。其实就相当于在普通C#代码里头抛了个异常。
