### ISSUE TITLE
xlua可以访问到c#中的多维数组吗？

### ISSUE THREAD

**Issue by RussellFF** [Tencent/xLua#256]
我在C#中已经new了一个固定长度的二维数组如aa，在xlua中想给aa赋值，但是一直未能成功。请问是不支持访问多维数组吗？

**Comment by chexiongsheng** [comment]
提问题描述好
什么操作（代码）
你期待什么结果
目前是啥现象（说“未成功”谁知道发生了啥？比如你写了个游戏，玩家告诉你玩你的游戏“未成功”，叫你定位你定位得了？）

**Comment by RussellFF** [comment]
我在c#脚本中定义了一个二维数组   public int[,] arr = new int[5,5];

然后在xlua中想给它赋值
for i=0, 4 do
		for j=0,4 do
			self.arr[i][j] = i
		end
	CS.UnityEngine.Debug.Log(self.arr[i][j])
end

然后会报一个数组不是一维数组。Array was not a one-dimensional array.

**Comment by chexiongsheng** [comment]
self.arr:GetValue(i, j)
