### ISSUE TITLE
使用两个LuaEnv遇到的问题

### ISSUE THREAD

**Issue by forsakenyang** [Tencent/xLua#257]
我们项目使用的是类似游戏大厅+子游戏的结构，所以需要同时支持两个LuaEnv的存在，以下简称Hall和Game。在Hall启动之后，玩家选择一个子游戏，启动一个Game（Hall不释放）。

在游戏过程中，Game会启动一个coroutine以维持连接，每帧都会调用并判断C#对象的session.IsConnected。在大约几分钟后，就会抛出InvalidCastException，异常报在session的Wrap内的_g_get_IsConnected，是因为translator.FastGetCSObj获取的就不是session对象的类型。调试发现是传入L的参数错了，它指向的是Hall下的某个对象，具体日志请看截图附件：

注：加了THREAD_SAFE宏，依旧会出这个问题

![issue](https://user-images.githubusercontent.com/2673696/33919268-b4ad1586-dff2-11e7-8ce3-cbf25b71d37f.jpg)

**Comment by chexiongsheng** [comment]
之前修改了一个问题，多线程+多LuaEnv会出现找错translator的问题。
检查下这里是否和master一致：https://github.com/Tencent/xLua/blob/master/Assets/XLua/Src/LuaEnv.cs#L49
