### ISSUE TITLE
编辑器下对lua代码的重新加载

### ISSUE THREAD

**Issue by suifcd** [Tencent/xLua#259]
游戏开发期间想在编辑器上提供一个接口，运行时改动了lua代码后，通过这个接口重新加载修改后的lua代码来执行，而不需要重新启动游戏，目前的加载方式是LuaEnv.DoString("require 'test'", "test", scriptEnv);如果要做这个功能的话，代码该怎么去写呢？

**Comment by chexiongsheng** [comment]
如果想从新require一个脚本，先把package.loaded对应的模块置空再require，详细做法google一下

**Comment by suifcd** [comment]
LuaEnv.Global.Set<string, LuaTable>(LuaName, null);
LuaEnv.Global.Get<LuaTable>("package").Get<LuaTable>("loaded").Set<string, LuaTable>(LuaName, null);
已经测试置空了，但是重新require后的代码还是之前的
