### ISSUE TITLE
string.find在安卓模拟器中返回不正确

### ISSUE THREAD

**Issue by forsakenyang** [Tencent/xLua#261]
local parse = function(t)
            local buf = {}
            for i=1,#t do
                table.insert(buf,string.format("%2X",string.byte(t,i)))
            end
            return table.concat(buf," ")
        end
    
    local run = function(str1,str2)
            print("=======================")
            print("str1=" .. str1)
            print("str2=" .. str2)
            print("bytes1=" .. parse(str1))
            print("bytes2=" .. parse(str2))
            local x,y = string.find(str1,str2,1,true)
            print(string.format("result x=%s y=%s",x,y))
            print("=======================")
        end

    run("普通房间/微端八十分-初级场","微端八十分-初级场")
    run("普通房间/初级场","初级场")
    run("普通房间微端八十分初级场","微端八十分")
    run("abcdef12345","1234")

以上lua代码在Unity编辑器、小米mix2真机上的返回结果是正确的，
尝试在天天模拟器、腾讯手游助手中运行，除了**非中文字符查找**结果都是返回nil：

注：lua 版本为5.3，没有使用luac预编译，也没有使用luajit

> [DevConsoleUI] execute cmd -> test
stack traceback:
	lua/Framework/Log/Logger.lua:26: in method 'debug'
	lua/UI/DevConsole/DevConsoleUI.lua:74: in method 'execute'
	lua/UI/DevConsole/DevConsoleUI.lua:28: in function <lua/UI/DevConsole/DevConsoleUI.lua:28>
LUA: =======================
LUA: str1=普通房间/微端八十分-初级场
LUA: str2=微端八十分-初级场
LUA: bytes1=E6 99 AE E9 80 9A E6 88 BF E9 97 B4 2F E5 BE AE E7 AB AF E5 85 AB E5 8D 81 E5 88 86 2D E5 88 9D E7 BA A7 E5 9C BA
LUA: bytes2=E5 BE AE E7 AB AF E5 85 AB E5 8D 81 E5 88 86 2D E5 88 9D E7 BA A7 E5 9C BA
LUA: result x=nil y=nil
LUA: =======================
LUA: =======================
LUA: str1=普通房间/初级场
LUA: str2=初级场
LUA: bytes1=E6 99 AE E9 80 9A E6 88 BF E9 97 B4 2F E5 88 9D E7 BA A7 E5 9C BA
LUA: bytes2=E5 88 9D E7 BA A7 E5 9C BA
LUA: result x=nil y=nil
LUA: =======================
LUA: =======================
LUA: str1=普通房间微端八十分初级场
LUA: str2=微端八十分
LUA: bytes1=E6 99 AE E9 80 9A E6 88 BF E9 97 B4 E5 BE AE E7 AB AF E5 85 AB E5 8D 81 E5 88 86 E5 88 9D E7 BA A7 E5 9C BA
LUA: bytes2=E5 BE AE E7 AB AF E5 85 AB E5 8D 81 E5 88 86
LUA: result x=nil y=nil
LUA: =======================
LUA: =======================
LUA: str1=abcdef12345
LUA: str2=1234
LUA: bytes1=61 62 63 64 65 66 31 32 33 34 35
LUA: bytes2=31 32 33 34
LUA: result x=7 y=10
LUA: =======================

**Comment by chexiongsheng** [comment]
lua的代码基本上没改过。现在看规律就是真机行，模拟器不行，我也不清楚模拟器的机制。
不过按模拟器的职责来说，真机ok的东西到它那跑不通应该就是它的bug。

**Comment by forsakenyang** [comment]
确认是模拟器的bug，且只存在执行armv7的so时会出现。如果apk里包含了x86的so，在模拟器中运行就一切正常。估计模拟器在模拟armv7某些指令时的实现有点问题，只能以后注意点了。
