### ISSUE TITLE
mac上安装luajit报错

### ISSUE THREAD

**Issue by ItsMePanda** [Tencent/xLua#262]
打算编bytecode，所以操作如下：
1. Terminal进入目录build/luajit-2.1.0b2/，运行make，报错
2. sudo make install成功
3. luajit，报错

请问是否还要配置什么环境？

**Comment by chexiongsheng** [comment]
xlua用的luajit就是原版的luajit，在网上搜索luajit的安装和使用

**Comment by ItsMePanda** [comment]
谢谢车兄回复，可是尝试下来发现，官方的2.1.0-beta2是可以正确运行上述3步的，我们xlua第一步make会报错

**Comment by chexiongsheng** [comment]
那就用官方的好了，可以直接用的。
xlua的应苹果要求，删掉了些从dll加载库的代码。

**Comment by chexiongsheng** [comment]
可能那些修改导致编译可执行程序不成功

**Comment by ItsMePanda** [comment]
收到。感谢~那顺便请假一下，是不是bit库也移除啦?

**Comment by chexiongsheng** [comment]
没有移除
你可以对比下代码，修改很小

**Comment by ItsMePanda** [comment]
好嘞，谢谢
