### ISSUE TITLE
IEnumerator<float>加入CSharpCallLua生成代码编译错误

### ISSUE THREAD

**Issue by lovestartian** [Tencent/xLua#263]
让生成的类SystemCollectionsGenericIEnumerator_1_SystemSingle_Bridge继承中间类A，实现IEnumerator<float>接口，然后A继承LuaBase,IEnumerator可以暂时解决 但是重新生成代码又得自己手动替换一遍

**Comment by chexiongsheng** [comment]
更新到master应该可以解决

**Comment by lovestartian** [comment]
可以了
public float Current{...}
object System.Collections.IEnumerator.Current{...}
黑科技解决:)
