### ISSUE TITLE
Lua中typeof一个委托类型返回空

### ISSUE THREAD

**Issue by lovestartian** [Tencent/xLua#264]
获取在类里面或者在命名空间下的委托类型返回是空，只有全局空间下定义的委托返回才成功。
我目前的替代方法：通过CS.System.Type.GetType("xxx")获得

**Comment by chexiongsheng** [comment]
在类里头你注意下是不是有public声明了

**Comment by lovestartian** [comment]
有public的 
namespace UISystem
{
    public class EventTriggerListener : EventTrigger
    {
        public delegate void PointerEventDelegate(PointerEventData eventData);
...
