### ISSUE TITLE
Windows下生成的安卓库太大

### ISSUE THREAD

**Issue by gxlggz** [Tencent/xLua#268]
你好，我想问下，为什么我用xlua目录下的make_android_lua53.bat生成安卓库的时候，是生成成功的，但是生成的库大小是4000+k，就算不编译任何第三方库，编译出的安卓库也有1000+k的样子，远大于提供的原始库文件的大小。
使用的cmake和ninja都是android studio里带的，cmake版本号是3.6.0-rc2，ninja的版本号是1.5.3，ndk版本是ndk-r10e

**Comment by chexiongsheng** [comment]
建议用make_android_lua53.sh吧，在linux下编译最好。
make_android_lua53.bat说实话，我也没用过，是一个热心用户提供的。

**Comment by gxlggz** [comment]
这个样子，好的，谢谢了
