### ISSUE TITLE
使用luabehaviour时lua继承问题

### ISSUE THREAD

**Issue by suifcd** [Tencent/xLua#269]
使用luabehaviour后，在c#端设置了env及__index指向_G,这个时候，如果lua有一个类UIBase，然后有另一个类Test,这个Test要继承Base的话该怎么做呢，继承的通用做法一般是__index的使用，这里已经在c#用过了.类似这样的功能能做到吗

UIBase.lua
function awake()
end

function func()
end

Test.lua
function awake()
    base:awake()
    func()
end

**Comment by suifcd** [comment]
已经通过_ENV和多继承实现了

**Comment by qazokmijn01** [comment]
how to do it ?
