### ISSUE TITLE
请问是否支持C#的try...catch?

### ISSUE THREAD

**Issue by roundsheep** [Tencent/xLua#27]
例如这种代码如何翻译为lua代码？

	void test1()
	{
		throw new Exception("abc");
	}
	void test5()
	{
		try
		{
			try
			{
				try
				{
					test1 ();
				}
				catch(Exception ex)
				{
					Debug.Log (ex.Message);
					throw new Exception("efg");
				}
			}
			catch(Exception ex)
			{
				Debug.Log (ex.Message);
				throw ex;
			}
		}
		catch(Exception ex)
		{
			Debug.Log (ex.Message);
		}
	}

**Comment by chexiongsheng** [comment]
lua的对应语法应该是pcall，你可以查阅下相关资料哈。。

**Comment by roundsheep** [comment]
话说如何在lua虚拟机和C#之间互相抛异常？如果C#抛出一个异常，xlua虚拟机能接收到么

**Comment by roundsheep** [comment]
额，那我去学习研究下
