### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by whj397909354** [Tencent/xLua#270]
您好，打包的出现如下错误：
XLua/Gen/UIWidgetWrap.cs(1134,43): error CS0117: `UIWidget' does not contain a definition for `showHandlesWithMoveTool'
XLua/Gen/UIWidgetWrap.cs(1146,43): error CS0117: `UIWidget' does not contain a definition for `showHandles'
看了一下，发现UIWidget.showHandlesWithMoveTool是编辑器下才可以使用，这个问题该这么改呢？

**Comment by chexiongsheng** [comment]
看下faq
https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/faq.md#%E7%BC%96%E8%BE%91%E5%99%A8%E4%B8%8B%E8%BF%90%E8%A1%8C%E6%AD%A3%E5%B8%B8%E6%89%93%E5%8C%85%E7%9A%84%E6%97%B6%E5%80%99%E7%94%9F%E6%88%90%E4%BB%A3%E7%A0%81%E6%8A%A5%E6%B2%A1%E6%9C%89%E6%9F%90%E6%96%B9%E6%B3%95%E5%B1%9E%E6%80%A7%E5%AD%97%E6%AE%B5%E5%AE%9A%E4%B9%89%E6%80%8E%E4%B9%88%E5%8A%9E
