### ISSUE TITLE
xlua dll在windows 10平台下的问题

### ISSUE THREAD

**Issue by itech4ever** [Tencent/xLua#275]
各位好。

最近遇到一个不知道算不算bug的东西。

用xlua到了unity项目，build到windows x86，windows 7下可以运行，但是直接拷贝到windows 10下面就运行不了，提示xlua那个dll的module无法找到（module not found）。发现有个dll在WSA的相关目录下，拷贝了其中的x86后也无法运行。想问下大家是我哪个地方做得不对么？

谢谢。

**Comment by chexiongsheng** [comment]
保持github上的目录结构是没问题。https://github.com/Tencent/xLua就是一个Unity项目的根目录。

**Comment by itech4ever** [comment]
@chexiongsheng 多谢。最后尝试了一下从release里面重新用dll覆盖，居然解决了问题。看来是dll在某个环节被我破坏了。。。但奇怪的是windows 7就可以运行。。。
