### ISSUE TITLE
关于文档和案例

### ISSUE THREAD

**Issue by MichelleGuan** [Tencent/xLua#276]
前辈打扰了，
想给您提个建议，就是教程可以写的稍微详细一点吗，或者分散开写到各个例子里面。
我是读了教程在看您的例子，有很多案例没有注释，不是很好理解，只能去看看博客什么的。
如果有时间的话，请多多关照下转行的萌新们哦o(*￣︶￣*)o
还有就是，非常感谢这个开源方案，辛苦了。

**Comment by chexiongsheng** [comment]
教程有配套的代码，运行下，自己改下看看。

**Comment by MichelleGuan** [comment]
好的 谢谢
