### ISSUE TITLE
建议增加一个自定义输出Log的接口

### ISSUE THREAD

**Issue by pillar** [Tencent/xLua#277]
现在好像都是直接调用 UnityEngine.Debug.Log 之类, 不方遍控制 Log 的关闭。

**Comment by chexiongsheng** [comment]
UnityEngine.Debug.Log只是Helloworld实例用来演示能调用Unity的api而已啊，不是让你平时这么用。。。
Log可以自己实现一套自己的。xLua做是不适合的，很多项目本身已经存在一套了。

**Comment by pillar** [comment]
我想你没理解我的意思，我意思是说，xLua 里面的Log都是直接用 UnityEngine.Debug.Log 输出。我自己实现了一套Log系统，请问如何替换 xLua 里面用到的 UnityEngine.Debug.Log ？ 就好像 AddLoader 一样。

**Comment by chexiongsheng** [comment]
xLua没有啥Log，关于UnityEngine.Debug.Log就做了一件事：把print重定向到UnityEngine.Debug.Log。但print不是log
你想替换print的实现不是超简单么？print = xxx就可以了

**Comment by pillar** [comment]
好的，麻烦了，^_^
