### ISSUE TITLE
08_Hotfix这个例子为什么我运行点击按钮是报错的？

### ISSUE THREAD

**Issue by ZhuOliver** [Tencent/xLua#28]
运行
if (GUI.Button(new Rect(10, 100, 300, 150), "Hotfix"))
        {
            luaenv.DoString(@"
                local tick = 0
                xlua.hotfix(CS.HotfixTest, 'Update', function()
                    --tick = tick + 1
                    --if (tick % 50) == 0 then
                        print('<<<<<<<<Update in lua, tick = ' .. tick)
                    --end
                end)
            ");
        }

是报错的   是我设置不对么

**Comment by shandongsu** [comment]
Unity的编译参数设置HOTFIX_ENABLE

**Comment by ZhuOliver** [comment]
打开哪些宏？只打开着一个宏代码报错

**Comment by chexiongsheng** [comment]
HOTFIX_ENABLE就应该不会报错了，你报啥错？

**Comment by ZhuOliver** [comment]
Assets/XLua/Src/Editor/Hotfix.cs(15,12): error CS0234: The type or namespace name `Cecil' does not exist in the namespace `Mono'. Are you missing an assembly reference?

**Comment by chexiongsheng** [comment]
你要拷贝cecil库进工程
https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/hotfix.md
热更特性依赖Cecil，添加HOTFIX_ENABLE宏之后，可能会报找不到Cecil。这时你需要到Unity安装目录下找到Mono.Cecil.dll，拷贝到项目里头。而HOTFIX_DEBUG_SYMBOLS则依赖Mono.Cecil.Pdb.dll，Mono.Cecil.Mdb.dll。

参考命令（可能Unity版本不同会略有不同，把别的Unity版本带的拷贝过来试了也能用，比如有的老版本Unity是不带Mono.Cecil.Pdb.dll，Mono.Cecil.Mdb.dll的，这时可以把新版本带的整套拷贝过来）：

OSX命令行 cp /Applications/Unity/Unity.app/Contents/Managed/Mono.Cecil.* Project/Assets/XLua/Src/Editor/
Win命令行 copy UnityPath\Editor\Data\Managed\Mono.Cecil.* Project\Assets\XLua\Src\Editor\
不支持静态构造函数。

**Comment by ZhuOliver** [comment]
还有个问题是这块代码需要触发，如果我想更新在线游戏的代码怎么来触发lua文件来覆盖。

**Comment by chexiongsheng** [comment]
http://gad.qq.com/article/detail/7182056

**Comment by ZhuOliver** [comment]
这个方法看过，可能所有可能出错的类里都要做这个判断了

**Comment by chexiongsheng** [comment]
晕，就程序启动的时侯有一个地方判断是否有hotfix，有就加载一下。
在加载的文件中指名替换哪些函数就可以了。C#那是感觉不到的

**Comment by chexiongsheng** [comment]
不是可能出现错误的类，只要整个进程有一个地方就可以了。

**Comment by polostart** [comment]
参考命令（可能Unity版本不同会略有不同，把别的Unity版本带的拷贝过来试了也能用，比如有的老版本Unity是不带Mono.Cecil.Pdb.dll，Mono.Cecil.Mdb.dll的，这时可以把新版本带的整套拷贝过来）：

Win命令行 copy UnityPath\Editor\Data\Managed\Mono.Cecil.* Project\Assets\XLua\Src\Editor\

我按这个拷贝了文件为什么没有打印hotfix inject finish! 一直xlua.access, no field __Hitfix0_Update。

**Comment by ZhuOliver** [comment]
NGUI的类需要自己手动导进工程么，大神

**Comment by FlaminiQian** [comment]
这个sample编译时会报下面这个warning
can not find delegate for HotfixTest..ctor! try re-genertate code.
UnityEngine.Debug:LogWarning(Object)
XLua.Hotfix:InjectMethod(AssemblyDefinition, MethodDefinition, Int32, FieldReference) (at Assets/XLua/Src/Editor/Hotfix.cs:314)
XLua.Hotfix:HotfixInject() (at Assets/XLua/Src/Editor/Hotfix.cs:250)
从而导致hotfix inject finish!不会被打印，从而点击按钮时会报xlua.access, no field __Hitfix0_Update的错误，是不是因为我是下载zip包的关系。。

**Comment by ZhuOliver** [comment]
我的这个示例能运行成功的

**Comment by chexiongsheng** [comment]
@FlaminiQian 你执行下xLua/Generate Code

**Comment by chexiongsheng** [comment]
@hwust 是最新的代码么？还是下载的预览版？

**Comment by ZhuOliver** [comment]
@chexiongsheng  xlua可以把NGUI导进lua么，没找到相关示例

**Comment by hwust** [comment]
@chexiongsheng OK 刚刚更新代码了。 已经能正常显示hotfix inject finish! 多谢

**Comment by ZhuOliver** [comment]
![image](https://cloud.githubusercontent.com/assets/13826063/21711356/7d21ed10-d429-11e6-88b5-3533d8b7d60a.png)是按照这个文档操作么

**Comment by chexiongsheng** [comment]
@ZhuOliver 不是。。。你怎么总把事情想得那么复杂！
看看《XLua教程》，看下C#代码怎么换成用lua来写。
你在C#里头用NGUI需要神马“导入”么？直接函数调用，new对象之类就ok了，这些C#代码都可以换成lua代码。

**Comment by FlaminiQian** [comment]
@chexiongsheng 可以了，多谢
