### ISSUE TITLE
 error CS1061: Type `UnityEngine.Texture2D' does not contain a definition for `alphaIsTransparency' and no extension method `alphaIsTransparency' of type `UnityEngine.Texture2D' could be found. Are you missing an assembly reference?

### ISSUE THREAD

**Issue by Think-Jumper** [Tencent/xLua#281]
[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
        static int _g_get_alphaIsTransparency(RealStatePtr L)
        {
		    try {
                ObjectTranslator translator = ObjectTranslatorPool.Instance.Find(L);
			
                UnityEngine.Texture2D __cl_gen_to_be_invoked = (UnityEngine.Texture2D)translator.FastGetCSObj(L, 1);
                **LuaAPI.lua_pushboolean(L, __cl_gen_to_be_invoked.alphaIsTransparency);**
            } catch(System.Exception __gen_e) {
                return LuaAPI.luaL_error(L, "c# exception:" + __gen_e);
            }
            return 1;
        }
        
        
        
        [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
        static int _s_set_alphaIsTransparency(RealStatePtr L)
        {
		    try {
                ObjectTranslator translator = ObjectTranslatorPool.Instance.Find(L);
			
                UnityEngine.Texture2D __cl_gen_to_be_invoked = (UnityEngine.Texture2D)translator.FastGetCSObj(L, 1);
                **__cl_gen_to_be_invoked.alphaIsTransparency = LuaAPI.lua_toboolean(L, 2);**
            
            } catch(System.Exception __gen_e) {
                return LuaAPI.luaL_error(L, "c# exception:" + __gen_e);
            }
            return 0;
        }

明明这两个属性UnityEngine里面都有，为啥便宜Android的时候报错提示没有找到引用？我的Unity版本是2017.1.0f3版本的，请帮忙看下这个情况。

**Comment by chexiongsheng** [comment]
这表示这个属性android下没有。
用黑名单排除掉。

**Comment by wangjianpeng** [comment]
请问Android下没有这个属性，是依据什么判断呢？iOS平台下会出现这种情况吗？
