### ISSUE TITLE
泛型方法的生成编译报错

### ISSUE THREAD

**Issue by drashnane** [Tencent/xLua#282]
因为很久没更新了，最近刚更新了一下，然后发现有的泛型方法生成代码的时候会报错：

原方法：

	public void SetDataForListItem<P, D>(P itemPrefab, ICollection<D> dataList)
		where P : MonoBehaviour

生成代码：

        [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
        static int _m_SetDataForListItem(RealStatePtr L)
        {
		    try {
            
                ObjectTranslator translator = ObjectTranslatorPool.Instance.Find(L);
            
            
                ListLayoutGroup __cl_gen_to_be_invoked = (ListLayoutGroup)translator.FastGetCSObj(L, 1);
            
            
                
                {
                    UnityEngine.MonoBehaviour itemPrefab = (UnityEngine.MonoBehaviour)translator.GetObject(L, 2, typeof(UnityEngine.MonoBehaviour));
                    System.Collections.Generic.ICollection<**D**> dataList = (System.Collections.Generic.ICollection<**D**>)translator.GetObject(L, 3, typeof(System.Collections.Generic.ICollection<**D**>));
                    
                    __cl_gen_to_be_invoked.SetDataForListItem( itemPrefab, dataList );
                    
                    
                    
                    return 0;
                }
                
            } catch(System.Exception __gen_e) {
                return LuaAPI.luaL_error(L, "c# exception:" + __gen_e);
            }
            
        }

上一次更新的时候如果第二个参数不加约束是可以编译成功的。

因为项目的原因，D是不能加约束的，所以我要怎么做？

**Comment by chexiongsheng** [comment]
以前生成代码是怎样的？

**Comment by chexiongsheng** [comment]
以前生成代码是怎样的？

**Comment by chexiongsheng** [comment]
应该是不生成的吧？你可以先把这个用黑名单去掉

**Comment by drashnane** [comment]
我现在用黑名单过滤掉了

以前代码是：

        [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
        static int _m_SetDataForListItem(RealStatePtr L)
        {
            
            ObjectTranslator translator = ObjectTranslatorPool.Instance.Find(L);
            
            
            ListLayoutGroup __cl_gen_to_be_invoked = (ListLayoutGroup)translator.FastGetCSObj(L, 1);
            
            
            try {
                
                {
                    UnityEngine.MonoBehaviour itemPrefab = (UnityEngine.MonoBehaviour)translator.GetObject(L, 2, typeof(UnityEngine.MonoBehaviour));
                    System.Collections.Generic.ICollection<object> dataList = (System.Collections.Generic.ICollection<object>)translator.GetObject(L, 3, typeof(System.Collections.Generic.ICollection<object>));
                    
                    __cl_gen_to_be_invoked.SetDataForListItem( itemPrefab, dataList );
                    
                    
                    
                    return 0;
                }
                
            } catch(System.Exception __gen_e) {
                return LuaAPI.luaL_error(L, "c# exception:" + __gen_e);
            }
            
        }

把D转成object了

**Comment by chexiongsheng** [comment]
那以前的处理也是不对的
~~~csharp
Debug.Log(typeof(ICollection<object>).IsAssignableFrom(typeof(ICollection<GameObject>)));//打印false
~~~

**Comment by drashnane** [comment]
嗯，看来我要单独写一个lua可以调用的方法了，多谢

**Comment by drashnane** [comment]
提交了一个pr，https://github.com/Tencent/xLua/pull/284，麻烦您看一下
