### ISSUE TITLE
请问xlua有提供LuaJit像v.lua,p.lua等分析jit是否成功的工具呢？

### ISSUE THREAD

**Issue by FrancisLiu1992** [Tencent/xLua#285]
我看LuaJIT-2.1.0-beta2编译后的jit文件夹中有v.lua、p.lua等一系列用来分析jit过程的工具，Xlua中好像没有找到相对应的文件。

**Comment by chexiongsheng** [comment]
https://github.com/Tencent/xLua/tree/master/build/luajit-2.1.0b2/src/jit

**Comment by FrancisLiu1992** [comment]
谢谢您的回答，我还想问一下，文档里提供的profiler.lua和memory.lua这两个profile工具是否能够在jit模式下正常使用呢？我试了一下，目前没有问题，想跟您确认一下再使用

**Comment by chexiongsheng** [comment]
有问题就反馈
