### ISSUE TITLE
有考虑集成自动C#转lua的功能么

### ISSUE THREAD

**Issue by roundsheep** [Tencent/xLua#29]
好像有好几个自动C#转lua的开源项目

**Comment by jeason1997** [comment]
能介绍下是哪些开源项目支持 c# 转 lua 么？有点好奇想看看

**Comment by miter** [comment]
目前只发现一个
https://github.com/yanghuan/bridge.lua
而且转换的结果不太符合我想要的样子
`namespace.class("Main", function ()
    local Start, Update
    Start = function (this) 
        System.Console.WriteLine("HelloWorld")
    end
    Update = function (this) 

    end
    return {
        __inherits__ = { UnityEngine.MonoBehaviour },
        Start = Start,
        Update = Update
    }
end)
`

**Comment by chexiongsheng** [comment]
之前了解过一两个，感觉都不怎么成熟。 miter发的我没了解过，有空看看。
之前有考虑过这事情，但目前还是聚焦在核心这块，会持续关注有没合适的方案。
但直接集成的可能性不会很大，应该会以扩展包的方式在放到另外的项目里头。

**Comment by Evan-dlut** [comment]
https://gameinstitute.qq.com/talk/detail/10158
如果可以集成下就太好了
