### ISSUE TITLE
ios构建失败，显示找不到_xlua_set_hotfix_flag

### ISSUE THREAD

**Issue by hello32768** [Tencent/xLua#295]
xlua是从github上clone的最新的。
宏定义是：HOTFIX_ENABLE;INJECT_WITHOUT_TOOL
xcode版本是9.2

做的是lua53版本，因为加了pbc，需要重新生成xlua库

构建时，会在BuildPipeline.BuildPlayer前调用CSObjectWrapEditor.Generator.GenAll();

unity构建完，在xcode进行构建的时候会报错：
Undefined symbols for architecture arm64:
  "_xlua_set_hotfix_flag", referenced from:
      _HotfixDelegateBridge_xlua_set_hotfix_flag_m700743380 in Bulk_Assembly-CSharp_26.o
      _HotfixDelegateBridge_Set_m781403264 in Bulk_Assembly-CSharp_26.o
     (maybe you meant: _HotfixDelegateBridge_xlua_set_hotfix_flag_m700743380)
  "_xlua_get_hotfix_flag", referenced from:
      _HotfixDelegateBridge_xlua_get_hotfix_flag_m376507549 in Bulk_Assembly-CSharp_26.o
     (maybe you meant: _HotfixDelegateBridge_xlua_get_hotfix_flag_m376507549)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

然后发现，只生成了.a文件，没有生成.so文件

附件是make_ios_lua53.sh的输出
[lua53.txt](https://github.com/Tencent/xLua/files/1676247/lua53.txt)

ps: android 、osx 和windows 是可以正常跑的

**Comment by hello32768** [comment]
搞定了。。有个cpp文件没有拷进去

**Comment by ZengYiming** [comment]
同样的问题，原因是编译新的plugin之后拷贝到Assets/Plugins中直接覆盖了之前的iOS目录。解决方法是，需要保留以前plugins/iOS目录下的HotfixFlags.cpp文件
