### ISSUE TITLE
关于[PostProcessScene]检查是否生成代码

### ISSUE THREAD

**Issue by hello32768** [Tencent/xLua#296]
xlua是从github上clone的最新的。
宏定义是：HOTFIX_ENABLE;INJECT_WITHOUT_TOOL
xcode版本是9.2

构建时要对每个场景打ab

构建时，会在BuildPipeline.BuildPlayer前调用CSObjectWrapEditor.Generator.GenAll()（也试过在实现IPreprocessBuild的接口中调用）

都会报“Code has not been genrated”

后来我注意到，Generator.CheckGenrate是在[PostProcessScene]检查是否生成代码。我如果也在[PostProcessScene(0)]中调用CSObjectWrapEditor.Generator.GenAll()，就不会报错，**但是会重复生成好几次代码。而且我编辑器运行时也会生成代码**

所以有没有更好的方法生成代码呢？

**Comment by chexiongsheng** [comment]
我看一些童鞋是build两次，第一次就只（调用CSObjectWrapEditor.Generator.GenAll）生成代码

**Comment by hello32768** [comment]
或者能不能再加一个宏做开关，因为可以自动调GenAll，就可以用宏把这个检查关掉

**Comment by chexiongsheng** [comment]
最好别关吧，那个检查代表当前的编译结果没有把生成代码编译在内，这不知道会不会导致问题。
分两步走能规避报错就最好
