### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by liuyanlin** [Tencent/xLua#298]
DelegatesGensBridge
EnumWrap
XLuaGenAutoRegister
WrapPusher
PackUnpack

这四个文件 是不是要考虑一下分解文件。我曾经就遇到过unity中文件过大造成unity解析文件的问题。大概30w行左右。
我看这几个文件 应该会随着项目的内容的增长而无限增长。
这种自动化的集成文件，几十万行还是可能的

**Comment by chexiongsheng** [comment]
理论上是这样的，但项目内容同时受限于其它，比如ios的__TEXT段，比如人类能掌控的规模。

目前看就DelegatesGensBridge在hotfix场景下会比较大，但目前看即使是一些大项目（__TEXT已经接近ios红线）采用全注入也没有大到那个程度。而且全注入往往就刚上线需要，后面迭代往往会把一些趋向稳定的模块排除掉。

如果到时有这方面的反馈，要修复也很快，也不是线上运行时的问题，影响不大。
