### ISSUE TITLE
关于iOS平台hotfix的疑问

### ISSUE THREAD

**Issue by xclouder** [Tencent/xLua#3]
Great work!  iOS平台hotfix的原理是什么，能否在wiki里详细说明，ios上性能与其他方案（slua/ulua等)的比较情况能否也给出数据，谢谢！

**Comment by chexiongsheng** [comment]
hotfix原理介绍在写，稍后会考虑以什么形式发布到外部。
过一阵子会出一个性能测试报告以及对应的性能测试代码。

**Comment by chexiongsheng** [comment]
http://gad.qq.com/article/detail/7182056
