### ISSUE TITLE
关于lua的gc问题

### ISSUE THREAD

**Issue by hunter3900** [Tencent/xLua#302]
在监测lua的内存时发现一个现象：
1.在不进行任何操作时，内存会不断上涨，当内存达到到gc阈值时会进行gc，内存逐步回落，没有异常。
2.在战斗场景中不断进行战斗，这时候每一次gc之后，gc的阈值会提高1000k，内存回落后的值也会相应提高。
3.在gc阈值提高了2-3次之后，停留在战斗场景中不进行任何操作，这时候每一次gc之后，gc的阈值和内存回落后的值，会慢慢恢复到正常水平。

问题：
1.这算不算是内存泄漏?
2.如果常驻内存不断上涨应该也会造成影响?
3.这是什么原因造成？有什么线索？

**Comment by chexiongsheng** [comment]
到lua官网上，或者google下这两个gc相关的参数：GcPause，GcStepmul，选择适合你们要求值，调用luaenv上接口设置
