### ISSUE TITLE
在 mac editor 下 luajit 报错

### ISSUE THREAD

**Issue by pillar** [Tencent/xLua#303]
直接跑 lua 代码没问题，但跑 luajit 的话，会报错误"bad header in precompiled chunk" ，32位和64位的luajit 字节码都跑了，都不行。这个问题困扰很久，不知道如何解决。

**Comment by pillar** [comment]
跑脚本make_osx_luajit编译libxlua.a ，发现编译的代码是 lua-5 。

**Comment by chexiongsheng** [comment]
Luajit不支持unity Mac 64bit
要么在window开发，要么mac下别用字节码

**Comment by pillar** [comment]
好的，谢谢。

**Comment by yangguanghenqing** [comment]
Luajit不支持unity Mac 64bit？有依据吗？我也发现同样的问题

**Comment by chexiongsheng** [comment]
luajit 支持Mac 64bit，但要求你可执行程序编译时加上它指定的参数。
所以unity Mac 64bit你要用luajit，你得搞到unity源码，加上luajit要求的参数自己编译一份unity。

**Comment by yangguanghenqing** [comment]
谢谢

**Comment by luxiaodong** [comment]
编译时加上指定的参数, 是说下面这段吗？   [( http://luajit.org/install.html#cross)]

Important: this relates to LuaJIT 2.0 only — use LuaJIT 2.1 to avoid these complications.
If you're building a 64 bit application on macOS which links directly or indirectly against LuaJIT, you need to link your main executable with these flags:
-pagezero_size 10000 -image_base 100000000

但这是2.0版本，还是还有其他的限制 ？
