### ISSUE TITLE
建议xLua “clear generated code” 操作选项不要删除.meta文件

### ISSUE THREAD

**Issue by CodeMasterYi** [Tencent/xLua#304]
如题，每次重新生成都要再传一遍那些根本不需要改动的.meta文件，真的很烦~

另外clear和generate完全可以合在一起啊，因为已经生成过一遍之后，做改动直接点generate是无效的

**Comment by chexiongsheng** [comment]
如果没有减少文件，不用clear，直接点generate即可（注意下要改动C#要等菊花转完才generate，你说的无效应该是菊花没转完就点了），这时不会改meta

**Comment by CodeMasterYi** [comment]
哦，原来如此！
