### ISSUE TITLE
前辈，请教一下关于热更下无法Dispose掉LuaEnv的问题

### ISSUE THREAD

**Issue by bbsuuo** [Tencent/xLua#307]
开启热补丁之后 如果想要dispose掉luaenv会报出InvalidOperationException: try to dispose a LuaEnv with C# callback! 的错误   可是仔细阅读了lua的api和hotfix的文档后 里没有将他注销掉的方法

热更里的教程里也没有Dispose掉luaenv 但是其他的lua C# 交互中都有dispose步骤

目前是不需要Dispose掉吗？

**Comment by chexiongsheng** [comment]
faq上有相关的答案
另外，一般而言，不Dispose也可以
