### ISSUE TITLE
GetComponentInChildren报错

### ISSUE THREAD

**Issue by dongxue** [Tencent/xLua#31]
GetComponent可以正常工作，但是GetComponentInChildren报错 LuaException: invalid arguments to UnityEngine.Component.GetComponentInChildren!

请问是怎么回事呢？

**Comment by chexiongsheng** [comment]
贴下代码？应该是参数输错了，或者调用的符号搞错了

**Comment by dongxue** [comment]
view:GetComponentInChildren("Button").onClick:AddListener(click) 这句报错
view.transform:Find("Panel/Button"):GetComponent("Button").onClick:AddListener(click) 这句OK

**Comment by chexiongsheng** [comment]
GetComponentInChildren没有string参数的版本呀，可以参照下Unity的API文档

**Comment by chexiongsheng** [comment]
你试试
view:GetComponentInChildren(typeof(CS.UnityEngine.UI.Button))
看看？

**Comment by dongxue** [comment]
成功了，Thanks！
