### ISSUE TITLE
64位Linux系统下编译make_android_luajit.sh报错求大神指点

### ISSUE THREAD

**Issue by xhl-zero** [Tencent/xLua#312]
[root@inu_dev1 XluaBuildProject]# sh make_android_luajit.sh 
/root/android-ndk-r10e
/data/client/BuildProject/Lua3rdIntegration/XluaBuildProject
/data/client/BuildProject/Lua3rdIntegration/XluaBuildProject/luajit-2.1.0b2
linux-x86_64
Building armv7 lib
make -C src clean
make[1]: Entering directory `/data/client/BuildProject/Lua3rdIntegration/XluaBuildProject/luajit-2.1.0b2/src'
rm -f luajit libluajit.a libluajit.so host/minilua host/buildvm lj_vm.S lj_bcdef.h lj_ffdef.h lj_libdef.h lj_recdef.h lj_folddef.h host/buildvm_arch.h jit/vmdef.lua *.o host/*.o *.obj *.lib *.exp *.dll *.exe *.manifest *.pdb *.ilk
make[1]: Leaving directory `/data/client/BuildProject/Lua3rdIntegration/XluaBuildProject/luajit-2.1.0b2/src'
==== Building LuaJIT 2.1.0-beta2 ====
make -C src
make[1]: Entering directory `/data/client/BuildProject/Lua3rdIntegration/XluaBuildProject/luajit-2.1.0b2/src'
HOSTCC    host/minilua.o
HOSTLINK  host/minilua
/usr/local/lib/gcc/x86_64-unknown-linux-gnu/4.9.1/crtbegin.o: could not read symbols: File in wrong format
collect2: 错误：ld 返回 1
make[1]: *** [host/minilua] 错误 1
make[1]: Leaving directory `/data/client/BuildProject/Lua3rdIntegration/XluaBuildProject/luajit-2.1.0b2/src'
make: *** [default] 错误 2
-- Configuring done
-- Generating done
-- Build files have been written to: /data/client/BuildProject/Lua3rdIntegration/XluaBuildProject/build_lj_v7a
gmake[2]: *** 没有规则可以创建“libxlua.so”需要的目标“../luajit-2.1.0b2/src/libluajit.a”。 停止。
gmake[1]: *** [CMakeFiles/xlua.dir/all] 错误 2
gmake: *** [all] 错误 2
cp: 无法获取"build_lj_v7a/libxlua.so" 的文件状态(stat): 没有那个文件或目录
Building x86 lib
make -C src clean
make[1]: Entering directory `/data/client/BuildProject/Lua3rdIntegration/XluaBuildProject/luajit-2.1.0b2/src'
rm -f luajit libluajit.a libluajit.so host/minilua host/buildvm lj_vm.S lj_bcdef.h lj_ffdef.h lj_libdef.h lj_recdef.h lj_folddef.h host/buildvm_arch.h jit/vmdef.lua *.o host/*.o *.obj *.lib *.exp *.dll *.exe *.manifest *.pdb *.ilk
make[1]: Leaving directory `/data/client/BuildProject/Lua3rdIntegration/XluaBuildProject/luajit-2.1.0b2/src'
==== Building LuaJIT 2.1.0-beta2 ====
make -C src
make[1]: Entering directory `/data/client/BuildProject/Lua3rdIntegration/XluaBuildProject/luajit-2.1.0b2/src'
HOSTCC    host/minilua.o
HOSTLINK  host/minilua
/usr/local/lib/gcc/x86_64-unknown-linux-gnu/4.9.1/crtbegin.o: could not read symbols: File in wrong format
collect2: 错误：ld 返回 1
make[1]: *** [host/minilua] 错误 1
make[1]: Leaving directory `/data/client/BuildProject/Lua3rdIntegration/XluaBuildProject/luajit-2.1.0b2/src'
make: *** [default] 错误 2
-- Configuring done
-- Generating done
-- Build files have been written to: /data/client/BuildProject/Lua3rdIntegration/XluaBuildProject/build_lj_x86
gmake[2]: *** 没有规则可以创建“libxlua.so”需要的目标“../luajit-2.1.0b2/src/libluajit.a”。 停止。
gmake[1]: *** [CMakeFiles/xlua.dir/all] 错误 2
gmake: *** [all] 错误 2
cp: 无法获取"build_lj_x86/libxlua.so" 的文件状态(stat): 没有那个文件或目录

**Comment by xhl-zero** [comment]
make[1]: Entering directory /data/client/BuildProject/Lua3rdIntegration/XluaBuildProject/luajit-2.1.0b2/src' HOSTCC host/minilua.o HOSTLINK host/minilua /usr/local/lib/gcc/x86_64-unknown-linux-gnu/4.9.1/crtbegin.o: could not read symbols: File in wrong format collect2: 错误：ld 返回 1 make[1]: *** [host/minilua] 错误

**Comment by haoziAndy** [comment]
我也遇到同样的问题~ 请问当时是如何解决的？
