### ISSUE TITLE
请教前辈Linux系统下编译make_android_luajit.sh对应的gcc版本号是多少呀？急急急！！！

### ISSUE THREAD

**Issue by xhl-zero** [Tencent/xLua#313]

**Comment by chexiongsheng** [comment]
我机器是4.4.6，但不知道cmake选的是gcc不

**Comment by chexiongsheng** [comment]
对哦，你编译android版本，应该不会用到gcc的啊
就是用ndk里头的，你ndk版本对应该就没问题

**Comment by xhl-zero** [comment]
我是在64位linu系统下 ndk用的是android-ndk-r10e 最开始我的报错是“/usr/include/gnu/stubs.h:7:27: 致命错误：gnu/stubs-32.h 这个问题解决后 又报了一个 /usr/local/lib/gcc/x86_64-unknown-linux-gnu/4.9.1/crtbegin.o: could not read symbols: File in wrong format
collect2: 错误：ld 返回 1           这个错误 问一下大神怎么解决呀？

**Comment by chexiongsheng** [comment]
没碰到过

**Comment by xhl-zero** [comment]
麻烦在问一下 您的 Linux系统是64位的吗？  还有就是 用到的软件版本号和位数 能都说一下吗？我看一下 我的配置和您的一样不一样。。。感谢啦。。。

**Comment by chexiongsheng** [comment]
基本大多数人都可以编过，应该这方面没啥要求

**Comment by xhl-zero** [comment]
make HOST_CC="gcc -m32" CROSS=$NDKP TARGET_SYS=Linux TARGET_FLAGS="$NDKF"中的
 “gcc -m32”需要改成“gcc -m64”吗？编译完的库文件是32位的吗？

**Comment by chexiongsheng** [comment]
我的linux也是64位的。

**Comment by xhl-zero** [comment]
哦哦 在问一下 就是 你的 linux 安装32位相关的运行库了吧？

**Comment by chexiongsheng** [comment]
没干过啥。64位系统本来就能跑32位程序。
我用的是centos
