### ISSUE TITLE
 A local variable named `L' cannot be declared in this scope because it would give a different meaning to `L', which is already used in a `parent or current' scope to denote something else

### ISSUE THREAD

**Issue by vihist** [Tencent/xLua#315]
使用Untiy编辑器菜单中XLua/Generate code 生成代码后编辑器报错
Assets/XLua/Gen/ToolsProbabilityWrap.cs(168,25): error CS0136: A local variable named `L' cannot be declared in this scope because it would give a different meaning to `L', which is already used in a `parent or current' scope to denote something else

看到生成的代码中L被重复定义了
 [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
        static int _m_gaussrand_xlua_st_(RealStatePtr **L**)
        {
		    try {
            
            
            
                
                {
                    int E = LuaAPI.xlua_tointeger(L, 1);
                    int V = LuaAPI.xlua_tointeger(L, 2);
                    int **L** = LuaAPI.xlua_tointeger(L, 3);
                    
                        int __cl_gen_ret = Tools.Probability.gaussrand( E, V, L );
                        LuaAPI.xlua_pushinteger(L, __cl_gen_ret);
                    
                    
                    
                    return 1;
                }
                
            } catch(System.Exception __gen_e) {
                return LuaAPI.luaL_error(L, "c# exception:" + __gen_e);
            }
            
        }

**Comment by chexiongsheng** [comment]
暂时你那重命名规避下吧。
我打算最近先发个版本，然后再处理下这问题
