### ISSUE TITLE
你好前辈，请教下C#dll里使用xlua的问题

### ISSUE THREAD

**Issue by ariganl** [Tencent/xLua#316]
是这样的，为了使代码和美术路径分离，我们把C#代码编成一个dll放在plugins下使用，在电脑上，没使用xlua generate code前程序是可以跑起来的，但generate code之后，会提示FairyGUI程序集找不到，（报错信息为 FileNotFoundException: Could not load file or assembly 'FairyGUI， Version=1.0.0.0,Culture-neutral,PublicKeyToken=null' or one of its dependencies）,因为没generate之前运行正常，所以我觉得可以排除找不到FairyGUI的依赖的错误，我在Xlua/Src/ObjectTranslator.cs里断点 Var  assemblies_usorted = AppDomain.CurrentDomain.GetAssemblies()获取到的列表，对比generate前后，发现generate之后确实没有FairyGUI了，但是不知道为什么，这个问题困扰了我挺久了，请你指导下~谢谢你了

**Comment by chexiongsheng** [comment]
这个我也处理不了呢，AppDomain.CurrentDomain.GetAssemblies()就不返回的话
