### ISSUE TITLE
关于Lua层的Callable对象在C#层要怎么调用呢？

### ISSUE THREAD

**Issue by CodeMasterYi** [Tencent/xLua#318]
起初我以为我的一个lua变量是function，后来发现竟然是个callable table，然后卡住了，咋调用嘞
比如，有个callable table叫funca，那C#层怎么调用funca()呢？

**Comment by CodeMasterYi** [comment]
最后的最后，我在 lua 层加了function，封装调用callable table，😂😂😂

**Comment by chexiongsheng** [comment]
可以这么搞

**Comment by CodeMasterYi** [comment]
所以，现在是没有更直接的方法，是吗？

**Comment by chexiongsheng** [comment]
目前没直接支持。LuaTable是partial的，可以自己加一个。
感觉也不是很多人都有这样的需求，所以先hold住，观察一下看看要不要加。
