### ISSUE TITLE
请教下添加第三方库在ios11 sdk下编译报错的标准解决方案

### ISSUE THREAD

**Issue by erlangs** [Tencent/xLua#320]
loslib.c error: 'system' is unavailable: not available on iOS
在网上找到的解决方案是：把system替换为popen。
请教下官方有标准的解决方案吗？

**Comment by chexiongsheng** [comment]
标准做法是更新版本，这问题很久之前就改了

**Comment by erlangs** [comment]
谢谢，在master版本里看见了。
我现在拉的是v2.1.10p1版本的，要解决这个问题我直接拉master版本来编译吗？
