### ISSUE TITLE
使用Marshal解决大值类型数据传递问题

### ISSUE THREAD

**Issue by whitespeed** [Tencent/xLua#322]
如题，对大值类型数据是否会考虑使用Marshal的方式传递到C层呢，毕竟现在no gc方式只支持bittable类型数据。

**Comment by chexiongsheng** [comment]
变长的东西是不好支持的，比如字符串，Marshal到C的结构体需要声明长度。
除掉这些变长的东西，其实就和现在xlua的支持程度差不多。
