### ISSUE TITLE
关于CSharpCallLua的问题，求知道

### ISSUE THREAD

**Issue by dudu502** [Tencent/xLua#324]
我在unity编辑器中运行的时候没有问题，但是导出pc版exe运行的时候会报InvalidCastException: This delegate must add to CSharpCallLua:System.Func...   然而我已经在ExampleGenConfig.cs里面的CSharpCallLua静态成员里加上了..typeof(Func<bool>),..

**Comment by chexiongsheng** [comment]
发包前执行生成代码

**Comment by dudu502** [comment]
谢谢，现在可以了

**Comment by LazyPlanet** [comment]
@chexiongsheng 是不是在unity编辑器里面不生成代码也是可以的，但是打包必须生成？很奇怪明明我只有ExampleConfig.cs这个文件，没有ExampleGenConfig.cs这个文件也是可以运行的，可以lua调用C#的接口。
