### ISSUE TITLE
lua里的协程有类似cs的StopCoroutine方法吗

### ISSUE THREAD

**Issue by qqzz0xx** [Tencent/xLua#328]

**Comment by chexiongsheng** [comment]
lua协程没引用就自动gc，不需要Stop

**Comment by qqzz0xx** [comment]
想让协程还如果没执行完就停止啊， 像这样的：
func-> { ... ; yield return 0; }
if ( isRunnig(func)
   stop(func)
start(func)

**Comment by kobechen413** [comment]
这个需要吧，外面的函数执行完了 还是会回到协程里面执行的啊

**Comment by ydykevin** [comment]
同问
