### ISSUE TITLE
关于热更新的问题

### ISSUE THREAD

**Issue by Frankzhaopku** [Tencent/xLua#329]
有几个关于热更新的问题，想请教一下：
1、HotFixAttribute可以给Method直接打么？可以更精细的控制注入的函数，另外是否提供黑名单能力，例如给类打上HotFix，但可以通过给特定方法打DontInject等使其不需要被注入
2、刚看了xLua时间不长，是否插桩和桩的调用代码是分两步生成的，调用代码在Generate Code时生成，而插桩则在Inject时进行，那如果一些新类打上了HotFix但没有重新Generate Code，即新的一些方法的参数列表的插桩调用函数，并没有生成到DelegateGensBridge中，这时Inject是否会出现问题？
3、XLuaHotFixInject.exe是否可以提供源码？使用ILSpy阅读起来并不是很友好，一些定制功能也很难实现，例如可以在注入时生成出可更新方法的列表，并生成热更模板，甚至利用一些IL2Lua的工具生成出lua版本的函数实现，对热更时的效率有极大提升。而没有XLuaHotFixInject的源码，则这些工具链都无从做起，不知是否可以开源。

**Comment by chexiongsheng** [comment]
1、目前看注入代码的主要影响是代码段。粒度到方法的话，感觉要做这么精细的配置，配起来也很麻烦，成千上百的类一个个梳理下来可能就省个一两M，万一你预判的不对可能还导致某个bug修复不了。
ps：直接打标签不是建议的方式，看下配置的文档
还有hotfix的注意实现可以看看这：http://gad.qq.com/article/detail/42303
2、新增注入类不一定要重新生成代码，因为很多适配器是共用的；注入过程找不到合适的适配器就会报错，那时你再重新生成；
3、源码是开放的：https://github.com/Tencent/xLua/tree/master/General/vs2013

**Comment by Frankzhaopku** [comment]
@chexiongsheng 啊，多谢，有注入工具的源码就方便很多了。另外现在遇到这样一个问题，使用namespace方式进行类型过滤，但是由于一些条件编译的问题，有些类型直接声明在了UNITY_EDITOR下面，如果在Editor上Generate Code，并在iOS下打包，会导致类型找不到的问题。
这种一般是怎么解决？是不在仓库里维护DelegateGensBridge，放在PreProcess下Generate还是Generate时可以对条件编译选项进行过滤？

**Comment by chexiongsheng** [comment]
注入都是你配置的啊，别配涉及到这种情况的类型不就可以了么？动态配置的自己在代码那过滤一下

**Comment by Frankzhaopku** [comment]
@chexiongsheng 好的哈，不知道有没有人之前出现过toLua和xLua混用的情况呢？因为我们之前一直使用toLua，但热更新部分想用xLua，这导致了在iOS上toLua初始化崩溃的问题，有过类似的案例么？

**Comment by chexiongsheng** [comment]
符号冲突导致的，你其中一个lua库的c代码里头所有函数都统一改下，加个前缀之类的就可以了

**Comment by Frankzhaopku** [comment]
@chexiongsheng 好的，我学习一下，多谢啦
