### ISSUE TITLE
C#注册类方法到Lua

### ISSUE THREAD

**Issue by liukaixdu** [Tencent/xLua#330]
我想把C#类方法注册到Lua中，然后可通过lua_pcall调用，通过MethodWrap实现吗？有没有类似LuaInterface中的RegisterFunction方法？

**Comment by chexiongsheng** [comment]
在C#那调用C#方法直接调不就可以了么？为什么要传给lua，然后用lua_pcall？
如果是lua调用C#方法，不需要有个手动注册的过程，你第一次访问的一瞬间自动帮你注册了。看看教程

**Comment by liukaixdu** [comment]
因为我的这部分主运行代码是C实现。之前的做法是把C#类方法注册到lua，实现函数绑定，比如C#中类方法Delay(）在lua中绑定一个名称"thread.delay"。然后在C代码中用lua_getglobal通过名称"thread.delay"获取Delay，把参数压入后，用lua_pcall调用执行。所以是一个C调用lua，lua调用C#的过程。

**Comment by chexiongsheng** [comment]
这些在xlua都有更简单的做法，具体看下教程
