### ISSUE TITLE
生成代码的行尾符是由什么决定的，由代码文件模板吗？

### ISSUE THREAD

**Issue by CodeMasterYi** [Tencent/xLua#338]
如题！
我们现在在Mac机上Jenkins自动打包流程中加入了自动生成xLua代码的过程，生成的代码文件用的是Windows行尾符，当我用我自己的Mac Mini手动的代码行尾符确是Unix风格的，前者打包流程会卡住，后者不会！
嗯。。。忽略打包问题，回到题目吧，生成的代码 用什么行尾符是由什么决定的呢？

**Comment by CodeMasterYi** [comment]
追加：以上两种情况均是切换到iOS平台之后再执行的Gen！

**Comment by chexiongsheng** [comment]
文件模版，你可以把那几个文件模版转换下
