### ISSUE TITLE
Interface获取Lua类型，方法调用传string不正确

### ISSUE THREAD

**Issue by XuTenTen** [Tencent/xLua#339]
C#代码
[CSharpCallLua]
		public interface ILuaMain
		{
			void OnStart();
			void OnRequire(string moduleName);
		}

Lua代码
main.OnRequire = function(moduleName)
	print(moduleName);
end

打印出来是个内存地址

**Comment by chexiongsheng** [comment]
第一个参数是self

**Comment by XuTenTen** [comment]
OK，搞定，是我看错了
