### ISSUE TITLE
Lua中如何实现Yield break？

### ISSUE THREAD

**Issue by dongxue** [Tencent/xLua#34]
在06_Coroutine的范例中，请问如何在lua中实现Yield break和stopCoroutine？

**Comment by chexiongsheng** [comment]
lua那直接return就可以相当于Yield break。
不用stopCoroutine，你不resume协程，然后引用也不指向它，自然它会被gc掉。

**Comment by dongxue** [comment]
如果我想中断一个运行中的Coroutine(不通过内部return的方式)，你的建议是什么呢？

**Comment by chexiongsheng** [comment]
在外部没有什么中断好说，lua是单线程的，当你在外部的时候，就代表这个协程不在运行，你不resume直接抛弃掉即可。

**Comment by chexiongsheng** [comment]
你是被Unity用genarator模拟的协程给误导了。Unity的模拟需要把一个genarator注册到协程调度里头，你在外部也要调用个Stop来反注册。

**Comment by dongxue** [comment]
在06_Coroutine范例中我通过在coruntine_test.lua中使用CS.GameObject.Destroy(gameobject)来实现了

**Comment by chexiongsheng** [comment]
哦，我理解错了，你是要中断在和Unity协程配合时，怎么清理Unity协程的问题。。不好意思！

**Comment by dongxue** [comment]
另外我想请教下，为了hotfix，我理论上是不是可以给所有自己的C#类打上HOTFIX_ENABLE，这样做有什么坏处么？

**Comment by chexiongsheng** [comment]
我在这里有分析overhead：https://www.zhihu.com/question/54344452，可以去看看
