### ISSUE TITLE
unity 5.6.4f1  windows平台偶尔crash

### ISSUE THREAD

**Issue by ihoukai** [Tencent/xLua#341]
大神，help，奔溃日志如下：

STACK_TEXT:  
039ad8e0 86c69814 unknown!unknown+0x0
039ad8e4 7766b9e2 ntdll_775e0000!ExecuteHandler2+0x26
039ad908 7766b9b4 ntdll_775e0000!ExecuteHandler+0x24
039adcd8 5e667a3e xlua!luaopen_lpeg+0x491e
039ae0c8 5e625de7 xlua!lua_setlocal+0x567
039ae0f4 5e621f7a xlua!lua_pcallk+0xba
039ae120 5e637df9 xlua!luaL_where+0xed9
039ae174 5e626039 xlua!lua_setlocal+0x7b9
039ae194 5e634514 xlua!lua_newthread+0x45a4
039ae2cc 5e625bde xlua!lua_setlocal+0x35e
039ae2dc 5e625c27 xlua!lua_setlocal+0x3a7
039ae2f4 5e621453 xlua+0x1453
039ae308 5e626249 xlua!lua_setlocal+0x9c9
039ae378 5e625de7 xlua!lua_setlocal+0x567
039ae3a4 5e621f7a xlua!lua_pcallk+0xba
039ae3d0 5e649de8 xlua!lua_pcall+0x18
039ae3f0 3680f660 unknown!unknown+0x0
039ae450 39a9bb70 unknown!unknown+0x0
039ae480 39a9ba1e unknown!unknown+0x0
039ae4b0 03cebf9f unknown!unknown+0x0
039ae4f4 0f5f1ce9 mono!mono_set_defaults+0x22cb
039ae524 0f55d8e4 mono!mono_runtime_invoke+0x51
039ae548 0128f198 Unity_x86!scripting_method_invoke+0x58
039ae568 01286908 Unity_x86!ScriptingInvocation::Invoke+0x78
039ae598 015f31ed Unity_x86!MonoBehaviour::CallMethodIfAvailable+0x1ad
039ae6b4 015f6ae8 Unity_x86!MonoBehaviour::CallUpdateMethod+0x108
039ae6c8 015f6af7 Unity_x86!MonoBehaviour::Update+0x7
039ae6d0 00db5f07 Unity_x86!BaseBehaviourManager::CommonUpdate<BehaviourManager>+0x157
039ae70c 00db6a42 Unity_x86!BehaviourManager::Update+0x62
039ae730 0100e722 Unity_x86!PlayerLoop+0x322
039ae750 01813719 Unity_x86!Application::UpdateScene+0x1b9
039ae788 01814d20 Unity_x86!Application::UpdateSceneIfNeeded+0x90
039ae7b0 0181ce43 Unity_x86!Application::TickTimer+0xa03
039ae8fc 018cbe66 Unity_x86!CrashCallback+0x386
039aeacc 018cd6a1 Unity_x86!WinMain+0x1581
039afef8 01b1e5a1 Unity_x86!strnlen+0x160
039aff88 769a38f4 KERNEL32!BaseThreadInitThunk+0x24
039aff9c 77645663 ntdll_775e0000!__RtlUserThreadStart+0x2f
039affe4 7764562e ntdll_775e0000!_RtlUserThreadStart+0x1b

（xlua库使用的这个https://github.com/chexiongsheng/build_xlua_with_libs）

**Comment by chexiongsheng** [comment]
看上去这个栈信息是乱的，lua_setlocal应该不可能调用luaopen_lpeg。
是乱的话，就没啥参考意义，上面的线上跑到xlua也不必当真。
