### ISSUE TITLE
hotfix inject in editor Error can not find delegate for ColorTools.nTof! try re-genertate code.

### ISSUE THREAD

**Issue by shwz** [Tencent/xLua#345]
finished! use 780.5557 ms
UnityEngine.Debug:Log(Object)
CSObjectWrapEditor.Generator:GenAll() (at Assets/XLua/Src/Editor/Generator.cs:1577)

已经genereate过，即使clear 再生成 再generate 再inject 报同样的错误

Error:can not find delegate for ColorTools.nTof! try re-genertate code.
XLua.Hotfix:HotfixInject() (at Assets/XLua/Src/Editor/Hotfix.cs:1296)

//报错方法
public class ColorTools
{
    private static float nTof(int n)
    {
        float t = (float)n / (float)255;
        return t;
    }
。。。。。。其它省略
]
2，我在项目plugins里有个Demo.dll  ，里面比如MainGameController公共类没有加命名空间，在xlua里hotfix调用怎么写 curLuaEnv.DoString(@"
                         xlua.hotfix(CS.Demo.MainGameController, 'LuaHotFix', function(self)
                                   。。。。。
用CS.Demo.MainGameController 报  cant find c# type
用Demo.MainGameController 报 LuaException: [string "chunk"]:2: attempt to index a nil value (global 'Demo')
用CS.MainGameController 报 LuaException: xlua.access, no field __Hotfix0_LuaHotFix

求解。
ps 源码里筛选hotfixconfig的地方有个这个判断条件  (type.Module.Assembly.GetName().Name == "Assembly-CSharp"))    意思是不支持其它dll的热更 只能是 Assembly-CSharp的热更吗

hotfix.md 里说 目前只支持Assets下代码的热补丁，不支持引擎，c#系统库的热补丁。  是不支持所有外来dll的热更么除了Assembly-CSharp

如果是，xlua核心文件必须和要热更的代码在同一个文件，是什么原因？能说明下吗？

**Comment by chexiongsheng** [comment]
问题1我试过是可以的。clear之后等编译完成再gen试试？另外确认下是不是最新版本。
问题2仔细看下xlua的文档，你这里有两个错误：不支持dll的热补丁；一个类的表示都是CS.名字空间.类名，不需要加dll名。

**Comment by shwz** [comment]
谢

**Comment by chexiongsheng** [comment]
主要担心被滥用，所以限定在业务代码这块，也就是仅支持Assembly-CSharp.dll的注入。

**Comment by shwz** [comment]
这么快，谢谢，我个人感觉应该需要支持。。。小小意见：1、以前的安卓热更很多基本都是走的dll热更的方式（比如我们公司、、），假如现在要迎合xlua，那么就要移动代码模块到unity里，有风险、、
2、现在游戏逻辑倒是很少，但是大部分都会把战斗逻辑那一块独立出去，正常情况也是用dll引用过来
3、unity既然支持这种方式，我觉得xlua也应该支持好些，这样能用的人更多了
我提的几个意见都是现在项目使用遇到的问题（以前只管安卓热更，ios的代码不热更的，现在想支持ios热更，所以在尝试阶段）’如果能支持，感谢万分

**Comment by chexiongsheng** [comment]
当时限死是担心乱配置，注入了unityengine.dll，mscrt这些程序集，搞出些幺蛾子出来，最终还是赖到xlua头上。
这种情况得考虑怎么防止。
而且要调整为支持多程序集的话，代码上也要做不小改动，最近又比较忙。
所以一时半会儿估计还是支持不了
先把这issues reopen跟进吧。

**Comment by chexiongsheng** [comment]
有个群友自己改成支持多dll的，可以联系一下“沧海遗粟”

**Comment by chexiongsheng** [comment]
@shwz master已经加入对多dll的注入支持，可以试试
