### ISSUE TITLE
请问 hotfix 子类中重载父类的方法

### ISSUE THREAD

**Issue by shishu123cn** [Tencent/xLua#35]
父类中有个  ：
  public virtual void Awake()
    {
        Debug.Log("name" + gameObject.name);
    }
子类中重载：
public override void Awake()
    {
        base.Awake();
        Debug.Log("testpanel awake===");
    }
我在hotfix 这个子类的Awake时：
xlua.hotfix(CS.TestPanel, 'Awake', function()
		print('<<<<<<<<Awake in lua')
	end)
这里，有什么办法还可以执行到父类的Awake。

**Comment by chexiongsheng** [comment]
目前没提供。。hotfix的话，你把父类逻辑也在lua实现就可以了。

**Comment by shishu123cn** [comment]
就是在hotfix的时候把父类的这个方法里面的逻辑也写到Lua里面？以后会有提供么？

**Comment by chexiongsheng** [comment]
想了下，貌似很难用很常规的办法提供。
