### ISSUE TITLE
关于开启hot_fix后执行luaEnv线程锁逻辑的问题

### ISSUE THREAD

**Issue by asunbb** [Tencent/xLua#350]
你好，
   默认情况下，开启宏HOTFIX_ENABLE后会执行luaEnv线程锁逻辑，请问是什么问题导致必须进行这样的操作？如果我能保证仅在单线程情况下使用luaEnv，开启HOTFIX_ENABLE后，是否可以不需要线程锁逻辑？

**Comment by chexiongsheng** [comment]
因为有些被你打补丁的函数可能会被析构函数调用。
析构函数是由gc线程调用的。

**Comment by asunbb** [comment]
谢谢:)
