### ISSUE TITLE
从tolua迁移到xlua的问题

### ISSUE THREAD

**Issue by chuqiuhan** [Tencent/xLua#351]
最近项目需要从tolua迁移到xlua，但是不想改之前tolua对dictionary和list的操作方法，如何让生成代码生成对应的get_Item和set_Item的方法给lua调用？需要怎样改一下xlua生成代码的逻辑？

**Comment by chexiongsheng** [comment]
https://github.com/Tencent/xLua/blob/master/Assets/XLua/Src/Editor/Generator.cs#L297

这里你判断下PropertyInfo的GetMethod/SetMethod的参数个数来判断是不是索引器，是索引器就别Remove

**Comment by chexiongsheng** [comment]
==,光这样还不够，还得在模版那特殊处理一下

**Comment by chexiongsheng** [comment]
https://github.com/Tencent/xLua/blob/master/Assets/XLua/Src/Editor/Template/LuaClassWrap.tpl.txt#L132

试下改下模版这里，把__CSIndexer，__NewIndexer，按名字为get_Item和set_Item的方法注册一次

**Comment by chuqiuhan** [comment]
改模板没有问题，https://github.com/Tencent/xLua/blob/790f08fa172a93565e1dee3462af43e71787b7f2/Assets/XLua/Src/Editor/Generator.cs#L402 这里为什么不能是string类型

**Comment by chexiongsheng** [comment]
看faq这里：https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/faq.md#%E6%9C%89%E7%9A%84unity%E5%AF%B9%E8%B1%A1%E5%9C%A8c%E4%B8%BAnull%E5%9C%A8lua%E4%B8%BA%E5%95%A5%E4%B8%8D%E4%B8%BAnil%E5%91%A2%E6%AF%94%E5%A6%82%E4%B8%80%E4%B8%AA%E5%B7%B2%E7%BB%8Fdestroy%E7%9A%84gameobject

你把括号索引这种方式完全去掉，换成get_Item和set_Item的话，还是可以去掉这个限制的。
另外，改这些只是修改了生成代码部分，还有emit和反射都一起改了，才完整，这样不生成代码行为也一致。
emit大概这地方：https://github.com/Tencent/xLua/blob/master/Assets/XLua/Src/CodeEmit.cs#L1199
反射大概这地方：https://github.com/Tencent/xLua/blob/master/Assets/XLua/Src/Utils.cs#L644
