### ISSUE TITLE
2.1.11版本调用Dictionary的GetEnumerator()会报以下错误

### ISSUE THREAD

**Issue by zhchbh** [Tencent/xLua#353]
LuaException: c# exception:System.Exception: SetCSTable for [System.Collections.Generic.Dictionary`2+Enumerator[System.Int32,System.Collections.Generic.List`1[LitJson.JsonData]]] error: 
  at XLua.Utils.SetCSTable (IntPtr L, System.Type type, Int32 cls_table) [0x00087] in /xlua/Assets/XLua/Src/Utils.cs:1361

**Comment by chexiongsheng** [comment]
我试了下没报错啊

**Comment by zhchbh** [comment]
这个和Unity版本有关系吗？我们之前用的5.6.4p1版本这个地方不会报错，升级到2017.4.1f1就出现这个错误了，这2者会有什么关联吗？

**Comment by chexiongsheng** [comment]
贴下你的代码？

**Comment by zhchbh** [comment]
这个就是我们用来验证这个问题的源代码，有效代码就这2句～～
 我们再开辟个新工程实验一下吧
