### ISSUE TITLE
Hotfix调用参数问题。

### ISSUE THREAD

**Issue by Meteor0679** [Tencent/xLua#354]
HotfixTest2中的一段代码。
double num;
string str = "hehe";
luaenv.DoString(@"
            xlua.hotfix(CS.HotfixCalc, 'TestOut', function(self, a, c, go)
                    print('TestOut', self, a, c, go)
                    print(go)
                    if go then error('test error') end
                    return a + 10, a + 20, 'right version'
                end)
        ");
Debug.LogError(num);
Debug.LogError(str);   
ret = calc.TestOut(100, out num, ref str);
得到的输出结果是
102
hehe
LUA: TestOut	HotfixCalc: -2056485760	100  	hehe 	nil

为什么在lua中输出变了 不应该是c=num go=str吗？

**Comment by chexiongsheng** [comment]
看下基本规则：https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/XLua%E6%95%99%E7%A8%8B.md

**Comment by Meteor0679** [comment]
找到了 感谢
