### ISSUE TITLE
[求助]HotFix注入导致iOS打包失败

### ISSUE THREAD

**Issue by Frankzhaopku** [Tencent/xLua#355]
HotFix开启后在iOS打包流程中自动注入，从Unity编译到xcode工程没有问题，但之后xcode工程编译会失败。

所有abstract类的abstract函数会在Ld arm64时报Undefined symbols for architecture arm64，不知是否出现过类似的问题，有什么解决的办法么？

**Comment by chexiongsheng** [comment]
更新到master

**Comment by chexiongsheng** [comment]
或者下载这两个文件覆盖下
https://github.com/Tencent/xLua/releases/tag/v2.1.11p2

**Comment by Frankzhaopku** [comment]
嗯嗯，好的，已经可以了，多谢

**Comment by Frankzhaopku** [comment]
@chexiongsheng 虽然关掉了，还是想再咨询一下，注入时对于Type和Method都是直接取Mono Cecil的进行遍历，对于重载函数是否可以保证不同平台下的稳定性呢？有没有考虑过可能会出现两个重载函数，在不同平台下各自注入时出现顺序不一致的情况呢？

**Comment by Frankzhaopku** [comment]
如果是这样的话，例如int add(int, int)和vector3 add(vector3, vector3)还好，但如果重载的参数列表完全不同，是依靠类型来区分的话怎么办呢？

**Comment by chexiongsheng** [comment]
通过检查参数类型和参数个数就可以区分。
lua基本类型用type(xx)，c#复杂类型用obj:GetType()

**Comment by fingerpasswang** [comment]
GetType用来做重载的match解决不了多态的问题。
这个有没有考虑过对各重载版本直接生成不同的桩呢？
这样也可以更精准地热更某个重载函数。

**Comment by fingerpasswang** [comment]
这样确实可以，谢谢。
还有个小问题，就是我找了下Doc里面似乎没有专门的页面或example解释热更新的各种case？
比如热更新一个带out/ref参数的函数时的写法，热更新一个泛型函数的写法（字符串格式按泛型类型的来？）。

**Comment by chexiongsheng** [comment]
hotfix.md

**Comment by Frankzhaopku** [comment]
请问一下热更新时，如果热更坏了一个函数，此时想要回退这个可以做到么？可以直接[funcName]=nil这样使桩失效么？或者有其他的函数可以做到清理已打热更新patch的么？

**Comment by chexiongsheng** [comment]
xlua.hotfix(cls, method, nil)
