### ISSUE TITLE
luac字节码加载报错

### ISSUE THREAD

**Issue by 850176300** [Tencent/xLua#356]
我使用lua 5.3.4生成的luac工具，打出来的luac文件在的时候一直提示"LuaException: error loading module Boot from CustomLoader, Boot.lua: size_t size mismatch in precompiled chunk"，而且我切换了luac的位数也没有解决这个问题，修改lua 5.3.4 ldump和lundump的size_t类型也不起作用，请问这个是什么原因导致的呢

**Comment by chexiongsheng** [comment]
得区分32、64位，还有注意你读文件是不是用了啥编码

**Comment by Jayatubi** [comment]
@850176300 https://www.jianshu.com/p/3c49cf454502 这个可以了解一下

**Comment by 850176300** [comment]
已经解决了，是android那边需要用32位的luac工具生成luac代码

**Comment by linimass** [comment]
请问有64位luac吗

**Comment by chexiongsheng** [comment]
@linimass 按这个处理下，就不用区分32、64了：https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/compatible_bytecode.md

**Comment by jerry-zeng** [comment]
@chexiongsheng 我按md里说的加了兼容性参数 -DLUAC_COMPATIBLE_FORMAT=ON，编完安卓的libxlua.so之后报新的错误：format mismatch in precompiled chunk。
然后你md链接那个make_unix.sh没了，里面是什么东西？现在要编一个你修改过的luac

**Comment by chexiongsheng** [comment]
@jerry-zeng make_unix.sh在这里https://github.com/Tencent/xLua/tree/master/build/luac

**Comment by jerry-zeng** [comment]
@chexiongsheng 好的，已经编出来luac了，安卓上能跑。好像苹果手机要求64位，同一份luac代码，不知道苹果手机上能不能直接用，还是说需要再编一份没有兼容性的luac代码给苹果用。手头没苹果手机，暂时没法测试。

**Comment by chexiongsheng** [comment]
@jerry-zeng 看下文档，改完就不区分32，64，什么平台都一样。

**Comment by BanMing** [comment]
直接用Process运行luac编译（这里用luac.exe也用了unix版的luac），在mac下会报错win32 invalid data，编译的某个文件就报这个错，并且每次报错的lua文件都不一样。在windows上编译是对的，编译出来在安卓和pc上可以运行。

**Comment by conyard** [comment]
> @chexiongsheng 好的，已经编出来luac了，安卓上能跑。好像苹果手机要求64位，同一份luac代码，不知道苹果手机上能不能直接用，还是说需要再编一份没有兼容性的luac代码给苹果用。手头没苹果手机，暂时没法测试。

我luac编译出来的，windows运行正常，android安卓上面不正常，报错：
LuaException: error loading module Main from CustomLoader, /storage/emulated/0/Android/data/xxx/files/_resRoot/Android/Lua/Main.lua: corrupted precompiled chunk

我用的 lua-5.3.5_Win64_bin/luac53.exe 进行的编译。

**Comment by conyard** [comment]
> 直接用Process运行luac编译（这里用luac.exe也用了unix版的luac），在mac下会报错win32 invalid data，编译的某个文件就报这个错，并且每次报错的lua文件都不一样。在windows上编译是对的，编译出来在安卓和pc上可以运行。

奇怪，我刚刚试了下，windows是可以的，但是android安卓缺不行，我用的 lua-5.3.5_Win64_bin/luac53.exe 进行的编译。

android安卓上面不正常，报错：
LuaException: error loading module Main from CustomLoader, /storage/emulated/0/Android/data/xxx/files/_resRoot/Android/Lua/Main.lua: corrupted precompiled chunk

**Comment by hongjunwang** [comment]
> > 直接用Process运行luac编译（这里用luac.exe也用了unix版的luac），在mac下会报错win32 invalid data，编译的某个文件就报这个错，并且每次报错的lua文件都不一样。在windows上编译是对的，编译出来在安卓和pc上可以运行。
> 
> 奇怪，我刚刚试了下，windows是可以的，但是android安卓缺不行，我用的 lua-5.3.5_Win64_bin/luac53.exe 进行的编译。
> 
> android安卓上面不正常，报错：
> LuaException: error loading module Main from CustomLoader, /storage/emulated/0/Android/data/xxx/files/_resRoot/Android/Lua/Main.lua: corrupted precompiled chunk

我基于Lua 5.3.5去跑出来，也同样遇到这个问题。请问谁可以帮忙回答一下这个问题

**Comment by IceFrogx** [comment]
> 已经解决了，是android需要用32位的luac工具生成luac代码

32位的luac工具有吗，我不知道在哪里弄
