### ISSUE TITLE
hotfix脚本的Awake方法后，为什么lua会重复执行2遍逻辑？

### ISSUE THREAD

**Issue by MiniKimmy** [Tencent/xLua#357]
我代码这样:
xlua.hotfix(CS.GameManager, {
    Awake = function(self)
          print('testtest')
  end;
}

然后控制台里看到执行了两次，不知道是什么问题。请指教

**Comment by chexiongsheng** [comment]
你不hotfix，在C#那加个打印看看？

**Comment by MiniKimmy** [comment]
我把hotfix Awake那部分注释掉之后，用回c#原本的逻辑执行的话，还是执行了2次Awake。

**Comment by MiniKimmy** [comment]
我找到问题了，我有2次调用了，，谢谢前辈，
