### ISSUE TITLE
Unable to open Editor/Data/UnityExtensions/Unity/GUISystem/UnityEngine.UI.dll: Check external application preferences.

### ISSUE THREAD

**Issue by shwz** [Tencent/xLua#358]
注入相关问题：
生成注入都提示成功了，但是部分预制体上挂的脚本会丢失（还没注入前是OK的），比如GraphicRaycaster 这个脚本，必丢失。但是脚本位置并没有显示miss，显示的是正确脚本位置，脚本下提示为：the associated script can not be load。。。。这个通用提示；点击脚本console里提示为Unable to open E:/Unity5.6.3/Editor/Data/UnityExtensions/Unity/GUISystem/UnityEngine.UI.dll: Check external application preferences.

我监听了注入时候加入AddSearchDirectory中的路径，引用的有上面那个路径，但是没有Library\UnityAssemblies这个路径，然后我改成手动添加（Library\UnityAssemblies）路径进去，但是错误内容并没有变化

求帮助、、、、、、、

**Comment by chexiongsheng** [comment]
上传个最简单能重现的工程？

**Comment by shwz** [comment]
线上项目，出同样问题的demo不太好做、、、我发现一个这样的注入bug，构造函数里注入是需要找到OpCodes.Ret，做切分，但是没有考虑到lambada公式，比如（经检测是注入错误）
        m_nRechargeAwardDic.Sort((a, b) =>
        {
            return a.id.CompareTo(b.id);
        });
这种写在构造函数内，注入就是错乱的

**Comment by chexiongsheng** [comment]
不会啊，闭包会编译器会另外生成一个匿名类和对应的函数，这个Ret不会在闭包所在函数那。
另外，你试试更新到master？2.1.11配套的注入工具会导致编译问题。

**Comment by shwz** [comment]
好的，我更新试下

**Comment by shwz** [comment]
更新后 构造函数内
public  xx(){
......
if（）
 {
   oringin_Instruction;
 }
}
这种方法 注入后代码
IL_00bf: ldsfld Main Main::Inst
IL_00c4: ldfld System.Boolean Main::IsOpenRecharge
IL_00c9: brfalse.s IL_0134
IL_00cb: ldsfld Main Main::Inst
IL_00d0: ldfld System.Boolean Main::IsShowTecentCoin
IL_00d5: brfalse.s IL_0134
IL_00d7: ldsfld Main Main::Inst
IL_00dc: ldfld YoukiaUnity.App.GlobalEvents YoukiaUnity.App.YKApplication::GlobalEvent
IL_00e1: ldc.i4.s 10
IL_00e3: box eSDKEvent
IL_00e8: ldarg.0
IL_00e9: ldftn System.Void RechargeModel::OnGetTencentQSuccess(System.Object[])
IL_00ef: newobj System.Void YoukiaCore.EventCallBack::.ctor(System.Object,System.IntPtr)
IL_00f4: ldc.i4.0
IL_00f5: ldc.i4.0
IL_00f6: callvirt System.Void YoukiaCore.YKEvent::AddEvent(System.Enum,YoukiaCore.EventCallBack,System.Boolean,System.Boolean)
IL_00fb: ldsfld Main Main::Inst
IL_0100: ldfld YoukiaUnity.App.GlobalEvents YoukiaUnity.App.YKApplication::GlobalEvent
IL_0105: ldc.i4.s 11
IL_0107: box eSDKEvent
IL_010c: ldarg.0
IL_010d: ldftn System.Void RechargeModel::OnBuyTencentQSuccess(System.Object[])
IL_0113: newobj System.Void YoukiaCore.EventCallBack::.ctor(System.Object,System.IntPtr)
IL_0118: ldc.i4.0
IL_0119: ldc.i4.0
IL_011a: callvirt System.Void YoukiaCore.YKEvent::AddEvent(System.Enum,YoukiaCore.EventCallBack,System.Boolean,System.Boolean)
IL_011f: ldsfld SDKHandler SDKHandler::inst
IL_0124: ldstr "selectMoney"
IL_0129: ldc.i4.0
IL_012a: newarr System.Object
IL_012f: callvirt System.Void SDKHandler::SendSDKMsg(System.String,System.Object[])
注入：
IL_0000: ldsfld XLua.DelegateBridge RechargeModel::_c__Hotfix0_ctor
IL_0000: stloc V_1
IL_0000: ldloc V_1
IL_0000: brfalse IL_0134
IL_0000: ldloc V_1
IL_0000: ldarg.0
IL_0000: call System.Void XLua.DelegateBridge::__Gen_Delegate_Imp8(System.Object)
注入：
IL_0134: ret

是不是变成这样了
public  xx(){
......
  if（）
  {
   oringin_Instructions;
   inject_Instructions;
  }
}
正常不是应该在if括号外吗，这个不经常看，是理解有问题吗？

**Comment by chexiongsheng** [comment]
没错，为空就跳到ret
反编译器会根据它的习惯来展现

**Comment by shwz** [comment]
这个是直接打的AssemblyDefinition 处理后的代码，我的意思是正常应该是在if外面，
这样 打出来的if是源代码里的
public xx()
{
    ......
    if（）
    {
    oringin_Instructions;
    }
    inject_Instructions;
}
而不是
public xx()
{
    ......
    if（）
    {
    oringin_Instructions;
    inject_Instructions;
   }
}

**Comment by chexiongsheng** [comment]
构造函数就是返回前，如果返回在if以内，注入代码就在if以内

**Comment by shwz** [comment]
已经确认这样在构造函数内注入是有问题的
1，用了reflector 、 系统自带的IL工具、ILSpy查看结果都显示同样结果，同样的问题
2，结合项目实际操作，注入log，检验也是一样

至少pc端运行是有问题的，
如果构造函数尾部有if语句，注入代码会注入进if中
还有个opcode的短字符问题也没有处理 

现注入会报
FileNotFoundException: Could not load file or assembly 'UnityEngine.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
System.MonoCustomAttrs.GetCustomAttributesBase (ICustomAttributeProvider obj, System.Type attributeType) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/MonoCustomAttrs.cs:108)
System.MonoCustomAttrs.GetCustomAttributes (ICustomAttributeProvider obj, System.Type attributeType, Boolean inherit) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/MonoCustomAttrs.cs:151)
System.MonoType.GetCustomAttributes (System.Type attributeType, Boolean inherit) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/MonoType.cs:595)
UnityEngine.AttributeHelperEngine.CheckIsEditorScript (System.Type klass) (at C:/buildslave/unity/build/Runtime/Export/AttributeHelperEngine.cs:131)

TypeLoadException: Could not load type 'YoukiaUnity.SpriteDeformerTools.SpriteDeformerWithBaseOfMaterialEditor' from assembly 'Assembly-CSharp-Editor, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.MonoCustomAttrs.GetCustomAttributesBase (ICustomAttributeProvider obj, System.Type attributeType) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/MonoCustomAttrs.cs:108)
System.MonoCustomAttrs.GetCustomAttributes (ICustomAttributeProvider obj, System.Type attributeType, Boolean inherit) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/MonoCustomAttrs.cs:151)
System.MonoType.GetCustomAttributes (System.Type attributeType, Boolean inherit) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/MonoType.cs:595)
UnityEngine.AttributeHelperEngine.CheckIsEditorScript (System.Type klass) (at C:/buildslave/unity/build/Runtime/Export/AttributeHelperEngine.cs:131)

这种类似的错误，暂时没发现对实际项目有影响
网上查找 个人判断是unity默认引用的某个程序集，和注入后的程序集版本不一致造成的，但是没有找到unity自动引用的某些程序集是否可以设置，比如 mscorlib

求帮助=。=（ps 上面的只是个人推测，有其它可能能提供给我也万分感谢！！！，还有我查看注入后的程序集引用发现会把自己的程序集加入自己的引用中，不知有没有影响）

**Comment by chexiongsheng** [comment]
不明白你说的“有问题”指的是？

**Comment by chexiongsheng** [comment]
为啥放if以内就是有问题呢？你这逻辑很奇怪啊

**Comment by chexiongsheng** [comment]
opcode的短字符问题指的是？

**Comment by chexiongsheng** [comment]
那个if的问题我知道你说的是什么问题了。opcode的短字符问题请描述下。
另外，注入报错得有个能重现的例子才比较好处理。

**Comment by shwz** [comment]
opcode 比如if的跳转
如果原代码里代码是brfalse_s 短字符的跳转，然后插入代码后，可能跳转的目标指令偏移超过1个字节了，然后注入后  并没有把brfalse_s 变成brfalse  生成的IL代码直接就有问题，我看了mono.cecil上已经有人描述过这个问题，我现在用的是5.6.3p3版本的unity里的mono.cecil，难道是这个版本还没有更正这个错误，但是我觉得xlua应该需要兼容这类短字符问题

**Comment by chexiongsheng** [comment]
丢脚本是不是你用的cecil和我代码不配套导致的？你用了inject_witdout_tool模式？你试试默认的小工具模式

**Comment by shwz** [comment]
嗯，用的without_tool模式，行，我试试工具模式

**Comment by shwz** [comment]
还是不行，我再找找先=。=

**Comment by chexiongsheng** [comment]
还有你用的xlua版本？如果是2.1.11的话，你要打上这个patch：https://github.com/Tencent/xLua/releases/tag/v2.1.11p2

**Comment by shwz** [comment]
版本是最新的

**Comment by chexiongsheng** [comment]
你是不是把xlua放到plugins、stand asserts之类的目录了？

**Comment by chexiongsheng** [comment]
构造函数if的那个问题已经改了。
短跳转指令貌似在unity不存在，unity的编译器貌似总是生成长指令跳转。.net编译器csc加上优化选项倒是会生成短指令
不过稳妥起见我还是加了短指令修复为长指令了
