### ISSUE TITLE
您好，请问hotfix在stateful模式下，在lua中怎么拿到其他lua类构造函数返回的表呢？

### ISSUE THREAD

**Issue by missxiaoxiao** [Tencent/xLua#359]
举例：
<pre>
xlua.hotfix(CS.A,
{
['.ctor'] = function(obj)
	return 
	NewA = {
	        obj = obj,
        	NewFunc = function()
	            print("new func")
	        end
	        }
end,
}
xlua.hotfix(CS.B,
{
    ['.ctor'] = function(obj)
	return 
	{
	    obj = obj,
	    NewFunc = function()
	     --这里我想调用CS.A中的NewFunc，请问要怎么调用呢？
    	end,
	}
 end,
}
</pre>
另外CS.A在hotfix后，构造函数返回的table（NewA），在lua的其他类中有没有办法获得呢？因为我现在遇到一个问题是，在lua中我通过getcompent()获得到一个hotfix过的组件后，不知道怎么调用在lua中新添加的函数了。

麻烦您解答一下疑惑，非常谢谢您了。

**Comment by missxiaoxiao** [comment]
您好，我这里函数之所以放里面，是想要在函数内部使用构造函数返回的表，放外边的话有没有办法可以拿到这个构造函数返回的table(NewA)呢？

**Comment by chexiongsheng** [comment]
在外部做个c#对象到table的关联不就可以了么？
其实就是个lua编程，程序组织问题。我不了解你很具体的情况，也给不出一定很合适的建议，况且，编程问题不宜在这问

**Comment by missxiaoxiao** [comment]
好的了解了，我也想过外部关联，但我以为lua内部会有现成的Api可以调用获得只是我不知道，谢谢您的回复哈。祝工作顺利~
