### ISSUE TITLE
前辈你好，想问下怎么在lua调用c#了带out参数的方法

### ISSUE THREAD

**Issue by MiniKimmy** [Tencent/xLua#360]
我在c#简单写了个方法: 
public class MyClass {
   public void CS_Method( out string ret_name)
   {
        ret_name = "Hello";
   }
}
------------------------------------
我在lua里这样用
function lua_method( myclass )
     local ret
     myclass:CS_Method( ret )
     print( ret )
end
------------------------------------
但是打印是nil 
想问问带out修饰的c#方法应该怎么在lua使用的？

**Comment by chexiongsheng** [comment]
看教程
