### ISSUE TITLE
Toggle反注册后依然报错， try to dispose a LuaEnv with C# callback

### ISSUE THREAD

**Issue by suifcd** [Tencent/xLua#361]
toggle进行了addListener，在onDestroy后进行了removeListener，但是luaEnv在Dispose时依然会出现这个错误。
重现方法，新建一个toggle，使用下面的测试代码，运行游戏后点击toggle进行切换，关闭游戏即可重现
LuaBehaviour.cs
`private LuaEnv luaEnv;//= new LuaEnv(); //all lua behaviour shared one luaenv only!
void OnDestroy()
       luaEnv.Dispose();`

LuaTestScript.lua
`local m_toggle;

function ToggleTest(isActive)
	print("ToggleTest");--要让这句话执行才能重现
end

function start()
	m_toggle = Toggle:GetComponent(typeof(CS.UnityEngine.UI.Toggle));
	m_toggle.onValueChanged:AddListener(ToggleTest);
end

function ondestroy()
	m_toggle.onValueChanged:RemoveListener(ToggleTest);
end`

**Comment by chexiongsheng** [comment]
估计是内部的cache，有相关issues，网上也有相关文章。

**Comment by suifcd** [comment]
查了unity源码，确实如此，里面有个m_ExecutingCalls对此持有引用，所以会报这个错误。
根据源码分析，由于是内部类，找到了清理的地方，查询调用关系，找到了一个解决方案，算是曲线救国吧。
在进行RemoveListener后，在自己手动调用下invoke，内部即会清理对应的引用
`function ondestroy()
m_toggle.onValueChanged:RemoveListener(ToggleTest);
m_toggle.onValueChanged:Invoke();
end`

**Comment by hlouis** [comment]
想问一下，有什么好的办法查出具体是哪个 Delegation 被 Unity 持有，因为现在项目比较复杂，从注册的Pool中也只能看到 Delegate 的声明样式，很难定位具体是哪里注册。

**Comment by chexiongsheng** [comment]
@hlouis 那么麻烦的话，还不如考虑下别Dispose好了。

**Comment by hlouis** [comment]
我们现在的设计是每个 scene 拥有自己的 Lua 虚拟机（热更scene，登陆scene，游戏scene），这样可以保证在小退、重新选服的情况下，没有任何临时状态的残留，所以会有 Dispose 的需求。

**Comment by suifcd** [comment]
delegate的注册时在ObjectTranslator.CreateDelegateBridge，注册的时候获取堆栈信息，refrence是唯一的可以做键，在dispose的时候也就是ObjectTranslator.AllDelegateBridgeReleased去查前面存取的堆栈信息就可以知道是哪个的引用没释放了

**Comment by suifcd** [comment]
有个问题就是如果是c#获取的lua引用，比如scriptEnv.Get("Awake", out luaAwake);这样的语句，在CreateDelegateBridge时我们能拿到的是L, luaEnv, reference这几个参数，不知道能不能利用这几个参数获取到该脚本具体对应的gameObject？

**Comment by Issacy** [comment]
#139
