### ISSUE TITLE
lua调用c#函数，无法识别Transform类型

### ISSUE THREAD

**Issue by yanfeijump** [Tencent/xLua#362]
刚使用xlua，不知道是不是我自己配置问题。
测试导出函数（静态，非静态都试过），也尝试generate code，但就是发现lua端传入参数类型为Transform时，会报错(can't convert source type to....)。其他引用类型如GameObject是正常的。当Transform类型参数传入nil时，才不会报错。参数位置也测试过，无关。
这个问题在xlua里，最可能发生的原因是什么?因为我们是从slua工程转过来的，slua相关的东西都删除了，lua代码里应该没有相关的东西了。

**Comment by chexiongsheng** [comment]
最可能是你用的是假xlua。
亲测不存在这问题。
没有特殊对待过Transform，可能是你代码里头特殊处理Transform

**Comment by yanfeijump** [comment]
问题已经找到了，是因为在参数列表里有一个int类型，而调用者把一个枚举值传进去，因为之前slua枚举和int类型是可以直接转的，而xlua认为枚举不是int，导致参数匹配出错。
