### ISSUE TITLE
XLua > Hotfix Inject In Editor提示了error,没有生成成功

### ISSUE THREAD

**Issue by SYRollingStone** [Tencent/xLua#364]
我是mac开发环境，下载了xlua的最新版本。倒入到了unity中。
按照文档操作：先添加了HOTFIX_ENABLE，然后生成代码，但是在XLua > Hotfix Inject In Editor，它提示了error，自动生成的文件中找不到路径，请教是什么问题？谢谢作者。
![bf7cf1a54068378933c38d051a28043b](https://user-images.githubusercontent.com/11360212/39392486-359be5b2-4ae9-11e8-89f4-67a29d294f5c.png)
我的开发环境是unity2017.3.1最新版本。

**Comment by SYRollingStone** [comment]
已结局，一定要内嵌模式。感谢作者提供这么优秀的工具。

**Comment by chexiongsheng** [comment]
别用内嵌模式。
是你第一次执行没生成代码，所以Gen目录不存在，所以在Gen目录下创建Resources目录不成功。
后面行是因为你把Gen目录给折腾出来，跟内嵌模式没关系。

**Comment by chexiongsheng** [comment]
master的版本在mac下是会报这个错误，你先用正式的发布版本：2.1.11加上patch
