### ISSUE TITLE
UnityEngine.LayerMask的静态成员函数无法调用

### ISSUE THREAD

**Issue by yanfeijump** [Tencent/xLua#366]
已经给UnityEngine.LayerMask打上了导出标签，但在lua端调用UnityEngine.LayerMask.NameToLayer时，却提示not such type的错误，似乎UnityEngine.LayerMask的特殊之处是它是个struct？请问是我们的没有使用对吗？

**Comment by chexiongsheng** [comment]
可以调用，检查下你的调用代码。

**Comment by 364199013** [comment]
hello  有解决这个问题么？？可否告知解决方案 ..谢谢
