### ISSUE TITLE
使用Unity命令行打包，batchmode 方式，无法被动调用Hotfix Inject

### ISSUE THREAD

**Issue by axlk** [Tencent/xLua#367]
情况是这样的，我们项目是使用脚本一键打包

但是集成xlua后，发现 Hotfix.cs中的 HotfixInject 函数没有被被动调用过。导致注入失败，热更代码无法执行，都提示 no field xxx

只有在Unity打开的情况下，打包，这个PostProcessBuild的 HotfixInject函数才会被调用

请问有碰到同样问题的人么?求教怎么解决

**Comment by chexiongsheng** [comment]
选择1，手动加上HOTFIX_ENABLE（不能在你打包脚本那设置这宏）。
选择2，你打包脚本那调用HotfixInject函数

**Comment by axlk** [comment]
找到问题了 ，就是因为Unity中的宏是打包时动态添加的，导致HOTFIX_ENABLE无效所以没有生成，谢谢提醒
