### ISSUE TITLE
xLua如何在lua层判断C#对象是null？

### ISSUE THREAD

**Issue by CodeMasterYi** [Tencent/xLua#369]
如题，想着tostring(go)=='null: 0'这种方法并不是特别好，是不是提供了别的方法，我不知道的？

**Comment by vanxining** [comment]
https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/faq.md#%E6%9C%89%E7%9A%84unity%E5%AF%B9%E8%B1%A1%E5%9C%A8c%E4%B8%BAnull%E5%9C%A8lua%E4%B8%BA%E5%95%A5%E4%B8%8D%E4%B8%BAnil%E5%91%A2%E6%AF%94%E5%A6%82%E4%B8%80%E4%B8%AA%E5%B7%B2%E7%BB%8Fdestroy%E7%9A%84gameobject

**Comment by CodeMasterYi** [comment]
thx
