### ISSUE TITLE
请问lua脚本怎么签名?

### ISSUE THREAD

**Issue by MxuerXF** [Tencent/xLua#371]
关于签名,文档说明的比较简单,示例是读取的示例,
运行Tools/FilesSignature.exe,仅仅弹出cmd一瞬间就自动关闭了
是我使用的方式有什么问题吗?

关于释放hotfix的C#回调
只能用使用
xlua.hotfix(class,'funcName',nil)
进行释放吗?
有一次性释放所有的函数吗?又或者说,在直接关闭整个app的时候,不Dispose会不会有影响?
以及想问下为什么
xlua.hotfix(class,{
   funcName = nil;
   funcName2 = nil
})
这种形式不能释放呢

**Comment by chexiongsheng** [comment]
按lua的语法，value是nil相当于没东西
所以你那代码相当于xlua.hotfix(class,{})

**Comment by chexiongsheng** [comment]
签名看这里：https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/signature.md

**Comment by MxuerXF** [comment]
@chexiongsheng 
谢谢回答
签名的文档我是看过的,其他都没有问题,唯独这个给lua文件加密搞不定
运行之后没有机会填写"参数是源目录和目标目录"的机会,窗口就自动关闭了

**Comment by chexiongsheng** [comment]
签名不是加密。
没提供加密功能。
