### ISSUE TITLE
XLua，lua文件中有module报错

### ISSUE THREAD

**Issue by AngiesEmail** [Tencent/xLua#373]
报错内容：LuaException: /data/unity/unityTest/XLuaTest/Assets/XLuaStudy/test.lua:1: attempt to call a nil value (global 'module')
lua脚本：
module(..., package.seeall)
print "I study u3d"

local start = function ()
	print "start ......"
end

start()

c#脚本：
luaenv = new LuaEnv();
luaenv.AddLoader((ref string filepath) =>{
filepath = Application.dataPath + "/XLuaStudy/" + filepath.Replace('.', '/') + ".lua";
if (File.Exists(filepath))
            {
                return File.ReadAllBytes(filepath);
            }
            else
            {
                return null;
            }
});
luaenv.DoString(string.Format("require '{0}'",  "test"));

**Comment by chexiongsheng** [comment]
lua5.3没这api，这种东西不会自己google一下么？或者自己查下lua官方文档么？
