### ISSUE TITLE
Unity停止运行后卡死

### ISSUE THREAD

**Issue by chankinkwan20135937** [Tencent/xLua#374]
![qq 20180522103453](https://user-images.githubusercontent.com/21972324/40339204-e965eae6-5dab-11e8-9496-1793a2c00f7c.png)
我在业务代码都基本开发完成后导入Xlua，开始Xlua的使用
但我在Unity中调试Xlua的06_Coroutine例子时运行后再停止，Unity会卡死，不是崩溃
我以为只是这个场景有问题，但运行上图中的第一个和第三个后停止也会卡死，第二个并不卡死而是正常停止。
没有报错，不知道什么原因，求解

**Comment by chexiongsheng** [comment]
我这都不卡

**Comment by chexiongsheng** [comment]
你导入的目录结构是？以工程根目录开始发下截图？

**Comment by chankinkwan20135937** [comment]
![qq 20180522111455](https://user-images.githubusercontent.com/21972324/40340437-88a717a6-5db1-11e8-9b6d-bada4f70c6c9.png)
![qq 20180522111517](https://user-images.githubusercontent.com/21972324/40340438-88dbeed6-5db1-11e8-948a-8888177ea204.png)
![qq 20180522111544](https://user-images.githubusercontent.com/21972324/40340439-8913a470-5db1-11e8-9c39-e22d59b85885.png)

**Comment by chankinkwan20135937** [comment]
第二张图是Asset文件里的目录，第三张图是Xlua的目录

**Comment by chexiongsheng** [comment]
和多没关系吧，不少大项目用了xlua也没卡。
可能是和某个插件冲突了。
