### ISSUE TITLE
关于枚举值

### ISSUE THREAD

**Issue by chankinkwan20135937** [Tencent/xLua#375]
![qq 20180522143937](https://user-images.githubusercontent.com/21972324/40346095-466215fe-5dce-11e8-9a3c-6f69e87f54fb.png)
![qq 20180522144101](https://user-images.githubusercontent.com/21972324/40346096-469700de-5dce-11e8-9d54-79dd9461db09.png)

CS.Common.SceneAnimType.DoctorNeedHelp 是一个具体枚举值
void NextSceneAnim(Common.SceneAnimType type) 是lua要调用的方法
可以看到，在lua里正常输出了这个枚举值，我感觉这里应该没问题，但是报这个错是什么意思

**Comment by chexiongsheng** [comment]
因为你用了.去调用成员方法

**Comment by chankinkwan20135937** [comment]
是我太粗心了，十分感谢
