### ISSUE TITLE
Call snapshot() error

### ISSUE THREAD

**Issue by UltraREX** [Tencent/xLua#377]
Hi

when call snapshot() function in perf/memory.lua, there is some error raise up.

LuaException: invalid key to 'next'
stack traceback:
	[C]: in field 'snapshot'
	perf/memory.lua:15: in function 'perf.memory.snapshot'

please help me out.

**Comment by chexiongsheng** [comment]
This feature plans to rewrite， it is best not to use

**Comment by UltraREX** [comment]
@chexiongsheng  ok, thx
