### ISSUE TITLE
导出UWP项目后。LuaCallCSharp的代码全部失效

### ISSUE THREAD

**Issue by 364199013** [Tencent/xLua#379]
做了一个简单的DEMO .执行 local newGameObj = CS.UnityEngine.GameObject() 时 报错： NO Such Type:UnityEngine.GameObject 。在Android 和 IOS以及Windows 下都可以正常执行。在uwp 平台下是否有特殊设置？ xlua 用的第一个支持uwp的版本 2.1.7。Unity 版本是5.6.5f1 .UWP SDK 版本是10.0.14393.

**Comment by chexiongsheng** [comment]
没特殊设置。

**Comment by 364199013** [comment]
今天早上做了个DEMO试了用.net 导出。是没有问题的。但是用IL2Cpp 导出就会报No Such Type 的错误了。。可否告知你们之前用的哪个unity 版本么

**Comment by chexiongsheng** [comment]
我就是用.net，没用il2cpp

**Comment by 364199013** [comment]
那有没有可能不支持UWP 版的IL2CPP 导出呢？

**Comment by chexiongsheng** [comment]
你查找替换下
把
UNITY_WSA
替换为
(UNITY_WSA && !ENABLE_IL2CPP)

**Comment by 364199013** [comment]
好的。我试试。。万分感谢

**Comment by 364199013** [comment]
你好。我把所有的UNITY_WSA 替换为(UNITY_WSA && !ENABLE_IL2CPP) 后。打出的包显示Unity标志后。卡死闪退。。我在预编译里面添加ENABLE_IL2CPP定义和不添加都是这个结果。。

**Comment by chexiongsheng** [comment]
那可能就不支持uwp下的il2cpp。
或许是uwp下的il2cpp本身有bug也可能。

**Comment by 364199013** [comment]
大佬。。有什么办法可以拯救一下么。。我半路接手这个项目。。刚刚试了用.net完全导不出当前项目。。只能用IL2CPP...

**Comment by chexiongsheng** [comment]
或者我之前说的那个替换，你试试只替换这里
https://github.com/Tencent/xLua/blob/master/Assets/XLua/Src/Utils.cs#L60

**Comment by 364199013** [comment]
谢谢大佬。Demo导出IL2CPP 的 UWP 可以正常访问C#层了。。这个地方也要按照你说的添加宏才正确。
https://github.com/Tencent/xLua/blob/master/Assets/XLua/Src/ObjectTranslator.cs#L230

**Comment by fischLxy** [comment]
你好，我在项目中使用xlua发现，如果我每帧调用local pos = self.transform.localPosition，就会引起大量内存泄露，请问是什么原因，有什么好的办法解决
