### ISSUE TITLE
HotFix易用性的问题

### ISSUE THREAD

**Issue by dongxue** [Tencent/xLua#38]
void OnGUI()
    {
        if (GUI.Button(new Rect(10, 100, 300, 150), "Hotfix"))
        {
            luaenv.DoString(@"
                local tick = 0
                xlua.hotfix(CS.HotfixTest, 'Update', function()
                    tick = tick + 1
                    if (tick % 50) == 0 then
                        print('<<<<<<<<Update in lua, tick = ' .. tick)
                    end
                end)
            ");
        }
    }
根据你的范例，我想用lua重写Update方法，tick是一个类变量，我不能直接使用而要在lua中重新声明，如果我update中调用了类方法，是不是我也要在lua中重写，再进一步，如果我调用了一个类，是不是我也得在lua中重写这个类？这是否影响了hotfix的易用性，因为我只是想重写update方法。

**Comment by chexiongsheng** [comment]
Lua的update第一个参数是那个c#对象，上面的public的东西你都能直接用，私有的可以通过反射来访问。
你可以在C#那自己封装一个高效，易用的通用工具类来访问私有变量

**Comment by chexiongsheng** [comment]
我看通用工具我能提供下不
目前有个未公布的api：xlua.access(obj/cls, name, [value])，但不高效，每次都会有一次GetField调用。

**Comment by chexiongsheng** [comment]
我改了下例子，现在的例子是直接访问C#的tick了。

**Comment by dongxue** [comment]
好的，还有个小问题，每次改了hotFix里的lua代码，都要关掉HOTFIX_ENABLE再打开才能生效？

**Comment by chexiongsheng** [comment]
不用

**Comment by chexiongsheng** [comment]
甚至如果是文件，可以运行时多次加载，每次加载不一样的，后面覆盖前面的

**Comment by chexiongsheng** [comment]
运行时该lua文件，重新加载立即生效

**Comment by dongxue** [comment]
如果我把tick改为非public的，你说的要通过反射来访问，能给个具体的例子么？

**Comment by chexiongsheng** [comment]
using UnityEngine;
using System.Collections;
using XLua;
using System;
using System.Reflection;

[LuaCallCSharp]
public static class HotfixUtils
{
    public static void GetPrivateAccessor(object obj, string fieldName, out XLua.LuaDLL.lua_CSFunction getter, out XLua.LuaDLL.lua_CSFunction setter)
    {
        var field = obj.GetType().GetField(fieldName, BindingFlags.NonPublic | BindingFlags.Instance);
        var fieldType = field.FieldType;

        getter = (L) =>
        {
            try
            {
                ObjectTranslator translator = ObjectTranslatorPool.Instance.Find(L);
                translator.PushAny(L, field.GetValue(obj));
                return 1;
            }
            catch(Exception e)
            {
                return XLua.LuaDLL.Lua.luaL_error(L, "exception in xlua.access: " + e);
            }
        };

        setter = (L) =>
        {
            try
            {
                ObjectTranslator translator = ObjectTranslatorPool.Instance.Find(L);
                field.SetValue(obj, translator.GetObject(L, 1, fieldType));
                return 0;
            }
            catch (Exception e)
            {
                return XLua.LuaDLL.Lua.luaL_error(L, "exception in xlua.access: " + e);
            }
        };
    }
}

[Hotfix]
public class HotfixTest : MonoBehaviour {
    LuaEnv luaenv = new LuaEnv();

    private int tick = 0; //如果是private的，在lua可以用反射来访问

    // Use this for initialization
    void Start () {
    }

    // Update is called once per frame
    void Update () {
	    if (++tick % 50 == 0)
        {
            Debug.Log(">>>>>>>>Update in C#, tick = " + tick);
        }
	}

    void OnGUI()
    {
        if (GUI.Button(new Rect(10, 100, 300, 150), "Hotfix"))
        {
            luaenv.DoString(@"
                local getter, setter
                xlua.hotfix(CS.HotfixTest, 'Update', function(self)
                    if getter == nil then
                        getter, setter = CS.HotfixUtils.GetPrivateAccessor(self, 'tick')
                    end
                    setter(getter() + 1)
                    if (getter() % 50) == 0 then
                        print('<<<<<<<<Update in lua, tick = ' .. getter())
                    end
                end)
            ");
        }
    }
}

**Comment by dongxue** [comment]
好吧，看上去还是xlua.access(obj/cls, name, [value])这个API看上去简约点，也许你可以考虑公开，反正都是反射

**Comment by chexiongsheng** [comment]
这只是为了性能才搞成getter/setter，为了省一次GetField和一个obj参数的传递。
类似xlua.access的接口你也可以实现

**Comment by chexiongsheng** [comment]
有个更完美的方案，xlua提供某个api设置一下某个类，然后这个类的private属性，方法都可以用了。

**Comment by dongxue** [comment]
[Hotfix]能默认就打开对private的属性访问就好了

**Comment by chexiongsheng** [comment]
已经增加，文档：https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/hotfix.md
默认打开不太好，xlua.private_accessible会把该类下的私有东东也生成个基于反射的wrapper，有一定开销。
