### ISSUE TITLE
vmware虚拟机里面报错 xcode 报错 _xlua_get_lib_version 

### ISSUE THREAD

**Issue by chenqiu1988** [Tencent/xLua#380]
xlua版本 2.1.6 
xcode版本 6.1.1 
一直在安卓打包发布都是ok的 
现在使用vmware装了macos 准备打包ipa在编译的时候报错 _xlua_get_lib_version ,我的libxlua.a 已经加到unity中了,为什么呢?

**Comment by chexiongsheng** [comment]
编辑器下用xlua.bundle

**Comment by chenqiu1988** [comment]
我添加了xlua.bundle还是不行 依然报这个错 mac开发不是很熟悉 我是这样操作的

**Comment by chexiongsheng** [comment]
为啥不直接在vmware里的unity导出ios工程呢？

**Comment by chenqiu1988** [comment]
我今天试试在vmware里面 用unity导出ios工程

**Comment by chenqiu1988** [comment]
在vmware虚拟机里面导出 ios工程 依然不行,和windows报错一样,我还是升级一下xlua的版本试试吧

**Comment by chenqiu1988** [comment]
升级到最新2.1.11 OK了
