### ISSUE TITLE
ios build error: "_luaopen_rapidjson" not found

### ISSUE THREAD

**Issue by Jason-Zy** [Tencent/xLua#381]
Undefined symbols for architecture arm64:
  "_luaopen_rapidjson", referenced from:
      _ReversePInvokeWrapper_Lua_LoadRapidJson_m4049631263 in Bulk_Assembly-CSharp_62.o
      _Lua_LoadRapidJson_m4049631263 in Bulk_Assembly-CSharp_62.o
      _Lua_luaopen_rapidjson_m2237371995 in Bulk_Assembly-CSharp_62.o
     (maybe you meant: _Lua_luaopen_rapidjson_m2237371995)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by chexiongsheng** [comment]
你的ios库没把这第三方库编辑进去
