### ISSUE TITLE
ios平台Animator.Play(string)报参数错误

### ISSUE THREAD

**Issue by CodeMasterYi** [Tencent/xLua#382]
前几天咱们ios项目打包出来后animator:Play(name)会报参数错误，但是安卓上却不会如此，请求指点方向，可能是什么原因导致的呢？！

**Comment by CodeMasterYi** [comment]
会是剪裁的原因吗？

**Comment by yasarzhang** [comment]
audiosource:Play 也报错了

**Comment by chexiongsheng** [comment]
可能是剪裁了，多个重载，你用到那个被剪裁，所以报参数错误。
加到LuaCallCSharp试试？
