### ISSUE TITLE
发布到安卓平台报这个错误，xLua exception : xlua.access, no field __Hotfix0_Update

### ISSUE THREAD

**Issue by CircleGood** [Tencent/xLua#383]
在Unity 点击 Hotfix Inject In Editor  不会有这个错误。

**Comment by CircleGood** [comment]
发布的时候也设置了。

**Comment by CircleGood** [comment]
官网的demo 是可以用的。就这个框架 发布到安卓不可以更新

**Comment by chexiongsheng** [comment]
哪块搞错了吧，很多项目用，没说不行

**Comment by chexiongsheng** [comment]
配错，配错地方，或者注入时报错。
总之没打印“hotfix inject finish!”或者“had injected!”就是没注入

**Comment by hansquirrel** [comment]
麻烦大佬帮看看日志，是不是这个No JNI_OnLoad found导致加载有问题，但是具体什么问题会导致这个呢？

D/dalvikvm( 5148): Trying to load lib /data/app-lib/com.hanjiasongshu.jianghux2-1/libxlua.so 0x94fb78a0
D/dalvikvm( 5148): Added shared lib /data/app-lib/com.hanjiasongshu.jianghux2-1/libxlua.so 0x94fb78a0
D/dalvikvm( 5148): No JNI_OnLoad found in /data/app-lib/com.hanjiasongshu.jianghux2-1/libxlua.so 0x94fb78a0, skipping init
E/Unity   ( 5148): LuaException: xlua.access, no field __Hotfix0_OnJump
E/Unity   ( 5148): stack traceback:
E/Unity   ( 5148):      [C]: in field 'access'
E/Unity   ( 5148):      [string "Init"]:88: in field 'hotfix'
E/Unity   ( 5148):      [string "hotfix.lua"]:9: in main chunk
E/Unity   ( 5148):   at XLua.LuaEnv.ThrowExceptionFromError (Int32 oldTop) [0x00000] in <filename unknown>:0
E/Unity   ( 5148):   at XLua.LuaEnv.DoString (System.Byte[] chunk, System.String chunkName, XLua.LuaTable env) [0x00000] in <filename unknown>:0
E/Unity   ( 5148):   at JianghuX.LuaManager.LoadLuaFiles () [0x00000] in <filename unknown>:0
E/Unity   ( 5148):   at JianghuX.LuaManager.Init (Boolean forceReset) [0x00000] in <filename unknown>:0
E/Unity   ( 5148):   at HotPatchingUI+<DOLoadResources>c__Iterator0.MoveNext () [0x00000] in <filename unknown>:0
E/Unity   ( 5148):   at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in <filename unknown>:0

**Comment by chexiongsheng** [comment]
和运行没关。
这问题就一个直接原因：没注入。

**Comment by hansquirrel** [comment]
实在是不太清楚应该如何来排查这个问题，在editor下都是OK的。但是不管怎么改，在真机上都无法hotfix，报错就是如上。

请问没注入的问题我应该如何来排查它？xlua会在什么时间点来进行注入？我理解应该不需要我来显式调用某些函数？

**Comment by chexiongsheng** [comment]
错误的做法，你看你打包日志应该看到注入失败的日志。
不能在同一次打包那生成代码并注入。因为生成的代码没编译。

**Comment by hansquirrel** [comment]
emmmm，我把打包流程中这几行都删掉。然后build出来，也还是一样的错误……

**Comment by hansquirrel** [comment]
额，看到报错了，应该是这个导致inject出错，但不太清楚怎么解决……

Error:can not find delegate for PlatformMsgManager.GetLongFromPlatform2! try re-genertate code.
WARNING: The runtime version supported by this application is unavailable.
Using default runtime: v4.0.30319

UnityEngine.Debug:Log(Object)
XLua.Hotfix:HotfixInject() (at Assets/XLua/Src/Editor/Hotfix.cs:1296)
UnityEditor.BuildPipeline:BuildPlayer(String[], String, BuildTarget, BuildOptions)
ChannelBuilder:GenericBuild(String[], String, String, BuildTarget, BuildOptions) (at Assets/Editor/ChannelBuilder.cs:396)
ChannelBuilder:BulidTarget(String, String) (at Assets/Editor/ChannelBuilder.cs:362)
ChannelBuilder:BuildAndroidHanjiasongshu() (at Assets/Editor/ChannelBuilder.cs:64)

**Comment by hansquirrel** [comment]
找到问题了。
把代码改成

CSObjectWrapEditor.Generator.ClearAll ();
CSObjectWrapEditor.Generator.GenAll();
while (EditorApplication.isCompiling) {
            ;
}

就可以了，正如您所说，原因是正在编译的时候无法inject成功。
建议您在Hotfix.Inject函数里如果直接return的话，报一个warning或者抛出异常来。这个问题查起来还不是那么直观。或者如果inject失败的时候，给一个明显的log提示。（抑或在hotfix的文档里写清楚，必须客户端日志打印hotfix inject  finish或者had injected才算注入成功）

**Comment by chexiongsheng** [comment]
文档写清楚了啊，一直都写必须打印那信息才算成功

**Comment by hansquirrel** [comment]
不好意思，是我们没有仔细查看。感谢帮助~

**Comment by Absolute127** [comment]
发布安卓apk之前已经手动进行了生成代码和注入，并显示finish。但到手机上运行还是会出现这个问题是为什么呢？

**Comment by chexiongsheng** [comment]
> 发布安卓apk之前已经手动进行了生成代码和注入，并显示finish。但到手机上运行还是会出现这个问题是为什么呢？

编辑器手动注入和手机没关系。编辑器手动注入仅仅用来调试你的补丁。

**Comment by Absolute127** [comment]
> > 发布安卓apk之前已经手动进行了生成代码和注入，并显示finish。但到手机上运行还是会出现这个问题是为什么呢？
> 
> 编辑器手动注入和手机没关系。编辑器手动注入仅仅用来调试你的补丁。

那么请问手机上出现这个xlua.access, no field __Hotfix0问题也是因为没有注入成功吗？该怎么解决呢？感谢

**Comment by nakamura343** [comment]
> 找到问题了。
> 把代码改成
> 
> CSObjectWrapEditor.Generator.ClearAll ();
> CSObjectWrapEditor.Generator.GenAll();
> while (EditorApplication.isCompiling) {
> ;
> }
> 
> 就可以了，正如您所说，原因是正在编译的时候无法inject成功。
> 建议您在Hotfix.Inject函数里如果直接return的话，报一个warning或者抛出异常来。这个问题查起来还不是那么直观。或者如果inject失败的时候，给一个明显的log提示。（抑或在hotfix的文档里写清楚，必须客户端日志打印hotfix inject finish或者had injected才算注入成功）

我想问一下，clearAll和GenAll之后，还用Hotfix.HotfixInject ();吗？
我和您遇到了完全一样的问题。就是打包后在真机上不能hotfix。在editor运行没有问题。

**Comment by BensonMaZIHao** [comment]
为啥我这边调用注入代码报错调不了那
   CSObjectWrapEditor.Generator.GenAll();
        CSObjectWrapEditor.Generator.GenAll();
        Hotfix.HotfixInject ();
