### ISSUE TITLE
addloader  加入的方法没有执行

### ISSUE THREAD

**Issue by shwz** [Tencent/xLua#385]
程序初始的时候   AddSearcher(StaticLuaCallbacks.LoadFromCustomLoaders, 3);  是执行了的

StaticLuaCallbacks.LoadFromCustomLoaders  没有执行过

加入的loader里面打断点也没有执行过

还有这句 “”如果需要支持调试，需要把filepath修改为真实路径传出“
是把 "require 'TemplateCommon'"   改成  类似 "require 'C:\xx\xx\TemplateCommon.lua.txt'" 的意思吗

**Comment by chexiongsheng** [comment]
CustomLoader传入的是require的参数，要把这个参数修改为调试器能找到的路径。

**Comment by shwz** [comment]
"require 'J:\\temp\\TemplateCommon.lua.txt'"    原路径是J:\temp\TemplateCommon.lua.txt  
用上面的方式 好像不支持转义符号
 "require 'J:/temp/TemplateCommon.lua.txt'"  还是不能调试

**Comment by chexiongsheng** [comment]
没说让你该require的参数啊。。
