### ISSUE TITLE
xlua 与 tolua 冲突了

### ISSUE THREAD

**Issue by Jason-Zy** [Tencent/xLua#387]
项目本来用的是tolua, 为了使用xlua 的hotfix 引入了xlua ，在android 和 pc上都没有问题，但是在ios上两边冲突了，是不是存在同名方法导致的？这个要怎么解决？

**Comment by chexiongsheng** [comment]
主要是lua库有很多函数是重名的，你把其中一个重命名，比如所有函数加个前缀

**Comment by rlafydid** [comment]
我这里是 xlua的 libxlua.a 和 其他第三方 .a文件 在IOS Xcode打包的时候 冲突了 这个应该怎么解决

**Comment by rlafydid** [comment]
在Xode报了以下报错，GameLink是无法修改的，能麻烦指定下需要改哪些文件，才能解决冲突吗？
duplicate symbol _numsiblings in:
    /Users/admin/Documents/Mahjong/iosmj/newios8/Libraries/Plugins/iOS/libGameLink.a(lptree.o)
    /Users/admin/Documents/Mahjong/iosmj/newios8/Libraries/Plugins/XLua/iOS/libxlua.a(lptree.o)
ld: 3 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by rlafydid** [comment]
重复的是 lptree.o 这个库文件，改这个库文件名需要在哪里改
