### ISSUE TITLE
Unity2018 .Net 4.0 生成C#代码报错

### ISSUE THREAD

**Issue by ming871** [Tencent/xLua#389]
![1528451514 1](https://user-images.githubusercontent.com/4309382/41152091-3d1abd1e-6b45-11e8-9c72-e9e1ba990383.png)
![1528451701 1](https://user-images.githubusercontent.com/4309382/41152093-3e8d61ba-6b45-11e8-8195-ac0d643e166f.png)
报错文本：
Assets/XLua/Gen/SystemCollectionsGenericDictionary2SystemStringSystemObjectWrap.cs(123,75): error CS1502: The best overloaded method match for `System.Collections.Generic.Dictionary<string,object>.Dictionary(System.Collections.Generic.IDictionary<string,object>)' has some invalid arguments

**Comment by ming871** [comment]
版本是：v2.1.10 patch

**Comment by chexiongsheng** [comment]
我下了个试没问题
2018.1.4f1
scripting runtime version设置为.net 4.x equivalient

**Comment by ming871** [comment]
我更新一下试试

**Comment by ming871** [comment]
[GameGenConfig.zip](https://github.com/Tencent/xLua/files/2100779/GameGenConfig.zip)
请试一下这个[CSharpCallLua] \[LuaCallCSharp] 配置，里面有配置：
typeof(Dictionary<String, System.Object>),
typeof(KeyValuePair<String, System.Object>),
这两个引起的

**Comment by chexiongsheng** [comment]
初步定位大概是2018这么设置时，editor和player的运行时版本不同导致的。

**Comment by ming871** [comment]
好的，Unity总有些这样那样得小毛病

**Comment by ming871** [comment]
那是否先不处理了，看看后续版本Unity会不会修改
