### ISSUE TITLE
lua文件 放置的目录有什么规定吗

### ISSUE THREAD

**Issue by matings79** [Tencent/xLua#39]
我把lua文件放到assets\resources\目录下， 总是报错module 'myfix' not found
放在XLua\Tutorial\LoadLuaScript\ByFile\Resources目录就没问题

**Comment by chexiongsheng** [comment]
放assets\Resources\可以的，可能是大小写或者拼写错误。

**Comment by chexiongsheng** [comment]
或者你写个CustomLoader，自己读文件。

**Comment by chexiongsheng** [comment]
自己写CustomLoader，规则由你定

**Comment by matings79** [comment]
谢谢， 我测试的结果是c#里面直接require的lua文件放到assets\resources\下面的子目录是不行的
我现在把c#require的lua文件放到assets\resources目录下， 然后在这个Lua文件里面再require这个目录的子目录里面的文件， 问题解决了

**Comment by lingllting** [comment]
如果是在lua侧要require非Resources的lua文件应该如何处理？毕竟热更新的文件是不在Resources目录下的

**Comment by chexiongsheng** [comment]
@lingllting 用customloader，想怎么玩都可以
