### ISSUE TITLE
存储在xlua中的gameObject,在IOS里面,被回收了,导致无法访问?

### ISSUE THREAD

**Issue by chenqiu1988** [Tencent/xLua#390]
先来一个小问题:
1.xlua在xcode里面,真机可以跑起来,但是不支持xcode模拟器运行?会提示找不到lib_version函数

第二个主要问题:
现象:游戏在安卓发布版和编辑器都没问题,但是导出ios真机测试,发现涉及xlua的几个接口,都异常.
环境:xlua 2.1.11(最新版). xcode 9, ios 10.3,
LOG:我有几个prefab,以前是在A场景中存储在lua中,然后B场景里面通过lua获得再初始化,现在lua返回gameobject为nil,报错导致.
猜想: 有提示
Unloading 16 unused Assets to reduce memory usage.
这些prefab在A场景,除了xlua,没有其他地方用到,好像被优化回收掉了,导致lua存储的gameobject为空
求问:为啥lua还在使用的对象,会被回收呢? 有没有办法保证lua使用的gameobject,不被系统回收呢?

**Comment by chenqiu1988** [comment]
关于问题2再补充一下 我把用lua 存储gameobject的那段代码用C# 重写了 没问题 和以前的安卓一样正常

**Comment by chexiongsheng** [comment]
在lua引用和在c#引用是一样的，lua也是通过C#那进行引用。
我猜你这问题是判空不当导致的，看下faq这里：
https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/faq.md#%E6%9C%89%E7%9A%84unity%E5%AF%B9%E8%B1%A1%E5%9C%A8c%E4%B8%BAnull%E5%9C%A8lua%E4%B8%BA%E5%95%A5%E4%B8%8D%E4%B8%BAnil%E5%91%A2%E6%AF%94%E5%A6%82%E4%B8%80%E4%B8%AA%E5%B7%B2%E7%BB%8Fdestroy%E7%9A%84gameobject

**Comment by chenqiu1988** [comment]
这个我再试试 还剩余一个问题
1.xlua在xcode里面,真机可以跑起来,但是不支持xcode模拟器运行，会提示找不到lib_version函数，老是真机跑，测试很不方便，怎么配置才能在xcode的模拟器里面跑呢？

**Comment by chexiongsheng** [comment]
自己编译模拟器版本的库

**Comment by chenqiu1988** [comment]
我试试
