### ISSUE TITLE
UnityEvent: Add lua function并Invoke再Remove, 并不会释放lua delegate bridge

### ISSUE THREAD

**Issue by Issacy** [Tencent/xLua#391]
将一个lua function添加到一个UnityEvent后, Invoke这个UnityEvent, 最后再从UnityEvent中Remove这个lua function, 此时如果这个UnityEvent没有被销毁, 则由这个lua function delegate bridge不会release

**Comment by Issacy** [comment]
例:  
lua侧  
```Lua
event = CS.UnityEngine.Events.UnityEvent()
local invokeFunc = function() print('inoking') end
event:AddListener(invokeFunc)
event:Invoke()
event:RemoveListener(invokeFunc)
```
如果这时C#侧  
```C#
luaEnv.Dispose()
```
会报`InvalidOperationException("try to dispose a LuaEnv with C# callback!")`  

但如果lua侧最后`event = nil`再调用`luaEnv.Dispose()`则不会报错

**Comment by chexiongsheng** [comment]
unity内部做了cache导致的，搜索下之前的issues或者google一下

**Comment by Issacy** [comment]
@chexiongsheng 谢谢

**Comment by chexiongsheng** [comment]
https://github.com/Tencent/xLua/issues/139
