### ISSUE TITLE
脚本使用module关键字会报错

### ISSUE THREAD

**Issue by frstrr** [Tencent/xLua#394]
在例子工程的LuaTestScript.lua.txt第一行加入 module("LuaTest")，提示attempt to call a nil value (global 'module')，是不支持使用module语法么，还是需要其他设置

**Comment by chexiongsheng** [comment]
lua 53已经废弃了module
你可以选择用luajit版本，或者改掉你用module的坏习惯。
ps，module不是什么关键字，只是个函数，因为其缺点早在lua5.2开始就废弃了。关于module的缺点网上一搜索一大堆。

**Comment by frstrr** [comment]
好的，谢谢
