### ISSUE TITLE
运行时xlua.private_accessible()在貌似查找类中event的时候出错

### ISSUE THREAD

**Issue by 1194451658** [Tencent/xLua#397]
先贴下Unity报错截图
![c575c0879ef1de2ed051778bb187e1c1](https://user-images.githubusercontent.com/4320428/41807458-cf66c2d6-7701-11e8-94e9-77be4a7915d8.png)
我们自己的代码
![281caa87e1c6c2c7280c0470f5a282f3](https://user-images.githubusercontent.com/4320428/41807472-e4fadd12-7701-11e8-9f9d-118be403a447.jpg)
运行的时候，在我们写的hotfix文件中，调用xlua.private_accessible(CS.SyncGame.SyncHeroController)的时候发生报错。请问下是否是我们使用上的错误?

**Comment by chexiongsheng** [comment]
这个早就修复了，你更新到master

**Comment by chexiongsheng** [comment]
或者找到那个提交合入

**Comment by 1194451658** [comment]
好的，谢谢
