### ISSUE TITLE
[hotfix]标签需要提前打上么

### ISSUE THREAD

**Issue by xclouder** [Tencent/xLua#4]
可能产品上线后才能知道具体哪里需要bugfix，热更新这个特性是否可以做到发布时没打[hotfix]标签的类，打补丁时再加上[hotfix]标签？

感觉这样比较适合一般使用场景，尤其是iOS平台。

**Comment by chexiongsheng** [comment]
热补丁的基本原理是在il层面上对原有代码加了一点逻辑实现的。
而Hotfix标签相当于白名单，列出哪些类型要做上述预处理。
当然，要默认对用户所有类型都预处理也是可以的，看需求，如果需求强烈，可以设置一个宏，不用打标签，对所有类型都处理。
ps：上面所说的“一点逻辑”，类似这样
int Add(int a, int b)
{
   if (hotfix_Add != null) return hotfix_Add(this, a, b);
   ...原有逻辑...
}

**Comment by xclouder** [comment]
谢谢回复，全部都打上也有点浪费，还要考量打包速度、il2cpp编译后包大小问题。

**Comment by chexiongsheng** [comment]
对的！

**Comment by wzhfantastic** [comment]
原理是il层面的话， unity5.3之前的安卓平台是不支持il的吧？

**Comment by chexiongsheng** [comment]
@wzhfantastic ，il一直都都支持。
android下，backend是mono的话，直接运行il，backend是il2cpp的话，是生成il后转cpp。
我开发环境就是5.2.3f1.

**Comment by wzhfantastic** [comment]
@chexiongsheng 
谢谢，原来是这样！

**Comment by daaoling** [comment]
当然，要默认对用户所有类型都预处理也是可以的，看需求，如果需求强烈，可以设置一个宏，不用打标签，对所有类型都处理。 

这一块我不是很明白？这个宏指的是HOTFIX_ENABLE？
