### ISSUE TITLE
lua怎样继承c#类

### ISSUE THREAD

**Issue by pl01898759** [Tencent/xLua#405]
类似cocos quick，可以 local A = class("A", function () return display.newNode() end)
这样A类，有Node的功能。

稍微看了下cocos quick的class，有这样的代码：

local setmetatableindex_
setmetatableindex_ = function(t, index)
    if type(t) == "userdata" then
        local peer = tolua.getpeer(t)
        if not peer then
            peer = {}
            tolua.setpeer(t, peer)
        end
        setmetatableindex_(peer, index)
    else
        local mt = getmetatable(t)
        if not mt then mt = {} end
        if not mt.__index then
            mt.__index = index
            setmetatable(t, mt)
        elseif mt.__index ~= index then
            setmetatableindex_(mt, index)
        end
    end
end
setmetatableindex = setmetatableindex_

本来是想照搬过来用一下，但是发现tolua.getpeer 跟 tolua.setpeer 不知道对应xlua哪个？

或者说有其他方式实现吗？

**Comment by chexiongsheng** [comment]
cs_obj["Add"] 就是访问cs对象的Add成员。括号里头换成变量也可以

**Comment by chexiongsheng** [comment]
我知道你的需求啊。
我只是说思路，不是说我给的就是你要的代码。

**Comment by chexiongsheng** [comment]
lua table那的元表__index那判断父类有没，没有就访问base

**Comment by pl01898759** [comment]
因为我创建的东西是要传到c#那边的，所以lua这边创建出来的是个userdata的东西，而不是个lua table。
然后lua的功能，是希望能挂在这个userdata上面。。比如给这个userdata添加个方法等等。。但是现在给这个userdata加字段就会报错。

function testA()
end

function createLuaObj()
    local csB = CS.ClassB() --就是这个地方，这个userdata，我想给他加一些方法，加不上。
    csB.testA = testA --这里会报错了，没法设置这个testA
    return csB
end

**Comment by chexiongsheng** [comment]
不用添加到userdata上啊。lua本身是不允许往userdata上加东西。
tolua的也是搞一个table，让你新增的自动放到那table上。你访问一个对象，他会先到那个table那查，有的话返回那个table的字段。没有就返回那个userdata的自动。造成可以往一个userdata那加字段的假象。

**Comment by pl01898759** [comment]
嗯，大致明白了，不过这个关联到userdata上，有没有什么好的建议？怎么做关联呢？

**Comment by chexiongsheng** [comment]
这有个类似的东西：https://github.com/Tencent/xLua/blob/master/Assets/XLua/Resources/xlua/util.lua.txt#L137
例子看这里：
https://github.com/Tencent/xLua/blob/master/Assets/XLua/Examples/08_Hotfix/HotfixTest2.cs#L285

**Comment by pl01898759** [comment]
好的，谢谢！我研究研究。
