### ISSUE TITLE
一处参数没有判空

### ISSUE THREAD

**Issue by JoyPanda** [Tencent/xLua#406]
![tim 20180628203130](https://user-images.githubusercontent.com/30594737/42034334-4aa0bb00-7b12-11e8-8f25-53b52eaf4787.png)

LuaInterfaceBridge.tpl.txt模板 少一个判空

**Comment by chexiongsheng** [comment]
有遇到空的情况么？啥时候会为空呢？

**Comment by JoyPanda** [comment]
public void Test(params string[] Arguments)
类似这样 调用的时候Test(null)  有些不需要参数

**Comment by JoyPanda** [comment]
![tim 20180628214504](https://user-images.githubusercontent.com/30594737/42038048-86b84cf2-7b1c-11e8-8531-709a542e226c.png)
生成的代码  上面判断空了 下面call的时候没有判断

**Comment by chexiongsheng** [comment]
ok，修复了

**Comment by JoyPanda** [comment]
赞 辛苦
