### ISSUE TITLE
二维数组params生成代码错误？

### ISSUE THREAD

**Issue by xerohuang** [Tencent/xLua#407]
生成代码后看到有个编译错误，
`
if (p3 != null)  { for (int __gen_i = 0; __gen_i < p3.Length; ++__gen_i) translator.Push(L, p3[__gen_i]); };
`
函数头是
`
public void __Gen_Delegate_Imp178(object p0, object p1, int p2, short[,][] p3)
`

猜测是对应的这个方法，应该是[]的位置错了
`
public void GenIdToColor(string file, int fromLevel, params short[][,] maps)
`

**Comment by chexiongsheng** [comment]
解决了，更新下代码
