### ISSUE TITLE
c#以委托方式调用lua函数时会有108B的GC开销，可以避免吗？

### ISSUE THREAD

**Issue by yangguosdxl** [Tencent/xLua#408]
如题

**Comment by chexiongsheng** [comment]
看这个例子：https://github.com/Tencent/xLua/tree/master/Assets/XLua/Examples/05_NoGc，委托调lua函数没gc

可能你每次获取到委托就释放了，下次用再获取，这样会有gc。
或者委托参数里头有个复杂值类型，但没配置到GCOptimize
或者你没执行生成代码

**Comment by yangguosdxl** [comment]
谢谢，好像是没有生成代码的原因
