### ISSUE TITLE
命名空间问题

### ISSUE THREAD

**Issue by jiezuowhu** [Tencent/xLua#41]
有些类使用的是Global空间啊，然后就导致了一些问题。比如Coroutine，会跟UnityEngine.Coroutine产生冲突！

**Comment by chexiongsheng** [comment]
是指在lua访问？
lua访问C#的UnityEngine.Coroutine是CS.UnityEngine.Coroutine，访问Coroutine是CS.Coroutine

**Comment by jiezuowhu** [comment]
C#的问题。在XLua的Example中有一个06_Coroutine，里面的一个全局空间类Coroutine和UnityEngine.Coroutine重复，导致在using UnityEngine;的C#文件中使用Coroutine类会报错。

**Comment by chexiongsheng** [comment]
哦，那个例子class名字起的不好。
