### ISSUE TITLE
如何实现 local position = transform.position 得到的是一个table

### ISSUE THREAD

**Issue by ming871** [Tencent/xLua#411]
即：用自己写的Vector3 Table替换transform.position得到C# Vector3对象

**Comment by ming871** [comment]
如果在Unity的Update和FixedUpdate中调用transform.position，性能还是有所损失

**Comment by chexiongsheng** [comment]
https://github.com/Tencent/xLua/blob/master/Assets/XLua/Examples/12_ReImplementInLua/ReImplementInLua.cs

**Comment by ming871** [comment]
那 xlua.genaccessor 和 xlua.setmetatable 有没有使用方法的文档？

**Comment by chexiongsheng** [comment]
木有，高级用法需呀你至少能够通过源码看出用法。这都做不到我觉得很危险。

**Comment by ming871** [comment]
好的
