### ISSUE TITLE
iphone模拟器运行报错！

### ISSUE THREAD

**Issue by cloudstlife** [Tencent/xLua#414]
在xcode9的模拟器下运行，会报错：dyld: lazy symbol binding failed: Symbol not found: _xlua_get_lib_version。真机是正常的。这个怎么问题怎么破呢？

**Comment by chexiongsheng** [comment]
自行编译模拟器版本的库。
之前有issues，翻翻看，那有我的建议，当然，只是建议而已，我自己也没试过。

**Comment by cloudstlife** [comment]
@chexiongsheng 我试了不行。make_ios_lua53.sh会自己编译iOS.cmake，编译出来了两个文件xlua.bundle只有2KB，u3d工程编译会一堆报错（保留原来的）。libxlua.a大约2MB。拷贝到对应目录，生成xcode。在模拟上，依然出现dyld: lazy symbol binding failed: Symbol not found: _xlua_get_lib_version。这个问题。

**Comment by chexiongsheng** [comment]
不知道你咋试的，我这里编译出一个2.6m的libxlua.a

**Comment by chexiongsheng** [comment]
保存为make_ios_simulator.sh试试，我编译没问题，不过没在模拟器上试过。我们没在模拟器上跑的需求。
~~~bash
mkdir -p build_ios_simulator && cd build_ios_simulator
cmake -DIOS_PLATFORM=SIMULATOR -DCMAKE_TOOLCHAIN_FILE=../cmake/iOS.cmake  -GXcode ../
cd ..
cmake --build build_ios_simulator --config Release
mkdir -p plugin_lua53/Plugins/iOS/
cp build_ios_simulator/Release-iphoneos/libxlua.a plugin_lua53/Plugins/iOS/libxlua.a
~~~

**Comment by cloudstlife** [comment]
@chexiongsheng mac打出libxlua.a是2.7m，覆盖过去，在模拟器下，一样报yld: lazy symbol binding failed: Symbol not found: _xlua_get_lib_version。 @chexiongsheng 没有出错么？

**Comment by chexiongsheng** [comment]
上个回答已经说了：我编译没问题，不过没在模拟器上试过。我们没在模拟器上跑的需求。

**Comment by chexiongsheng** [comment]
我网上搜索了下，据说unity本身不支持在模拟器上用plugins

**Comment by chexiongsheng** [comment]
https://answers.unity.com/questions/768959/why-are-unity-plugins-disabled-on-the-ios-simulato.html
