### ISSUE TITLE
MacOS：在Editor中使用HotFix宏后，GenerateCode报错

### ISSUE THREAD

**Issue by DavidShenIdf** [Tencent/xLua#418]
<img width="1102" alt="597d322be4210e4661a3155e7d8b0760" src="https://user-images.githubusercontent.com/5292598/42920074-905b938c-8b47-11e8-93d1-a1ea9305c90e.png">
貌似是和库冲突了

**Comment by chexiongsheng** [comment]
你更新下代码看能解决问题不？

**Comment by DavidShenIdf** [comment]
好的 我试试

**Comment by DavidShenIdf** [comment]
好了 谢谢
