### ISSUE TITLE
Unity2018 arm64

### ISSUE THREAD

**Issue by AmaranthYan** [Tencent/xLua#419]
请问XLua的安卓库支持Unity2018新加入的Android ARM64编译选项吗？

**Comment by AmaranthYan** [comment]
我尝试用xLua源码编译了一个ARM64的库（-DANDROID_ABI=arm64-v8a）
但是在机器上运行测试代码的时候
CS.UnityEngine.Mathf.PingPong(CS.UnityEngine.Time.time, 1.0)
这行报错了 attempt to call a nil value(field 'PingPong')
代码中的其他UnityEngine函数都能正常调用
请问为什么会出现这个问题

**Comment by chexiongsheng** [comment]
CS.UnityEngine.Mathf.PingPong(CS.UnityEngine.Time.time, 1.0)
这个在armv7下面运行是正常的么？

**Comment by AmaranthYan** [comment]
是的 同样的Hotfix代码在armv7上测试没有任何问题

**Comment by chexiongsheng** [comment]
UnityEngine.Mathf有加到LuaCallCSharp并生成代码么？

**Comment by AmaranthYan** [comment]
没有加到过LuaCallCSharp，其他的代码中用到的UnityEngine类比如Vector3，Time，Quaternion，Random等也没有加到LuaCallCSharp

**Comment by chexiongsheng** [comment]
那你试试加下，可能是arm64和armv7的代码剪裁策略不同。

**Comment by AmaranthYan** [comment]
确实是代码剪裁导致的，加上LuaCallCSharp就可以正常运行了
