### ISSUE TITLE
在Lua中构造C#类对象，能否提供自定义构造函数名？

### ISSUE THREAD

**Issue by forsakenyang** [Tencent/xLua#42]
目前使用的是：
local myGameObject = CS.UnityEngine.GameObject()

可否提供接口增加如下方式创建：
local myGameObject = CS.UnityEngine.GameObject.New()

**Comment by chexiongsheng** [comment]
尽量不用占用某名字，万一类本身定义可个静态的New方法，那那个方法就用不了了。
你提这个主要想达成什么效果呢？

**Comment by forsakenyang** [comment]
主要是想把之前用ulua/tolua实现的游戏业务逻辑模块迁移到xlua。由于某些历史遗留问题，我们在生成通讯协议/数据结构时会同时生成C#和lua的代码，导致在lua中使用数据的时候，有可能使用的是C#对象，也有可能使用的是luatable。

如果使用不同的构造方式，一方面是编码风格上不太一致（团队约定所有module使用New作为构造函数，和ulua/tolua保持一致），另一方面在lua中构造某个协议类型类型时还要考虑这个类型是从C#导出的还是在lua中就有的，比较麻烦。

类本身定义New方法这个问题倒是有可能的，所以希望能提供一个配置项，支持额外的自定义构造函数名，比如new。：)

**Comment by chexiongsheng** [comment]
其实加倒简单，几行代码的事情，只是不希望为很小众添加代码，这种东西估计会很多，这会导致越来越庞大。
单独给一个支持New做构造函数的patch给你们，你们自己维护，怎样？

**Comment by forsakenyang** [comment]
那也是极好的：)

**Comment by chexiongsheng** [comment]
LuaEnv.cs:382

        private string init_xlua = @" 
            local metatable = {}
            local rawget = rawget
            local setmetatable = setmetatable
            local import_type = xlua.import_type
            local load_assembly = xlua.load_assembly

            function metatable:__index(key) 
                local fqn = rawget(self,'.fqn')
                fqn = ((fqn and fqn .. '.') or '') .. key

                local obj = import_type(fqn)
                local is_class = true

                if obj == nil then
                    -- It might be an assembly, so we load it too.
                    obj = { ['.fqn'] = fqn }
                    setmetatable(obj, metatable)
                    is_class = false
                elseif obj == true then
                    obj = rawget(self, key)
                end

                if is_class then
                    rawset(obj, 'New', function(...)
                        return obj(...)
                    end)
                end

                -- Cache this lookup
                rawset(self, key, obj)
                return obj
            end

**Comment by forsakenyang** [comment]
测试通过了，非常感谢！
