### ISSUE TITLE
UnityEngineLineRendererWrap compile error.

### ISSUE THREAD

**Issue by comedyy** [Tencent/xLua#421]
UnityEngine.LineRenderer gen code:
  UnityEngine.Vector3[] positions;
                    
                        int __cl_gen_ret = __cl_gen_to_be_invoked.GetPositions( positions );
                        LuaAPI.xlua_pushinteger(L, __cl_gen_ret);

positions used before assign.

**Comment by chexiongsheng** [comment]
unity version?

**Comment by comedyy** [comment]
2018.1.0f2(64bit)

**Comment by chexiongsheng** [comment]
update xlua, at least,  to v2.1.12
