### ISSUE TITLE
wrap大量类型导致LuaEnv构造时崩溃

### ISSUE THREAD

**Issue by xmzyl** [Tencent/xLua#422]
我是通过ExampleGenConfig.cs中AllDelegate函数配置delegate到  CSharpCallLua，在三星 Galaxy Tab S2 平板上运行时崩溃，android 7.0
![image](https://user-images.githubusercontent.com/1343477/43069297-5178a28a-8e9f-11e8-9119-01b13393caaf.png)

**Comment by xmzyl** [comment]
我发现导出太多类型到 LuaCallCSharp也会导致崩溃，如下图：我导出所有的游戏逻辑代码
![image](https://user-images.githubusercontent.com/1343477/43082145-e72a1b08-8ec5-11e8-8402-63ff4422b19c.png)

**Comment by chexiongsheng** [comment]
可能和unity的mono在android下的一个bug有关，如果函数体很大就有可能崩溃。
能看到具体崩在那个c#函数么？

**Comment by chexiongsheng** [comment]
已经在这个commit上修复：https://github.com/Tencent/xLua/commit/5ef91a5c5ce5149bc7c5f89fe24992cc130601c3
