### ISSUE TITLE
Unity API 拓展时，如果去除LuaCallCSharp标签，反射执行不了这个拓展方法

### ISSUE THREAD

**Issue by zxgblade** [Tencent/xLua#423]
1、对Component拓展了一个SetActive方法， 不添加 [XLua.LuaCallCSharp]
![image](https://user-images.githubusercontent.com/11960359/43136160-62053a88-8f7a-11e8-8e8a-379a03b20a36.png)
不执行 XLua/Generate Code,  在lua端对Component的派生类执行 SetActive的方法：
![image](https://user-images.githubusercontent.com/11960359/43136431-4680dc94-8f7b-11e8-8b56-017996e903aa.png)
查看log, 执行注册的__index方法，StaticLuaCalback.cs中的MetaFuncIndex(RealStatePtr L):
![image](https://user-images.githubusercontent.com/11960359/43136308-e3debb6a-8f7a-11e8-8020-d996923779a6.png)
对应的unity的log:
![image](https://user-images.githubusercontent.com/11960359/43136421-3d8faf52-8f7b-11e8-9eb7-9da3e0c584ea.png)

遍历各个基类，最终检索到System.Object 也没有查找到该拓展方法 SetActive

2、如果对这个扩展方法打一个 [XLua.LuaCallCSharp]的标签，则检索到Component的时候，发现其可执行拓展方法，log:
![image](https://user-images.githubusercontent.com/11960359/43136533-9ad0be4a-8f7b-11e8-9bdf-5d132b987856.png)

![image](https://user-images.githubusercontent.com/11960359/43136500-8adc7f6a-8f7b-11e8-87cb-3308bdbcc14c.png)

所以问题是，给拓展的方法如果不加[XLua.LuaCallCSharp]， 执行反射的时候检索不到这个拓展方法，请问是需要怎么设置还是反射执行需要怎么处理？
这个标签在反射执行时有什么作用，可以让其标记的方法可被执行？

注： 两个测试均未执行生成代码，如果要执行生成代码，则需要将Component也加上标签（已测，可行）。在编辑器中测试。

**Comment by chexiongsheng** [comment]
反射就两个都加上ReflectionUse

**Comment by zxgblade** [comment]
ReflectionUse/LuaCallCSharp的标签添加后，反射机制能查找到基类的拓展方法，这是测试可行的。
比较疑惑的是，游戏启动的时候加载的assembly是编译后的结果，应该已经包含了基类的拓展方法以及拓展类了，为什么不加标签反射查找不到？
还是说不加标签，编译后的assembly里面没有这个拓展类和拓展方法？我查看Util.cs代码中发现：
![image](https://user-images.githubusercontent.com/11960359/43175051-c9eda8ae-8fef-11e8-8dfc-f5045e30e65a.png)
在获取拓展方法的时候，是需要满足ReflectionUse/LuaCallCSharp标签，才会被添加到type_def_extension_method这个列表中的，这就表示XLua本身在对拓展方法执行反射的时候，是要求拓展方法需要有对应的两个标签的，是这样设计的么？不知道我的理解是否正确

**Comment by chexiongsheng** [comment]
原理自己看代码。
