### ISSUE TITLE
怎么快速添加[Hotfix]这个标签呢？  项目中有好多代码，要全部手动添加吗？这样太累的吧

### ISSUE THREAD

**Issue by CircleGood** [Tencent/xLua#426]

**Comment by chexiongsheng** [comment]
看配置文档啊，文档开篇就说不建议类上直接打标签。
首页就说了，配置文档必看。
或者看下网上的攻略：http://gad.qq.com/article/detail/42303

**Comment by CircleGood** [comment]
还是不知道怎么弄的，大神 能给在说的详细一点吗？ 我们这个是旧项目，以前没有接 lua。  谢谢

**Comment by chexiongsheng** [comment]
看了这个还不知道怎么弄么？https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/configure.md

根据你的情况去写动态配置。

**Comment by CircleGood** [comment]
还是看不懂，能给写一个小demo吗？  这个方法好像不错，不知道怎么用的

**Comment by CircleGood** [comment]
谢谢，已经弄好了。看懂什么意思了。
