### ISSUE TITLE
Unity2018 Build 报错

### ISSUE THREAD

**Issue by dongweiPeng** [Tencent/xLua#427]
Assets/XLua/Gen/UnityEngineLightWrap.cs(1042,35): error CS1061: Type `UnityEngine.Light' does not contain a definition for `shadowAngle' and no extension method `shadowAngle' of type `UnityEngine.Light' could be found. Are you missing an assembly reference?

Assets/XLua/Gen/UnityEngineLightWrap.cs(1027,35): error CS1061: Type `UnityEngine.Light' does not contain a definition for `shadowRadius' and no extension method `shadowRadius' of type `UnityEngine.Light' could be found. Are you missing an assembly reference?

看了下生成的Wrap文件是有shadowAngle 和 shadowRadius 的。求大神帮忙看下 
版本：2018.1.0f2
环境：Android平台打包

**Comment by chexiongsheng** [comment]
配置黑名单

**Comment by dongweiPeng** [comment]
ok  感谢

**Comment by flowerdog** [comment]
> 配置黑名单

遇到类似问题， 请问一下是什么原理呢？ Play的时候没有报错，在Build的时候报错。

**Comment by chexiongsheng** [comment]
> > 配置黑名单
> 
> 遇到类似问题， 请问一下是什么原理呢？ Play的时候没有报错，在Build的时候报错。

生成代码在Editor，所以会UNITY_EDITOR宏框住的函数也生成了。
