### ISSUE TITLE
How to stop coroutine?

### ISSUE THREAD

**Issue by dungmv** [Tencent/xLua#429]
How to stop a coroutine?
I can start a coroutine with below code
https://github.com/Tencent/xLua/blob/master/Assets/XLua/Examples/06_Coroutine/Resources/coruntine_test.lua.txt
But I can't see anything to stop the coroutine.

**Comment by chexiongsheng** [comment]
i change the example to a more easy to understand implement, i can be stop now.

**Comment by dungmv** [comment]
Thank. It's very useful
