### ISSUE TITLE
集中了几个问题在一个issue

### ISSUE THREAD

**Issue by daaoling** [Tencent/xLua#43]
1.我看了下介绍
 * 开发期无需生成代码
 * Generate Code 和反射间可无缝切换
这里的意思是指平时不生成的时候 lua 是用反射来调用c#的类吗？或者说这个生成代码到底干了什么？

2. https://github.com/Tencent/xLua/issues/4 

热补丁的基本原理是在il层面上对原有代码加了一点逻辑实现的。
而Hotfix标签相当于白名单，列出哪些类型要做上述预处理。
当然，要默认对用户所有类型都预处理也是可以的，看需求，如果需求强烈，可以设置一个宏，不用打标签，对所有类型都处理。

我还是有点不解，这里设置一个宏的意思是什么？

3.我实际运行了一下hotfix的那个例子，添加了HOTFIX_ENABLE宏 ，cp 了Mono.Cecil.dll，但是还是需要我 inject 标识那个类，并且要生成代码才能inject finish? 
这样一来是不是就是说如果想要热补丁，就必须对那个c#类进行inject处理 然后发布的时候生成代码？
这样一来如果发布的时候那个c#类出问题了该怎么办呢？

不好意思，麻烦解答下

**Comment by daaoling** [comment]
还有
```shell
OSX命令行 cp /Applications/Unity/Unity.app/Contents/Managed/Mono.Cecil.* Project/Assets/XLua/Src/Editor/
Win命令行 copy UnityPath\Editor\Data\Managed\Mono.Cecil.* Project\Assets\XLua\Src\Editor\
```
实际路径应该是这个
/Applications/Unity/Unity.app/Contents/Frameworks/Managed

**Comment by chexiongsheng** [comment]
1、生成代码的好处是性能更好，反射的好处是对安装包影响更小，两者直接切换业务代码不用变，你可以随时根据需要调整下配置选择（比如某天你发现你的代码超过苹果的80M限制，你可以把一些性能要求不高的改为反射）；
2、意思是我可以新增一个宏，要是打开之后就不看你有没打Hotfix，不分青红皂白全帮你注入；
3、打包时设置了HOTFIX_ENABLE并且执行了Generate cdoe，所有标识了Hotfix的类型都可以热补丁。不明白你说的“这样一来如果发布的时候那个c#类出问题了该怎么办呢？”
4、cp命令上面也有说明“可能Unity版本不同会略有不同”，改为你这个也会有人说路径不对。

**Comment by daaoling** [comment]
嗯 第3点的意思就是万一没有打上hotfix标识的话 就只能在发布前干脆无脑全部标识了吗？
🙏车大的耐心解释

**Comment by chexiongsheng** [comment]
无脑全部标识会有开销，主要是安装包的影响，如果在能接受的情况下问题不大。
或者只把热更可能性大的部分打了，出问题的地方有hotfix就修复，没有就只好发版本了。按28原则，可能为20%的代码打了hotfix就可以解决80%的热更问题，呵呵。

**Comment by zjwps** [comment]
希望可以设置一个宏，不用打hotfix标签，对所有类型都处理，只要没bug，我觉得挺需要这个东西，如果有这个宏，就可以把一个老项目，马上加上热更的功能。

**Comment by chexiongsheng** [comment]
@zjwps 提供宏很简单，但后续影响很难评估，我怕给用户做了错误的引导，一个公共库做加法简单，但加了之后就很难减了。

**Comment by chexiongsheng** [comment]
@zjwps 毕竟，手动都加加貌似也不是很费力的事情。目前Hotfix标签就有stateless和stateful的选择，这也是希望你要去考虑的。

**Comment by zjwps** [comment]
@chexiongsheng 感谢回答，实用角度来讲，就算没有这个宏，个人肯定会写个工具来把一个文件夹的类全部加上标签。手动给每一个类或者大部分类加上hotfix标签还是挺不科学。
