### ISSUE TITLE
雄哥求教关于 LuaException: c# exception:System.NullReferenceException: at XLua.CSObjectWrap.UnityEngineComponentWrap._g_get_transform (IntPtr L) [0x00000] in的报错

### ISSUE THREAD

**Issue by tufeng060** [Tencent/xLua#431]
雄哥好，我在开发中遇到了这样一个报错，源lua代码如下（部分省略）：
function CRenderObject:GetTransform()
    if not self.m_RO then
        return
    end
    return self.m_RO.transform
end

在最后一行eturn self.m_RO.transform 报出了
LuaException: c# exception:System.NullReferenceException: at XLua.CSObjectWrap.UnityEngineComponentWrap._g_get_transform (IntPtr L) [0x00000] in <filename unknown>:0 stack traceback: [C]: at 0x94d83660 [C]: at 0x94d82624 [C]: at 0x94d82624 [C]: at 0x94d82624 [C]: at 0x94d82624 [C]: in function '__index' objects/uno/CRenderObject:80: in function 'GetTransform' 
这段错误
我查了下代码，应该是这个_g_get_gameObject函数里抛出异常了，我怀疑是translator.FastGetCSObj(L, 1)返回为null，请问一般什么情况下会出现这种情况呢？那个self.m_RO明明是不为nil的

**Comment by chexiongsheng** [comment]
某个地方调用了UnityEngine.Object.Destroy销毁了这个对象

**Comment by tufeng060** [comment]
原来是这样  那如果我在lua里想做个判断，比方说真正的C#对象已经通过UnityEngine.Object.Destroy销毁了，但是lua那边的的代理table还在， 想这类情况 除了抛异常外 还有其他正规的渠道判断得知吗？

**Comment by chexiongsheng** [comment]
怎么判断是否Destroy，faq有。

**Comment by donnki** [comment]
@chexiongsheng 我也遇到了这个报错，但是，如果是像你说的“某个地方调用了UnityEngine.Object.Destroy销毁了这个对象”，报错应该是c# exception:UnityEngine.MissingReferenceException: The object of type 'XXXX' has been destroyed but you are still trying to access it.
我测试过多种情况的删除，都是报的MissingReferenceException的错，而不是这个 c# exception:System.NullReferenceException: at XLua.CSObjectWrap.UnityEngineComponentWrap._g_get_transform的错，请问你知道原因不？
