### ISSUE TITLE
请问Xlua怎么调用DotTween的方法

### ISSUE THREAD

**Issue by yv4** [Tencent/xLua#434]
DotTween是个第三方的插件 可以给物体做移动扩展缩小之类的效果

我的lua代码如下

xlua.hotfix(CS.Login,'LoginClick',function(self)
	self.loginBut.transformDOScale(0,1)
end)

这里DoScal(0,1)就是DotTween中的静态方法，我代码运行起来就报nil，说这个方法为nil，写原生代码的话就没问题。请问怎么办。要怎么调用第三方的方法。

**Comment by jerry-zeng** [comment]
要先将DoTween导出吧，参考tolua。

**Comment by chexiongsheng** [comment]
Google一下，有很多相互文章

**Comment by tufeng060** [comment]
给你个参考：
可以创建一个静态类（xlua在generate的时候会自动找到这个类生成代码）
//配置的详细介绍请看Doc下《XLua的配置.doc》
public static class XLuaGenConfig
    {
        [CSharpCallLua]
        public static List<Type> CSharpCallLua = new List<Type>() {
            typeof(DG.Tweening.TweenCallback),
        };

        //lua中要使用到C#库的配置，比如C#标准库，或者Unity API，第三方库等。
        [LuaCallCSharp]
        public static List<Type> LuaCallCSharp = new List<Type>() {
            typeof(DG.Tweening.Ease),
            typeof(DG.Tweening.LoopType),
            typeof(DG.Tweening.Tweener),
            typeof(DG.Tweening.TweenExtensions),
            typeof(DG.Tweening.Sequence),
            typeof(DG.Tweening.TweenSettingsExtensions)
        };

配置好后就可以在lua里直接调用了

但是推荐的方法是基础的dotween动作都在C#写好接口 比方说
public static int Unity_DoTweenScale(object obj, Vector3 pos, float duration, LuaFunction onComplate = null)
然后lua去调用这个接口进行dotween动作

另外注意onComplate 这个lua回调函数一般情况下往往是匿名函数，所以调用然后 一定要dispose，不然匿名函数是带闭包的，可能调用频繁就会导致闭包大涨 内存不足。
