### ISSUE TITLE
Examples 报错

### ISSUE THREAD

**Issue by jerry-zeng** [Tencent/xLua#435]
用的Unity2018和xlua_v2.1.12

1. 08_Hotfix报错:
LuaException: xlua.access, no field __Hotfix0_Add
stack traceback:
	[C]: in field 'access'
	[string "Init"]:88: in field 'hotfix'
	[string "chunk"]:2: in main chunk
XLua.LuaEnv.ThrowExceptionFromError (Int32 oldTop) (at Assets/Libs/XLua/Src/LuaEnv.cs:430)
XLua.LuaEnv.DoString (System.Byte[] chunk, System.String chunkName, XLua.LuaTable env) (at Assets/Libs/XLua/Src/LuaEnv.cs:263)
XLua.LuaEnv.DoString (System.String chunk, System.String chunkName, XLua.LuaTable env) (at Assets/Libs/XLua/Src/LuaEnv.cs:277)
HotfixTest2.Start () (at Assets/Libs/XLua/Examples/08_Hotfix/HotfixTest2.cs:212)

2. 10_SignatureLoader报错：
LuaException: error loading module signatured1 from resource, signatured1.lua:1: unexpected symbol near '<\16>'
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	[string "chunk"]:2: in main chunk
XLua.LuaEnv.ThrowExceptionFromError (Int32 oldTop) (at Assets/Libs/XLua/Src/LuaEnv.cs:430)
XLua.LuaEnv.DoString (System.Byte[] chunk, System.String chunkName, XLua.LuaTable env) (at Assets/Libs/XLua/Src/LuaEnv.cs:263)
XLua.LuaEnv.DoString (System.String chunk, System.String chunkName, XLua.LuaTable env) (at Assets/Libs/XLua/Src/LuaEnv.cs:277)
SignatureLoaderTest.Start () (at Assets/Libs/XLua/Examples/10_SignatureLoader/SignatureLoaderTest.cs:40)

已经执行了Xlua/Generate Code和Xlua/Hotfix Inject In Editor，还是报错，其它都好的。

**Comment by chexiongsheng** [comment]
第一个错误是例子过时了，更新一下。第二个错误是路径，例子的路径是写死的，得按那写死的放

**Comment by jerry-zeng** [comment]
@chexiongsheng 好的，谢谢。另外，建议Xlua的根目录单独配置，其它地方都用相对路径，这样只改一个地方，Generate Code的时候也不用改了。
