### ISSUE TITLE
一个关闭C#委托没释放干净导致的异常

### ISSUE THREAD

**Issue by tufeng060** [Tencent/xLua#436]
大雄哥早上好，这个异常在FAQ已经有解决方案了，主要是[CSharpCallLua]的委托在lua虚拟机dispose之前因为没释放干净导致抛出InvalidOperationException: try to dispose a LuaEnv with C# callback!
这边我有个疑惑， 就是每次在游戏退出的时候就抛出这个异常，然后似乎unity的内存没释放干净，所以在unity不关掉的前提下，不断的重新关闭和打开游戏，内存会持续攀高，指导虚拟机抛出memory not enough的异常，然后就得重新关掉整个unity才能解决问题了，这种情况是不是因为在关掉游戏的时候抛出这个异常导致lua虚拟机一直挂着呢，然后重启后又新开了一个lua虚拟机，老的依旧还在，然后越积越多？

**Comment by chexiongsheng** [comment]
抛了异常lua虚拟机就释放不了了。相当于内存泄漏。
泄漏到一定程度，你又是用luajit的话，会比较容易出现memory not enough

**Comment by tufeng060** [comment]
好的 明白了 我们用的的确就是luajit， 谢谢大雄哥
