### ISSUE TITLE
Generator.cs中317行报错

### ISSUE THREAD

**Issue by JourneyHans** [Tencent/xLua#438]
在例子当中是没问题的，当时我放到自己的项目里后会报这个错，请问是怎么回事？

extension_methods.Contains(method)

类型“MethodInfo”不能用作泛型类型或方法“DotNetExtend.Contains<T>(T[], T)”中的类型参数"T"。没有从“System.Reflection.MethodInfo”到"System.IEquatable<System.Relfection.MethodInfo>"的隐式引用转换。

**Comment by chexiongsheng** [comment]
你代码有个全局的，对MethodInfo的扩展。

**Comment by JourneyHans** [comment]
原来如此，谢谢。找到问题了。。。
