### ISSUE TITLE
struce/class 映射只支持int类型吗？

### ISSUE THREAD

**Issue by daaoling** [Tencent/xLua#44]
public struct Param1
{
    public int x;
    public string y;
}

[CSharpCallLua]
public interface Param2
{
    int x{ get; set; }
    int y { get; set; }
}

[XLua.LuaCallCSharp]
public class MyClass 
{
    public void Test() { Debug.Log("TEST"); }

    public void ComplexFunc1(Param1 p1)
    {
        Debug.Log("P1 = {x=" + p1.x + ",y=" + p1.y + "}");
    }

    public void ComplexFunc(Param1 p1, Param2 p2)
    {
        Debug.Log("P1 = {x=" + p1.x + ",y=" + p1.y + "}");
        Debug.Log("P1 = {x=" + p2.x + ",y=" + p2.y + "}");
        p2.x = 3;
    }
}

发现p1.y 是不行的？ 这个特性可以考虑加上吗？

**Comment by chexiongsheng** [comment]
你怎么调用的？

**Comment by chexiongsheng** [comment]
没有只支持int不支持string的设定

**Comment by daaoling** [comment]
嗯 是我没有太仔细看源码，
table1 = {x = 1, y = 2}
obj: ComplexFunc1(table1)
我这边的y是number

**Comment by daaoling** [comment]
🙏解释
