### ISSUE TITLE
 扩展方法是不是只能支持基类，不支持接口？this IMessage message

### ISSUE THREAD

**Issue by leiq2005** [Tencent/xLua#441]
应用场景如下:
`public interface IMessage<T> : IMessage`
`public sealed partial class Parent : IMessage<Parent>`
`public static class MessageExtensions`
`{`
           `public static byte[] ToByteArray(this IMessage message)`
`}`

C# 正常调用
Parent parent = new Parent();
parent.ToByteArray();

Lua 调用报错
parent = CS.xxx.Parent()
parent:ToByteArray()  报错

 扩展方法是不是只能支持基类，不支持接口？this IMessage message
谢谢

**Comment by chexiongsheng** [comment]
这种现在不支持
