### ISSUE TITLE
调用LuaAPI.lua_pushstring(L, o as byte[]) 经常报错Lua no enough memory

### ISSUE THREAD

**Issue by better666** [Tencent/xLua#442]
我们这边通过C#将byte数据传给Lua解析。但是经常崩溃报错。Lua no enough memory，跟踪日志，怀疑是不是byte数据过大。
0x00007FFA532CA388 (KERNELBASE) RaiseException
0x00007FFA332A558E (xlua) lua_yield
0x00007FFA332A530C (xlua) lua_yield
0x00007FFA332ABD98 (xlua) lua_loadx
0x00007FFA332AC229 (xlua) lua_loadx
0x00007FFA332A3BD9 (xlua) lua_pushlstring
0x0000000018B6257B (Mono JIT Code) (wrapper managed-to-native) XLua.LuaDLL.Lua:xlua_pushlstring (intptr,byte[],int)
0x000000004223CAC4 (Mono JIT Code) [E:\WorkSpace\Unity\animal2018\Assets\ThirdPlugins\XLua\Src\LuaDLL.cs:336] XLua.LuaDLL.Lua:lua_pushstring (intptr,byte[]) 
0x0000000018BB84BD (Mono JIT Code) [E:\WorkSpace\Unity\animal2018\Assets\ThirdPlugins\XLua\Src\ObjectTranslator.cs:953] XLua.ObjectTranslator:PushAny (intptr,object) 
0x000000004223C82F (Mono JIT Code) XLuaGenDelegateImpl0:Invoke21 (byte[],LPCFramework.HttpReqData)
0x000000004223C625 (Mono JIT Code) [E:\WorkSpace\Unity\animal2018\Assets\Scripts\Managers\CSCallLua.cs:95] LPCFramework.CSCallLua:OnUnpackHttpMsg (byte[]&,LPCFramework.HttpReqData) 
0x000000004223C4EC (Mono JIT Code) [E:\WorkSpace\Unity\animal2018\Assets\Scripts\Managers\LuaVMManager.cs:156] LPCFramework.LuaVMManager:OnUnpackHttpMsg (byte[]&,LPCFramework.HttpReqData) 
0x000000004223C3AD (Mono JIT Code) [E:\WorkSpace\Unity\animal2018\Assets\Scripts\Managers\LuaManager.cs:171] LPCFramework.LuaManager:OnUnpackHttpMsg (byte[]&,LPCFramework.HttpReqData) 
0x0000000042233BD2 (Mono JIT Code) [E:\WorkSpace\Unity\animal2018\Assets\Scripts\Managers\NetworkManager.cs:450] LPCFramework.NetworkManager/<HttpRequest>c__Iterator0:MoveNext ()

**Comment by chexiongsheng** [comment]
用的是luajit版本还是lua53版本的xlua呢？

**Comment by better666** [comment]
xlua， xlua版本v2.1.10 2017年9月18日

**Comment by chexiongsheng** [comment]
每个版本都会有个luajit版本和lua53版本。

**Comment by better666** [comment]
目前用的是xlua默认的，看日志用的是lua53

**Comment by chexiongsheng** [comment]
lua版本报这错误表示申请不到内存了。
你留意下你们的进程内存占用情况。
还有看看你们是否有这种情况：https://github.com/Tencent/xLua/issues/436
