### ISSUE TITLE
麻烦问一下xlua是否可以支持或有计划支持Unity的Script compilation and assembly definition files

### ISSUE THREAD

**Issue by hansquirrel** [Tencent/xLua#443]
unity2017的新特性：https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html

麻烦问一下单独定义的程序集如何支持hotfix？
是否支持或者是否有计划支持？

**Comment by chexiongsheng** [comment]
master上的版本新做了支持，不过现在用得人不多。
首先xlua的库要放到Assembly-CSharp程序集。
Hotfix列表配置要放到Editor目录。
应该就可以了。不过注入到其它程序集，注入代码会多一些。

**Comment by hansquirrel** [comment]
感觉需要一篇详细的教程
xlua放到Assembly-CSharp的话其他程序集如何using Xlua的命名空间？……
还是使用单独的配置写法？

**Comment by chexiongsheng** [comment]
单独的配置啊，放Editor目录，上个回答就说了。

**Comment by hansquirrel** [comment]
抱歉，“Hotfix列表配置要放到Editor目录。”这个还是不是太明白……
比如我原来直接在class上增加标签[Hotfix]，分离程序集的话[Hotfix]是无法用的（因为无法using Xlua）
那么我在Editor下要如何去配置呢？

**Comment by chexiongsheng** [comment]
看文档。
直接往类上打标签是很久之前就不建议的方式。

**Comment by hansquirrel** [comment]
收到，非常感谢！
