### ISSUE TITLE
调用CS.System.Collections.Generic.Dictionary(CS.System.String, CS.UnityEngine.Vector3)报错

### ISSUE THREAD

**Issue by tanhaojin** [Tencent/xLua#445]
LuaException: c# exception:Attempting to call method 'System.Collections.Generic.Dictionary`2[[System.String, mscorlib, Version=2.0.5.0, Culture=, PublicKeyToken=7cec85d7bea7798e],[UnityEngine.Vector3, UnityEngine, Version=0.0.0.0, Culture=, PublicKeyToken=null]]::.ctor' for which no ahead of time (AOT) code was generated.,stack:  at System.Reflection.MonoCMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
  at XLua.OverloadMethodWrap.Call (IntPtr L) [0x00000] in <filename unknown>:0 
  at XLua.MethodWrap.Call (IntPtr L) [0x00000] in <filename unknown>:0 
  at XLua.StaticLuaCallbacks.FixCSFunction (IntPtr L) [0x00000] in <filename unknown>:0 
  at XLua.DelegateBridge.PCall (IntPtr L, Int32 nArgs, Int32 nResults, Int32 errFunc) [0x00000] in <filename unknown>:0 
  at XLua.DelegateBridge.__Gen_Delegate_Imp78 (Boolean p0, System.String p1) [0x00000] in <filename unknown>:0 
  at XLuaMgr.Init () [0x00000] in <filename unknown>:0 
  at UIDownloading.InitializeUIAndTable () [0x00000] in <filename unknown>:0 
  at CSResUpdateMgr.PreDownload () [0x00000] in <filename unknown>:0 
  at CSResUpdateMgr.Update () [0x00000] in <filename unknown>:0 
stack traceback:
[C]: in local 'Dictionary_String_Vector3'
/var/mobile/Containers/Data/Application/DE8F6C7D-9EE2-417C-8812-E3372C408CB6/Documents/luaRes/main_out.lua:94: in function 'TestNewDicList'
/var/mobile/Containers/Data/Application/DE8F6C7D-9EE2-417C-8812-E3372C408CB6/Documents/luaRes/main_out.lua:38: in function 'InitRequire'
  at XLua.LuaEnv.ThrowExceptionFromError (Int32 oldTop) [0x00000] in <filename unknown>:0 
  at XLua.DelegateBridge.__Gen_Delegate_Imp78 (Boolean p0, System.String p1) [0x00000] in <filename unknown>:0 
  at XLuaMgr.Init () [0x00000] in <filename unknown>:0 
  at UIDownloading.InitializeUIAndTable () [0x00000] in <filename unknown>:0 
  at CSResUpdateMgr.PreDownload () [0x00000] in <filename unknown>:0 
  at CSResUpdateMgr.Update () [0x00000] in <filename unknown>:0 
 
(Filename: currently not available on il2cpp Line: -1) 

在ios下使用xlua-v2.1.12版本的CS.System.Collections.Generic.Dictionary(CS.System.String, CS.UnityEngine.Vector3)时报错了，看起来是ios不支持反射？
有没有更好的解决在ios下创建dictionary实例的方法？

**Comment by tanhaojin** [comment]
使用的是lua53版本的xlua

**Comment by chexiongsheng** [comment]
Dictionary<string, Vector3>要加到LuaCallCSharp列表里头。
