### ISSUE TITLE
无法找到XLua性能分析工具.md中提到的函数

### ISSUE THREAD

**Issue by LeoQIao** [Tencent/xLua#446]
如题

**Comment by chexiongsheng** [comment]
看doc版本吧：https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/XLua%E5%A2%9E%E5%8A%A0%E5%88%A0%E9%99%A4%E7%AC%AC%E4%B8%89%E6%96%B9lua%E5%BA%93.doc

**Comment by LeoQIao** [comment]
哈！谢谢找到啦
