### ISSUE TITLE
关于try to dispose a LuaEnv with C# callback!，如何追踪所有未释放的C# delegate

### ISSUE THREAD

**Issue by tufeng060** [Tencent/xLua#448]
大雄哥晚上好,
因为项目已经比较后期了，现在集中解决try to dispose a LuaEnv with C# callback!的问题，我遍历了 Dictionary<int, WeakReference> delegate_bridges这个字典，他的value是一个DelegateBridgeBase类型，他保存了所有指向同一个lua函数的delegate代理，但是打印出来后，自定义的delegate比较好找，但是存在大量的Action  Func  UnityAction等，这些很难找到具体在那个lua文件里被赋值，如下：
2018-09-04 11:30:24 try to dispose a LuaEnv with C# callback!
#####################Some delegates are still not set to null, see below list for detail!============
total delegate count:86
Void System.Action`1<System.Boolean>(Boolean obj)
Void System.Action>()
Void System.Action`1<System.Boolean>(Boolean obj)
Void System.Action>()
Void System.Action`1<System.String>(String obj)
Void System.Action>()
Void System.Action>()
Void System.Action>()
Void System.Action`1<System.String>(String obj)
Void System.Action`2<System.Boolean,System.String,>(Boolean arg1,String arg2,)
Void System.Action`1<System.String>(String obj)
Void System.Action`1<System.String>(String obj)
Void System.Action`1<System.String>(String obj)
Void System.Action`2<System.Boolean,System.String,>(Boolean arg1,String arg2,)
Void System.Action`1<System.String>(String obj)
Void System.Action`2<System.String,System.String,>(String arg1,String arg2,)

不知道有什么方法能通过delegate_bridges的key值（也就是luaref）去找到这些delegate所指向的那个lua函数的具体位置呢？

**Comment by chexiongsheng** [comment]
通过引用能拿到那函数，然后可以通过在lua那调用debug.getinfo获取源码信息。

**Comment by tufeng060** [comment]
好的 谢谢哦 我写段测试一下

**Comment by chexiongsheng** [comment]
我写了个函数找这类C#引用的lua函数，
https://github.com/Tencent/xLua/commit/6f2b5d885593483d44c05019e2abfa749316e289

**Comment by tufeng060** [comment]
666 十分感谢大雄哥
