### ISSUE TITLE
添加lua之间搜索路径

### ISSUE THREAD

**Issue by wulei** [Tencent/xLua#45]
请问一下，如何添加lua之间调用的搜索路径？

**Comment by chexiongsheng** [comment]
1、lua的原生lua文件加载机制还是可以用的，可以通过package.path去设置；
2、可以用CustomLoader，这个可以由你来控制，在网络，内存里头加载都可以；
3、xLua默认提供了从Resources加载的Loader，这个require的路径都是从Resources往下找，不会根据require调用所在文件的路径去找相对目录。

**Comment by wulei** [comment]
👍

**Comment by chexiongsheng** [comment]
> 2.可以用CustomLoader，这个可以由你来控制，在网络，内存里头加载都可以； 设置了这个之后 lua原生的 package.path 是否就不生效了。

生效，不过不建议用package.path。
