### ISSUE TITLE
hotfix模式下lua调用泛型方法的问题

### ISSUE THREAD

**Issue by fabio41230** [Tencent/xLua#450]
请问xlua.generic_method生成的lua方法在editor上能用，在ios真机上报参数错误是怎么回事

**Comment by chexiongsheng** [comment]
确认是参数错误么？
有可能会抛jit异常，如果这个泛型参数是值类型，而且在C#那没调用过的话，会抛jit异常。

**Comment by fabio41230** [comment]
我刚找到了问题，是因为这个泛型方法内有可变参数列表，导入到lua后原先的params object[] args 变成了object[]

**Comment by fabio41230** [comment]
导致lua调用这个泛型不能像之前传入可变参数那样的写法，而是把这些参数塞到一个array里，再传给c#

**Comment by fabio41230** [comment]
导致lua调用这个泛型不能像之前传入可变参数那样的写法，而是把这些参数塞到一个array里，再传给c#
