### ISSUE TITLE
Jenkins打包的时候，能否通过使用命令的方式，来使用XLua？

### ISSUE THREAD

**Issue by Chen-kaiyuan** [Tencent/xLua#451]
Hi，请教一下，在Jenkins打包的时候，能否通过使用命令的方式，来使用XLua？
我现在在Jenkins打包的时候，总是遇见这个error
![image](https://user-images.githubusercontent.com/17740259/45399352-4d109d80-b67a-11e8-9fc2-746a90a8fd75.png)
但是，wo我手动去执行一次，“Clear Generated Code”and"Generated Code"以后，就没有这个问题了。
![image](https://user-images.githubusercontent.com/17740259/45399450-a1b41880-b67a-11e8-98fb-5030044f2eee.png)
请问一下，有没有什么办法，能够代替手动执行？

**Comment by chexiongsheng** [comment]
看示例：https://github.com/Tencent/xLua/tree/master/Assets/XLua/Examples/13_BuildFromCLI

**Comment by Chen-kaiyuan** [comment]
> 看示例：[https](https://github.com/Tencent/xLua/tree/master/Assets/XLua/Examples/13_BuildFromCLI)：[//github.com/Tencent/xLua/tree/master/Assets/XLua/Examples/13_BuildFromCLI](https://github.com/Tencent/xLua/tree/master/Assets/XLua/Examples/13_BuildFromCLI)

Hi, @chexiongsheng  我就是这样写的
以下是我现在使用的命令
/Applications/Unity/Unity.app/Contents/MacOS/Unity -buildTarget iOS -quit -batchmode -executeMethod CommandBuild.BuildIOS -projectPath /Users/tanukimai/.jenkins/workspace/Unity-dev-new/Limizhiboke/ -logFile /Users/tanukimai/cky/build.log

**Comment by chexiongsheng** [comment]
看示例里头怎么调用菜单啊
