### ISSUE TITLE
调用 perf.snapshot() 导致untiy3d 直接崩溃，发生概率高。

### ISSUE THREAD

**Issue by Zetorchen** [Tencent/xLua#452]

**Comment by Zetorchen** [comment]
unity2018.2.1f1
但估计和版本无关，应该是c层的代码导致的

**Comment by chexiongsheng** [comment]
之前有issues反馈过，不过没有可以重现的小工程给我定位不了。建议先别用这个东东。

**Comment by chexiongsheng** [comment]
写了个新的内存泄漏工具，更简单（所以有问题也更好定位），更好用
https://zhuanlan.zhihu.com/p/45000232
