### ISSUE TITLE
浮点数跨平台编译的疑问

### ISSUE THREAD

**Issue by cuixin** [Tencent/xLua#453]
由于我们服务器和客户端有很多代码是公用的，并且用到了很多浮点数运算，我们用的lua版本是5.3.5，lua底层实现是double，但不能保证所有平台出现结果都是一致的。

现在大多数cpu（包括手机）都是支持IEEE754的标准的，我们服务端用的lua也是跟xlua的lua一致，现在有个担心是比如安卓或者苹果平台的编译 ，如果编译出来的指令跟服务器不一样，结果就不一致了？

另外，编译安卓用的r11ndk，clang-3.6已经不能用了。
```
-cmake -DANDROID_ABI=armeabi-v7a -DCMAKE_TOOLCHAIN_FILE=../cmake/android.toolchain.cmake -DANDROID_TOOLCHAIN_NAME=arm-linux-androideabi-clang3.6 -DANDROID_NATIVE_API_LEVEL=android-9 ../
```
替换成：
```
+cmake -DANDROID_ABI=armeabi-v7a -DCMAKE_TOOLCHAIN_FILE=../cmake/android.toolchain.cmake -DANDROID_TOOLCHAIN_NAME=arm-linux-androideabi-4.9  -DANDROID_NATIVE_API_LEVEL=android-9 ../
```

目前的疑问就是，怎么能保证最终各自平台（ios,linux,android)下的指令是一致的？才能保证最终 的浮点数结果也是一致的，请大神帮忙解答下，谢谢。

**Comment by chexiongsheng** [comment]
arm的指令肯定和x86指令不一样。问题不在指令，在于执行浮点运算的规则。
浮点表示倒是基本上都是IEEE754，不过浮点运算，从内存到fpu寄存器的位扩展，寄存器到内存的舍入规则不见得一样，一些特殊值比如nan的处理也不一定一样。
所以，结论是服务器和手机运算可能有细微差别，如果这种差别存在的话，多次累计还是有影响的。
如果拿不准，只能当不一样的处理，所以，建议：
1、建议用定点数（比如规划一定的位数作为小数），lua53是支持整数（64位）的；
2、如果非得用浮点，运算尽量放一个地方；
3、如果非得双方计算，建议时不时双方对一下，避免累计误差把。

**Comment by cuixin** [comment]
@chexiongsheng 非常感谢！
目前用到的地方不算太多，还没发现问题。定点数是个解决办法。
还有从编译参数上，能不能规避这个问题？

**Comment by chexiongsheng** [comment]
除非指定用软件模拟浮点运算，这在不存在浮点硬件的机器上是这么实现的，当然，我不知道怎么指定，而且这应该会比较慢。
如果用硬件运算，就依赖硬件的实现了。通常浮点运算器的寄存器都会扩展更多位，比如64 double，浮点寄存器可能是80位的，就有个位扩展和舍入规则了，我不清楚是不是所有硬件都一样。
