### ISSUE TITLE
hotfix的移动平台的injection的入口在哪？

### ISSUE THREAD

**Issue by CodeMasterYi** [Tencent/xLua#458]
如题，我很想手动调用~不知道自动化构建的时候为什么没有执行injection，看过Q&A说不能用代码修改宏，于是我注释掉修改宏的代码，但是，仍然发现运行时报什么injection错误——但是我用Unity手动打包则发现injection又是ok的（另外，Q&A说的意思时不能修改宏而已吗？还是说有什么其他的也不能用代码修改呢？好苛刻的injection）

**Comment by chexiongsheng** [comment]
项目设置里头“手动”定义宏就可以了啊。
faq是有些人，在自动化打包的时候通过调用editor api去“自动”设置那宏，这不行。
好苛刻？90%以上的人都不会有问题。搞不定只能自我检讨下为啥是10%。连设置个宏都搞不定。

**Comment by CodeMasterYi** [comment]
---：哎~~~这蠢孩子~
