### ISSUE TITLE
hotfixInject：非Assembly-CSharp的其他dll代码注入

### ISSUE THREAD

**Issue by ChampionGuan** [Tencent/xLua#459]
项目里有一些核心代码会打成一个独立的dll。
看到文档里有说明： //如果涉及到Assembly-CSharp.dll之外的其它dll，如下代码需要放到Editor目录
按照文档说明，提示注入成功。Assembly-CSharp下的补丁运行正常，但其他dll下的补丁运行时抛出异常 no field __Hotfix0_Update，所以咨询下是否支持对非Assembly-CSharp的其他dll打标签？

**Comment by chexiongsheng** [comment]
支持
