### ISSUE TITLE
使用C#访问Lua的全局函数导致Unity崩溃

### ISSUE THREAD

**Issue by YimiCGH** [Tencent/xLua#461]
如题，在学习xlua过程中使用delegate获取lua中的一个全局函数
`function Test(id)`
 ` print('test'..id)`
`end`
在C#这边编写了对应的委托
` [CSharpCallLua]`
    `public delegate void Test(int id);`
`...`
`Test m_test = luaEnv.Global.Get<Test>("Test");`
       ` m_test(1);`
       ` m_test(2);`
       ` m_test(3);`
然后一运行Unity就崩溃
然后寻思是什么地方导致，分别测试了其他的情况，同样是这个函数，把它的参数变两个以上或没有参数，或者使用LuaFunction来映射，都没有问题，有点迷，前来请教大家，看看是什么问题。

**Comment by YimiCGH** [comment]
继续试了一下，发现把委托中的参数类型改为 object类型或者string类型就不会有问题，一改成int型就闪退

**Comment by chexiongsheng** [comment]
任何类型都支持，更不用说int这么常见的类型
麻烦反馈unity 版本，xLua 版本等信息，最好附上可以重现的工程，节后再看下

**Comment by YimiCGH** [comment]
自己又折腾了一下，先清除一下生成代码，然后重新生成一遍就可以正常使用了~尬，会是这个原因导致的吗？
-_-|||
