### ISSUE TITLE
请问自定义的Loader如何去找文件夹下的lua文件？

### ISSUE THREAD

**Issue by JourneyHans** [Tencent/xLua#464]

**Comment by JourneyHans** [comment]
我把Lua代码放在外部，目录结构为：
LuaLogic
      |— framework
                  |— util.lua
      |— main.lua

然后在main.lua中调用 require ("framework/util")
在我自定义的Loader中，并不知道util在framework下，就会报找不到文件的错，请问如何解决？

**Comment by chexiongsheng** [comment]
loader得到的参数是"framework/util"

**Comment by JourneyHans** [comment]
> loader得到的参数是"framework/util"

我这里打印参数是文件名，请问是哪里写错了吗？

**Comment by JourneyHans** [comment]
解决了。。。改错文件了。。。
