### ISSUE TITLE
Xcode 10  libc++ 问题

### ISSUE THREAD

**Issue by iMemento** [Tencent/xLua#465]
请问 libxlua.a 的依赖是libstdc++ ？ 有无版本支持 libc++? 更新Xcode 10 之后编译不了了

**Comment by chexiongsheng** [comment]
没依赖libstdc++

**Comment by leechking1987** [comment]
Xcode10是因为苹果把这个库去除掉了，一个临时的解决方法是从Xcode9里面把这个库拷过来

**Comment by chexiongsheng** [comment]
@leechking1987 xlua native部分纯C的，没用C++
