### ISSUE TITLE
是否支持lua字节码编译

### ISSUE THREAD

**Issue by mansamtsui** [Tencent/xLua#466]
请问下，是否支持lua字节码编译？生成bytes文件。

**Comment by chexiongsheng** [comment]
faq有：https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/faq.md

**Comment by mansamtsui** [comment]
是有提供byte编译工具吗？例如使用luajit是有的，lua53你有提供吗

**Comment by chexiongsheng** [comment]
faq看了么？上面不是有么？
