### ISSUE TITLE
BlackList参数匹配问题

### ISSUE THREAD

**Issue by forsakenyang** [Tencent/xLua#47]
System.IO.Direcotory有两个CreateDirectory的重载：
1、CreateDirectory(System.String,System.Security.AccessControl.DirectorySecurity)
2、CreateDirectory(System.String)

前者在导出的时候会提示找不到类型，所以在BlackList中添加如下配置来屏蔽这个方法：

public static List<List<string>> BlackList = new List<List<string>>{
   new List<string> {"System.IO.Directory", "CreateDirectory", "System.String", "System.Security.AccessControl.DirectorySecurity"},
}

发现生成出来的Wrap文件把两个CreateDirectory都屏蔽了，但期望是能够保留后者的。
看了下Generator.cs:350，发现是在判断isMethodInBlackList时如果方法的参数数量少于配置，都会进入黑名单。

最后临时修改成这样了：
if (parameters.Length != exclude.Count - 2)
    continue;

**Comment by chexiongsheng** [comment]
这里逻辑确实有问题，谢谢！

**Comment by chexiongsheng** [comment]
已修改
