### ISSUE TITLE
多久Tick()一次比较好

### ISSUE THREAD

**Issue by vic910** [Tencent/xLua#470]

**Comment by chexiongsheng** [comment]
秒级别就够了

**Comment by vic910** [comment]
tick后 立即UnityEngine.Resources.UnloadUnusedAssets();
            GC.Collect(); 发现有些资源还是被引用  过几秒再UnityEngine.Resources.UnloadUnusedAssets();
            GC.Collect();资源引用就没了 是什么原因呢

**Comment by chexiongsheng** [comment]
看unity和C#的源码。
只回答xlua的问题：tick秒级调用即可。
