### ISSUE TITLE
泛型方法注册 以及调用的问题

### ISSUE THREAD

**Issue by benbenhefeifei** [Tencent/xLua#472]
你好，车老师！首先很感谢您的无私奉献，我最近也在学习您的XLua,感觉非常棒！同时也有一点儿有关泛型的疑惑，自己查了您的相关例子大多偏重原生的方法。我上一段代码 希望在Xlua上 调用注册消息和调用
1：注册消息 CS代码如下：
public static void AddEventListener<T, U>(int eventType, Action<T, U> handler)
{
EventDispatcher.OnListenerAdding(eventType, handler);
EventDispatcher.m_theRouter[eventType] = (Action<T, U>) Delegate.Combine((Action<T, U>) EventDispatcher.m_theRouter[eventType], handler);
}
2：调用处是
EventDispatcher.TriggerEvent<int,int>(EventDefine.ROOM_USER_RedBagMoneyUpdate, RedBagScore, RedBagScoreTotal);
我也研究好久不知如何去实现，如果老师有空 还望指导一下 学生十分感谢！！！

**Comment by chexiongsheng** [comment]
看下这里：https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/faq.md#%E6%94%AF%E6%8C%81%E6%B3%9B%E5%9E%8B%E6%96%B9%E6%B3%95%E7%9A%84%E8%B0%83%E7%94%A8%E4%B9%88
