### ISSUE TITLE
HotFix注入提示成功，pc上测试正常，但是ios打手机包测试提示no access

### ISSUE THREAD

**Issue by icfnight** [Tencent/xLua#473]
Unity版本5.6.5
打包前解析dll：
public class PlayerDataManager
{
    ...
    private static DelegateBridge _Hotfix0_TestA;
    ...
}
然后ios包的log如下：
Xlua.LuaExceptio: xlua.access, no field __Hotfix0_TestA
请问xcode打手机包的时候有什么需要特殊配置的地方吗？

**Comment by chexiongsheng** [comment]
看文档：https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/hotfix.md

**Comment by icfnight** [comment]
> 看文档：https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/hotfix.md

谢谢查看。我是按照文档操作的。已经打印了“hotfix inject finish!”或者“had injected!”，而且pc上跑是正常hotfix，但是打包到手机后，就提示Xlua.LuaExceptio: xlua.access, no field __Hotfix0_TestA。 文档里说“触发重新编译”是什么意思？打包导出有可能会覆盖么？

**Comment by chexiongsheng** [comment]
你在pc打印这个代表pc可以而已。
你要打包的过程中有打印这个才代表打包注入成功了。

**Comment by icfnight** [comment]
> 你在pc打印这个代表pc可以而已。
> 你要打包的过程中有打印这个才代表打包注入成功了。
打包的过程中有打印"inject finish"
我是执行clear code-> generate code -> hotfix inject，这时候log提示了"finish"，查看dll也是有了hotfix字段， 然后unity build出来xcode工程，装到手机上却提示"no access"

**Comment by icfnight** [comment]
> 你在pc打印这个代表pc可以而已。
> 你要打包的过程中有打印这个才代表打包注入成功了。

打包的过程中有打印"inject finish"
我是执行clear code-> generate code -> hotfix inject，这时候log提示了"finish"，查看dll也是有了hotfix字段， 然后unity build出来xcode工程，装到手机上却提示"no access"

**Comment by chexiongsheng** [comment]
手机打包不用手动执行菜单，你手动执行那个打印成功跟你手机打包没半点关系。
"no access"就一个原因，那个类没注入。
仔细看文档，每一个字，你前面有一亿人誓言旦旦说自己按文档操作了，实际上自查还是发现某步错了，目前为止100%的人认真按指南都必定成功，所以我不想多说了，自查吧。
