### ISSUE TITLE
2018.3.0b7上编译错误

### ISSUE THREAD

**Issue by sophiepeithos** [Tencent/xLua#475]
当player setting里的api compatibility level为.net standard 2.0时
![snipaste_2018-10-27_18-15-41](https://user-images.githubusercontent.com/1758796/47602687-d571b480-da14-11e8-86a4-cab5efa94851.png)

**Comment by chexiongsheng** [comment]
你为什么要选这个呢？

**Comment by sophiepeithos** [comment]
这个选项是两个选项其中之一，xLua也没有文档说不可以选

**Comment by chexiongsheng** [comment]
那你选另外一个。
