### ISSUE TITLE
Fatal signal 11 (SIGSEGV)

### ISSUE THREAD

**Issue by FirmianaMarsili** [Tencent/xLua#476]
在运行过程中闪退，在连上Logcat后得到以下日志
backtrace:
     #00 pc 0001161c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_errormsg+152)
     #01 pc 0001116c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_runerror+228)
     #02 pc 0001107c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_typeerror+136)
     #03 pc 00013e88  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (tryfuncTM+96)
     #04 pc 00013c0c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_precall+1184)
     #05 pc 00013f90  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_call+76)
     #06 pc 00014068  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_callnoyield+56)
     #07 pc 00011668  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_errormsg+228)
     #08 pc 0001116c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_runerror+228)
     #09 pc 0001107c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_typeerror+136)
     #10 pc 00013e88  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (tryfuncTM+96)
     #11 pc 00013c0c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_precall+1184)
     #12 pc 00013f90  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_call+76)
     #13 pc 00014068  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_callnoyield+56)
     #14 pc 00011668  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_errormsg+228)
     #15 pc 0001116c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_runerror+228)
     #16 pc 0001107c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_typeerror+136)
     #17 pc 00013e88  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (tryfuncTM+96)
     #18 pc 00013c0c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_precall+1184)
     #19 pc 00013f90  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_call+76)
     #20 pc 00014068  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_callnoyield+56)
     #21 pc 00011668  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_errormsg+228)
     #22 pc 0001116c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_runerror+228)
     #23 pc 0001107c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_typeerror+136)
     #24 pc 00013e88  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (tryfuncTM+96)
     #25 pc 00013c0c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_precall+1184)
     #26 pc 00013f90  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_call+76)
     #27 pc 00014068  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_callnoyield+56)
     #28 pc 00011668  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_errormsg+228)
     #29 pc 0001116c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_runerror+228)
     #30 pc 0001107c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_typeerror+136)
     #31 pc 00013e88  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (tryfuncTM+96)
     #32 pc 00013c0c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_precall+1184)
     #33 pc 00013f90  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_call+76)
     #34 pc 00014068  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_callnoyield+56)
     #35 pc 00011668  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_errormsg+228)
     #36 pc 0001116c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_runerror+228)
     #37 pc 0001107c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_typeerror+136)
     #38 pc 00013e88  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (tryfuncTM+96)
     #39 pc 00013c0c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_precall+1184)
     #40 pc 00013f90  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_call+76)
     #41 pc 00014068  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_callnoyield+56)
     #42 pc 00011668  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_errormsg+228)
     #43 pc 0001116c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_runerror+228)
     #44 pc 0001107c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_typeerror+136)
     #45 pc 00013e88  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (tryfuncTM+96)
     #46 pc 00013c0c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_precall+1184)
     #47 pc 00013f90  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_call+76)
     #48 pc 00014068  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_callnoyield+56)
     #49 pc 00011668  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_errormsg+228)
     #50 pc 0001116c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_runerror+228)
     #51 pc 0001107c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_typeerror+136)
     #52 pc 00013e88  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (tryfuncTM+96)
     #53 pc 00013c0c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_precall+1184)
     #54 pc 00013f90  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_call+76)
     #55 pc 00014068  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_callnoyield+56)
     #56 pc 00011668  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_errormsg+228)
     #57 pc 0001116c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_runerror+228)
     #58 pc 0001107c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_typeerror+136)
     #59 pc 00013e88  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (tryfuncTM+96)
     #60 pc 00013c0c  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_precall+1184)
     #61 pc 00013f90  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_call+76)
     #62 pc 00014068  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaD_callnoyield+56)
     #63 pc 00011668  /data/app/com.aiqiyi.tt-2/lib/arm/libxlua.so (luaG_errormsg+228)

应该是内存引用可能出现错误，接着我用arm-linux-androideabi-addr2line还原这个错误栈，其反馈的也是类似上面的后缀 (luaG_errormsg+228)这样的，像这种情况是属于类型转换还是空指针等等之类的吗，
因为出现在so层所以不太清楚应该怎么排查

**Comment by chexiongsheng** [comment]
看栈应该是死循环递归调用导致的栈溢出。

**Comment by chexiongsheng** [comment]
感觉像是你用xpcall去调用一个函数，这个函数异常了，然后错误处理函数再次调用了触发了原来的错误逻辑

**Comment by FirmianaMarsili** [comment]
感谢

**Comment by chexiongsheng** [comment]
定位到具体原因了么？

**Comment by FirmianaMarsili** [comment]
我有写一个while 是随时间改变slider,加长每次循环了的间隔,改善了很多,不过偶尔还是会闪退,但是就没有抛出栈信息只有提醒Fatal signal 11 (SIGSEGV),正在慢慢排查

**Comment by FirmianaMarsili** [comment]
至于多重xpcall,看了下在c#侧是有使用try catch,但是在走到lua侧后也使用了xpcall
