### ISSUE TITLE
有计划支持vs2017编译吗？

### ISSUE THREAD

**Issue by sophiepeithos** [Tencent/xLua#477]
如题

**Comment by chexiongsheng** [comment]
你改下那个bat就可以了。把“"Visual Studio 14 2015"”改为"Visual Studio 15 2017"
lua53版本最新已经有人改成发现vs2015没有就找vs2017，你更新就可以用。

**Comment by sophiepeithos** [comment]
我就是用的更新后的，无论vs2017的命令行和build目录用powershell

[make_win64_luajit.bat.txt](https://github.com/Tencent/xLua/files/2524167/make_win64_luajit.bat.txt)
我上传的是可以的

看起来好像IF %ERRORLEVEL% NEQ 0在我的电脑上即使没装vs2015这句不会被执行到

**Comment by chexiongsheng** [comment]
我说的是lua53版本。
luajit你还要设置vc工具的路径
打开bat，看VS140COMNTOOLS相关那块。
