### ISSUE TITLE
如何修改生成的Wrap文件内容？？

### ISSUE THREAD

**Issue by qiuchangjie** [Tencent/xLua#478]
调整unity2018.2.2的Scripting Runtime Version为.Net 4.x Equivalent，生成的SystemCollectionsGenericDictionary2SystemStringUnityEngineGameObjectWrap.cs文件发现有类型转换错误，我想调整一下生成Wrap文件的内容，请问在哪里调整？ 附上我的报错信息
![image](https://user-images.githubusercontent.com/5474239/47690463-18a47100-dc29-11e8-9928-bee9123031be.png)

**Comment by qiuchangjie** [comment]
请问要如何解决呢？

**Comment by chexiongsheng** [comment]
暂时来说，你可以用黑名单排除。
或者别用Net 4.x。

**Comment by qiuchangjie** [comment]
好的，我试试，谢谢

**Comment by chexiongsheng** [comment]
刚刚研究了下，unity2018设置.Net 4.x时，运行和编译用的库不一样
运行用的是：unity安装目录\Editor\Data\MonoBleedingEdge\lib\mono\unityjit\mscorlib.dll
编译链接的是：unity安装目录\Editor\Data\MonoBleedingEdge\lib\mono\4.7.1-api\mscorlib.dll
这两个dll的api是不一样的，应该算是unity的bug。

**Comment by qiuchangjie** [comment]
好的，谢谢

**Comment by chexiongsheng** [comment]
xLua平时开发是不用生成代码的，所以不用管。
发包前生成代码也好办，先切换到.NET 3.5生成，再切回来就可以了。

**Comment by qiuchangjie** [comment]
好的
