### ISSUE TITLE
关于Nintendo Switch

### ISSUE THREAD

**Issue by TiancJester** [Tencent/xLua#479]
xLua是否能支持Nintendo Switch的编译？

另外，我在Luajit项目中，看到一个相关的 [issues](https://github.com/LuaJIT/LuaJIT/issues/347)

**Comment by chexiongsheng** [comment]
xlua的原生部分有两部分：lua虚拟机和xlua的一些lua扩展。

xlua的扩展是纯c的，如果你用lua53版本也，lua虚拟机也是纯c的，纯c的平台兼容性性都比较好，目前cmake编译，你可以查下cmake对Nintendo Switch的支持，如果cmake不直接支持，而且Nintendo Switch也有特殊的构建要求，可以按Nintendo Switch的要求把CMakeLists.txt涉及的c源文件编译即可，一般而言不会有啥问题；

如果你用luajit版本，luajit会比较特殊，它vm用汇编些，而且jit时也会生成目标机器码，所以它的跨平台是要一个个平台来搞的，如果它不支持，或者本身在该平台有bug，都比较难处理。

**Comment by chexiongsheng** [comment]
有个童鞋弄了，并提交过来：
https://github.com/Tencent/xLua/pull/507
