### ISSUE TITLE
希望LuaCallCSharpAttribute增加自动包含内部类型的功能

### ISSUE THREAD

**Issue by Jayatubi** [Tencent/xLua#48]
希望[LuaCallCSharp]能够提供选项支持自动包含内部类型。例如：

````
[LuaCallCSharp(GenFlag.IncludeInnnerClass)]
public class MyClass
{
    public class MyInnerClass {}
}
````
将同时将`MyClass`和`MyClass+MyInnerClass`一同暴露给lua，而不需要对每一个内部类再打上[LuaCallCSharp]的标记。

**Comment by chexiongsheng** [comment]
个人觉得最好还是不做吧，这类快捷方式可以提出很多，要都做就太臃肿了。

**Comment by Jayatubi** [comment]
这个想法主要是因为一些第三方库，或者unity本身，会自动依赖一些内部类，比如UnityEngine.Random会依赖UnityEngine.Random+State。这种内部类一般不易被察觉，只有开启了NOT_GEN_WARNIN才能从warning中知道。

当然我们也可以自己根据反射去扫描出来这些类。

**Comment by chexiongsheng** [comment]
那这种还真不需要，是一种浪费。生成代码只有c#和lua交互才需要，lua没直接调用到的是不需要的。你举的例子是那是C#间交互。
另外，即使lua直接要调用，也不见得要加LuaCallCSharp，xlua支持反射，而且和生成代码无缝配合。所以如果那个类调用不频繁，可以用ReflectionUse，这个也是ios下有保障的。

**Comment by Jayatubi** [comment]
如果不加LuaCallCSharp的话，实时反射会有额外的GC Alloc的开销么？

**Comment by chexiongsheng** [comment]
你刚刚举的例子不会。那个state你lua没直接用是不用生成的。
直接调用没生成代码走反射的话，值类型参数肯定会有gc alloc。
引用类型可能没有，可能有

**Comment by Jayatubi** [comment]
好的，我会往这方面考虑的。
