### ISSUE TITLE
XLUA With .Net Standard 2.0

### ISSUE THREAD

**Issue by farzinp7** [Tencent/xLua#480]
We upgraded Unity to 2018 and .NET standard 2.0.

After the .NET change, there is the following error in the class (CodeEmit).

Assets/XLua/Src/CodeEmit.cs(30,18): error CS0246: The type or namespace name `ModuleBuilder' could not be found. Are you missing an assembly reference?

![image](https://user-images.githubusercontent.com/13505199/47953871-4b879580-df98-11e8-894b-e7b421eebd59.png)

How to fix this problem? Need for .NET Standard 2.0

**Comment by chexiongsheng** [comment]
it seem that there is no emit module in .net standard 2.0, you have to add this yourself : 
https://stackoverflow.com/questions/42075766/where-are-the-methodbuilder-modulebuilder-and-assemblybuilder-in-dotnet-core

ps: why you have to use .net standard 2.0?

**Comment by farzinp7** [comment]
We needed NET 2.0 to communicate with the signalR Core , which made us unsuccessful.
We are currently using websockets And no longer need to .NET standard 2.0
Thanks
