### ISSUE TITLE
多线程使用 crash 问题

### ISSUE THREAD

**Issue by sillyousu** [Tencent/xLua#486]
在 Linux   dotnet core 平台下，会crash。
```
using System;
using System.Threading;
using System.Threading.Tasks;
using XLua;

namespace BugReproduce
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("begin");
            long cnt = 1000;
            long finishCnt = 0;
            for(long i=0; i< cnt; i++)
            {
                Task.Run(async () =>
                {
                    var env = new XLua.LuaEnv();
                    await Task.Delay(200);
                    System.Threading.Interlocked.Increment(ref finishCnt);
                });
            }

            while (Interlocked.Read(ref finishCnt) < cnt)
            {
                Task.Delay(10).Wait();
                GC.GetTotalMemory(true);
            }
        }
    }
}
```

**Comment by sillyousu** [comment]
目前的锁使用有问题：
实例成员luaEnvLock 保护了里面的静态的 LuaIndexes.LUA_REGISTRYINDEX 。多线程环境下 LuaIndexes.LUA_REGISTRYINDEX 读写就有 race condition 了。

https://github.com/Tencent/xLua/pull/347#issuecomment-437562683

**Comment by Jayatubi** [comment]
LuaIndexes确实会有问题，这里需要一个单独的锁。

**Comment by sillyousu** [comment]
> LuaIndexes确实会有问题，这里需要一个单独的锁。

这里有什么特殊理由使用 static 吗？能不能放到 LuaEnv 里面？

**Comment by sillyousu** [comment]
可能整个 `XLua.InternalGlobals` 里面的东西都的考虑一下线程安全的问题。

**Comment by sillyousu** [comment]
InternalGlobals 里面有几处需要修改的

- [ ] strBuff
- [ ] objectTranslatorPool
- [ ] LUA_REGISTRYINDEX

`genTryArraySetPtr ` 和 `genTryArrayGetPtr` 看起来是 readonly 的不需要修改？

**Comment by sillyousu** [comment]
strBuff 我想改为线程本地变量
```csharp
#if THREAD_SAFE
        private static System.Threading.ThreadLocal<byte[]> _strBuff;
        internal static byte[] strBuff
        {
            get
            {
                if (!_strBuff.IsValueCreated)
                {
                    _strBuff.Value = new byte[256];
                }
                return _strBuff.Value;
            }
            set
            {
                _strBuff.Value = value;
            }
        }
#else
        internal static byte[] strBuff = new byte[256];
#endif
```

**Comment by sillyousu** [comment]
`LUA_REGISTRYINDEX`  和 `ObjectTranslatorPool` 里面的 `ObjectTranslator` 看起来是跟着 LuaEnv 走的。

**Comment by sillyousu** [comment]
搞个 `LuaEnvGlobal` 放 TLS 里面，让用户使用这个 LuaEnv 之前切换设置一下本线程的 `LuaEnvGlobal`？

**Comment by sillyousu** [comment]
我有一些地方没有搞清楚，乱改可能会出bug。
1. Dispose LuaEnv 为什么需要 GC ？
2. ObjectTranslator  里面为什么要用 弱引用 装 Translator ？

**Comment by chexiongsheng** [comment]
我最近有事回老家了，回来再处理下一代问题

**Comment by chexiongsheng** [comment]
LUA_REGISTRYINDEX 比较多的静态函数用到，所以做成静态的，本来这对于特定版本的lua只是个常量，xlua为了兼容luajit和lua53才搞成new LuaEnv时赋值。不过理论上这不会有多线程问题，因为新线程要修改，还是会修改为同一个值。
strBuff确实是个很严重的问题，我相信很多反馈的多线程下多luaenv的相互冲突问题都是这个引起的，不过这个本来只是为了优化pushstring的效率，可以在多线程下不用这个优化。
objectTranslatorPool是个单例，按单例的多线程去处理即可。

**Comment by chexiongsheng** [comment]
我改一版你试试

**Comment by chexiongsheng** [comment]
你合入这个commit试试解决问题不：https://github.com/Tencent/xLua/commit/b29ab3e16091e90bbecdcd467befc8f27c6897c3
没解决你reopen这个issue

**Comment by sillyousu** [comment]
>LUA_REGISTRYINDEX 比较多的静态函数用到，所以做成静态的，本来这对于特定版本的lua只是个常量，xlua为了兼容luajit和lua53才搞成new LuaEnv时赋值。不过理论上这不会有多线程问题，因为新线程要修改，还是会修改为同一个值。

那应该是一个 const ？

**Comment by sillyousu** [comment]
看起来没有crash了。多谢
