### ISSUE TITLE
Magic Leap

### ISSUE THREAD

**Issue by cieraej** [Tencent/xLua#487]
Hi is there any way to get this to run on the Lumin os? Having issues with it not instantiating the VM.

**Comment by chexiongsheng** [comment]
We have not supported Magic Leap yet. You can try to compile the native plugin of xlua yourself.
xlua native plugin's source code here: https://github.com/Tencent/xLua/tree/master/build
it use cmake for cross-platform compilation.

**Comment by cieraej** [comment]
Thank you! Will have a go at this.
Also, is there a tool to easily change C# unity script to lua?

**Comment by cieraej** [comment]
Alright I wasn't sure. Thank you for replying!
Do you know of any tools that do this?

Thanks!

**Comment by chexiongsheng** [comment]
Sorry, i don't know.
