### ISSUE TITLE
类方法IEnumerator导出相关疑问

### ISSUE THREAD

**Issue by 724286867** [Tencent/xLua#489]
类中含有IEnumerator方法，导出wrap类后，开启NOT_GEN_WARNING打印：
会报：AssetbundleUpdater+<CheckDecompress>c__Iterator0 not gen, using reflection instead
AssetBundles.AssetBundleManager+<CoLoadAssetAsync>c__Iterator2 not gen, using reflection instead
这样类似的错无，请问有解决方案吗

**Comment by chexiongsheng** [comment]
额。。其实反射没那么可怕。
这里的类是编译器生成的匿名类，是不可见的，自然也无法对其生成代码。
