### ISSUE TITLE
webgl文档

### ISSUE THREAD

**Issue by txiaoci** [Tencent/xLua#490]
有一个webgl的目录，但是没有关于如何配置webgl的文档描述

**Comment by chexiongsheng** [comment]
如何配置webgl不是要看unity的文档么？

**Comment by txiaoci** [comment]
xlua unzip后里面的webgl目录有用吗，要拖到unity工程下什么目录里吗？

**Comment by chexiongsheng** [comment]
首页有安装说明。按首页安装说明就能用。

**Comment by txiaoci** [comment]
谢谢，好像和我自己代码有关
