### ISSUE TITLE
Lua number to C# object issue

### ISSUE THREAD

**Issue by AmaranthYan** [Tencent/xLua#496]
我们需要在Lua里调用一个参数为object的C#方法
self:CSharp_Method(string_type, object_type)
C#里方法为
void CSharp_Method(string str, object obj)
{
  int i = (int)obj;
  ...
}

我们发现在Lua里使用number类型作为第二个参数，会以Int64的类型传出
这会导致unboxing int时发生invalid cast

想请教有没有方法在不改动现有项目C#代码的情况下，在lua层面解决这个问题？

**Comment by chexiongsheng** [comment]
faq有，例子有
