### ISSUE TITLE
Benchmark question

### ISSUE THREAD

**Issue by omid3098** [Tencent/xLua#497]
I did a little benchmark comparison between having a Monobehaviour and LuaBehaviour:
- make 50*50 cubes
- attach a MonoBehaviour to rotate them in each update.
- attach a LuaBehaviour to rotate them in each update.

![image](https://user-images.githubusercontent.com/6388730/48836520-3c765500-ed98-11e8-895e-a8b0f11d220e.png)

here is the results. as you can see monobehaviour runs much faster than luabehaviour.

Is it possible to reduce this difference?

the base idea is to build whole game logic in lua and put everything in assetbundles to add more minigames in the base game and avoid market updates for new versions or bugfixes.

**Comment by chexiongsheng** [comment]
LuaBehaviour is just a example. 
lua is shower than c#, and, even worse, the cross language call is expensive.
so, we are not recommend that whole app implement by lua. 
frame base work, recommend using c#.
user operation react can use lua.
