### ISSUE TITLE
how can i  invoke lua coroutine in c# coroutine 

### ISSUE THREAD

**Issue by xiangyuan** [Tencent/xLua#499]
i have some c# function IEnumerator  coroutine , if i want invoke lua function which the lua function is coroutine.

how can i implement this

**Comment by chexiongsheng** [comment]
i think there may be some misunderstanding here: there is no "lua function is coroutine" in lua. function is function, coroutine is coroutine, you can yield in any function if the function is run in coroutine, this just like the relationship of function and thread in c#.
c# no coroutine, there is unity's "coroutine".
i guess what you want is:  call a lua function in unity's "coroutine", and yield the  unity's "coroutine" in lua function?

**Comment by chexiongsheng** [comment]
use util.cs_generator  to gen a IEnumerator implement.
the myluafunction below return a IEnumerator instance just like any c# function that return IEnumerator.
~~~lua
local util = require 'xlua.util'
function myluafunction()
    return util.cs_generator(function()
        while true do
            coroutine.yield(CS.UnityEngine.WaitForSeconds(3))
            print('Wait for 3 seconds')
        end
    end)
end
~~~

**Comment by xiangyuan** [comment]
thank you very much @chexiongsheng
