### ISSUE TITLE
支持逻辑热更吗？

### ISSUE THREAD

**Issue by Patrick-Kill** [Tencent/xLua#5]
请问支持逻辑热更吗，现在有使用这套方案的上线项目吗？

**Comment by chexiongsheng** [comment]
本来就是为了逻辑热更而做这套东西的。
有两种方式
1、某个系统完全用lua开发，那这lua代码下载新代码覆盖原来的就可以了。
2、平时用C#开发，打了Hotfix标签的C#类型出现问题后可以用lua来修复。

**Comment by chexiongsheng** [comment]
有上线的项目
