### ISSUE TITLE
Stateful Hotfix 如何扩展方法

### ISSUE THREAD

**Issue by Sparrowfc** [Tencent/xLua#50]
测试了下Stateful Hotfix，还挺方便的。现在的问题是lua里定义的hotfix对象不能包含原来类里不存在的成员，否则加载时会报错。
所以我现在如果想利用这个机制去扩展添加一些新功能的话只能是定义Global的变量（local的变量无法在hotfix对象中调用）。像下面这样
`
local c = {...}

c_extend = 
{
  self = c,
  ext = function() ... end
  ...
}

xlua.hotfix(CS.c, c)
`
这种方案是可行的还是应该有什么更好的解决办法？

**Comment by chexiongsheng** [comment]
Stateful 方式你可以在lua对构造函数的hotfix那返回一个新table，这个table在后续调用都回传，可以认为这对应c#的this，你可以存任何东西

**Comment by chexiongsheng** [comment]
Stateless才不能添加新字段

**Comment by Sparrowfc** [comment]
感谢回答，照你的方式修正了一下（发现之前还有个错误是因为先new的对象后加载的lua，所以self都为空了），我刚接触lua不知道理解对不对啊，现在我改成了这样
`
local c = {
  ['.ctor'] = function(csobj)
    return {
      newBtn = nil,
      HandleNewBtnClick = function()
        --handle logic
      end
    }
  end;
  
  OpenUI = function(self)
     self.newBtn = .....
     self.newBtn:AddListener(self.HandleNewBtnClick)
  end;
}
`
执行没有问题，其中HandleNewBtnClick是原来代码里没有新添加的方法，现在的问题是在HandleNewBtnClick里面我不知道怎么去调用newBtn或者是OpenUI这类原来的方法，不知道是不是哪儿理解错了

**Comment by chexiongsheng** [comment]
你可以用闭包来访问self，这属于lua语法的范畴了

**Comment by chexiongsheng** [comment]
建议系统的学下lua

**Comment by Sparrowfc** [comment]
好的，谢谢了

**Comment by chexiongsheng** [comment]
Stateful 模式建议程序启动时加载补丁，否则就会出现你碰到的一开始那个问题

**Comment by Sparrowfc** [comment]
恩，这个知道。另外还有一个问题，麻烦请教一下，比如我如果同时hotfix了两个对象，luaA现在希望能够调用luaB的扩展接口，那我在luaA里面调用CS.B:NewInterface应该肯定是不行的吧，那除了luaB内部方法闭包的话还有能在外部访问到luaB的self的方法么？

**Comment by chexiongsheng** [comment]
就lua内部调用。
除非你在C#那是一个delegate，把你的lua函数赋值过去后，别的地方，包括lua都可以通过delegate调用到那lua函数。
