### ISSUE TITLE
macos上运行make_android_luajit.sh报错

### ISSUE THREAD

**Issue by sophiepeithos** [Tencent/xLua#500]
macos10.14
xcode10
ndk r10e
xlua代码用的是master分支最新
输出：
Building armv7 lib
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src clean
rm -f luajit libluajit.a libluajit.so host/minilua host/buildvm lj_vm.S lj_bcdef.h lj_ffdef.h lj_libdef.h lj_recdef.h lj_folddef.h host/buildvm_arch.h jit/vmdef.lua *.o host/*.o *.obj *.lib *.exp *.dll *.exe *.manifest *.pdb *.ilk
==== Building LuaJIT 2.1.0-beta3 ====
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src
HOSTCC    host/minilua.o
HOSTLINK  host/minilua
ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libm.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libm.tbd
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
Undefined symbols for architecture i386:
  "__DefaultRuneLocale", referenced from:
      _luaB_tonumber in minilua.o
      _llex in minilua.o
      _luaX_lexerror in minilua.o
      _read_numeral in minilua.o
      _statement in minilua.o
      _check_match in minilua.o
      _constructor in minilua.o
      ...
  "___bzero", referenced from:
      _luaS_resize in minilua.o
      _luaD_call in minilua.o
      _f_parser in minilua.o
  "___error", referenced from:
      _io_fclose in minilua.o
      _io_pclose in minilua.o
      _f_flush in minilua.o
      _io_readline in minilua.o
      _g_read in minilua.o
      _g_write in minilua.o
      _io_flush in minilua.o
      ...
  "___maskrune", referenced from:
      _luaB_tonumber in minilua.o
      _llex in minilua.o
      _luaX_lexerror in minilua.o
      _read_numeral in minilua.o
      _check_match in minilua.o
      _error_expected in minilua.o
      _match_class in minilua.o
      ...
  "___sprintf_chk", referenced from:
      _main in minilua.o
      _luaL_loadfile in minilua.o
      _panic in minilua.o
      _luaO_pushvfstring in minilua.o
      _luaV_concat in minilua.o
      _luaB_assert in minilua.o
      _luaB_loadfile in minilua.o
      ...
  "___stack_chk_fail", referenced from:
      _main in minilua.o
      _luaL_loadfile in minilua.o
      _panic in minilua.o
      _luaG_runerror in minilua.o
      _luaO_pushvfstring in minilua.o
      _luaV_concat in minilua.o
      _newkey in minilua.o
      ...
  "___stack_chk_guard", referenced from:
      _main in minilua.o
      _luaL_loadfile in minilua.o
      _panic in minilua.o
      _luaG_runerror in minilua.o
      _luaO_pushvfstring in minilua.o
      _luaV_concat in minilua.o
      _newkey in minilua.o
      ...
  "___stderrp", referenced from:
      _main in minilua.o
      _panic in minilua.o
      _luaopen_io in minilua.o
  "___stdinp", referenced from:
      _luaL_loadfile in minilua.o
      _luaopen_io in minilua.o
  "___stdoutp", referenced from:
      _luaopen_io in minilua.o
  "___strcat_chk", referenced from:
      _luaO_chunkid in minilua.o
  "___strncat_chk", referenced from:
      _luaO_chunkid in minilua.o
  "___strncpy_chk", referenced from:
      _str_format in minilua.o
  "___tolower", referenced from:
      _str_lower in minilua.o
      _match_class in minilua.o
  "___toupper", referenced from:
      _str_upper in minilua.o
  "_clearerr", referenced from:
      _g_read in minilua.o
  "_exit", referenced from:
      _f_luaopen in minilua.o
      _luaH_new in minilua.o
      _luaS_resize in minilua.o
      _luaS_newlstr in minilua.o
      _luaD_throw in minilua.o
      _resetstack in minilua.o
      _luaG_errormsg in minilua.o
      ...
  "_fclose", referenced from:
      _luaL_loadfile in minilua.o
      _io_fclose in minilua.o
  "_feof", referenced from:
      _getF in minilua.o
  "_ferror", referenced from:
      _luaL_loadfile in minilua.o
      _io_readline in minilua.o
      _g_read in minilua.o
  "_fflush", referenced from:
      _f_flush in minilua.o
      _io_flush in minilua.o
  "_fgets", referenced from:
      _read_line in minilua.o
  "_fopen$UNIX2003", referenced from:
      _luaL_loadfile in minilua.o
      _io_lines in minilua.o
      _io_open in minilua.o
      _g_iofile in minilua.o
  "_fprintf", referenced from:
      _main in minilua.o
      _panic in minilua.o
      _g_write in minilua.o
  "_fread", referenced from:
      _read_chars in minilua.o
      _getF in minilua.o
  "_free", referenced from:
      _l_alloc in minilua.o
  "_freopen$UNIX2003", referenced from:
      _luaL_loadfile in minilua.o
  "_fscanf", referenced from:
      _g_read in minilua.o
  "_fwrite$UNIX2003", referenced from:
      _g_write in minilua.o
  "_getc", referenced from:
      _luaL_loadfile in minilua.o
      _g_read in minilua.o
  "_isspace", referenced from:
      _luaO_str2d in minilua.o
  "_longjmp", referenced from:
      _f_luaopen in minilua.o
      _luaH_new in minilua.o
      _luaS_resize in minilua.o
      _luaS_newlstr in minilua.o
      _luaD_throw in minilua.o
      _resetstack in minilua.o
      _luaG_errormsg in minilua.o
      ...
  "_memchr", referenced from:
      _llex in minilua.o
      _read_numeral in minilua.o
      _str_format in minilua.o
      _str_find_aux in minilua.o
  "_memcmp", referenced from:
      _luaS_newlstr in minilua.o
      _str_find_aux in minilua.o
      _match in minilua.o
  "_memcpy", referenced from:
      _luaS_newlstr in minilua.o
      _luaV_concat in minilua.o
      _luaL_addvalue in minilua.o
  "_pow", referenced from:
      _luaD_call in minilua.o
      _Arith in minilua.o
      _codearith in minilua.o
  "_realloc", referenced from:
      _main in minilua.o
      _l_alloc in minilua.o
  "_remove", referenced from:
      _os_remove in minilua.o
  "_setjmp", referenced from:
      _luaD_rawrunprotected in minilua.o
  "_strchr", referenced from:
      _luaO_pushvfstring in minilua.o
      _propagatemark in minilua.o
      _lua_getinfo in minilua.o
      _str_format in minilua.o
      _luaL_findtable in minilua.o
  "_strcmp", referenced from:
      _ipairsaux in minilua.o
      _luaB_assert in minilua.o
      _luaB_loadstring in minilua.o
      _luaB_rawget in minilua.o
      _luaB_setfenv in minilua.o
      _luaB_setmetatable in minilua.o
      _luaB_tonumber in minilua.o
      ...
  "_strcoll", referenced from:
      _luaD_call in minilua.o
      _luaV_lessthan in minilua.o
  "_strcspn", referenced from:
      _luaO_chunkid in minilua.o
  "_strerror$UNIX2003", referenced from:
      _io_fclose in minilua.o
      _io_pclose in minilua.o
      _f_flush in minilua.o
      _io_readline in minilua.o
      _g_read in minilua.o
      _g_write in minilua.o
      _io_flush in minilua.o
      ...
  "_strlen", referenced from:
      _main in minilua.o
      _luaL_register in minilua.o
      _luaL_loadfile in minilua.o
      _panic in minilua.o
      _f_luaopen in minilua.o
      _luaO_pushvfstring in minilua.o
      _luaO_chunkid in minilua.o
      ...
  "_strncpy", referenced from:
      _luaO_chunkid in minilua.o
  "_strpbrk", referenced from:
      _str_find_aux in minilua.o
  "_strtod$UNIX2003", referenced from:
      _luaO_str2d in minilua.o
  "_strtoul", referenced from:
      _luaO_str2d in minilua.o
      _luaB_tonumber in minilua.o
  "_ungetc", referenced from:
      _luaL_loadfile in minilua.o
      _g_read in minilua.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [host/minilua] Error 1
make: *** [default] Error 2
CMake Deprecation Warning at /usr/local/Cellar/cmake/3.10.3/share/cmake/Modules/CMakeForceCompiler.cmake:69 (message):
  The CMAKE_FORCE_C_COMPILER macro is deprecated.  Instead just set
  CMAKE_C_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  cmake/android.toolchain.cmake:1177 (CMAKE_FORCE_C_COMPILER)
  /usr/local/Cellar/cmake/3.10.3/share/cmake/Modules/CMakeDetermineSystem.cmake:91 (include)
  CMakeLists.txt:16 (project)

CMake Deprecation Warning at /usr/local/Cellar/cmake/3.10.3/share/cmake/Modules/CMakeForceCompiler.cmake:83 (message):
  The CMAKE_FORCE_CXX_COMPILER macro is deprecated.  Instead just set
  CMAKE_CXX_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  cmake/android.toolchain.cmake:1189 (CMAKE_FORCE_CXX_COMPILER)
  /usr/local/Cellar/cmake/3.10.3/share/cmake/Modules/CMakeDetermineSystem.cmake:91 (include)
  CMakeLists.txt:16 (project)

-- Configuring done
-- Generating done
-- Build files have been written to: /Users/hui/Downloads/xLua-master/build/build_lj_v7a
Scanning dependencies of target xlua
[  5%] Building C object CMakeFiles/xlua.dir/luasocket/auxiliar.c.o
[ 11%] Building C object CMakeFiles/xlua.dir/luasocket/buffer.c.o
[ 17%] Building C object CMakeFiles/xlua.dir/luasocket/except.c.o
[ 23%] Building C object CMakeFiles/xlua.dir/luasocket/inet.c.o
[ 29%] Building C object CMakeFiles/xlua.dir/luasocket/io.c.o
[ 35%] Building C object CMakeFiles/xlua.dir/luasocket/luasocket.c.o
[ 41%] Building C object CMakeFiles/xlua.dir/luasocket/mime.c.o
[ 47%] Building C object CMakeFiles/xlua.dir/luasocket/options.c.o
[ 52%] Building C object CMakeFiles/xlua.dir/luasocket/select.c.o
[ 58%] Building C object CMakeFiles/xlua.dir/luasocket/tcp.c.o
[ 64%] Building C object CMakeFiles/xlua.dir/luasocket/timeout.c.o
[ 70%] Building C object CMakeFiles/xlua.dir/luasocket/udp.c.o
[ 76%] Building C object CMakeFiles/xlua.dir/luasocket/usocket.c.o
[ 82%] Building C object CMakeFiles/xlua.dir/i64lib.c.o
[ 88%] Building C object CMakeFiles/xlua.dir/perflib.c.o
[ 94%] Building C object CMakeFiles/xlua.dir/xlua.c.o
make[2]: *** No rule to make target `../luajit-2.1.0b3/src/libluajit.a', needed by `libxlua.so'.  Stop.
make[1]: *** [CMakeFiles/xlua.dir/all] Error 2
make: *** [all] Error 2
cp: build_lj_v7a/libxlua.so: No such file or directory

**Comment by chexiongsheng** [comment]
本来这东西预计在linux上跑的

**Comment by sophiepeithos** [comment]
然而在make_android_luajit.sh里看见了
if [[ "$OS" == "Darwin" ]]; then
    PREBUILT_PLATFORM=darwin-x86_64
fi
所以请大神加入macos的支持吧

**Comment by sophiepeithos** [comment]
嗯，确定了，是xcode10的问题，换回xcode9.4.1就行了

**Comment by zhouzhanglin** [comment]
这个bug还没有修复吗

**Comment by chexiongsheng** [comment]
> 这个bug还没有修复吗？我也遇到这个问题，现在基本都是用的xcode10

你版本太老了吧，早支持了，我不过现在我也没用xcode10那么老的版本。
