### ISSUE TITLE
HOTFIX有没有办法做到函数粒度的控制?

### ISSUE THREAD

**Issue by fofewyoung** [Tencent/xLua#504]
比如我有一个Class A, 里面有fun1和 fun2,  fun1由于某种原因(性能考虑，调用过于频繁)我希望XLUA不要注入代码, fun2正常支持热修复,这样有办法做到吗？

**Comment by chexiongsheng** [comment]
不支持
如果有那么几个函数连这点开销都接受不了的话，我觉得整个类都别注入好了。
ps：有个竞速类的项目做过全部类型全注入，实际线上运行也没发现性能上有啥影响。
