### ISSUE TITLE
生成包裹与未生成的行为不一致

### ISSUE THREAD

**Issue by cuinc** [Tencent/xLua#505]
local go = CS.UnityEngine.GameObject();
--- 在生成包裹代码时，会报空
--- 未生成代码时，能正常执行
go.active = false; 

---- 期望两都的行为统一

**Comment by chexiongsheng** [comment]
active是Obsolete的api，以前版本xlua没生成代码不会检查Obsolete。
新版本2.1.13这块是一致的。
ps：Obsolete的api你本来就不该用。

**Comment by cuinc** [comment]
我主要担心的是大家在正常开发的时候，都是没有去生成包裹代码，如果不小心使用到了，上线的时候，行为不一致，容易产生bug
我当前的版本是稳定版的2.1.13，它们在表现是不一样的
`local go = CS.UnityEngine.GameObject();
--- 未生成代码时，能正常执行
go.active = false;
--- 在生成包裹代码时，会报空
go.active = false;

Execute Lua Fail => XLua.LuaException: cannot set active, no such field`

**Comment by chexiongsheng** [comment]
嗯，之前加了BlackList的判断，没加上ObsoleteAttribute，你待会合入下修复。

**Comment by kwedr** [comment]
xLua : v2.1.14
Unity:  2018.4.0f1

--- 未生成代码时，能正常执行
go.active = false;

**Comment by kwedr** [comment]
xLua : v2.1.14
Unity: 2018.4.0f1

--- 未生成代码时，仍能正常执行
go.active = false;
