### ISSUE TITLE
关于IOS平台禁用热更新的问题

### ISSUE THREAD

**Issue by sqiuzhao** [Tencent/xLua#508]
首选，肯定一下Xlua是一款十分优秀的热更新以及热补丁解决方案。

因为听说ios平台上已经下架了很多实用热更新方案的应用，所以我想确认一下，xlua实用的生成代码情况下的热补丁是否在ios平台禁用行列，也就是说如果我实用xlua进行热补丁修正，是否能在ios平台上正常实用而不会被下架。求作者告知下，谢谢。
因为如果ios端被禁止，我们的应用就只在安卓上实用xlua进行热补丁修正，在ios端暂时不添加该方案。

谢谢！

**Comment by chexiongsheng** [comment]
1、很多项目一直在各平台用，没听说有啥问题；
2、正确理解“热更新”，“热更新”是指下载代码执行的行为，用lua不下载就不是热更新，你不用lua，下载了个python来执行也是热更新。xlua只是个支持你用lua写代码的库，没“下载”，所以不是什么热更新方案。
3、如果你用了某种脚本方案，又下载了，被苹果盯上了，你就停止下载。

**Comment by sqiuzhao** [comment]
感谢你的回答！还有个问题不是很明白，如果我用xlua的hotfix热补丁修正，我肯定要从远程如腾讯云上下载用hotfix修正的lua文件（然后通过原生的C#代码进行读取lua文件中的lua代码）。这种下载是你指的下载吗，xlua热补丁算你说的““热更新”是指下载代码执行的行为”吗？如果不是从远程下载，那么还有其他方法可以直接实现热更新吗？

**Comment by chexiongsheng** [comment]
xlua热补丁没下载，你怎么用是你的选择。
如果是xlua热补丁，你从用改为不用，需要啥工作量么？有什么值得考虑的事情？
别光编程，语文阅读理解能力也是很必要的。

**Comment by sqiuzhao** [comment]
感谢指正，但是关于xlua热补丁没下载，真心理解不了是什么意思，因为在我的概念里，当我们往平台发布应用后，所有用到的文件都已经打进包里了，也就是如果我要做xlua热补丁，就得重新编写lua程序，这样，只能从远程下载我编写的程序文件，然后再执行。具体怎么处理，能简单教一下吗？
这个问题对前辈你来说或许比较低级，但是对我来说或许有那么点智商不够用吧，希望不吝赐教哈，多谢！

**Comment by chexiongsheng** [comment]
但xlua本身没做下载，不对么？

**Comment by sqiuzhao** [comment]
嗯，这个理解，所有下载的资源都是原生的C#代码处理的。意思是，只要xlua不做下载，ios就不会把xlua判定为热更新对吗？尽管我们用C#下载的，是这样吗

**Comment by chexiongsheng** [comment]
因为没下载，就不能以热更新为理由禁用xlua。
某个具体项目的下载行为，被苹果禁，就那个项目整改，把下载部分去掉。
为人为己，别提什么xlua是热更新了，因为没下载，听明白了么？

政策这种东西不好说，万一明天苹果就把unity应用给禁用你怎么办？苹果也曾经因为flash性能不好禁了flash。

**Comment by sqiuzhao** [comment]
嗯，了解，xlua就是xlua。
多谢！

**Comment by ckyQwQ** [comment]
哈哈哈，死活不解释什么是下载
