### ISSUE TITLE
将XLua.zip解压到Asset文件夹，在添加完HOTFIX_ENABLE后立即报错

### ISSUE THREAD

**Issue by zheng4tao** [Tencent/xLua#51]
（1）在https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/hotfix.md 有看到类似的错误：
“打开HOTFIX_DEBUG_SYMBOLS可以解决il和源代码对应不上的问题，但如果在编辑器下运行过后在修改代码，会报Assembly-CSharp.dll.mdb的写冲突错误。”但不清楚这个问题是如何解决的。

（2）我们实际遇到的报错和（1）有些差别：
        目前解压XLua到两个工程目录后运行08Example，第一个工程顺利地测试完热修复，但第二个工程解压完，在添加HOTFIX_ENABLE之后，会立即弹出这个错误，不知道是不是我多处理了哪些步骤。已经尝试多次，第二个工程都会报这个错误：
Console:
AssemblyResolutionException: Failed to resolve assembly: 'Assembly-CSharp-firstpass, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
Mono.Cecil.BaseAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name, Mono.Cecil.ReaderParameters parameters)
Mono.Cecil.BaseAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name)
Mono.Cecil.DefaultAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name)
Mono.Cecil.MetadataResolver.Resolve (Mono.Cecil.TypeReference type)
Mono.Cecil.ModuleDefinition.Resolve (Mono.Cecil.TypeReference type)
Mono.Cecil.TypeReference.Resolve ()
Mono.Cecil.Mixin.CheckedResolve (Mono.Cecil.TypeReference self)
Mono.Cecil.SignatureReader.ReadCustomAttributeEnum (Mono.Cecil.TypeReference enum_type)
Mono.Cecil.SignatureReader.ReadCustomAttributeElementValue (Mono.Cecil.TypeReference type)
Mono.Cecil.SignatureReader.ReadCustomAttributeElement (Mono.Cecil.TypeReference type)
Mono.Cecil.SignatureReader.ReadCustomAttributeElement (Mono.Cecil.TypeReference type)
Mono.Cecil.SignatureReader.ReadCustomAttributeFixedArgument (Mono.Cecil.TypeReference type)
Mono.Cecil.SignatureReader.ReadCustomAttributeConstructorArguments (Mono.Cecil.CustomAttribute attribute, Mono.Collections.Generic.Collection`1 parameters)
Mono.Cecil.MetadataReader.ReadCustomAttributeSignature (Mono.Cecil.CustomAttribute attribute)
Mono.Cecil.CustomAttribute.<Resolve>b__2 (Mono.Cecil.CustomAttribute attribute, Mono.Cecil.MetadataReader reader)
Mono.Cecil.ModuleDefinition.Read[CustomAttribute,CustomAttribute] (Mono.Cecil.CustomAttribute item, System.Func`3 read)
Mono.Cecil.CustomAttribute.Resolve ()
Mono.Cecil.CustomAttribute.get_ConstructorArguments ()
Mono.Cecil.ImmediateModuleReader.ReadCustomAttributes (ICustomAttributeProvider provider)
Mono.Cecil.ImmediateModuleReader.ReadProperties (Mono.Cecil.TypeDefinition type)
Mono.Cecil.ImmediateModuleReader.ReadType (Mono.Cecil.TypeDefinition type)
Mono.Cecil.ImmediateModuleReader.ReadTypes (Mono.Collections.Generic.Collection`1 types)
Mono.Cecil.ImmediateModuleReader.ReadModule (Mono.Cecil.ModuleDefinition module)
Mono.Cecil.ModuleWriter.WriteModuleTo (Mono.Cecil.ModuleDefinition module, System.IO.Stream stream, Mono.Cecil.WriterParameters parameters)
Mono.Cecil.ModuleDefinition.Write (System.IO.Stream stream, Mono.Cecil.WriterParameters parameters)
Mono.Cecil.ModuleDefinition.Write (System.String fileName, Mono.Cecil.WriterParameters parameters)
Mono.Cecil.AssemblyDefinition.Write (System.String fileName, Mono.Cecil.WriterParameters parameters)
Mono.Cecil.AssemblyDefinition.Write (System.String fileName)
XLua.Hotfix.HotfixInject () (at Assets/XLua/Src/Editor/Hotfix.cs:263)

不知道具体的处理方案是怎样的？

感谢你在百忙之中阅读我的问题，如未回复请别在意，也是在给自己整理思路，感谢提供XLua！

**Comment by zheng4tao** [comment]
![1](https://cloud.githubusercontent.com/assets/14070061/21806220/05776f54-d773-11e6-8ff4-491b0ec8659a.png)

**Comment by zheng4tao** [comment]
忽视这个错误，运行08Example 则会出现以下报错：
![2](https://cloud.githubusercontent.com/assets/14070061/21806293/635b82a4-d773-11e6-9b5f-a59be3733607.png)

**Comment by chexiongsheng** [comment]
打包下有问题的工程发chexiongsheng@qq.com，可以么？

**Comment by zheng4tao** [comment]
谢谢回复！
我在想这个错误跟你在约束里提到的这个错误，是否有相似的处理方法呢？
> “打开HOTFIX_DEBUG_SYMBOLS可以解决il和源代码对应不上的问题，但如果在编辑器下运行过后在修改代码，会报Assembly-CSharp.dll.mdb的写冲突错误。”

**Comment by chexiongsheng** [comment]
有位童鞋解决了写冲突的问题以及AssemblyResolutionException了，你update一下看看是否解决你的问题了。

**Comment by zheng4tao** [comment]
重新导入后没问题，但添加完HOTFIX_ENABLE并将Mono.Cecil.dll放入工程Asset文档下后 
提示 No delegate for HotfixTest.cs 建议 re-regenerate
1.无视这个提示，则运行click Hotfix 按钮：

> LuaException: xlua.access, no field __Hitfix0_Update

2.Clear Generated Code 接着 Generate Code 后 ，原问题中错误再次出现了
![3](https://cloud.githubusercontent.com/assets/14070061/21841216/43fa5d46-d81c-11e6-8722-a69a01dcaffe.png)

这种状况…

**Comment by chexiongsheng** [comment]
没看到打印inject finish

**Comment by chexiongsheng** [comment]
执行Generate Code
坐等inject finish
点击运行

**Comment by zheng4tao** [comment]
等不到hotfix inject finish!
等来的是：
![image](https://cloud.githubusercontent.com/assets/14070061/21842032/eba07ea6-d81f-11e6-8d99-cfb5e86dea27.png)

**Comment by chexiongsheng** [comment]
update了最新代码了么？

**Comment by chexiongsheng** [comment]
firstpass这个我又提交过一个commit

**Comment by zheng4tao** [comment]
解决了！ 原因是工程里有个nameplace 与 Xlua的Utils重名
我在修改前将HOTFIX_ENABLE去掉后，再修改Utils→Xlua.Utils
将重名问题解决后 再将HOTFIX_ENABLE加上
便不会报这个错误了
不知道是什么原因呢？
