### ISSUE TITLE
生成与未生成包裹代码，extension方法行为不一致

### ISSUE THREAD

**Issue by cuinc** [Tencent/xLua#512]

**Comment by cuinc** [comment]
`using UnityEngine;
using XLua;


public class FooParent
{
    public void SayHello()
    {
        Debug.Log("Hello");
    }
}

[LuaCallCSharp]
public class FooChild : FooParent
{
}

[LuaCallCSharp]
public static class ExtensionTest
{
    public static void PlainExtension(this FooParent a)
    {
        a.SayHello();
    }
}

public class GenericMethodExample : MonoBehaviour
{
    private const string script = @"
        local foo1 = CS.FooChild();
        foo1:PlainExtension()
";
    private LuaEnv env;

    private void Start()
    {
        env = new LuaEnv();
        env.DoString(script);
    }

    private void Update()
    {
        if (env != null)
            env.Tick();
    }

    private void OnDestroy()
    {
        env.Dispose();
    }
}
`

**Comment by cuinc** [comment]
父类如果没有添加LuaCallCSharp,子类访问父类的扩展方法，报空，如果没有生成包裹代码，则行为正常，

**Comment by chexiongsheng** [comment]
最近比较忙，稍闲点时处理

**Comment by cuinc** [comment]
我跟了一下 生成包裹代码Generator.cs:1094
`var extension_methods = from t in ReflectionUse
                                    where isDefined(t, typeof(ExtensionAttribute))
                                    from method in t.GetMethods(BindingFlags.Static | BindingFlags.Public)
                                    where isDefined(method, typeof(ExtensionAttribute))
                                    where !method.ContainsGenericParameters || isSupportedGenericMethod(method)
                                    select makeGenericMethodIfNeeded(method);`
与 未生成代码时 Utils:331
`if (type.IsDefined(typeof(ExtensionAttribute), false) && (
							type.IsDefined(typeof(ReflectionUseAttribute), false)
#if UNITY_EDITOR || XLUA_GENERAL
							|| type.IsDefined(typeof(LuaCallCSharpAttribute), false)
#endif
						))
					{
						type_def_extention_method.Add(type);
					}`
此处的逻辑不一致

**Comment by chexiongsheng** [comment]
你看下是不是最新版本？如果最新版本没问题，就不处理了。

**Comment by cuinc** [comment]
我使用了master分支&2.1.13两个版本，都重现了

**Comment by cuinc** [comment]
可以直接将我反馈的代码拷贝下来运行，比较容易重现
