### ISSUE TITLE
发布WebGL报错

### ISSUE THREAD

**Issue by demon04551** [Tencent/xLua#514]
Failed running python "/Applications/Unity-2017-4.1/PlaybackEngines/WebGLSupport/BuildTools/Emscripten/emcc" @"/Users/mac/coding/New Unity Project (2)/Assets/../Temp/emcc_arguments.resp"

mac系统，u3d版本2017－2018都试过，xlua试过2.1.11，2.1.13都是同样的问题

**Comment by chexiongsheng** [comment]
亲测可以。
你比较可能漏了WebGLPlugins目录。
仔细按首页安装说明安装一遍
