### ISSUE TITLE
Mac下编译ios报错

### ISSUE THREAD

**Issue by yangchg** [Tencent/xLua#515]
macOS：10.14.2 (18C54)
Xcode：10.1 (10B61)
xLua： 2.1.13
编译ios失败：运行make_ios_lua53.sh和make_ios_luajit.sh （android和osx可以正常编译）
./make_ios_lua53.sh 
-- Toolchain using default iOS SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:16 (project):
  No CMAKE_C_COMPILER could be found.

CMake Error at CMakeLists.txt:16 (project):
  No CMAKE_CXX_COMPILER could be found.

-- Configuring incomplete, errors occurred!
See also "/Users/yangchuanguo/Work/Github/build_xlua_with_libs/build/build_ios/CMakeFiles/CMakeOutput.log".
See also "/Users/yangchuanguo/Work/Github/build_xlua_with_libs/build/build_ios/CMakeFiles/CMakeError.log".
xcodebuild: error: 'XLua.xcodeproj' does not exist.
cp: build_ios/Release-iphoneos/libxlua.a: No such file or directory

--------- CMakeError.log -------------
Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler:  
Build flags: 
Id flags:  

The output was:
65
note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: Signing for "CompilerIdC" requires a development team. Select a development team in the project editor. (in target 'CompilerIdC')

Build system information
warning: Traditional headermap style is no longer supported; please migrate to using separate headermaps and set 'ALWAYS_SEARCH_USER_PATHS' to NO. (in target 'CompilerIdC')

** BUILD FAILED **

Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler:  
Build flags: 
Id flags:  

The output was:
65
note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: Signing for "CompilerIdC" requires a development team. Select a development team in the project editor. (in target 'CompilerIdC')

Build system information
warning: Traditional headermap style is no longer supported; please migrate to using separate headermaps and set 'ALWAYS_SEARCH_USER_PATHS' to NO. (in target 'CompilerIdC')

** BUILD FAILED **

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler:  
Build flags: -fvisibility=hidden;-fvisibility-inlines-hidden;-isysroot;/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk
Id flags:  

The output was:
65
note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: Signing for "CompilerIdCXX" requires a development team. Select a development team in the project editor. (in target 'CompilerIdCXX')

Build system information
warning: Traditional headermap style is no longer supported; please migrate to using separate headermaps and set 'ALWAYS_SEARCH_USER_PATHS' to NO. (in target 'CompilerIdCXX')

** BUILD FAILED **

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler:  
Build flags: 
Id flags:  

The output was:
65
note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: Signing for "CompilerIdCXX" requires a development team. Select a development team in the project editor. (in target 'CompilerIdCXX')

Build system information
warning: Traditional headermap style is no longer supported; please migrate to using separate headermaps and set 'ALWAYS_SEARCH_USER_PATHS' to NO. (in target 'CompilerIdCXX')

** BUILD FAILED **

**Comment by chexiongsheng** [comment]
和xcode、cmake有关的环境问题。google一下解决办法

**Comment by WuShiliang** [comment]
请问你解决了吗，我也遇到同样的问题

**Comment by yangchg** [comment]
cmake -DCMAKE_XCODE_ATTRIBUTE_DEVELOPMENT_TEAM=XXXX -DCMAKE_TOOLCHAIN_FILE=../cmake/iOS.cmake -GXcode ../

在 2019-01-07 10:59:23，"WuShiliang" <notifications@github.com> 写道：


请问你解决了吗，我也遇到同样的问题

**Comment by WuShiliang** [comment]
> cmake -DCMAKE_XCODE_ATTRIBUTE_DEVELOPMENT_TEAM=XXXX -DCMAKE_TOOLCHAIN_FILE=../cmake/iOS.cmake -GXcode ../ 在 2019-01-07 10:59:23，"WuShiliang" <notifications@github.com> 写道： 请问你解决了吗，我也遇到同样的问题 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

问题解决了，非常感谢！

**Comment by yangchg** [comment]
Apple开发者证书的TeamId
