### ISSUE TITLE
luasocket在xlua中使用出错

### ISSUE THREAD

**Issue by yiyucyp** [Tencent/xLua#516]
在luaenv.cs中是这么引入luasocket库的，两次调用luaopen_socket_core，如下：
                AddBuildin("socket.core", StaticLuaCallbacks.LoadSocketCore);
                AddBuildin("socket", StaticLuaCallbacks.LoadSocketCore);
问题：
导致使用socket时出错，如果把下面的一行注释掉，就能正常使用
                AddBuildin("socket.core", StaticLuaCallbacks.LoadSocketCore);
                //AddBuildin("socket", StaticLuaCallbacks.LoadSocketCore);
我想了解下，为什么这里要打socket.core又负值给全局的socket表，这么做有什么目的
在最新的luasocket库里，已经加进去了对http等其他库的支持，里面会有自已的socket的导出逻辑，作者在代码中引入了多个lua文件实现相应的逻辑：
socket.lua文件，内容如下：
https://github.com/diegonehab/luasocket/blob/master/src/socket.lua
还请告知下原因，同时能否把luasocket也同步到最新谢谢！

**Comment by chexiongsheng** [comment]
那你注释掉下面那行吧。
把socket也加记得是某些库只是用到socket下的部分api，而这部分api刚好在socket.core都有。
