### ISSUE TITLE
Lua侧对C#Application赋值问题

### ISSUE THREAD

**Issue by 724286867** [Tencent/xLua#517]
Lua 侧代码
function UIPerformanceCounterCtrl:OnFrameRateValueChanged(value)
    CS.UnityEngine.QualitySettings.vSyncCount = 0
    self.model:SetFrameRateValue(value)
    local cfg = self.model:GetFrameRateCfg()
    CS.Application.targetFrameRate = cfg
    Logger.Log("targetFrameRate=" .. cfg)
    Logger.Log("CS.Application.targetFrameRate=" .. CS.Application.targetFrameRate)
end
这里Application.targetFrameRate确实赋值成功了，但是却没有帧率却没有变化，但是写C#侧赋值，帧率却有变化，请问大神是什么问题

**Comment by chexiongsheng** [comment]
少了名字空间
