### ISSUE TITLE
ExampleConfig里的纯lua编程配置参考运行报错

### ISSUE THREAD

**Issue by sophiepeithos** [Tencent/xLua#518]
打开了ExampleConfig里的纯lua编程配置参考后，在xLua最新版本，Unity2018.3.0f2上，Scripting Runtime Version为.NET 3.5时运行Examples/U3DScripting会报错：
TypeLoadException: A type load exception has occurred.
XLua.ObjectTranslator.getDelegate (XLua.DelegateBridgeBase bridge, System.Type delegateType) (at Assets/XLua/Src/ObjectTranslator.cs:423)
XLua.ObjectTranslator.CreateDelegateBridge (IntPtr L, System.Type delegateType, Int32 idx) (at Assets/XLua/Src/ObjectTranslator.cs:527)

Scripting Runtime Version为.NET 4.x，Api Compatibility Level为.Net 4.x时也会报错：
BadImageFormatException: Method with open type while not compiling gshared
XLua.LuaTable.Get[TKey,TValue] (TKey key, TValue& value) (at Assets/XLua/Src/LuaTable.cs:65)
LuaBehaviour.Awake () (at Assets/XLua/Examples/02_U3DScripting/LuaBehaviour.cs:56)

**Comment by chexiongsheng** [comment]
我把这个配置改为默认只对“UnityEngine”，“UnityEngine.UI”生成，你试试看能解决问题不：https://github.com/Tencent/xLua/commit/10b412448f3a13e81a405630921e4c79318a86e3

**Comment by sophiepeithos** [comment]
Examples应该可以了，但是在真正的项目里还是有问题，这类问题有什么解决思路吗？

**Comment by chexiongsheng** [comment]
真正项目有什么问题？问题都没描述就有解决思路？

**Comment by sophiepeithos** [comment]
还是我发的Method with open type while not compiling gshared这个错，应该是CSharpCallLua导致的错误，我把返回的types输出到文件了，你帮忙看看，谢谢
[1.txt](https://github.com/Tencent/xLua/files/2735574/1.txt)

**Comment by chexiongsheng** [comment]
这个就是你工程里某个库有问题了。
这个库编译得在新版本unity用不了。
之前没报错可能你代码没用到。

**Comment by chexiongsheng** [comment]
之前也有人出现这问题，后来找到那个有问题的dll，删了就好了

**Comment by sophiepeithos** [comment]
LITJson.ExporterFunc`1[T]         LITJson
LITJson.ImporterFunc`2[TJson,TValue]         LITJson
LITJson.FactoryFunc`1[T]         LITJson

LITJson導致的問題

**Comment by sophiepeithos** [comment]
能反射出来的method加了DeclaredOnly的限制是有什么特殊考虑吗，因为如果这样像UnityEngine.UI.Dropdown.onValueChanged用起来就会因为UnityEvent<int>没添加到CSharpCallLua报错

**Comment by sophiepeithos** [comment]
另外LuaCallCSharp会排除所有的枚举类型但是定义NOT_GEN_WAR后又会报反射，是什么考虑？

**Comment by sophiepeithos** [comment]
```
where type.Namespace != null && namespaces.Contains(type.Namespace) && !isExcluded(type)
                                      && type.BaseType != typeof(MulticastDelegate) && !type.IsInterface && !type.IsEnum
```
没排除枚举?
