### ISSUE TITLE
奇怪的调用堆栈

### ISSUE THREAD

**Issue by Henry-T** [Tencent/xLua#523]
某种情况下（具体怎么触发的还没定位到），会出现下面的调用堆栈

...
UnityEngine.Debug:Log(Object)
XLua.StaticLuaCallbacks:Print(IntPtr) (at Assets/Xlua/Src/StaticLuaCallbacks.cs:637)
XLua.LuaDLL.Lua:lua_pcall(IntPtr, Int32, Int32, Int32)
XLua.CSObjectWrap.SystemCollectionsIEnumeratorBridge:MoveNext() (at Assets/Xlua/Gen/SystemCollectionsIEnumeratorBridge.cs:55)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)  <-- 很神器地调用到这里了
XLua.CSObjectWrap.UnityEngineMonoBehaviourWrap:_m_StartCoroutine(IntPtr) (at Assets/Xlua/Gen/UnityEngineMonoBehaviourWrap.cs:257)
XLua.LuaDLL.Lua:lua_pcall(IntPtr, Int32, Int32, Int32)
XLua.DelegateBridge:PCall(IntPtr, Int32, Int32, Int32) (at Assets/Xlua/Src/DelegateBridge.cs:138)
XLua.DelegateBridge:__Gen_Delegate_Imp4() (at Assets/Xlua/Gen/DelegatesGensBridge.cs:122)
LuaMgr:Tick(Single) (at Assets/Scripts/LuaMgr.cs:102)  <-- 这行调用event: onUpdate，onUpdate只有一个delegate，是一个lua函数
Timi.SimpleMgrContainer:Update() (at Assets/Scripts/Core/SimpleMgrContainer.cs:195)

**Comment by chexiongsheng** [comment]
为什么不能调用到这里？

**Comment by Henry-T** [comment]
那必然是业务的lua脚本自己调用了StartCoroutine，对吗？

**Comment by chexiongsheng** [comment]
当然了

**Comment by Henry-T** [comment]
确实业务脚本误调了，多谢哈！
