### ISSUE TITLE
HotfixInject调用时机问题

### ISSUE THREAD

**Issue by CodeMasterYi** [Tencent/xLua#526]
对于同时需要修改Assembly的两个插件XLua和Obfuscator（rename symbols, add fake code ...），XLua的HotfixInject的调用时机应该怎么处理？

**Comment by CodeMasterYi** [comment]
我将HotfixInject的执行时机改成[PostProcessScene(1)]

**Comment by CodeMasterYi** [comment]
![step1](https://user-images.githubusercontent.com/10430162/51242867-092cfc80-19bc-11e9-8bc9-75cbdf9cbb5c.png)

**Comment by CodeMasterYi** [comment]
![step2](https://user-images.githubusercontent.com/10430162/51242881-10eca100-19bc-11e9-8aed-c5ae54a1ced7.png)

**Comment by chexiongsheng** [comment]
建议修改下注入那，搞个变量，让它注入一次就不注入。

**Comment by CodeMasterYi** [comment]
嗯，可以确定第一次调用是PostProcessScene所致，那第二次是谁启动的呢？

**Comment by CodeMasterYi** [comment]
不管怎样，你说的方法防止了第二次第三次注入~

**Comment by chexiongsheng** [comment]
多个场景就有多次，只不过注入后代码有标志类型防止重复注入。
这个标志类型被混淆器改名了就失效了
