### ISSUE TITLE
gc crash

### ISSUE THREAD

**Issue by yangguosdxl** [Tencent/xLua#530]
Xlua版本：2.1.12
Unity3D版本：2017.4.14f1
手机型号：MI 6
系统：Android OS 8.0.0 / API-26

E:\home\work\m3mobile2\misc\deps\xLua-2.1.12\build/xlua.c:359                                                                                         E:\home\work\m3mobile2\misc\deps\xLua-2.1.12\build\lua-5.3.4\src/lapi.c:1189 (discriminator 1)                                                        E:\home\work\m3mobile2\misc\deps\xLua-2.1.12\build\lua-5.3.4\src/lgc.c:1137                                                                           E:\home\work\m3mobile2\misc\deps\xLua-2.1.12\build\lua-5.3.4\src/lgc.c:1057                                                                           E:\home\work\m3mobile2\misc\deps\xLua-2.1.12\build\lua-5.3.4\src/lgc.c:568                                                                            E:\home\work\m3mobile2\misc\deps\xLua-2.1.12\build\lua-5.3.4\src/lgc.c:468                                                                            E:\home\work\m3mobile2\misc\deps\xLua-2.1.12\build\lua-5.3.4\src/lgc.c:444 (discriminator 1)
--

**Comment by chexiongsheng** [comment]
lua5.3.4 gc有几个bug，看官网：https://www.lua.org/bugs.html

你先试试升级到xlua 2.1.13版本，这个版本把lua升级到5.3.5了。

**Comment by chexiongsheng** [comment]
怎么样，问题解决了么？
