### ISSUE TITLE
Support .Net 4.0 scripting runtime.

### ISSUE THREAD

**Issue by xpol** [Tencent/xLua#532]
See post [here](https://forum.unity.com/threads/net-3-5-runtime-has-been-deprecated-in-unity-2018-3.601384/).

.Net 3.5 scripting runtime has been deprecated in Unity 2018.3 and will removed in 2019.x.
And the new scripting runtime is .Net 4.x.

Will xLua consider any support for  .Net 4.x or any migration guide? 

Like #480

**Comment by chexiongsheng** [comment]
faq：https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/faq.md#unity-2018%E5%85%BC%E5%AE%B9%E6%80%A7%E9%97%AE%E9%A2%98%E8%A7%A3%E5%86%B3

**Comment by chexiongsheng** [comment]
update to xlua v2.1.14
