### ISSUE TITLE
'Input' does not contain a definition for 'IsJoystickPreconfigured'

### ISSUE THREAD

**Issue by iningwei** [Tencent/xLua#534]
环境：unity2018.3.0f2
打包exe的时候报错，如题。

这里找到一个类似的Light类的报错。https://github.com/Tencent/xLua/issues/237
按照上述链接中的提示，在黑名单中加入了：
new List<string>(){"UnityEngine.Input", "IsJoystickPreconfigured" },
打包EXE的时候依旧报错。
请教一下，该怎么处理。还有造成这个错误的原因是什么呢？

**Comment by chexiongsheng** [comment]
你黑名单配错了

**Comment by iningwei** [comment]
谢谢，已解决。
对于带参数的方法，还需要把参数全路径传入。

**Comment by Rockswell** [comment]
具体来说是这样写的
`new List<string>() { "UnityEngine.Input", "IsJoystickPreconfigured", "System.String" },`
因为 IsJoystickPreconfigured 有个类型是 string 的参数
