### ISSUE TITLE
windows下编译make_android_lua53.bat失败 

### ISSUE THREAD

**Issue by xiayu519** [Tencent/xLua#536]
环境 VS2017 AS下载的cmake3.10 ndk 13b 
报错CMake Error: Could not create named generator Android Gradle - Ninja

**Comment by xiayu519** [comment]
> 这个依赖的东西较多。
> 建议用make_android_lua53.sh在linux或者mac下编译

so我生成了 但是不能加HOTFIX_ENABLE 不加的话我可以安卓打包 但是加了的话会报错 如图
![image](https://user-images.githubusercontent.com/43023377/51673191-5cc8c700-2008-11e9-9488-021c45ed9b3e.png)
这个一般是什么原因

**Comment by chexiongsheng** [comment]
截屏栈不全

**Comment by sos263665629** [comment]
我在windows下也遇到同样问题，一直无法解决。
![9999](https://user-images.githubusercontent.com/35225578/52897168-5d6e0b00-320c-11e9-93bd-72fbc8600afd.png)

**Comment by xiayu519** [comment]
> 我在windows下也遇到同样问题，一直无法解决。
> ![9999](https://user-images.githubusercontent.com/35225578/52897168-5d6e0b00-320c-11e9-93bd-72fbc8600afd.png)

下载旧版的安卓屎丢丢 然后安装配套的cmake 新版的屎丢丢的cmake版本太高

**Comment by restuname** [comment]
ndk使用r10e可以编译
