### ISSUE TITLE
XLua on Hololens

### ISSUE THREAD

**Issue by dlannan** [Tencent/xLua#542]
I am getting many odd errors with XLua on HoloLens. The same script runs fine on all other tested platforms (5 types - Android Mobile, Vizux Blade, Moverio and PC and OSX).
The types of errors are:
When I use 
```
CS.UnityEngine.GUI.Button( CS.UnityEngine.Rect(10, 10, 100, 100), "Test"); I get
LuaException: invalid arguments to Button
```
Also methods like Rotate on a transform are referred to as missing.
And GetComponent( typeof(CS.UnityEngine.Light) ); throws exceptions about missing type.

Any help on these would be greatly appreciated. Has anyone successfully used XLua on the HoloLens?

**Comment by dlannan** [comment]
Ok. I found a solution. Turns out the IL2CPP compiler is optimising away these class types. 
I added "Dummy" declarations in the C# source and the problems were resolved. I managed to make a "addon junk" file that declares all the types I need and that ensures the scripts will run without issues.

**Comment by chexiongsheng** [comment]
Add type to LuaCallCSharp List，can avoid the problem cause by code stripping and make c# access faster。
How to config here: https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/Configure_EN.md
