### ISSUE TITLE
failed to gen code when use Unity.Addressables

### ISSUE THREAD

**Issue by xmxiaoq** [Tencent/xLua#546]
gen wrap file fail! err=TemplateCommon:200: attempt to index a nil value (field 'FullName')
stack traceback:
	TemplateCommon:200: in upvalue '_CsFullTypeName'
	TemplateCommon:213: in function 'CsFullTypeName'
	[string "luatemplate"]:40: in local 'callback'
	TemplateCommon:145: in function 'ForEachCsList'
	[string "luatemplate"]:24: in local 'callback'
	TemplateCommon:145: in function 'ForEachCsList'
	[string "luatemplate"]:8: in main chunk, stack=  at XLua.LuaEnv.ThrowExceptionFromError (System.Int32 oldTop) [0x00057] in D:\clientNew\Assets\XLua\Src\LuaEnv.cs:443 
  at XLua.LuaFunction.Call (System.Object[] args, System.Type[] returnTypes) [0x000aa] in D:\clientNew\Assets\XLua\Src\LuaFunction.cs:168 
  at XLua.LuaFunction.Call (System.Object[] args) [0x00001] in D:\clientNew\Assets\XLua\Src\LuaFunction.cs:183 
  at XLua.TemplateEngine.LuaTemplate.Execute (XLua.LuaFunction compiledTemplate, XLua.LuaTable parameters) [0x00009] in D:\clientNew\Assets\XLua\Src\TemplateEngine\TemplateEngine.cs:186 
  at CSObjectWrapEditor.Generator.GenOne (System.Type type, System.Action`2[T1,T2] type_info_getter, CSObjectWrapEditor.XLuaTemplate templateAsset, System.IO.StreamWriter textWriter) [0x00095] in D:\clientNew\Assets\XLua\Src\Editor\Generator.cs:595 
UnityEngine.Debug:LogError(Object)
CSObjectWrapEditor.Generator:GenOne(Type, Action`2, XLuaTemplate, StreamWriter) (at Assets/XLua/Src/Editor/Generator.cs:605)
CSObjectWrapEditor.Generator:GenDelegateBridge(IEnumerable`1, String, IEnumerable`1) (at Assets/XLua/Src/Editor/Generator.cs:932)
CSObjectWrapEditor.Generator:GenDelegateBridges(IEnumerable`1) (at Assets/XLua/Src/Editor/Generator.cs:1051)
CSObjectWrapEditor.Generator:GenAll() (at Assets/XLua/Src/Editor/Generator.cs:1633)

**Comment by chexiongsheng** [comment]
unity version？

**Comment by xmxiaoq** [comment]
Unity 2018.3.6f1 (64-bit)

**Comment by xmxiaoq** [comment]
> unity version？

Unity 2018.3.6f1 (64-bit)

**Comment by chexiongsheng** [comment]
我的是2018.3.5，没这个类

**Comment by xmxiaoq** [comment]
> UnityEngine.AddressableAssets.Addressables?
> I add this to LuaCallCSharp, and gen code, no error.

this assembly: Unity.Addressables.dll

**Comment by chexiongsheng** [comment]
you mean gen code for all types in assembly: Unity.Addressables.dll？

**Comment by ayang008** [comment]
I encountered the same issue on Unity 2018.3.13f. I'm not using Addressables. I just uncommented the pure Lua part in the ExampleConfig.cs and then generate code.

**Comment by chexiongsheng** [comment]
i can not re-product in Unity 2018.3.10f by doing the same thing: uncommented the pure Lua part in the ExampleConfig.cs and then generate code

**Comment by ayang008** [comment]
I am sorry for the faulty information. The error comes from the Google.Protobuf I included in my project. I filtered the namespace in the ExampleConfig.cs and the error is gone.
