### ISSUE TITLE
关于xlua框架的设计

### ISSUE THREAD

**Issue by xiayu519** [Tencent/xLua#547]
两个问题 如果是月经贴望见谅
1、官方推荐是一个lua入口运行整个lua框架  比如dostring一个main.lua然后初始化各个lua模块 是整个游戏都只dostring这一个lua脚本的意思么还是我理解的错误了 我看有的人是每个场景甚至预制体都会加上一个LuaBehavior 然后dostring对应的lua脚本  这两种做法作者推荐哪一种 或者觉得哪些适合第一种做法哪些适合第二种做法 需要注意哪些问题

2、在xlua里面require全局的lua脚本该怎么释放 比如require("Util") 我想让整个工具表全局都可以使用  如果require过多的这样的全局表会对性能产生影响么 该怎么释放它

**Comment by chexiongsheng** [comment]
require是lua自带的api，所以这问题类似问某个c#系统api的使用
因为不希望这变成个lua/C#语法、系统api学习园地，所以这类问题我知道也不会答，建议查阅官方文档，专门的学习论坛等。
我在C#封装了个DoString，lua也是有对应的系统api，我只是封装给C#使用而已，表现一样，lua官方相关描述也适用。

**Comment by xiayu519** [comment]
> require是lua自带的api，所以这问题类似问某个c#系统api的使用
> 因为不希望这变成个lua/C#语法、系统api学习园地，所以这类问题我知道也不会答，建议查阅官方文档，专门的学习论坛等。
> 我在C#封装了个DoString，lua也是有对应的系统api，我只是封装给C#使用而已，表现一样，lua官方相关描述也适用。

好的 感谢回答
