### ISSUE TITLE
如何获得Luatable的name？

### ISSUE THREAD

**Issue by sericaer** [Tencent/xLua#548]
lua脚本如下：
    next=
    {
      process = function(self)
        return native.event.test
      end
    }
其中 native.event.test是另一个lua table，现在C#代码中已经能够通过delegate获取到process 这个function，执行此function获取到结果是Luatable对象，但是如何获取这个对象的名字字符串“native.event.test”？

**Comment by chexiongsheng** [comment]
native.event.test只是表示这东西存在native.event（一个table）的test字段上，不是是这table的名字

**Comment by sericaer** [comment]
多谢！
那已经获取到了 Luatable对象 如何获取到其对应的字段“native.event.test” ?

**Comment by chexiongsheng** [comment]
不能，这没啥关系。lua table就一个hash表。
就像你把一个GameObject放到Dictionary<string, GameObject>里，你拿到这个GameObject，并不能得到它放在什么Dictionary的什么key下。
