### ISSUE TITLE
[GCOptimize(OptimizeFlag.PackAsTable)]对Unity内置结构体无法生成代码

### ISSUE THREAD

**Issue by jackson1991123** [Tencent/xLua#550]
我是修改的GenAttributes.cs中的标签，导致生成的WrapPusher中报错。
猜测是有[GCOptimize(OptimizeFlag.PackAsTable)]与AdditionalProperties有意料之外的冲突

**Comment by chexiongsheng** [comment]
这个commit修复了：https://github.com/Tencent/xLua/commit/9f6f0d455f7341bb9b1845d5dd4061b7d28cf8cd
