### ISSUE TITLE
对C#中重载的多个函数可以单独对其中某一个进行热补丁吗？

### ISSUE THREAD

**Issue by dave5177** [Tencent/xLua#551]
对C#中重载的多个函数可以单独对其中某一个进行热补丁吗？

**Comment by chexiongsheng** [comment]
可以，会麻烦些，都要依赖反编译信息
默认设置下你看下xlua.hotfix的实现：https://github.com/Tencent/xLua/blob/master/Assets/XLua/Src/LuaEnv.cs#L555
反编译找到那重载排第几位，然后设置对应的字段
如果你用的IntKey的注入方式，也要反编译，找到特定重载分配的id，然后通过CS.XLua.HotfixDelegateBridge.Set来补丁

**Comment by dave5177** [comment]
厉害了，有点复杂，我最终还是选择了通用的方法，在lua的函数体里做判断把多个重载的逻辑都实现一般。感谢。
