### ISSUE TITLE
Hotfix inject 自己封装的dll时，Error:can not find delegate for xxx! try re-genertate code.

### ISSUE THREAD

**Issue by ChampionGuan** [Tencent/xLua#552]
查看文档看到是支持其他dll进行代码注入的，但我在尝试注入时，出现了上述异常，注入失败

1、当我把dll中的代码全部移入工程内，dll删除，可以注入成功
2、当我把dll中带有返回值（返回值为引擎组件）的方法删除，dll可以注入成功

所以咨询下是否在dll中带有引擎组件返回值的方法，属性等，是无法注入的？还是我哪里设置出现了异常，感谢

**Comment by chexiongsheng** [comment]
最好能附带个能重现的最小工程

**Comment by chexiongsheng** [comment]
引擎组件具体是什么？
我在其它dll里加入如下方法，能成功注入：
```csharp
	public UnityEngine.Vector3 GetVector3(double a, float b, int c)
	{
		return new UnityEngine.Vector3(0, 9, 0);
	}
```

**Comment by ChampionGuan** [comment]
[Core.zip](https://github.com/Tencent/xLua/files/2981496/Core.zip)
unity version 2017.4.16f1 personal
xlua version v2.1.114
vs2017

**Comment by chexiongsheng** [comment]
??
Core.zip生成的dll你注入失败么？

**Comment by ChampionGuan** [comment]
> ??
> Core.zip生成的dll你注入失败么？

是的，注入失败，提示如下
Error:can not find delegate for Core.Class1.GetVector3! try re-genertate code.

**Comment by chexiongsheng** [comment]
我能成功

**Comment by ChampionGuan** [comment]
> 我能成功

能把你的unity工程贴给我参考吗？我按照文档来回操作了多遍，始终未成功，十分感谢

**Comment by chexiongsheng** [comment]
你试试用unity的自带的mono来编译dll
(build_unity_dll.bat)
```bat
@set UNITY_DIR="path to your unity"
@set GMCS="%UNITY_DIR%\Editor\Data\Mono\bin\gmcs"
@set DLL_OUTPUT="Assets\XLuaDllTest.dll"
call %GMCS% -define:UNITY_IPHONE -optimize+ -target:library -out:%DLL_OUTPUT% -r:"%UNITY_DIR%\Editor\Data\PlaybackEngines\AndroidPlayer\Variations\mono\Managed\UnityEngine.dll" XLuaDllTest.cs
pause
```

**Comment by ChampionGuan** [comment]
> ```batchfile
> gmcs
> ```

批处理的方式可以成功。

**Comment by chexiongsheng** [comment]
那就可能是注入工具不兼容微软编译出来的dll。
不过尽管没这问题，unity下最好用unity自带编译器编出来的东西。
