### ISSUE TITLE
Dispose时报错

### ISSUE THREAD

**Issue by Meteor0679** [Tencent/xLua#554]
![image](https://user-images.githubusercontent.com/5011202/53551773-f853d700-3b74-11e9-8de3-1a2af941c037.png)
最小测试样例如上
运行环境2018.3.5f1
.net4.x equivalent
api level :net4.x

**Comment by chexiongsheng** [comment]
引用检查是用C#的弱引用，弱引用尚未失效，就代表东西尚未释放。
释放策略是GC定的。栈上变量null后回不回收，由GC决定。
要么修改自己的程序规避，要么修改Unity源码，把回收策略给改了。
规范方式可以参考例子4

**Comment by Meteor0679** [comment]
![image](https://user-images.githubusercontent.com/5011202/53555336-b62e9380-3b7c-11e9-9f73-3da10229e3dd.png)
![image](https://user-images.githubusercontent.com/5011202/53555370-c8103680-3b7c-11e9-8249-57c98f361696.png)
参考了一下例子4得到这样的结果 带有Debug.Log(i)的才可以执行成功  所以必须要函数带一个不管是否有意义的返回值并且使用过这个返回值才能规避？awake的生命周期好奇怪。。先说这个返回值的问题吧

**Comment by Meteor0679** [comment]
例子4的规避方式还有个问题  因为calc_new是在Test中新建的 
相当于用之前先获取  似乎不太符合首页建议的一次绑定  重复使用。
如果把calc_new的定义拿到类中， Start获取， Test调用， 即使有返回值并且使用过返回值， 再把calc_new置空也无法清除引用。目前知道的规避办法是置空之后等一帧再调用Dispose。但是如果用在OnDestroy中  就没法这样做了
那么有什么娶她的规避办法吗？

**Comment by Winvz** [comment]
local util = require 'xlua.util'
util.print_func_ref_by_csharp()
调用faq的方法后，发现有好几个引用存在，怎么都去不掉，但是我在dispose前tick一下后，报错就变成时而有 时而无

**Comment by chexiongsheng** [comment]
1、并不一定需要Dispose，有很多有些不Dispose；
2、你选择Dispose，就清理干净，然后想办法迎合gc的回收规则。比如我估计你都释放后，延迟个几桢Dispose应该能规避。
