### ISSUE TITLE
XLua的Examples中代码可否加一下命名空间，否则容易和别库中的代码发生命名冲突

### ISSUE THREAD

**Issue by cocowolf** [Tencent/xLua#556]
XLua的Examples 中的代码可以加一下命名空间，要不然很容易和别的插件发生冲突。
比如：InvokeLua类中的 PropertyChangedEventArgs 和使用到System.ComponentModel.PropertyChangedEventArgs的类会冲突。

**Comment by chexiongsheng** [comment]
嗯
