### ISSUE TITLE
想编译PS4用的XLua版本，不用jit，有相应的步骤教程吗

### ISSUE THREAD

**Issue by XuTenTen** [Tencent/xLua#557]
你好，我想编译PS4用的XLua版本，不用jit，有相应的步骤教程吗

**Comment by chexiongsheng** [comment]
xlua用cmake编译，cmake的ps4编译网上一搜索一大把，比如这个：https://blog.madnation.net/ps4-cmake-toolchain/

**Comment by XuTenTen** [comment]
> xlua用cmake编译，cmake的ps4编译网上一搜索一大把，比如这个：https://blog.madnation.net/ps4-cmake-toolchain/

现在工程里的xlua.dll直接勾上PS4平台可以吗？还是一定要自己编译个专用的放进去，我这边不用luajit

**Comment by XuTenTen** [comment]
不好意思，可能我问的有点问题。我重新问一下
现在平时拉到的XLua工程里的xlua.dll是不是勾上PS4平台就可以直接打包到PS4平台了？

**Comment by chexiongsheng** [comment]
xlua.dll是window用的

**Comment by XuTenTen** [comment]
> xlua.dll是window用的

如果PS4平台想用XLua的话，一定要自己编译一个PS4专用的库放进工程吗

**Comment by chexiongsheng** [comment]
所有平台都是，包括window。
之所以window，android，ios这些你不用编译，是我把常用平台的编译了。
我发你的文章很简单，有功夫问都搞完了

**Comment by XuTenTen** [comment]
> 所有平台都是，包括window。
> 之所以window，android，ios这些你不用编译，是我把常用平台的编译了。
> 我发你的文章很简单，有功夫问都搞完了

好的，多谢啦
