### ISSUE TITLE
关于byte数组传值问题

### ISSUE THREAD

**Issue by zhangjinlong1234** [Tencent/xLua#558]
C#
private static void Client_OnReceive(int id, byte[] data, int nSize)
    {
        _packetProcesses[id].ReceiveDataAsync(data); //这句
        while (_packetProcesses[id].PacketCount > 0)
        {
            Packet packet = _packetProcesses[id].PacketQueue;
            CommandBase command = Static_SC_CommandList.GetClassByCommand(packet.Command);
            if (command != null)
            {
                command.Process(id, packet);
            }
        }
    }
Lua
xlua.hotfix(CS.GlobalNetworkManager,'Client_OnReceive', function(id,data,nSize)
	GlobalNetworkManager._packetProcesses[id]:ReceiveDataAsync(data) --这句
	while _packetProcesses[id].PacketCount > 0  do
		local packet = _packetProcesses[id].PacketQueue
		local command = Static_SC_CommandList.GetClassByCommand(packet.Command)
		if command ~= nil then 
			command:Process(id,packet)
		end
	end
end)
这边字节数组一传入lua函数就变成string了，字节数组再函数中原封不动的被传递给了另一个函数，想要不在改动C#函数的前提下完成。
尝试使用了 class BytesRef : RawObject 这种方式，但是因为字节数组从C#传入Lua函数马上就变成了string，所以这种方式好像没效果。

**Comment by chexiongsheng** [comment]
假如ReceiveDataAsync只是想读取Client_OnReceive调用者的传入的数据（data）是没啥问题的。
但如果ReceiveDataAsync想修改data里头的数据，传给Client_OnReceive调用方就不行了。
对于后者，我考虑下以后要怎么支持。
