### ISSUE TITLE
2018.3.5f1 打开ExampleConfig中所有的注释项，生成代码Delegate出错

### ISSUE THREAD

**Issue by yinghuizhou** [Tencent/xLua#559]
....
if (type == typeof(System.Func<T>))
			{
			    return new System.Func<T>(__Gen_Delegate_Imp63);
			}
....
		public T __Gen_Delegate_Imp63()
		{
#if THREAD_SAFE || HOTFIX_ENABLE
            lock (luaEnv.luaEnvLock)
            {
#endif
                RealStatePtr L = luaEnv.rawL;
                int errFunc = LuaAPI.pcall_prepare(L, errorFuncRef, luaReference);
                ObjectTranslator translator = luaEnv.translator;
                
                PCall(L, 0, 1, errFunc);
                
                
                T __gen_ret = (T)translator.GetObject(L, errFunc + 1, typeof(T));
                LuaAPI.lua_settop(L, errFunc - 1);
                return  __gen_ret;
#if THREAD_SAFE || HOTFIX_ENABLE
            }
#endif
		}

**Comment by chexiongsheng** [comment]
是哪个版本的xlua？

**Comment by yinghuizhou** [comment]
xLua LIB_VERSION 是105, 导出脚本和模板都是最新的！

**Comment by chexiongsheng** [comment]
105是plugin的版本，这个N年没动了。
你那几个扩展和上面错误对不上。

**Comment by yinghuizhou** [comment]
不好意思，第一个IsNull是我的锅，是跟UnityEngine.Animations.AnimationClipPlayable [PlayableExtensions] 中的IsNull重名了，导致错误！   
    [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
        static int _m_IsNull(RealStatePtr L)
        {
		    try {
            
                ObjectTranslator translator = ObjectTranslatorPool.Instance.Find(L);
                UnityEngine.Animations.AnimationClipPlayable gen_to_be_invoked;translator.Get(L, 1, out gen_to_be_invoked);
                {
                    
                        bool gen_ret = gen_to_be_invoked.IsNull(  );
                        LuaAPI.lua_pushboolean(L, gen_ret);  
                        translator.Update(L, 1, gen_to_be_invoked);
                    return 1;
                }
                
            } catch(System.Exception gen_e) {
                return LuaAPI.luaL_error(L, "c# exception:" + gen_e);
            }            
        }
第二个错误我是把这个扩展注释掉，就没有下面的代码生成，我是猜测是这个扩展导致的问题！！
		public T __Gen_Delegate_Imp63()
		{
#if THREAD_SAFE || HOTFIX_ENABLE
            lock (luaEnv.luaEnvLock)
            {
#endif
                RealStatePtr L = luaEnv.rawL;
                int errFunc = LuaAPI.pcall_prepare(L, errorFuncRef, luaReference);
                ObjectTranslator translator = luaEnv.translator;
                
                PCall(L, 0, 1, errFunc);
                
                
                T __gen_ret = (T)translator.GetObject(L, errFunc + 1, typeof(T));
                LuaAPI.lua_settop(L, errFunc - 1);
                return  __gen_ret;
#if THREAD_SAFE || HOTFIX_ENABLE
            }
#endif
		}

**Comment by chexiongsheng** [comment]
也就是加上
~~~csharp
public static T InvokeGracefully(this Func < T > selfFunc)
{
return null != selfFunc ? selfFunc() : default(T);
}
~~~
然后打开ExampleConfig中所有的注释项，就会生成如下代码？
~~~csharp
public T __Gen_Delegate_Imp63()
{
。。。
}
~~~
