### ISSUE TITLE
关于Hotfix属性标签

### ISSUE THREAD

**Issue by cjsworld** [Tencent/xLua#56]
在实际项目接入过程中，对于我们这个已经上线的项目来讲，为了引进热更代码功能，需要在所有所需的类打上标签，数量太多了。。虽然可以写Editor脚本处理，但是我选择了直接改Hotfix中筛选类的代码，放弃了判断Hotfix标签，而采用了判断类的命名空间的做法（我们项目中的业务代码都有命名空间），并修复了一些随之而来的小问题。
建议的话，在判断是否要Hotfix的时候，在原有判断Hotfix的基础上，加一个命名空间白名单的功能，指定命名空间下的类都处理掉。

**Comment by cjsworld** [comment]
如果你同意的话，我可以把我改过的发个pull request给你。。

**Comment by chexiongsheng** [comment]
不少人反馈过，你的白名单配置方法是怎样的？和xlua原有配置风格一致？

**Comment by cjsworld** [comment]
额。。接触xlua时间不长，原有配置在哪。。？

白名单这块儿我目前只是简单实现，因为项目赶着打包更新上传。类似于这样的
public static bool NeedHotfix(string typeNamespace) {
    if (string.IsNullOrEmpty(typeNamespace)) {
        return false;
    } else {
        return typeNamespace.StartsWith("Game") || typeNamespace.StartsWith("UI");
    }
}
至于这样匹配的后果。。会把一些声明的代理类也尝试处理，然后会遇到method.Body是null的情况，过滤掉就好了。
if (method.Body == null) {
    return true;
}
还有，不知为何，生成代理wrap的时候，有些参数名取不出来，造成生成的代码文件无法编译。可能是Action<int, bool>这种情况？所以生成模板我也稍微改了下，参数名取不到就用a+参数序号代替。

还有遇到一个问题，业务代码里写了个名为Item的属性，但是this[]这种的生成的属性名也是Item吧。所以这里也出错了。。我也改过了。

还有改了啥来着，记不太清了。。

**Comment by cjsworld** [comment]
还有，我这边实现了个LuaComponent，用Lua脚本做MonoBehaviour，关键是实现脚本数值序列化。。有没有兴趣？

**Comment by mydodolookdo** [comment]
希望xlua出一个Hotfix白名单功能

**Comment by chexiongsheng** [comment]
@mydodolookdo   现在的Hotfix标签就是白名单呀。你指的是批量的吧？类似 @cjsworld 说的namespace的？

**Comment by mydodolookdo** [comment]
我指的是批量。不一定非要namespace，类似于以下这样也可以。这样以后只修改一个文件就可以了。
[LuaCallCSharp]
    public static List<Type> mymodule_lua_call_cs_list = new List<Type>()
    {
        typeof(GameObject),
        typeof(Dictionary<string, int>),
        typeof(Debug),
    };

**Comment by chexiongsheng** [comment]
打标签确实不是十分好的方式。我考虑下以什么形式好。

**Comment by chexiongsheng** [comment]
还有，不知为何，生成代理wrap的时候，有些参数名取不出来，造成生成的代码文件无法编译。可能是Action<int, bool>这种情况？所以生成模板我也稍微改了下，参数名取不到就用a+参数序号代替。

这有具体的例子么？

**Comment by wodedabao** [comment]
File->Build Setting->Scripting Define Symbols在添加宏的时候，为什么我点击player设置无响应啊？大神快救救我

在 2017-01-11 13:21:09，"cjsworld" <notifications@github.com> 写道：


在实际项目接入过程中，对于我们这个已经上线的项目来讲，为了引进热更代码功能，需要在所有所需的类打上标签，数量太多了。。虽然可以写Editor脚本处理，但是我选择了直接改Hotfix中筛选类的代码，放弃了判断Hotfix标签，而采用了判断类的命名空间的做法（我们项目中的业务代码都有命名空间），并修复了一些随之而来的小问题。
建议的话，在判断是否要Hotfix的时候，在原有判断Hotfix的基础上，加一个命名空间白名单的功能，指定命名空间下的类都处理掉。

**Comment by chexiongsheng** [comment]
有报错或者warning么？

**Comment by wodedabao** [comment]
已经弄好了，谢谢

在 2017-01-13 11:16:48，"chexiongsheng" <notifications@github.com> 写道：


有报错或者warning么？

**Comment by chexiongsheng** [comment]
@cjsworld 什么情况下参数名会为空呢？像Action<xx, xx>参数名也是有的。

**Comment by cjsworld** [comment]
调试了一下，发现貌似是内嵌的lambda表达式。。
Void <OnCharacterSpawn>m__268(System.Type, Game.CharacterCom)
我已经把改过的代码模板发pull request给你了

**Comment by chexiongsheng** [comment]
@cjsworld 你这namspace白名单太大了。。lambda最好不用注入，有点浪费空间。要修复也是修复其包含这lambda的函数。
不反编译你也不知道编辑器生成的匿名类，匿名函数的名字是啥。

**Comment by chexiongsheng** [comment]
@cjsworld 还有method.Body为空的情况，除了抽象方法和pinvoke，还有别的么？是不是interface之类的方法？估计也是对namespace白名单的导致的。Hotfix attribute现在只能加到class和struct上面。

**Comment by cjsworld** [comment]
如何过滤lambda表达式呢？我没有继续深入下去研究了。。
话说，注入lambda表达式对于我们的项目也有好处的啊，因为我们项目中大量使用lambda表达式做回调，例如服务器请求回调，事件回调等等。。如果出现bug，单独改lambda也省事的。。

**Comment by cjsworld** [comment]
Body为空，当时具体遇到什么也没有细究，反正调试发现Body为空，大概是没有方法体，这种情况肯定注入不了，索性直接return  -_-||

**Comment by cjsworld** [comment]
白名单的话，我这边图省事，用的命名空间。。因为我们项目做了1年半。。里面类多到无法统计。。然后项目上线近1年期间，饱受代码bug无法热更的痛苦。当时用的uLua，代码中各种留事件接口，可以在lua中注册时间，插入原本的代码流程。。如果bug出现在事件系统无法插足的地方，就尝试用LuaComponent暴力update检测。。但仍然遇到修不了的问题。前一阵都在想能否通过改虚函数表实现替换函数。。
所以了解到这个xLua的代码注入后，异常兴奋，花了2天时间将xLua接入，试了下代码注入。但是已有类实在太多，无论是Hotfix标签，还是类的List，配置都很麻烦，所以想到用命名空间。我觉得可以在前面2种的基础上，保留这种配置方式，方便跟我们同样情况的项目。。感谢~

**Comment by chexiongsheng** [comment]
我肯定会为项目方便而考虑的。
只是公共组件的特性都是能放不能收的，xLua之前就吃过这类亏，一个小众东西放出去，别人已经用了，就没法删了，这样会越来越臃肿。
开源的话，这方面要更谨慎些，并不是不重视你们的想法，希望理解。
大众需求会做进xlua，小众需求会通过提供扩展的方式支持。

**Comment by kwx** [comment]
弱弱的问一下, Hotfix 标签会弄成像 LuaCallCSharp 标签那样可以在一个 List 中配置吗?或者是有其它更好的办法了 :)

**Comment by chexiongsheng** [comment]
@kwx 这几天会提供更便利的方式

**Comment by iMemento** [comment]
请问hotfix的lua脚本一般用什么方式加密啊？

**Comment by chexiongsheng** [comment]
@iMemento 这得你们想办法加密，tx有另外的插件做这事情，但没有对外。
ps一下，你android下要是没用il2cpp的话，il代码的反编译后跟源码差不多，也同样面临加密的问题。

**Comment by chexiongsheng** [comment]
@cjsworld Hotfix标签如果支持程度和LuaCallCSharp这些一样的话，是能实现你的namespace白名单的。
LuaCallCSharp标签支持打到一个property上，然后property的get实现你可以做任何东西，包括你现在的根据namespace做白名单。

**Comment by xiaobin83** [comment]
有关重载，可以做一个评分resolve的方法，然后用mangle后的名字绑定method到cache里面. 第二次调用避免再次resolve. 在我的实现中，对直接匹配的参数评10分，可转换的参数评5分. params直接匹配的评9分. 可转换的评5分. 这样来决定使用哪个重载. 

对于lua component，我的实现中是dump整个初始化函数. 反序列化的时候用这个函数替换原来的反序列化函数. 然后在awake之前调用.

**Comment by chexiongsheng** [comment]
@xiaobin83 重载那不太明白，第二次调用可能是希望调用另外一个重载了。

**Comment by xiaobin83** [comment]
@chexiongsheng 重载是根据参数类型来决定，所以我觉得绑定一次就应该是一直绑定。 否则就应该是一个二义性错误。

**Comment by chexiongsheng** [comment]
@cjsworld 我已经做了配置的增强，你可以用增强功能实现白名单了。
https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/hotfix.md
ps一下，新增了QQ群（612705778），诚邀你这高手进群
