### ISSUE TITLE
Unity2018.3.4导入master最新代码报错

### ISSUE THREAD

**Issue by lisiliang** [Tencent/xLua#560]
Assets\XLua\Gen\WrapPusher.cs(977,65): error CS0234: The type or namespace name 'DrivenClass' does not exist in the namespace 'Tutorial' (are you missing an assembly reference?)
我看了一下是
提交： 900fbd88a7efe739d15141b0a583218afface8c5 [900fbd8]
父级： 904ede0370
作者： johnche(车雄生) <johnche@tencent.com>
日期： 2018年10月29日 星期一 10:39:56
提交者： johnche(车雄生)
修正教程例子拼写错误 fix https://github.com/Tencent/xLua/issues/457
这次提交把DrivenClass改成了DerivedClass，但是相应用到的地方并没有改过来，或者改过来后没有提交。

**Comment by chexiongsheng** [comment]
都提交了
估计是你的生成代码的问题
生成代码不会提交
你平时也不应该生成代码（首页开篇就这么介绍）。
手动删Gen目录就可以了。。

**Comment by lisiliang** [comment]
好的，谢谢大佬指教！
