### ISSUE TITLE
映射到interface实例，by ref，这个要求interface加到生成列表，否则会返回null，建议用法

### ISSUE THREAD

**Issue by LiangAiYing** [Tencent/xLua#561]
我在看示例的时候这个报错了，加到生成列表是什么意思！
报错的是时候是显示InvalidCastException: This type must add to CSharpCallLua: XXX（数据类型）
: XXX（数据类型）有添加标签CSharpCallLua 还是错 lua正常运行

**Comment by chexiongsheng** [comment]
看faq
