### ISSUE TITLE
webgl中请求图片

### ISSUE THREAD

**Issue by demon04551** [Tencent/xLua#564]
local mat = CS.UnityEngine.Object.Instantiate(CS.UnityEngine.Resources.Load("Sphere")):GetComponent(typeof(CS.UnityEngine.MeshRenderer))

local cs_coroutine = (require 'cs_coroutine')

local a = cs_coroutine.start(function()
    print('coroutine a started')

    coroutine.yield(CS.UnityEngine.WaitForSeconds(1))

    local url = "http://localhost:5000/7.jpg"

    local w = CS.UnityEngine.WWW(url)
    coroutine.yield(w)
    mat.material.mainTexture = w.texture

    print('coroutine a end')

end)

这个请求图片，报错LuaException: xlua/util.lua:45: cannot set mainTexture, no such field。
我觉得可能是webgl是单线程的问题，这个怎么下载图片呢？

**Comment by chexiongsheng** [comment]
webgl会做代码剪裁，看faq里有解决方案。

**Comment by demon04551** [comment]
> webgl会做代码剪裁，看faq里有解决方案。

是HOTFIX_ENABLE这个吗

**Comment by chexiongsheng** [comment]
打开faq，查找“代码剪裁”
