### ISSUE TITLE
还是关于 LuaException: c# exception:System.NullReferenceException: at XLua.CSObjectWrap.UnityEngineComponentWrap._g_get_transform (IntPtr L) [0x00000] in的报错

### ISSUE THREAD

**Issue by donnki** [Tencent/xLua#565]
跟这个问题是一样的，https://github.com/Tencent/xLua/issues/431

但我测试过，如果某个地方调用了UnityEngine.Object.Destroy销毁了这个对象，报错应该是c# exception:UnityEngine.MissingReferenceException: The object of type 'XXXX' has been destroyed but you are still trying to access it. 而不是 LuaException: c# exception:System.NullReferenceException: at XLua.CSObjectWrap.UnityEngineComponentWrap._g_get_transform (IntPtr L) [0x00000] 

请问这个报错的大概原因究竟是什么？我刻意想去重现，直接Destroy对象时报MissingReferenceException错，如果置空则LUA报空，始终无法重现这个报错。。而在游戏中偶尔就会出现这个报错导致一些异常情况，一直没查到原因

**Comment by chexiongsheng** [comment]
LuaEnv.Tick有个清理无用对象过程，UnityEngine.Object.Destroy后，如果被清理前调用就是MissingReferenceException，清理后调用就是NullReferenceException。

抛哪个不重要，根据栈找到那地方，加上faq的空判断即可。

**Comment by donnki** [comment]
了解~ 谢谢
判空有处理并且用容错的方式解决了，但一直没定位到哪里删除的，原本想通过这个异常来定位，看来还是不行，得想别的办法了
