### ISSUE TITLE
有计划支持 微软 UWP ARM 64么，

### ISSUE THREAD

**Issue by nethz** [Tencent/xLua#569]
我们是开发HoloLens 应用（UWP X86）的团队，之前引入xlua作为脚本。但是目前HoloLens2使用了ARM64的UWP，也只有最新的Uniyt3D 2019 bate版本才能支持，请问xLua有计划支持 UWP ARM64么，或者问下如果我想做这个平台如何入手呢（需要如何编译相应的库？）

**Comment by chexiongsheng** [comment]
1、xlua库用cmake编译的，当cmake支持了uwp arm64，自然就支持了；
2、我搜索了下uwp的的vc工程是可以通过修改设置改成输出arm64的，运行make_uwp.bat会生成三个uwp vc工程，x86，x64和arm，你选一个按网上教程改下试试？不过我自己试不成功，暂时没时间研究。
3、xlua库（lua53版本）就一些c文件而已，微软的uwp支持肯定会有c语言的支持，把这些c文件编译成arm64版本的就可以了

**Comment by FreakTheMighty** [comment]
Just want to add a plus one to this. We have a similar interest in trying this out on the HL.

**Comment by chexiongsheng** [comment]
> Just want to add a plus one to this. We have a similar interest in trying this out on the HL.

I had compiled xlua.dll for uwp arm64, but not test yet.
https://github.com/Tencent/xLua/commit/1ed9643f79c9d0c0ca98f8ddf4559404d6d89f7a

**Comment by FreakTheMighty** [comment]
Thanks @chexiongsheng ! Looking forward to testing, I'll report back when I do.

**Comment by FreakTheMighty** [comment]
@chexiongsheng that dll seems to work fine. I haven’t don’t extensive testing, but I was able to build and execute some simple scripts.
