### ISSUE TITLE
UnityEngine.Object == null 和 object == null 需要分别判断

### ISSUE THREAD

**Issue by tianye910208** [Tencent/xLua#57]
UnityEngine.Object == null 是运算符重载 
go = new GameObject()
GameObject.Destroy(go)

go == null  -> True
(object)go == null -> False

当在Lua中调用类似 GetComponent 的接口时，如果组件不存在,会得到一个 (null:0) 的UnityEngine.Object而不是nil，在Lua中无法判断

XLua中的PushXXX接口 没有对UnityEngine.Object做重载，o==null接口判断无效
public void Push(RealStatePtr L, object o)
 {
            if (o == null)
            {
                LuaAPI.lua_pushnil(L);
                return;
            }
...
}

**Comment by chexiongsheng** [comment]
xlua的设计是尽量不要和UnityEngine有太多耦合，因为后续xlua会考虑在UnityEngine之外的环境使用。
特别是UnityEngine.Object重载==的那种奇怪规则。
你要在lua里头判断，你可以这么来：
1、UnityEngine.Object添加到LuaCallCSharp；
2、为UnityEngine.Object写一个扩展方法，加到LuaCallCSharp；
public static bool IsNull(this UnityEngine.Object self)
{
    return self == null;
}
3、lua里头不要用obj == nil来判断，而是用那个扩展方法obj:IsNull()

**Comment by tianye910208** [comment]
好吧 用起来麻烦一些，如果是普通的Object类，lua里可能得到nil，需要不同的方法判断。
而且这个可能没有报错，只是逻辑上出现问题，迁移现有项目比较困难

我尝试在外围添加重载
public partial class ObjectTranslator
    {
        public void Push(RealStatePtr L, UnityEngine.Object o)
        {
            if (o == null)
            {
                LuaAPI.lua_pushnil(L);
            }
            else
            {
                Push(L, (object)o);
            }
        }

        public void PushObject(RealStatePtr L, UnityEngine.Object o, int type_id)
        {
            if (o == null)
            {
                LuaAPI.lua_pushnil(L);
            }
            else
            {
                PushObject(L, (object)o, type_id);
            }
        }
         
    }
还有一个PushAny的接口，添加之后会报AmbiguousMatchException: Ambiguous matching in method resolution

**Comment by chexiongsheng** [comment]
不要用重载，会有比较多的问题。xlua是通过在生成代码那生成不同的函数名，调用也生成不同的调用来替代重载的。
重载会有比较大的缺陷，某类有implicit声明会出现一些问题，比如一个类声明implicit转换到int，这时这个类push进去后就是一个int。
或者有一个类可以同时适用两个重载的话，就会出现Ambiguous match。

好几个版本前xlua是用重载的，早改掉了。

**Comment by chexiongsheng** [comment]
还是用扩展方法吧，这样也不用分开处理
 if obj == nil or obj:IsNull() then
end
或者在lua那再封装一个

function IsNull(obj) return obj == nil or  obj:IsNull() end

**Comment by tianye910208** [comment]
好，谢谢
