### ISSUE TITLE
Generate Code Error

### ISSUE THREAD

**Issue by TheWindRest** [Tencent/xLua#576]
在将UnityEngine.UI.Text加上[LuaCallCSharp]属性生成代码后，使用AssetBundleBrowser这个插件打包时会报以下错误：Assets/XLua/Gen/UnityEngineUITextWrap.cs(251,39): error CS1061: Type `UnityEngine.UI.Text' does not contain a definition for `OnRebuildRequested' and no extension method `OnRebuildRequested' of type `UnityEngine.UI.Text' could be found. Are you missing an assembly reference?
    请问是什么原因呢

**Comment by chexiongsheng** [comment]
用黑名单排除，看faq相关条目
