### ISSUE TITLE
Mac编译安卓失败

### ISSUE THREAD

**Issue by jerry-zeng** [Tencent/xLua#578]
用的最新的master版本，iOS和osx都可以编译通过，但是编译安卓版本的时候，报错：
.../XLua/build/extlibs/lsocket/gai_async.c:137:13: warning: implicit
      declaration of function 'pthread_cancel' is invalid in C99 [-Wimplicit-function-declaration]
                int err = pthread_cancel(rq->worker);

.../XLua/build/extlibs/lsocket/gai_async.c:179:14: error: use of
      undeclared identifier 'PTHREAD_CANCELED'
                        if (rv == PTHREAD_CANCELED) {
1 warning and 1 error generated.

这个枚举应该是在<pthread.h>里面定义的，不知道为什么会没找到。
我要怎么操作？

**Comment by jerry-zeng** [comment]
mac版本是10.13.6

**Comment by jerry-zeng** [comment]
ndk是r10e版本

**Comment by chexiongsheng** [comment]
你不是该到lsocket那问下为啥android编译失败么？
