### ISSUE TITLE
StreamingAssets这个文件夹是做什么用呢？

### ISSUE THREAD

**Issue by LazyPlanet** [Tencent/xLua#58]
我看楼主的LUA代码都在这个里面写的，后面是都在这里进行lua文件搜索？

**Comment by chexiongsheng** [comment]
xlua本身是没代码在里头的。
StreamingAssets以前是支持，lua文件不用改txt后缀，但现在是不建议使用，在android下有性能问题。
那些lua代码你指的是测试用例吧？那是测试组写的，当时图方便放StreamingAssets，反正用来测试，就一直那么放了。

**Comment by LazyPlanet** [comment]
这样，多谢啦！我还在里面写代码。。。
