### ISSUE TITLE
Unity2018.3.11f1版本下,按照ExampleConfig中方法读取程序集出错.

### ISSUE THREAD

**Issue by xxxxxxxyyyyyyy** [Tencent/xLua#582]
按照exampleConfig中方法,读取AppDomain中的程序集,
![image](https://user-images.githubusercontent.com/12658570/56208182-11f8a180-6083-11e9-894b-712ab6472e16.png), 在GenerateCode的时候, 会出现如下报错:
![image](https://user-images.githubusercontent.com/12658570/56208223-30f73380-6083-11e9-87c7-972325c9abcc.png)
PS: 1. AppDomian读取时,会有
![image](https://user-images.githubusercontent.com/12658570/56208294-6439c280-6083-11e9-906b-376ac4531880.png) 如上报错, 经查是Microsoft.GenerateCode该程序集无法执行GetExportType方法.
 2. 在去除AppDomain读取后, 还是会有
![image](https://user-images.githubusercontent.com/12658570/56208386-9a774200-6083-11e9-9259-64de79b10d14.png).
3. 自己设置的CustomAssembly读取
![image](https://user-images.githubusercontent.com/12658570/56208460-c72b5980-6083-11e9-84e3-29110fbee4a6.png)
 , 没有出现问题.

**Comment by chexiongsheng** [comment]
有可能是你某个程序集是坏的，你试试去掉DOTween。

**Comment by xxxxxxxyyyyyyy** [comment]
按测试来看, 跟CustomAssemblys中设置的程序集是没关系的, 是UnityTypes中的程序集读取出现了问题

**Comment by chexiongsheng** [comment]
那你一个个的排除。可能是unity遗留了个不能在当前环境下用的程序集。
