### ISSUE TITLE
有没有办法强制给一些保护的成员函数，添加注入或生成绑定

### ISSUE THREAD

**Issue by FatDaffy** [Tencent/xLua#584]
1.有时候确实需要修补一些保护的成员函数，不然所有的函数都要写成公有的啦。
2.有时需要在lua中调用一些本对象或父类的保护成员函数，现在只能通过反射调用。

**Comment by chexiongsheng** [comment]
一直都支持私有函数的注入和修复。连例子都是修复私有函数。
反射用法和非反射是一样的，差别只是性能，修复场景下局部使用是够的。修复场景并不建议生成代码，甚至public也不建议，因为你不知道有那些函数要调用，意味着所有都要生成代码，会导致包体极大。

**Comment by FatDaffy** [comment]
感谢回答
