### ISSUE TITLE
try to dispose a LuaEnv with C# callback!

### ISSUE THREAD

**Issue by jerry-zeng** [Tencent/xLua#588]
当C#中还持有Lua那边的function时，调用LuaEnv.Dispose()会抛这个异常。

能否通过clear掉ObjectTranslator中的delegate_bridges来强行让LuaEnv.Dispose，然后new一个新的LuaEnv，达到重启的目的？其中bridge应该也要清理。至于资源和内存能不能释放，就是另一个问题了。

听起来很野蛮，代码里好多UI事件还有加载资源方法都有回调，各种delegate，还有少量System.Action。之前用Tolua时，C#和Lua function之间没有bridge，是建议参数填LuaFunction，而不是直接用delegate，这样就可以在回调之后调LuaFunction.Dispose()。现在xLua简化了这种操作，所以我们基本都是直接用的delegate。

我所知道的2个处理方法：
1.就是刚才说的，把回调参数改成LuaFunction，用完就Dispose，同时为了支持C#端的调用，重载一个正常delegate的方法。
2.是lua端的回调function放到一个全局表中生成一个唯一ID，向C#传参的时候只传这个ID，就没有引用问题，就像LuaBase中的luaReference。不过现在项目组的人，完全没有这个习惯，还是喜欢cocos中那种直接传function的习惯，因为cocos的lua模块自动处理了这个function和ID互转的过程。

我就是想问一下，有没有统一的方法，处理所有在lua端传过来的function回调？而且是在不改变使用习惯的情况下。

**Comment by chexiongsheng** [comment]
报错的原因不是delegate_bridges清理不了。相反，delegate_bridges是用来检查是否有c#仍然指向待释放的虚拟机里的某种资源。
就像咳嗽是感冒的一种表现，你把嘴巴和鼻子用万能胶水填起来并不能治疗感冒。
如果你连“clear掉ObjectTranslator中的delegate_bridges”这种方式都能，为什么不考虑别Dispose呢？

**Comment by jerry-zeng** [comment]
主要是想简化释放lua引用，严谨的做法还是哪里注册就哪里清除，类似的，lua端引用Unity的资源，UI销毁或者lua生命周期到的时候也要全部清掉引用。但是这工作非常分散，如果是我一个人写的代码，查找起来自然方便。组员写的东西，让他们自己改还不乐意。
清除delegate_bridges也不是我想出来的，就是因为对这种暴力做法有疑问，所以才来请教一下。
