### ISSUE TITLE
关于安卓上部分UnityEngine的方法和字段问题

### ISSUE THREAD

**Issue by Winvz** [Tencent/xLua#589]
两个问题
1：Instantiate(Object obj,Transform parent)这个方法在PC上使用没问题，在安卓上使用报错，Invalid argument，哪怕我指定去获取这个方法，在PC上打印没问题，安卓上为NIL
2：有些字段有问题，比如Camera的depth无法访问，在PC上又没问题

**Comment by chexiongsheng** [comment]
可能是被剪裁导致的，faq文档有处理方式

**Comment by Winvz** [comment]
我试试
