### ISSUE TITLE
添加HOTFIX_ENABLE之后包访问权限错误 `Mono.Cecil.MethodReference.ContainsGenericParameter' is inaccessible due to its protection leve

### ISSUE THREAD

**Issue by hong672850430** [Tencent/xLua#59]
Assets/XLua/Src/Editor/Hotfix.cs(170,72): error CS0122: `Mono.Cecil.MethodReference.ContainsGenericParameter' is inaccessible due to its protection level

Cecil也拷贝到Editor那个文件夹下面了，然后就直接包这个错误，Unity版本5.3.2f1

**Comment by chexiongsheng** [comment]
你这是下载的那个预览版吧？
请用最新的代码。

**Comment by hong672850430** [comment]
好的，我这个是下载的你们当天放出来的那个版本。我再现在个最新的试试
