### ISSUE TITLE
没有生成代码时，纯净的例子也会报 This type must add to CSharpCallLua: Tutorial.CSCallLua+ItfD

### ISSUE THREAD

**Issue by jackson1991123** [Tencent/xLua#592]
1.新下载的完整例子，没有Gen过代码
2.使用例子自带的Tutorial.CSCallLua 也会报告这个错误

**Comment by jackson1991123** [comment]
引擎版本Unity2018.3.14

**Comment by jackson1991123** [comment]
此问题在生成代码以后就没有了，目测是反射条件下有一些问题

**Comment by jackson1991123** [comment]
通过阅读代码发现，想要使用反射功能，必须设置Unity版本为 Net4.x。Api Compatibilty Level 设置为.Net 4.x即可解决

**Comment by chexiongsheng** [comment]
faq有说明的
