### ISSUE TITLE
关于xlua与tolua同时使用的解决方法

### ISSUE THREAD

**Issue by huiball** [Tencent/xLua#598]
项目使用tolua已经完成大部分功能，全部转xlua的工作量太大，目前只想使用hotfix功能，看了之前的issues和网上的一些资料，ios平台因为__Internal的问题xlua会跟tolua有命名空间的冲突，前面提到说修改一方luaDLL中导入的函数名。

是不是意思是假如我luaDLL中都导入了luaL_newstate这个lua原生的函数，我需要在一方库的c文件里新建一个其他函数x_luaL_newstate调用luaL_newstate，然后导入函数修改为x_luaL_newstate，这样把冲突函数全部修改一遍理论上就可以了？

另外lua本身的虚拟机特性，是不是我同时运行tolua和xlua的话，其实tolua逻辑脚本是在tolua虚拟机里，xlua的热更逻辑跑在xlua开辟的虚拟机里，天生是隔离的所以不需要太关心他们之前的冲突是这样的吧。

谢谢

**Comment by chexiongsheng** [comment]
要把其中一个lua虚拟机的c api改名（最少xlua和tolua用到的交集都改，不过最简单的是所有对外的c api都改），然后LuaDLL.cs那用到的地方也跟着改名。

**Comment by huiball** [comment]
也就是说对应使用的虚拟机的lua.h、lualib.h、lauxlib.h这几个里面的api都要改名是吧？
