### ISSUE TITLE
关于LuaCallCSharp标签问题

### ISSUE THREAD

**Issue by sqiuzhao** [Tencent/xLua#599]
你好，关于作者你推荐的热补丁配置中，只有HotFix标签，而不需要LuaCallCSharp，这样可以生成代码吗？

按照你推荐的配置，可以正常热补丁，就是不知道，没有LuaCallCSharp标签，是不是性能上有所音响。

望解答，谢谢！

**Comment by chexiongsheng** [comment]
多数人都不加，也没反馈什么性能问题。主要是包量。

**Comment by sqiuzhao** [comment]
那我是不是我按照你给的配置生成代码就可以了？包量是只生成的脚本大小吗？这个多生成的那部分是有什么特色作用吗
