### ISSUE TITLE
Lua中以此AnimationCurve(KeyFrame[ ])构造函数创建对象报参数无效。

### ISSUE THREAD

**Issue by Nero-Wei** [Tencent/xLua#602]
`if(LuaAPI.lua_gettop(L) >= 1 && (LuaTypes.LUA_TNONE == LuaAPI.lua_type(L, 2) || translator.Assignable<UnityEngine.Keyframe>(L, 2)))`
最后的参数类型是否应该是：
`translator.Assignable<UnityEngine.Keyframe[]>`

**Comment by chexiongsheng** [comment]
这个是可变参数
你在lua那要用可变参数的方式一个个传
