### ISSUE TITLE
（代码生成报错问题）Invalid token '<' in class, struct, or interface member declaration

### ISSUE THREAD

**Issue by sqiuzhao** [Tencent/xLua#603]
作者你好，
我按照你给的推荐配置生成的代码出现了如下内容
public <>f__AnonymousType1<System.Type, System.Reflection.MethodInfo>
然后就报错了，请问是怎么回事，应该怎么解决？thankyou
（热补丁配置）

**Comment by sqiuzhao** [comment]
会不会是版本的问题，我用的unity是2018的版本

**Comment by sqiuzhao** [comment]
找到相同问题了，谢谢

**Comment by ShenKang4181** [comment]
> 找到相同问题了，谢谢

在哪里找到的？我的也是这个问题
