### ISSUE TITLE
关于ios luajit编译的问题

### ISSUE THREAD

**Issue by tufeng060** [Tencent/xLua#605]
问题描述：
hi,我们需要编译ios版本的v2.1.14  xlua库。
我们使用的环境是：xcode版本是10.1，需要同时支持armv7和arm64。但是我们使用最新的 make_ios_luajit.sh遇到了问题，具体是生成xCode工程的cmake只支持OS64：

`
mkdir -p build_lj_ios && cd build_lj_ios
cmake -DUSING_LUAJIT=ON  -DCMAKE_TOOLCHAIN_FILE=../cmake/ios.toolchain.cmake -DPLATFORM=OS64  -GXcode ../
cd ..
cmake --build build_lj_ios --config Release
`

尝试将 -DPLATFORM=OS64 改成 -DPLATFORM=OS，同时将xCode target deployment改成 9.0。编译报错提示：

`
#ifndef _BUILDVM_H
#if LJ_TARGET_X64
#if __USING_SJLJ_EXCEPTIONS__
#error "Need a C compiler with native exception handling on x64"
#endif
`
求雄哥指导

**Comment by chexiongsheng** [comment]
好像是新一些的xcode不支持armv7。
你可以选择把xcode降级，但我觉得没必要，苹果都不支持了，你还生成这个干嘛？

**Comment by onlyfeng** [comment]
可以更新获取最新的 ios.toolchain.cmake (https://github.com/leetal/ios-cmake) ， -DPLATFORM使用默认即可（OS）。(或者用回 iOS.cmake 文件)

另外，make_ios_luajit.sh 编译脚本判断Xcode版本处有些问题，我这边尝试调整了一下：

-XCODEVER=`xcodebuild -version|head -n 1|sed 's/Xcode \([0-9]*\)/\1/g'`
+XCODEVER=`xcodebuild -version|head -n 1|sed 's/Xcode \([0-9]*\).*/\1/g'`
 
-if [ $XCODEVER -lt 10]
+if [ $XCODEVER -lt 10 ]

**Comment by tufeng060** [comment]
谢谢大家的意见，我们把build\luajit-2.1.0b3\src\lj_arch.h文件中的第408行
`
#error "Need a C compiler with native exception handling on x64"
`
直接注释掉就可以编译除armv7了  但是我们不清楚这样做会不会又什么风险，目前测试来看跑起来都是正常的
