### ISSUE TITLE
当使用DoTween插件得扩展方法的时候, genminicode选项生成出来的代码并不能正确的工作

### ISSUE THREAD

**Issue by UpUpLiu** [Tencent/xLua#609]

**Comment by UpUpLiu** [comment]
local obj = GameObject()
obj.transform.DOScale(obj.transform, 1, 0.5):OnComplete(function()
                            print("this is ok")
                        end)

**Comment by UpUpLiu** [comment]
DoTween的扩展方法是这样的
/// <summary>Tweens a Transform's localScale to the given value.
    /// Also stores the transform as the tween's target so it can be used for filtered operations</summary>
    /// <param name="endValue">The end value to reach</param>
    /// <param name="duration">The duration of the tween</param>
    public static Tweener DOScale(this Transform target, Vector3 endValue, float duration)
    {
     ......
    }

**Comment by chexiongsheng** [comment]
genminicode选项是最初用来缓解unity2018以上版本的兼容问题。不过现在不建议使用。
建议开发期别设置.NET Standard 2.0，这样就不用生成代码了。
