### ISSUE TITLE
关于编译第三方库

### ISSUE THREAD

**Issue by LazyPlanet** [Tencent/xLua#61]
问几个比较基础的问题，还望指教：

1.xlua是只支持加载一个，且只有xlua.dll库吧？

2.如果可以直接加载第三方dll，那假设我现在有个LUAReader.dll库，那么我可以这么写吧？
namespace LuaDLL
{ 
	public partial class Lua
    { 
        [DllImport("LUAReader.dll", CallingConvention = CallingConvention.Cdecl)]
        public static extern int luaopen_LUAReader(System.IntPtr L);

        [MonoPInvokeCallback(typeof(LuaDLL.lua_CSFunction))]
        public static int LoadLUAReader(System.IntPtr L)
        {
            return luaopen_LUAReader(L);
        }
}
}
然后调用AddBuildin：
luaenv.AddBuildin("LUAReader", LuaDLL.Lua.LoadLUAReader);

3.可以在lua里面直接调用dll库吗？
比如：

LUAReader = require "LUAReader"
LUAReader.DoSomething()

非常感谢！！！

**Comment by chexiongsheng** [comment]
不是随便拿个dll来就可以
1、各平台都要编译一份；
2、你那dll编译时链接的lua，如果是静态链接，lua版本要和xlua用的要严格一致，如果是动态链接，大版本号，中版本号也要一值；

综上所述，建议按文档编译进xlua。
当然，你能做到上面两点，你另开一个dll应该也可以。但我没试过。

**Comment by LazyPlanet** [comment]
非常感谢回答！我这边还有两个问题：
1.我这个dll是我用vs 的c++工程生成的动态库。这个和C语言的生成的库，没有什么本质区别吧？都是可以通过写cmakelist来解决、生成各个平台的库吧？

2.这种如果想要编进xlua.dll，那我现在在Windows平台测试，可以直接利用你的build64 vs工程进行dll加载，这种可以，对吧？然而我还没有开始用我的库，直接打开工程进行编译，就有2000多个错误，比如cmath这个文件。这个是为啥呢？

非常感谢！！！

**Comment by chexiongsheng** [comment]
看那个文档，那个文档的示例就是c++的。
不需要打开vc工程，直接运行那个脚本就搞定了，然后把其中一个plugin_xxx（比如plugin_lua53）Plugins下找到相应的库覆盖过去。

**Comment by LazyPlanet** [comment]
文档在看，我试试你这个例子吧。灰常感谢，我先试试。
有问题再请教您。

**Comment by LazyPlanet** [comment]
hi，我这个用到了boost第三方库，这个需要如何配置呢？多谢。

**Comment by chexiongsheng** [comment]
其实就是cmake如何加boost库依赖的问题，最好google一下。
我没操作过，我去解决也是google一下。

**Comment by LazyPlanet** [comment]
这样，好的，我看您的文档里面说 THIRDPART_LIB，我以为是要配置这路径。多谢。

**Comment by chexiongsheng** [comment]
你找到boost的添加办法后，对应add_library的地方，你就可以通过添加到THIRDPART_LIB来实现，否则你要改好几个地方

**Comment by LazyPlanet** [comment]
恩，不太好搞，我之前是用VS编好的BOOST库，然后加载到项目的。现在这个看来需要重新编了吧，在Makelist里面，不知道怎么加库，我得看看，多谢！

**Comment by chexiongsheng** [comment]
不一定要重新编译的，直接可以链库的，像boost这么大的东西，编译好后在cmake链接好一些。

这可以给个参考，我们内部有个组件依赖iconv，然后是这么加的。
find_library(ICONV_LIB NAMES iconv)
list (APPEND THIRDPART_LIB ${ICONV_LIB})

**Comment by LazyPlanet** [comment]
感谢您的回答。按照官方的文档和您给的参考，我现在改成如下：

#begin lua-rapidjson
set (RAPIDJSON_SRC 
    lua-rapidjson/src/rapidjson.cpp
)
set_property(
	SOURCE ${RAPIDJSON_SRC}
	APPEND
	PROPERTY COMPILE_DEFINITIONS
	LUA_LIB
)
list(APPEND THIRDPART_INC  lua-rapidjson/rapidjson/include)
set (THIRDPART_SRC ${THIRDPART_SRC} ${RAPIDJSON_SRC})
#end lua-rapidjson
#----------------------------------------------------------------
#二进制PB数据读取
set (LUAREADER_SRC lua-reader/src/LUAMain.cpp)
set (BOOST_LIB lua-reader/libs_x64)
set_property(
	SOURCE ${LUAREADER_SRC}
	APPEND
	PROPERTY COMPILE_DEFINITIONS
	LUA_LIB
)
list(APPEND THIRDPART_INC  lua-reader/include)
set (THIRDPART_SRC ${THIRDPART_SRC} ${LUAREADER_SRC})

find_library(BOOST_LIB NAMES libboost_filesystem-vc140-mt-gd-1_60)
list (APPEND THIRDPART_LIB ${BOOST_LIB})
#二进制PB数据读取
#----------------------------------------------------------------
按照上面写的，json可以编译、正常的使用，但是我这个项目，看log没有进行编译，是不是还漏了什么操作步骤呢？非常感谢！

**Comment by chexiongsheng** [comment]
或者你删了它生成的工程目录看看

**Comment by LazyPlanet** [comment]
您iconv这个的写法，能给俺贴出来看看么？

**Comment by chexiongsheng** [comment]
就这段
find_library(ICONV_LIB NAMES iconv)
list (APPEND THIRDPART_LIB ${ICONV_LIB})

**Comment by LazyPlanet** [comment]
ICONV_LIB 没有定义吗？ 应该定义库文件目录还是库文件呢？

**Comment by chexiongsheng** [comment]
不用先定义再使用的，find_library找到的话会赋值

**Comment by LazyPlanet** [comment]
我总需要告诉cmake我这个boost库dll文件，在哪个路径，叫什么名字吧？

楼主这个第三库的教程，上面写的都是直接调用源码编译进去，有木有，我已经写好的dll或者lib能直接用编到xlua.dll的教程呢？就差这一步了！！

非常感谢楼主的解答！！！

**Comment by chexiongsheng** [comment]
编好后链接可以看看CMakeLists里头luajit版本的处理，都是在外部编译好后链接进来的。
看看定义了USING_LUAJIT的地方，看怎么把现成库链接进来。

**Comment by LazyPlanet** [comment]
好的！！
