### ISSUE TITLE
安卓il2cpp打包,prefab丢失问题

### ISSUE THREAD

**Issue by chenqiu1988** [Tencent/xLua#612]
问题简要描述:
项目之前都是用mono打包安卓,一切正常,最近换成了il2cpp打包,通过injection传入的prefab,lua里面访问全部为null,多个地方都是类似情况,,看了xlua和il2cpp相关说明,并没有提到类似问题.求问是什么原因? 
unity版本:
2018.3.6f1
xlua版本:
2.14 最新版

**Comment by chexiongsheng** [comment]
没听说过会导致prefab丢失
和il2cpp，nil相关的问题我就知道代码剪裁。faq有介绍。

**Comment by chenqiu1988** [comment]
初步判断是碰到unity il2cpp打包本身的bug了,我们还在解决中
