### ISSUE TITLE
win 下编译 android 失败

### ISSUE THREAD

**Issue by hsl9999** [Tencent/xLua#614]
直接在CMD下运行make_android_lua53.bat，出错如下：
ninja: error: loading 'build.ninja': 系统找不到指定的文件。

**Comment by hsl9999** [comment]
解决了，版本太高了

**Comment by kean2013** [comment]
我也是。请问你解决了么

**Comment by backjy** [comment]
这个是Android SDK Tool 中的cmake 版本过高导致的

**Comment by BAJIAObujie** [comment]
同问
