### ISSUE TITLE
方法的参数是泛型委托时，如何传参

### ISSUE THREAD

**Issue by oldLetter** [Tencent/xLua#615]
lua调用C#的一个方法，c#端这个方法的参数是泛型委托，我该如何传这个参数
c# : static public void PerformedToCreateAndWindow < T > (WindowAction< T > action, WindowIndex index)
我知道了如何调用这个泛型方法，但是不知道如何传泛型委托参数

**Comment by chexiongsheng** [comment]
这个WindowAction<泛型>的参数确定后，比如int，把WindowAction<int>加到CSharpCallLua（如果之前有生成代码就重新生成）。然后lua调用的时候直接传个lua函数

**Comment by oldLetter** [comment]
> 这个WindowAction<泛型>的参数确定后，比如int，把WindowAction加到CSharpCallLua（如果之前有生成代码就重新生成）。然后lua调用的时候直接传个lua函数

我是在hotfix修复方法中传这个泛型委托参数，这个泛型委托是有基类约束的，请问可以不通过添加CSharpCallLua吗调用吗

**Comment by 110jiangnan** [comment]
大哥，怎么解决啊，我也遇到这个问题了
