### ISSUE TITLE
注册参数是结构体的回调，在反射模式下运行出错

### ISSUE THREAD

**Issue by watsonsong** [Tencent/xLua#616]
通过CSharpCallLua注册了一个Action的回调：
`typeof(Action<UnityEngine.AnimatorStateInfo>),`

由于AnimatorStateInfo是结构体，在反射模式下代码运行到了ObjectTranslator.cs的376行：
`if (pinfo.ParameterType.IsValueType() || pinfo.IsOut || pinfo.ParameterType.IsByRef)`
这个判断IsValueType是true直接导致回调失败，但是生成的代码运行完全没有问题。

**Comment by chexiongsheng** [comment]
你是在编辑器下还是手机运行？

**Comment by watsonsong** [comment]
编辑器中，没有生成代码，直接运行时候产生的错误。
这个判断我临时改成只检查out就可以了，但感觉不太合适：
`if(pinfo.IsOut)`

**Comment by chexiongsheng** [comment]
你要用的类型配置到CSharpCallLua的话，不会走到那逻辑的，在调用getDelegateUsingGeneric前就会返回了。

**Comment by watsonsong** [comment]
我测试了一下反射就报错，生成代码是可以运行。错误信息就是没添加，但这个类型我确实是添加进去了：
`This type must add to CSharpCallLua: System.Action<UnityEngine.AnimatorStateInfo>`

在getDelegate这个方法里面，getDelegateUsingGeneric之前的那一个循环判断，确实大部分都没有通过：
```
// get by parameters
MethodInfo delegateMethod = delegateType.GetMethod("Invoke");
var methods = bridge.GetType().GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly).Where(m => !m.IsGenericMethodDefinition && (m.Name.StartsWith("__Gen_Delegate_Imp") || m.Name == "Action")).ToArray();
for (int i = 0; i < methods.Length; i++)
{
        UnityEngine.Debug.LogError("delegateMethod: " + delegateMethod + ", methods[i].IsConstructor: " + methods[i].IsConstructor + ", Utils.IsParamsMatch(delegateMethod, methods[i]) = " + Utils.IsParamsMatch(delegateMethod, methods[i]));
        if (!methods[i].IsConstructor && Utils.IsParamsMatch(delegateMethod, methods[i]))
        {
#if !UNITY_WSA || UNITY_EDITOR
            return Delegate.CreateDelegate(delegateType, bridge, methods[i]);
#else
            return methods[i].CreateDelegate(delegateType, bridge); 
#endif
        }
}
```

只要是带泛型的回调都没通过，走的是getDelegateUsingGeneric，例如Action<LuaTable>
`delegateMethod: Void Invoke(XLua.LuaTable), methods[i].IsConstructor: False, Utils.IsParamsMatch(delegateMethod, methods[i]) = False
`
还有我一直通不过的Action<AnimatorStateInfo>
`Void Invoke(UnityEngine.AnimatorStateInfo), methods[i].IsConstructor: False, Utils.IsParamsMatch(delegateMethod, methods[i]) = False`

**Comment by watsonsong** [comment]
没事了，问题还是NetStandard2.0产生的~
其实最好能有一些检查的日志提示
