### ISSUE TITLE
如何获得重载的泛型方法

### ISSUE THREAD

**Issue by oldLetter** [Tencent/xLua#618]
static public void PerformedToCreateAndWindow<T> (WindowAction<T> action) where T : WindowBase
     static public void PerformedToCreateAndWindow<T> (WindowAction<T> action, WindowIndex index) where T : WindowBase
有这样两个重载方法，然后用 xlua.get_generic_method总是只能获得第一个
      `local method_generic = xlua.get_generic_method(CS.WindowManager, 'PerformedToCreateAndWindow');       `
          `  local method=method_generic(CS.UIAdvancedInventoryWindow)`
然后调用method，不管传几个参数，都会默认调用第一个重载方法

想使用`typeof(CS.WindowManager):GetMethod(“PerformedToCreateAndWindow”)`然后xlua.tofunction()，GetMethod也无法获取正确的泛型方法

**Comment by chexiongsheng** [comment]
xlua.get_generic_method的参数3是数字，可以在各重载那选择，默认是0

**Comment by oldLetter** [comment]
解决了，感谢
