### ISSUE TITLE
如果lua对象不为nil，但是c#对象为空，会是什么原因造成？

### ISSUE THREAD

**Issue by sophiepeithos** [Tencent/xLua#619]

**Comment by chexiongsheng** [comment]
不明白你问啥？
c#对象为不为空和lua对象为不为nil有什么关系？
感觉像是在问“张三家鸡没事，但李四家鸡挂了，会是什么原因造成？”

**Comment by sophiepeithos** [comment]
呵呵，
完整一点是“如果lua对象不为nil，但是它指向的c#对象为空，会是什么原因造成？”

**Comment by chexiongsheng** [comment]
UnityEngine.Object对象，如果在C#那调用了Destroy释放了，就有可能出现这种情况。
