### ISSUE TITLE
通过metatable的__index方法返回function调用cs的对象里面的方法报错

### ISSUE THREAD

**Issue by qcbf** [Tencent/xLua#621]
![xlua](https://user-images.githubusercontent.com/3467543/61922526-60c3aa80-af93-11e9-8d2c-8d4cbf487468.png)

因为这里有个这样的需求, 我在写一个lua工具脚本, 
传进来的可以是lua的table 也可以是cs的对象
尝试跟了一下代码 发现在`translator.FastGetCSObj(L, 1)`方法里面的`LuaAPI.xlua_tocsobj_fast(L,index)`返回-1了
这是能重现这个bug的示例

```
local testLuaObjBase = {}
testLuaObjBase.Value = nil
function testLuaObjBase:__index(key)
    return self.Value[key]
end
local testLuaObj = setmetatable({}, testLuaObjBase)

local tmp = {}
function tmp:Func(name)
    print("func>>>>>>>>>>>>>>>>>>>>", name)
end
testLuaObj.Value = tmp
testLuaObj:Func("TestLuaCall")

testLuaObj.Value = CS.UnityEngine.GameObject.Find("Game")
print(testLuaObj.SetActive)
testLuaObj:SetActive(false)
```

**Comment by chexiongsheng** [comment]
__index传入的是设置了metatable的那个table

**Comment by qcbf** [comment]
> __index传入的是设置了metatable的那个table

明白了, 谢谢.

**Comment by qcbf** [comment]
> __index传入的是设置了metatable的那个table

我之前想做一个工具, 会包裹住原始对象, 然后外部可以像操作原始对象一样 不用换种方式来写.
