### ISSUE TITLE
请问这种异常怎样处理, 看不到Lua的堆栈信息, 使用的Release

### ISSUE THREAD

**Issue by ming871** [Tencent/xLua#623]
"type": "LuaException",
        "message": "LuaException: function :206",
        "stack_trace": "XLua.LuaEnv.ThrowExceptionFromError (System.Int32 oldTop) (at <00000000000000000000000000000000>:0)\n
        XLua.CSObjectWrap.GameICollisionCallbackBridge.Game.ICollisionCallback.OnTriggerStay (UnityEngine.Collider collider) (at <00000000000000000000000000000000>:0)\n"

**Comment by ming871** [comment]
这是生成的代码:
[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
        static int _m_OnTriggerStay(RealStatePtr L)
        {
		    try {
            
                ObjectTranslator translator = ObjectTranslatorPool.Instance.Find(L);
            
            
                Game.CollisionCallback gen_to_be_invoked = (Game.CollisionCallback)translator.FastGetCSObj(L, 1);
            
            
                
                {
                    UnityEngine.Collider _collider = (UnityEngine.Collider)translator.GetObject(L, 2, typeof(UnityEngine.Collider));
                    
                    gen_to_be_invoked.OnTriggerStay( _collider );
                    
                    
                    
                    return 0;
                }
                
            } catch(System.Exception gen_e) {
                return LuaAPI.luaL_error(L, "c# exception:" + gen_e);
            }
            
        }

**Comment by ming871** [comment]
Game.CollisionCallback:
namespace Game
{
	[LuaCallCSharp]
	[CSharpCallLua]
	public class CollisionCallback : MonoBehaviour
	{
		public ICollisionCallback callback = null;
		public void OnCollisionEnter(Collision collision) {
			if(callback != null){
				callback.OnCollisionEnter (collision);
			}
		}
		public void OnCollisionStay(Collision collision) {
			if(callback != null){
				callback.OnCollisionStay (collision);
			}
		}
		public void OnCollisionExit(Collision collision) {
			if(callback != null){
				callback.OnCollisionExit (collision);
			}
		}
		public void OnTriggerEnter(Collider collider) {
			if(callback != null){
				callback.OnTriggerEnter (collider);
			}
		}
		public void OnTriggerStay(Collider collider) {
			if(callback != null){
				callback.OnTriggerStay (collider);
			}
		}

		public void OnTriggerExit(Collider collider) {
			if(callback != null){
				callback.OnTriggerExit (collider);
			}
		}

	}

**Comment by ming871** [comment]
ICollisionCallback:
```
[CSharpCallLua]
	[LuaCallCSharp]
	public interface ICollisionCallback
	{
		void OnCollisionEnter(Collision collision);
		void OnCollisionStay(Collision collision);
		void OnCollisionExit(Collision collision);

		void OnTriggerEnter(Collider collider);
		void OnTriggerStay(Collider collider);
		void OnTriggerExit(Collider collider);
	}
```

**Comment by chexiongsheng** [comment]
什么版本的xlua呢？

**Comment by ming871** [comment]
v2.1.14以后从master上clone的版本

**Comment by ming871** [comment]
我用最新的master版本试一下

**Comment by chexiongsheng** [comment]
v2.1.14也是挺新的，应该也没这问题

**Comment by chexiongsheng** [comment]
我在04_LuaObjectOrented上试了是由错误信息的

**Comment by ming871** [comment]
好的 我再试试
