### ISSUE TITLE
考虑加一个直接require一个Lua文件的原生函数

### ISSUE THREAD

**Issue by watsonsong** [Tencent/xLua#625]
很多时候C#需要去require一个Lua的代码，直接DoString看起来效率太低了。如果能增加一个原生函数，会提高这部分的效率。

可以在xlua.c中加一个类似这样的函数：
https://github.com/topameng/tolua_runtime/blob/4053c2321fa246293be5a2831ece25c74595d799/tolua.c#L1920

**Comment by chexiongsheng** [comment]
真要用这东西的话，首页不是有个把math.max映射为delegate在C#调用的例子么？同理require也可以。
但require建议别在C#用，逻辑上说上不通。

**Comment by watsonsong** [comment]
最常用的需求就是做一个类似LuaBehavior这样的类，继承MonoBehavior然后创建对应Lua的类。这个时候就需要由C#去require一个Lua文件。

**Comment by chexiongsheng** [comment]
> 真要用这东西的话，首页不是有个把math.max映射为delegate在C#调用的例子么？同理require也可以。

你自己想用就按这方式用。
