### ISSUE TITLE
how can i construct System.String data to use some string extension methods

### ISSUE THREAD

**Issue by xiangyuan** [Tencent/xLua#627]
how can i construct System.String data to use some string extension methods (EDIT)

i don't know why , please help

Example:
print(type("work")) --> this print string
local a = "work"
cast(a,typeof(CS.System.String))
print(a:ToHash()) --> c# extension method
print(type(a)) --->> this will print LUA: <invalid c# object>

**Comment by chexiongsheng** [comment]
for example, you want to call GetHashCode of string, write a C# method like this:
`public static int GetHashcode(string str)
{
    return str.GetHashCode();
}`
call it in lua
