### ISSUE TITLE
请问如何排除某些指定的Delegate对象呢？

### ISSUE THREAD

**Issue by JourneyHans** [Tencent/xLua#628]
对于第三方插件对象不想生成__Gen_Delegate_Imp，请问有什么方法呢？

**Comment by chexiongsheng** [comment]
__Gen_Delegate_Imp都是用来适配lua函数的调用。产生的来源就两个：你配置的“CSharpCallLua”，你配置的Hotfix列表。
都是你配置的东西，想不生成啥，不配置即可。
你可能排除A的东西，但DelegatesGensBridge.cs仍然有A的引用，那是你有另外一个模块B，那有对A的引用，这个没排除。
ps，生成__Gen_Delegate_Imp对你有啥影响？

**Comment by JourneyHans** [comment]
大概就是有个插件只有我在用，没有进版本管理，但是其他人拉取的时候就会发现一些他们找不到的对象在DelegatesGensBridge里

**Comment by JourneyHans** [comment]
再比如有的时候会出现这种
![image](https://user-images.githubusercontent.com/8108912/63139237-30aa7d00-c010-11e9-9626-006499c66376.png)
这个类是编辑器下才执行的，我想排除掉这个，除了重新生成，还有什么办法吗？

**Comment by chexiongsheng** [comment]
按我之前的答复，你不加就可以了

**Comment by JourneyHans** [comment]
好的，理解了，谢谢耐心解答~
