### ISSUE TITLE
Hotfix注入Assembly失败

### ISSUE THREAD

**Issue by Sparrowfc** [Tencent/xLua#63]
- 在实例工程里跑通了我们的更新框架，打算接入到开发工程中去。拷贝了xLua文件夹以及ExampleGenConfig.cs到Assets目录下，设置好Symbol并GenCode。菊花转完发现在HotfixInject()里执行到L224 assembly.Write(INTERCEPT_ASSEMBLY_PATH)时抛出异常AssymblyResolutionException: Failed to resolve assembly: 'UnityEngine ...。在文件系统中可以看到Library/ScriptAssemblies/Assembly-CSharp.dll文件大小为0，写入失败了。

- 现在考虑问题可能出现在两方面，一个可能是我们工程的程序集过大（将近8M）导致的，另一个可能是工程里的哪些脚本引用导致的。希望能确认下是否存在第一种的可能性，另外对于第二个猜想希望能得到一些指点。
    

- 首先我把hotfix里其他代码都注释掉只保留了assembly.Read和Write，问题依然存在。

- 然后我从网上下载了Mono.cecil库，稍微修改了下，在MetadataResolver.Resolve里抓取了异常再抛出得到了下面的信息ResolutionException: Failed to resolve UnityEngine.WrapMode. 随后我在我们的工程和示例工程里均加入了输出assembly中FullName包含‘WrapMode’的type名称，并且在示例工程里添加了一些WrapMode的代码，但运行结果却是示例工程没有任何输出，而我们的工程里含有一个叫eWrapMode的type。
    目前暂时没了思路，不知道你们应用在大型工程上时有没有遇到这种问题，我们的Untiy版本是5.3.4p1

**Comment by chexiongsheng** [comment]
更新到最新代码了么？更新下试试？今天解决过类似的问题。

**Comment by Sparrowfc** [comment]
哇擦，我写了半天你秒回啊，我马上更新试试！

**Comment by Sparrowfc** [comment]
不行，还是同样的问题，应该还是哪个类的问题

**Comment by chexiongsheng** [comment]
AssymblyResolutionException: Failed to resolve assembly: 'UnityEngine ..
省略的是啥？

**Comment by chexiongsheng** [comment]
UnityEngine.WrapMode试了在我的工程里头添加了个方法，能inject成功，反编译看也是正常的。
 void ABC(UnityEngine.WrapMode wm)
 {
 }

**Comment by Sparrowfc** [comment]
跟另一个问题类似的
AssemblyResolutionException: Failed to resolve assembly: 'UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
Mono.Cecil.BaseAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name, Mono.Cecil.ReaderParameters parameters)
Mono.Cecil.BaseAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name)
Mono.Cecil.DefaultAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name)
Mono.Cecil.MetadataResolver.Resolve (Mono.Cecil.TypeReference type)
Mono.Cecil.ModuleDefinition.Resolve (Mono.Cecil.TypeReference type)
Mono.Cecil.TypeReference.Resolve ()
Mono.Cecil.Mixin.CheckedResolve (Mono.Cecil.TypeReference self)
Mono.Cecil.SignatureReader.ReadCustomAttributeEnum (Mono.Cecil.TypeReference enum_type)
Mono.Cecil.SignatureReader.ReadCustomAttributeElementValue (Mono.Cecil.TypeReference type)
Mono.Cecil.SignatureReader.ReadCustomAttributeElement (Mono.Cecil.TypeReference type)
Mono.Cecil.SignatureReader.ReadCustomAttributeElement (Mono.Cecil.TypeReference type)
Mono.Cecil.SignatureReader.ReadCustomAttributeFixedArgument (Mono.Cecil.TypeReference type)
Mono.Cecil.SignatureReader.ReadCustomAttributeConstructorArguments (Mono.Cecil.CustomAttribute attribute, Mono.Collections.Generic.Collection1 parameters) Mono.Cecil.MetadataReader.ReadCustomAttributeSignature (Mono.Cecil.CustomAttribute attribute) Mono.Cecil.CustomAttribute.<Resolve>b__2 (Mono.Cecil.CustomAttribute attribute, Mono.Cecil.MetadataReader reader) Mono.Cecil.ModuleDefinition.Read[CustomAttribute,CustomAttribute] (Mono.Cecil.CustomAttribute item, System.Func3 read)
Mono.Cecil.CustomAttribute.Resolve ()
Mono.Cecil.CustomAttribute.get_ConstructorArguments ()
Mono.Cecil.ImmediateModuleReader.ReadCustomAttributes (ICustomAttributeProvider provider)
Mono.Cecil.ImmediateModuleReader.ReadProperties (Mono.Cecil.TypeDefinition type)
Mono.Cecil.ImmediateModuleReader.ReadType (Mono.Cecil.TypeDefinition type)
Mono.Cecil.ImmediateModuleReader.ReadTypes (Mono.Collections.Generic.Collection`1 types)
Mono.Cecil.ImmediateModuleReader.ReadModule (Mono.Cecil.ModuleDefinition module)
Mono.Cecil.ModuleWriter.WriteModuleTo (Mono.Cecil.ModuleDefinition module, System.IO.Stream stream, Mono.Cecil.WriterParameters parameters)
Mono.Cecil.ModuleDefinition.Write (System.IO.Stream stream, Mono.Cecil.WriterParameters parameters)
Mono.Cecil.ModuleDefinition.Write (System.String fileName, Mono.Cecil.WriterParameters parameters)
Mono.Cecil.AssemblyDefinition.Write (System.String fileName, Mono.Cecil.WriterParameters parameters)
Mono.Cecil.AssemblyDefinition.Write (System.String fileName)
XLua.Hotfix.HotfixInject () (at Assets/XLua/Src/Editor/Hotfix.cs:263)

我在示例工程里添加了WrapMode也没有问题，但是发现我们主工程Assembly里面有个sWrapMode的type但是示例工程里却没有，不知道跟这个有没有关系。现在想不到什么好的定位问题文件的方式，只能一点点删着试了

**Comment by chexiongsheng** [comment]
XLua.Hotfix.HotfixInject () (at Assets/XLua/Src/Editor/Hotfix.cs:263)
貌似和最新代码对不上，你确定你更新啦？

**Comment by Sparrowfc** [comment]
我堆栈我从另一个issue拷过来的，工程在内网发不了，但是堆栈是一样的

**Comment by chexiongsheng** [comment]
我这没法重现，所以也没法定位。能给个最小重新工程就最好

**Comment by Sparrowfc** [comment]
好麻烦了，我自己一点点定位吧

**Comment by Sparrowfc** [comment]
问题解决了，太激动了！先说下解决方法哈，仔细跟了下Mono.Cecil的代码，跟你之前修复fistpass一样，在init里添加一下查找路径就可以了。
`resolver.AddSearchDirectory(System.IO.Path.GetDirectoryName(typeof(WrapMode).Model.FullyQualifiedName);`
不一定非得是WrapMode，只要是UnityEngine下的类就行，这样就可以找到UnityEngine.dll了。

然后就是为什么UnityEngine的东西会混进来，看了下异常的堆栈是从GetConstantType里调用的，因此怀疑是定义了常量对象，测试了一下这个就是罪魁祸首。你在测试工程里声明一下const [UnityEngine Type] a就能复现这个问题。回头先让他们把代码里的const都改成static readonly....

**Comment by chexiongsheng** [comment]
奇怪了，在Library\UnityAssemblies就有UnityEngine.dll
为啥typeof(WrapMode).Module.FullyQualifiedName会指向C:\Program Files\Unity\Editor\Data\Managed\UnityEngine.dll呢？

**Comment by chexiongsheng** [comment]
而且，我定义了const也没问题
const GameObject go = null;
const WrapMode wm = WrapMode.Once;

难道和unity版本有关？
你打印下typeof(WrapMode).Module.FullyQualifiedName看看指向哪里？
还有帮忙看看Library\UnityAssemblies下有没有UnityEngine.dll？

有个项目是把他整个工程都打hotfix了，也没碰到问题，没定义unity类型的常量的可能性不大吧？

**Comment by Sparrowfc** [comment]
ok，我再跟一下。我在测试工程里定义了一个public const WrapMode sWrapMode = WrapMode.Clamp，然后在Awake里Debug.Log(sWrapMode)了一下就会出问题。FullQualifiedName就是定位到Unity程序安装目录下的Managed目录下。

**Comment by Sparrowfc** [comment]
我在Cecil里打了log，发现我们的工程产生常量WrapMode的原因是定义方法参数默认值导致的，比如Method(WrapMode a = WrapMode.Once)就会导致生成常量WrapMode到Assembly里面

**Comment by Sparrowfc** [comment]
我的工程Library下没有UnityAssemblies，是版本原因吗？我用的两个工程是5.3.4p1和5.3.6p2

**Comment by chexiongsheng** [comment]
估计是没那目录，可能和版本有关。我的有，所以没问题，用你那种方式兼容性更好些
