### ISSUE TITLE
"try to dispose a LuaEnv with C# callback! exception  in "General/Src/XLuaTest.cs"   

### ISSUE THREAD

**Issue by TestVan** [Tencent/xLua#630]
Hi, still get error  even if set max = null, any help will be appreciated.
![20190819180425](https://user-images.githubusercontent.com/50074809/63257462-6b304600-c2ac-11e9-9631-34a4719456f2.png)
![image](https://user-images.githubusercontent.com/50074809/63257919-67e98a00-c2ad-11e9-8094-076f4b7af263.png)

**Comment by chexiongsheng** [comment]
it depend  on clr gc.
you try like this: 
~~~csharp
static void test()
{
// all you code 
}

public static void Main()
{
    test();
}
~~~

**Comment by TestVan** [comment]
Thanks for your help!  make LuaEnv as parameter will fix this issue.
