### ISSUE TITLE
不能访问Unity Package里面的internal方法

### ISSUE THREAD

**Issue by maxcat** [Tencent/xLua#633]
我们试着用xlua的热补丁去修复Unity Package里面的方法，但是当我们试着去访问Unity Package里面的internal方法的时候，unity报错attempt to call a nil value (method "xxx").

**Comment by chexiongsheng** [comment]
非public方法用这个声明下：https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/XLua_API.md#xluaprivate_accessibleclass

**Comment by maxcat** [comment]
谢谢，用了xlua.private_accessible就可以访问internal方法了。
