### ISSUE TITLE
LuaException: [string "chunk"]:25: No such type: System.Collections.Generic.List

### ISSUE THREAD

**Issue by iningwei** [Tencent/xLua#64]
你好，我在hotfix的lua代码中声明了如下代码
keys=CS.System.Collections.Generic.List(typeof(CS.System.Int32))

报错如题，是哪里没有设置对吗？

另外我想在lua代码中遍历c#中的一个Dictionary<,> A，是不是必须把A转换成lua的table,然后用for来遍历？

感谢作者！

**Comment by chexiongsheng** [comment]
你试试
keys= System.Collections.Generic['List`1[System.Int32]']()
其实很少这么用，可读性不是很好，泛化一般都是C#那new了，传过来，lua直接用。

Dictionary的遍历，c#的foreach是用不了的，但Dictionary的c#的api都可以用，foreach也是c# api的语法糖。

**Comment by iningwei** [comment]
你好，试了。报错：LuaException: [string "chunk"]:27: attempt to index a nil value (global 'System')

另外，你提到C#那边new后，供lua用。是什么意思？demo里面有提供类似的用法吗？

**Comment by chexiongsheng** [comment]
keys= CS.System.Collections.Generic'List`1[System.Int32]'
漏了

**Comment by iningwei** [comment]
补充：
我的初衷是想在lua脚本中创建一个C# List<int>类型的变量。

**Comment by chexiongsheng** [comment]
就是这个对象往往是C#那构造的，很少在lua下构造。
你在lua里头构造是为了啥呢？List<int>你可以直接{1, 2, 3}这么传递。

**Comment by iningwei** [comment]
再次打扰：
是这样的，C# 代码如下：
`public Dictionary<int, Person> persons = new Dictionary<int, Person>();
    public int _getAllPersonMoney()
    {
        int allMoney = 0;
        foreach (KeyValuePair<int, Person> item in persons)
        {
            allMoney += item.Value.Age;
        }
        return allMoney;
    }`
我想在lua中hotfix  _getAllPersonMoney()这个函数，把allMoney+=item.Value.Age,改成allMoney+=item.Value.Money。
这种情况，怎么处理比较好？

lua中构造List也是做的过程中顺手写的。
PS:把System前加了CS.依旧要报错。

**Comment by chexiongsheng** [comment]
list构造那个刚刚我试过是可以的，貌似这的回复有些符号自动帮我删了
 local lst = CS.System.Collections.Generic['List`1[System.Int32]']()

**Comment by chexiongsheng** [comment]
是的，有符号自动帮我删了，'List`1[System.Int32]'外面要加上一层中括号

**Comment by chexiongsheng** [comment]
foreach是语法糖，实际上是帮你调用GetEnumerator返回一个IEnumerator，然后调用IEnumerator的MoveNext和Current来遍历
