### ISSUE TITLE
最新的xlua 代码 libxlua.a  默认只有arm64  没有 armv7 

### ISSUE THREAD

**Issue by k0204** [Tencent/xLua#640]
最新的xlua 代码 libxlua.a  默认只有arm64  没有 armv7 
文档中也没找到文档说明该如何做,

查看以往的 issues     
关于ios luajit编译的问题 #605

更新了 ios.toolchain.cmake  重新编译 可生成 armv7 arm64

**Comment by chexiongsheng** [comment]
这不是么？
https://github.com/Tencent/xLua/tree/master/Assets/Plugins/Android/libs/armeabi-v7a

**Comment by chexiongsheng** [comment]
新的ios.toolchain.cmake在哪里拿呢？

**Comment by k0204** [comment]
https://github.com/leetal/ios-cmake

**Comment by k0204** [comment]
这个能写到文档中或者 FAQ 中把   需要自己添加第三方库的时候. 就需要自己编译.  出现这个问题网上各种找原因.  新人比较困惑

**Comment by chexiongsheng** [comment]
我确认下，如果能用我更新下

**Comment by chexiongsheng** [comment]
还是你只是编译lua53版本的？这和 #605描述的不太一样

**Comment by k0204** [comment]
我  就编译 ios  lua53  ,  不编译 luajit . 用 https://github.com/leetal/ios-cmake 这个能编译出 armv7 的 . 不用编译不了 只有arm64

**Comment by k0204** [comment]
#605 是我看到了  去下的 文件. 以为是同一个问题

**Comment by chexiongsheng** [comment]
只是更新https://github.com/leetal/ios-cmake就可以了么？我更新后编译的还是一样arm64，编译脚本要做什么改动么？

**Comment by k0204** [comment]
确定了下 就只做了更新  把 android.toolchain.cmake 覆盖了下

**Comment by chexiongsheng** [comment]
那你怎么确认是否又armv7呢？我更新后，重编译，用lipo -info查，只有arm64

**Comment by k0204** [comment]
用 lipo -info    查的    然后.a 文件大小从1.8 到了3.5

**Comment by k0204** [comment]
确实没做过其他的改动.

**Comment by chexiongsheng** [comment]
你的编译脚本和master上的是一致的么？

**Comment by quicklyslow** [comment]
本来是想要用ios.toolchain.cmake编译iOS的armv7/s，arm64的fat lib，但是我试了用Set -DPLATFORM to "OS" 编译出来也是arm64的，然后修改了ios.toolchain.cmake里面的OS部分去掉arm64也不行。
最后的办法是直接修改CMakeLists.txt，把if (IOS)
        set(CMAKE_OSX_ARCHITECTURES "$(ARCHS_STANDARD)")中的$(ARCHS_STANDARD)改为
armv7 armv7s arm64就可以了。

**Comment by chexiongsheng** [comment]
> 本来是想要用ios.toolchain.cmake编译iOS的armv7/s，arm64的fat lib，但是我试了用Set -DPLATFORM to "OS" 编译出来也是arm64的，然后修改了ios.toolchain.cmake里面的OS部分去掉arm64也不行。
> 最后的办法是直接修改CMakeLists.txt，把if (IOS)
> set(CMAKE_OSX_ARCHITECTURES "$(ARCHS_STANDARD)")中的$(ARCHS_STANDARD)改为
> armv7 armv7s arm64就可以了。

亲测这个可以，不用升级 ios.toolchain.cmake， @k0204

**Comment by k0204** [comment]
好的 谢谢  空了试试!
