### ISSUE TITLE
unity5.5打包iOS报错

### ISSUE THREAD

**Issue by hsl4125** [Tencent/xLua#65]
Assets/XLua/Gen/UnityEngineMonoBehaviourWrap.cs(410,66): error CS1061: Type `UnityEngine.MonoBehaviour' does not contain a definition for `runInEditMode' and no extension method `runInEditMode' of type `UnityEngine.MonoBehaviour' could be found. Are you missing an assembly reference?

Assets/XLua/Gen/UnityEngineMonoBehaviourWrap.cs(441,40): error CS1061: Type `UnityEngine.MonoBehaviour' does not contain a definition for `runInEditMode' and no extension method `runInEditMode' of type `UnityEngine.MonoBehaviour' could be found. Are you missing an assembly reference?

**Comment by chexiongsheng** [comment]
你要把这个属性加到BlackList里头。
这个属性是编辑器特有的，生成代码又依赖于编辑器。

**Comment by hsl4125** [comment]
打包用的就是你们官方的Examples，选的场景01_HelloWorld，这需要添加BlackList吗？？
不好意思，没太听明白，可以详细的说一下吗？

**Comment by chexiongsheng** [comment]
和例子没关，unity5.5添加了runInEditMode，这个是包在Editor宏里头的。实际上手机上是没这属性。

生成代码是编辑器下进行的，会包装runInEditMode，然后打包手机版本就错了。

你按文档操作，添加runInEditMode到黑名单就可以了。

**Comment by chexiongsheng** [comment]
也可以参考下ExampleGenConfig.cs

**Comment by hsl4125** [comment]
[BlackList]
    public static List<List<string>> BlackList = new List<List<string>>()  {
          new List<string>(){"UnityEngine.MonoBehaviour", "runInEditMode"}, 
    }

OK，通过编译

**Comment by hsl4125** [comment]
现在是否接受个人提交fix？？

**Comment by chexiongsheng** [comment]
今天接收了几个pull request。
