### ISSUE TITLE
new LuaEnv()消耗时间比较多，有什么优化空间？

### ISSUE THREAD

**Issue by jerry-zeng** [Tencent/xLua#650]
RT。
1. 在1500块以下的华为和小米手机，就算千元机吧，大概耗时600-800ms；在2000块的手机上耗时是400ms多。
不知道这里有没有什么优化空间，少个100-200ms什么的？

2. 还有一个，第一次加载wrap的耗时，导出的函数越多越耗时，少的几ms，多的几十ms，像UnityEngine.Application就60多ms，Camera是30多ms。其它自己的类有100-200ms的。
    这种有没有办法让时间分散一点？一次耗时这么多会有卡顿的感觉。目前是把少部分调用的API通过别的工具类调用，避免wrap大的类，但工具类如果接口多的话，也会变慢。

**Comment by chexiongsheng** [comment]
你用的是il2cpp还是mono？

**Comment by jerry-zeng** [comment]
用的是mono的

**Comment by chexiongsheng** [comment]
应该是mono的jit导致的，你换il2cpp就好了

**Comment by jerry-zeng** [comment]
嗯，不好意思，碰到要放假就没试。早上下了个NDK，用il2cpp试了一下，同样的手机，new LuaEnv()只要110ms，wrap加载也快了一些。
