### ISSUE TITLE
在Lua代码中给Button绑定点击事件并且点击，然后调用luaenv.Dispose()会报异常

### ISSUE THREAD

**Issue by lizh5343** [Tencent/xLua#653]
lua代码中使用 **btn.onClick:AddListener(function() self:Func() end)** 绑定点击响应函数，并且确保了在调用 luaenv.Dispose() 之前调用 **btn.onClick:RemoveAllListeners()** 。如果不点击这个按钮，就不会报异常，一旦点击按钮调用了响应函数以后，就会报 InvalidOperationException: try to dispose a LuaEnv with C# callback!

**Comment by chexiongsheng** [comment]
ugui做了cache导致的，翻下老issue，网上也有人分享过

**Comment by lizh5343** [comment]
#139
