### ISSUE TITLE
静态this 扩展方法方法在未生成与生成代码的行为不一致 

### ISSUE THREAD

**Issue by cuinc** [Tencent/xLua#659]
`
namespace Test
{
    public static class TestClass
    {
        public static void Print(this System.Object obj, string msg)
        {
            System.Console.Write(msg);
        }
    }
}

// 调用方法
// 未生成的代码，可以正常使用，但是如果生成的代码，就会报方法不存在
CS.Test.TestClass.Print(nil, 'Hello World!!')`

**Comment by chexiongsheng** [comment]
生成和不生成你都这么用：
obj:Print('Hello World!!')
