### ISSUE TITLE
使用LuaTable在c#获取delegate的情况下，好像没法释放干净，一定会报try to dispose a LuaEnv with C# callback!

### ISSUE THREAD

**Issue by karsuszhang** [Tencent/xLua#661]
最近在尝试使用xlua时遇到怎么都清不掉引用的问题，明明对应的delegate都设置null了，LuaTable也释放了

使用U3DScripting这个例子进行测试，在OnDestroy最后加入luaEnv.Dispose();
退出场景会报try to dispose a LuaEnv with C# callback!
屏蔽掉Awake()里获取delegate的代码
/*
scriptEnv.Get("start", out luaStart);
scriptEnv.Get("update", out luaUpdate);
scriptEnv.Get("ondestroy", out luaOnDestroy);
*/
再次执行例子退出就不会报错，看起来所有应该做的清洁操作都做了，还是说有哪些还要做？

**Comment by karsuszhang** [comment]
补充一下，gen code/gen min code/no gen code都试过了，没有变化

**Comment by chexiongsheng** [comment]
释放指的是gc认为没引用了。而不是你认为没引用了。
可以翻下之前的issue，比如ugui会对事件回调做cache，你以为Remove了，但实际上ugui帮你cache着呢。比如栈上的对象，你赋值为空，gc仍然认为有引用，要等当前函数指向完了，gc才认为没引用。
要干净的清理是有难度的，要了解引擎，第三方库，gc的一些潜规则。要是觉得搞不定，也可以选择别Dispose

**Comment by karsuszhang** [comment]
看起来想手动处理干净很复杂，我目前的需求是执行不同的下载的bundle里的lua文件，环境不释放也会很麻烦，我想确认一个事情，我看faq里说这个异常检查是为了防止虚拟机释放后业务还在调用，如果我确定不会再调用，那么不理这个异常是否没有实际的影响？

**Comment by chexiongsheng** [comment]
抛了着异常就代表还没Dispose，跟没调用Dispose之前是一样的

**Comment by karsuszhang** [comment]
呃，我稍微纠正一下说法再请教一下，我的意思是我在项目里把异常注掉，我看它主要是判断delegatebridge这部分，是不是说让它正常执行后面的清理操作，实际上底层这个环境已经被正常释放掉了，我这边就算被cache一些delegate，不去使用，估计过段时间就会自动会被清理掉，或者说unity cache一个引用也没啥大不了的，业务层已经释放了，只要底层环境清干净，不会有内存泄漏，不会影响后面创建的新环境就行。

**Comment by isbdnt** [comment]
简单粗暴的解决办法如下
ObjectTranslator.cs里加上
```c#
        public void ReleaseAllDelegateBridge() {
            foreach (var kv in delegate_bridges.ToArray()) {
                if (kv.Value.IsAlive) {
                    ((LuaBase)kv.Value.Target).Dispose();
                }
            }
        }
```
然后到LuaEnv里调用
![image](https://user-images.githubusercontent.com/26591233/67311096-84b27000-f531-11e9-807e-c160f10b1499.png)

**Comment by karsuszhang** [comment]
> 简单粗暴的解决办法如下
> ObjectTranslator.cs里加上
> 
> ```cs
>         public void ReleaseAllDelegateBridge() {
>             foreach (var kv in delegate_bridges.ToArray()) {
>                 if (kv.Value.IsAlive) {
>                     ((LuaBase)kv.Value.Target).Dispose();
>                 }
>             }
>         }
> ```
> 
> 然后到LuaEnv.cs里调用
> ![image](https://user-images.githubusercontent.com/26591233/67311096-84b27000-f531-11e9-807e-c160f10b1499.png)

打了个standalone版本测了一下，100,000次级别的创建和释放env，使用U3DScripting例子里的lua脚本，创建luatable获取delegate，dispose前做完必要的清理，内存上做不做这个translator的release好像没什么变化，不知道其他的地方有没有什么区别，当然还是清了放心一些，感谢回复。

**Comment by chexiongsheng** [comment]
假如这种释放方式是解决问题的方式，根本不用做那麻烦的检查啊，我直接Dispose不就可以了么？我做那检查写的代码绝对比你这些代码要多啊，issue的这个回答就比你这代码要长。我是闲着蛋疼？消遣别人也消遣自己？

**Comment by karsuszhang** [comment]
我觉得这是个值得讨论的问题，我也可以说一下个人看法。做检查这件事本身没有什么问题，检查也很好，但说实在话，就目前的这个情况来看，底层的这个检查结果，不具有诊断意义，最多只有参考价值。
不论是因为cache还是gc的原因，目前这个检查结果无法及时反映应用层的清理操作是否正常，应用层无从得知什么时候清理是有效的，在无法知道怎么样是正确的情况下，也就无从判断如何做是错误的，相反，这个异常还经常会报出false alert，这个结果只能是说env不能dispose，因为这个异常反而会打断后面的dispose流程。当然我觉得不能dispose更不合理一点。
归根到底，这个是个责任划清问题，就算env不dispose，应用层也能折腾出各种调用崩溃或者调用异常的幺蛾子，但是如果目前这个异常无法诊断清楚到底应用层是否写的有问题的情况下，我觉得还不如不要这个诊断，就全扔应用层解决就好了，到底都是上面用的有问题，提供一个检查函数已经很好了，上面测试发现问题，就自己把引用打出来一个一个对就好，如果上面需要dispose env，那就自己把架构做好一次清干净，不然就自己收拾自己的屁股。所以我觉得这个地方它肯定不应该是异常，给个logerror都多，logwarning了不起了。
所以我觉得，如果做不干净，那还不如不要做，这样使用的时候也能划得清楚一些，不然这样反而闹不清。这边一点使用层的看法，可以参考一下。

**Comment by karsuszhang** [comment]
solved
close
