### ISSUE TITLE
release2.1.14在Unity2018.4.2f1下安卓平台无法打包，编译出错

### ISSUE THREAD

**Issue by Magicqy** [Tencent/xLua#662]
打开ExampleConfig中纯Lua开发模式的注释，生成Wrap代码
直接保存一个空场景打包，会出现编译错误，提示类似以下有一些属性找不到，有27处错误。
在UnityEditor中直接运行没有问题，Mono或il2cpp都会相应的提示。

如果不打开ExampleConfig中的注释，则可以正常打包编译。

`Assets\XLua\Gen\UnityEngineTextureWrap.cs(780,23): error CS1061: 'Texture' does not contain a definition for 'imageContentsHash' and no accessible extension method 'imageContentsHash' accepting a first argument of type 'Texture' could be found (are you missing a using directive or an assembly reference?)
`

**Comment by Magicqy** [comment]
经测试在exclude列表中补充以下类型，才可以正常编译。
        "Texture", "Light", "LightProbe", "DrivenRectTransformTracker", "QualitySettings", "ParticleSystem",
        "Input", "Caching", "AudioSettings", "AnimatorControllerParameter", "CanvasRenderer"

问题虽然解决，但想请教一下原因是什么？

**Comment by chexiongsheng** [comment]
看FAQ

**Comment by Magicqy** [comment]
谢谢，知道怎么解决了。
