### ISSUE TITLE
如何重定向io.open

### ISSUE THREAD

**Issue by isbdnt** [Tencent/xLua#665]
现在这个api默认从项目根目录下加载，不知道有没有提供类似CustomLoader那样的接口来重新实现读取

**Comment by chexiongsheng** [comment]
用C#写一个然后调用

**Comment by isbdnt** [comment]
> 用C#写一个然后调用

有一些第三方库是直接调用io

**Comment by chexiongsheng** [comment]
io.open = xxx

**Comment by isbdnt** [comment]
> io.open = xxx

简单粗暴。。。厉害୧(๑•̀◡•́๑)૭
