### ISSUE TITLE
Hotfix Generate Code issue 

### ISSUE THREAD

**Issue by mydishes** [Tencent/xLua#67]
AssemblyResolutionException: Failed to resolve assembly: 'UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
Mono.Cecil.BaseAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name, Mono.Cecil.ReaderParameters parameters)
Mono.Cecil.BaseAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name)
Mono.Cecil.DefaultAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name)
...
...
Mono.Cecil.ModuleWriter.WriteModuleTo (Mono.Cecil.ModuleDefinition module, System.IO.Stream stream, Mono.Cecil.WriterParameters parameters)
Mono.Cecil.ModuleDefinition.Write (System.IO.Stream stream, Mono.Cecil.WriterParameters parameters)
Mono.Cecil.ModuleDefinition.Write (System.String fileName, Mono.Cecil.WriterParameters parameters)
Mono.Cecil.AssemblyDefinition.Write (System.String fileName, Mono.Cecil.WriterParameters parameters)
Mono.Cecil.AssemblyDefinition.Write (System.String fileName)
XLua.Hotfix.HotfixInject () (at Assets/XLua/Src/Editor/Hotfix.cs:263)

点击 生成GenerateCode报错，参考https://groups.google.com/forum/#!topic/mono-cecil/2YrccvV3dpY 加了AddSearchDirectory还是一样的错误

**Comment by chexiongsheng** [comment]
更新了最新的代码了么？AddSearchDirectory加的是什么目录？

**Comment by mydishes** [comment]
是最新的代码,AddSearchDirectory目录加    ./Library/UnityAssemblies/UnityEditor.dll

**Comment by mydishes** [comment]
换成./Library/UnityAssemblies目录是可以的了,tks~ 自己半天没看出来

**Comment by Sparrowfc** [comment]
你添加包含UnityEngine.dll的路径了么？我昨天也遇到同样的问题，添加一下就解决了

**Comment by chexiongsheng** [comment]
昨天的版本是有./Library/UnityAssemblies的
有的Unity版本没有./Library/UnityAssemblies
所以我改成：
resolver.AddSearchDirectory(System.IO.Path.GetDirectoryName(typeof(GameObject).Module.FullyQualifiedName));
难道这改法不兼容有./Library/UnityAssemblies的版本么？
麻烦帮忙确认下

**Comment by mydishes** [comment]
git上在哪里加的 resolver.AddSearchDirectory？我更新了没有搜到

**Comment by chexiongsheng** [comment]
是冲突了没更新成功吧？

**Comment by chexiongsheng** [comment]
https://github.com/Tencent/xLua/blob/master/Assets/XLua/Src/Editor/Hotfix.cs#L54

**Comment by chexiongsheng** [comment]
帮忙确认下，你的代码是不是这样？这样在你的版本会不会有问题？

**Comment by mydishes** [comment]
刚刚是没更新成功，现在用最新的放过去，生成代码没有打印hotfix inject finish!。。。lua代码可以执行

**Comment by chexiongsheng** [comment]
没打印是因为没触发Assets下的编译
你随便改改代码试试，等hotfix inject finish!

**Comment by chexiongsheng** [comment]
用新的方式应该是各版本通用的。

**Comment by mydishes** [comment]
有打印这个  finished! use 808 ms的

**Comment by chexiongsheng** [comment]
这个是生成代码的打印，菊花转完应该有hotfix inject finish!的

**Comment by chexiongsheng** [comment]
随便在一个文件加个空格保存都可以触发hotfix inject

**Comment by mydishes** [comment]
转完了的，看到Assembly-CSharp.dll文件都生成了，就是没有打印hotfix inject finish!

**Comment by chexiongsheng** [comment]
不可能吧，你关闭了log的显示吧

**Comment by mydishes** [comment]
can not find delegate for FileCtrl.get_VERSIONCODE! try re-genertate code.
UnityEngine.Debug:LogWarning(Object)
XLua.Hotfix:injectMethod(AssemblyDefinition, MethodDefinition, Int32, FieldReference) (at Assets/XLua/Src/Editor/Hotfix.cs:341)
XLua.Hotfix:injectType(AssemblyDefinition, TypeReference, TypeDefinition) (at Assets/XLua/Src/Editor/Hotfix.cs:237)
XLua.Hotfix:HotfixInject() (at Assets/XLua/Src/Editor/Hotfix.cs:275)
有这样的警告

**Comment by chexiongsheng** [comment]
哦，那就是没成功了。。
你执行下xlua/generate code

**Comment by mydishes** [comment]
我那个类去掉就有了，应该是有的类生成失败了？警告不好看到啊

**Comment by chexiongsheng** [comment]
我改为错误日志好了
你执行下xlua/generate code看看能出hotfix inject finish!不

**Comment by mydishes** [comment]
可以了，有打印了:)

**Comment by chexiongsheng** [comment]
好的，谢谢！

**Comment by mydishes** [comment]
刚刚测试有构造函数的类，用hotfix就会警告 can not find delegate for Tssss..ctor! try re-genertate code. 然后生成失败！

**Comment by chexiongsheng** [comment]
从新执行下xlua/generate code

**Comment by mydishes** [comment]
试过很多次了，每次都先clean再generate

**Comment by chexiongsheng** [comment]
要等编译完成再generate
还是不行，贴下你那类

**Comment by mydishes** [comment]
编译完成是什么意思？我这个就正常加的一个测试类哦
`[Hotfix]
class Tssss
{
   public Tssss()
    {

    }
}`

**Comment by chexiongsheng** [comment]
就是等菊花转完才执行generate。

这个类没什么特别，我加了可以的。
目前已知有两个项目把整个工程都加Hotfix了。我这里也测试了把NGUI全部类型都加的，都能通过。

**Comment by mydishes** [comment]
https://github.com/Tencent/xLua/blob/master/Assets/XLua/Src/Editor/Hotfix.cs#L235
这里的ctor多了个c了

**Comment by mydishes** [comment]
去掉就过了

**Comment by chexiongsheng** [comment]
晕。。。

**Comment by chexiongsheng** [comment]
没多，那个是过滤掉静态构造函数

**Comment by chexiongsheng** [comment]
你这是把构造函数都过滤了

**Comment by chexiongsheng** [comment]
估计你那工程有问题，建议你重新clone一份

**Comment by mydishes** [comment]
。。。。ok,那我重新弄个工程看下

**Comment by chexiongsheng** [comment]
可能是你之前那里改出问题了

**Comment by mydishes** [comment]
现在可以了，还有个问题 有 get 属性返回其他私有参数就会生成失败。。而且去除该属性后还不能用，需要重新添加库，重启项目才可以。

**Comment by chexiongsheng** [comment]
“有 get 属性返回其他私有参数就会生成失败”贴下代码？
别动不动就删啥的，反馈解决就好了。

**Comment by mydishes** [comment]
没删xlua代码的，我在测试用了我一个类生成失败的原因。在新建工程测试第一次失败，后面又可以。但是我原工程上一直不行。

[Hotfix]
public class Hotfixxxx
{
    Hotfixxxx()
    {

    }

    private string _sss;
    public string SSS { get { return _sss; } }


    void addSearchCache(string text)
    {
    }
    
    IEnumerable onDownload()
    {
        yield break;
    }
}

**Comment by chexiongsheng** [comment]
我那仍然是没问题的。

你unity版本是？

**Comment by chexiongsheng** [comment]
而且你那类也没啥特别。有两个大项目整个工程都加了Hotfix，应该不会有很低级的错误。

另外，你的cecil库从哪里搞过来的？

**Comment by mydishes** [comment]
5.4.3f1,cecil库是文档写的路径拷的。。。Generate 会有读哪的缓存吗，我新建的项目测试又可以了。

**Comment by chexiongsheng** [comment]
你每次添加一个新的hotfix类型，或者新增一个接口，都要等待编译完成后，重新执行Generate Code菜单！
应该你的问题出在这里。

**Comment by chexiongsheng** [comment]
任何对hotfix类型的增加或者修改，都要重新执行Generate Code菜单。
另外，提示不是很明确了么？re-generate

**Comment by mydishes** [comment]
有的每次都重新执行Generate Code菜单的。找不到原因了，我直接整个游戏工程拷到新那个工程原生成就可以，原来那边重加xlua关闭重启项目都没用。

**Comment by chexiongsheng** [comment]
要等待编译完成后才执行Generate Code。马上改完马上generate没用。
关闭重启没用，hotfix是你改了代码才会触发注入。

无脑一点，看到提示re-generate，你就re-generate一下。

**Comment by mydishes** [comment]
没有转菊花游戏都可以跑了也还没编译完成吗，没看过提示re-generate

**Comment by chexiongsheng** [comment]
“没删xlua代码的，我在测试用了我一个类生成失败的原因。在新建工程测试第一次失败，后面又可以。但是我原工程上一直不行。”
生成失败指的是？

**Comment by mydishes** [comment]
can not find delegate for FileCtrl.get_VERSIONCODE! try re-genertate code.  类似这样的提示

**Comment by chexiongsheng** [comment]
额，里头不是有“ re-genertate ”么。。。

**Comment by mydishes** [comment]
哦，是这个啊。但是我那个项目出现这个提示后点生成还是一样报这个错。

**Comment by chexiongsheng** [comment]
额，，看整个讨论过程，觉得你误操作的可能性比较大。。好了，总之现在行就可以了。

**Comment by mydishes** [comment]
有邮箱吗，我这里有个测试的项目怎么生成都生成不了，发给你看下？

**Comment by chexiongsheng** [comment]
chexiongsheng@qq.com

**Comment by mydishes** [comment]
有收到邮件吗，我已经发了

**Comment by chexiongsheng** [comment]
知道原因了，是那个class没有声明成public的原因，已经修复了，请更新下代码。
谢谢了，呵呵

**Comment by mydishes** [comment]
= =！更新了，我这里看有协程还是会生成失败！
    IEnumerable onDownload()
    {
        yield break;
    }

**Comment by chexiongsheng** [comment]
我在你那工程添加了这个，可以。。
你是不是又没re-generate？

**Comment by chexiongsheng** [comment]
直接用你那工程没问题

你那有啥提示？

**Comment by mydishes** [comment]
下午比较忙，忘记回啦。现在测试问题找到了。有个函数传参用的是私有结构体，把结构体改成public就可以了。谢啦! :)

**Comment by chexiongsheng** [comment]
参数私有结构体也支持啊……
总之，目前除了静态构造函数，什么情况都要都支持。
你把你确认不行的工程发给我。

**Comment by mydishes** [comment]
发了哈，就下面这段
[Hotfix]
class STTTTT
{

    struct SData
    {
        public int v;
    }

    IEnumerator update(List<SData> d)
    {
        yield break;
    }
}

**Comment by chexiongsheng** [comment]
List<SData>这种确实有问题，已经修复了。

**Comment by sisufo** [comment]
我的主要目的还是桌面开发传统winform客户端如何进行hotfix，github上的测试代码 XLuaTest 中的hotfix还是无法起作用，所以问了您之后说是，需要先进行 XLuaHotfixInject，但是尝试了多次还是无果

我的处理方法：
执行 `XLuaHotfixInject.exe XLuaTest.exe “”` （因为不知道search path 和 id_map_file_path 怎么填）

然后，就会报错

~~~
Error:Exception! System.InvalidOperationException: 序列不包含任何匹配元素
   在 System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   在 XLua.Hotfix.init(AssemblyDefinition assembly, IEnumerable`1 search_directorys) 位置 F:\xLua\Assets\XLua\Src\Editor\Hotfix.cs:行号 122
   在 XLua.Hotfix.HotfixInject(String inject_assembly_path, IEnumerable`1 search_directorys, String id_map_file_path, IEnumerable`1 cfg_check_types) 位置 F:\xLua\Assets\XLua\Src\Editor\Hotfix.cs:行号 473
~~~

看了代码，是要加载XLua.HotfixAttribute这些类型找不到，而这些类型只存在于 XLua.Mini.dll中，不在 XLuaTest.exe里，我就改了一些代码，从XLua.Mini.dll加载类型，然后再继续inject到 XLuaTest中，然后 又报错了

~~~
Error:Exception! System.ArgumentException: Member 'XLua.DelegateBridge' is declared in another module and needs to be imported
   在 Mono.Cecil.MetadataBuilder.LookupToken(IMetadataTokenProvider provider)
   在 Mono.Cecil.SignatureWriter.WriteTypeSignature(TypeReference type)
   在 Mono.Cecil.MetadataBuilder.AddField(FieldDefinition field)
   在 Mono.Cecil.MetadataBuilder.AddFields(TypeDefinition type)
   在 Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   在 Mono.Cecil.MetadataBuilder.AddTypeDefs()
   在 Mono.Cecil.MetadataBuilder.BuildTypes()
   在 Mono.Cecil.MetadataBuilder.BuildModule()
   在 Mono.Cecil.ModuleWriter.<BuildMetadata>b__0(MetadataBuilder builder, MetadataReader _)
   在 Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   在 Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   在 Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Stream stream, WriterParameters parameters)
   在 Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   在 Mono.Cecil.AssemblyDefinition.Write(String fileName)
   在 XLua.Hotfix.HotfixInject(String inject_assembly_path, String xlua_dll_path, IEnumerable`1 search_directorys, String id_map_file_path, IEnumerable`1 cfg_check_types) 位置 C:\Users\space\workspace\source\xLua\Assets\XLua\Src\Editor\Hotfix.cs:行号 513
~~~

现在感觉，有点误入歧途的感觉，求解惑；

万分感谢
