### ISSUE TITLE
build ios error  按照正常，ios build 失败

### ISSUE THREAD

**Issue by FGSEA** [Tencent/xLua#676]
-- Not setting any manual command-line buildflags, since Xcode is selected as generator.
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.14/Modules/Platform/iOS-Initialize.cmake:4 (message):
  iphoneos is not an iOS SDK
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.14/Modules/CMakeSystemSpecificInitialize.cmake:21 (include)
  CMakeLists.txt:16 (project)

-- Configuring incomplete, errors occurred!
See also "/Users/fg/Desktop/xlua/XLuaGit3/xLua/build/build_ios/CMakeFiles/CMakeOutput.log".
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
cp: build_ios/Release-iphoneos/libxlua.a: No such file or directory

**Comment by FGSEA** [comment]
cmake 是官网下载直接装的

**Comment by chexiongsheng** [comment]
没装xcode，或者xcode没桩ios的sdk吧

**Comment by FGSEA** [comment]
有装xcode， xcode 可以正常导出 ipa包，是xcode没配置好吗？

**Comment by FGSEA** [comment]
谢谢大佬 chexiongsheng  是xcode 默认路径问题；已解决
https://blog.csdn.net/li15809284891/article/details/79629190
在运行脚本的时候遇到一个问题，报错"
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

"

在网上查找资料，最后根据http://blog.csdn.net/woaizijiheni/article/details/50614062这篇博客终于解决，仅以此记录一下自己遇到的问题

1. 执行运行脚本的命令：报错如下“

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

”

2. 执行“

xcodebuild -showsdks

”，报错如下“
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

”

3. 执行“

sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer/

”切换到当前Xcode路径下

4. 执行"

 xcodebuild -showsdks
————————————————
版权声明：本文为CSDN博主「li15809284891」的原创文章，遵循 CC 4.0 BY-SA 版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/li15809284891/article/details/79629190
