### ISSUE TITLE
请问xlua可以打印lua的内存快照吗

### ISSUE THREAD

**Issue by l1000965431** [Tencent/xLua#68]

**Comment by chexiongsheng** [comment]
有写一个这样的工具，只是简单测试了，没人用过。看下Doc目录的《XLua性能分析工具.doc》

**Comment by LetGo** [comment]
请问	memory = memory or require('Luascripts/Common/Base/memory')
	memory.total() 这里的total 跟快照当中所获取TYPE_NAME = {'GLOBAL', 'REGISTRY', 'UPVALUE', 'LOCAL'}四个类型的所有的Size 是什么关系呀？ 我发现我清空的时候memory.total() 没降却升，但是快照计算的所有SIZE 是下降的 有点懵逼呀。。。

**Comment by chexiongsheng** [comment]
memory.total统计的是当前内存占用，而lua内存占用要等一趟gc完成后才回收（所有带gc的语言都一样）

**Comment by LetGo** [comment]
可是我等了好一会memory.total都没下降 lua代码没继续执行了，而且 memory.total 只要执行操作就一直涨。 请问这个咋搞捏。。这个是内存泄漏么？？

**Comment by chexiongsheng** [comment]
lua的gc不是等就进行的。

你可以主动来一次全量gc
