### ISSUE TITLE
通过Get<object>取int，得到long的object装箱，而不是int的object装箱。

### ISSUE THREAD

**Issue by KumoKyaku** [Tencent/xLua#680]
https://github.com/Tencent/xLua/blob/d026ce238c48ec5ac6bd17f7d5cfec7d848632e3/Assets/XLua/Src/ObjectCasters.cs#L337

如果lua侧是一个int32值，必然满足LuaAPI.lua_isint64，此处应该是if判断顺序错误。

**Comment by chexiongsheng** [comment]
lua没有int32。只有int64

**Comment by KumoKyaku** [comment]
那么假如lua侧值100，通过get<object>取值，返回long的装箱object是预期行为吗？为什么不返回int的装箱？

**Comment by chexiongsheng** [comment]
即使按你的思路，100也不会是int，c#的整数有8种，按最新小取值范围是sbyte：
https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/builtin-types/integral-numeric-types
而且你的思路本身就是错误的，类型不是由值范围决定的，一个long也可以是0，相反，是类型决定值范围，你因果都搞反了。

**Comment by chexiongsheng** [comment]
不过你想做的事是可以办得到的，在C#侧或者lua侧都可以指定要转的类型，自己在文档和例子里找下。

**Comment by KumoKyaku** [comment]
了解
