### ISSUE TITLE
2018.4.9.f1,inject得时候报错。请问是什么问题？

### ISSUE THREAD

**Issue by mrwhale89** [Tencent/xLua#685]
![image](https://user-images.githubusercontent.com/58911025/70883996-984cf500-200f-11ea-8716-091e213452ee.png)

**Comment by chexiongsheng** [comment]
你自己的配置？这是配置里头抛异常了

**Comment by chexiongsheng** [comment]
配置里不能调用unity的api，只能用C#的系统api

**Comment by mrwhale89** [comment]
我发现问题了。忘记换tool了。
