### ISSUE TITLE
trouble with overload functions inside xlua wrapper

### ISSUE THREAD

**Issue by CGWang** [Tencent/xLua#687]
I was using Raycast in lua, and found some bugs with overload functions in XLua\Gen\UnityEnginePhysicsWrap.cs

For example, in function '_m_Raycast_xlua_st_', there are several if statements with same conditions

`L290: if(gen_param_count == 1&& translator.Assignable<UnityEngine.Ray>(L, 1)) ...`
`L313: if(gen_param_count == 1&& translator.Assignable<UnityEngine.Ray>(L, 1)) ...`

so I cannot call the Raycast funciton in L313, since the first if statement was fully satified.

So any solution for my to modify the wapper template code?

**Comment by chexiongsheng** [comment]
write anther class 
~~~csharp
class UnityEnginePhysics //any name you like
{
    public bool Raycast(UnityEngine.Ray ray, UnityEngine.RaycastHit hitInfo) // call this one in lua instead
    {
         return UnityEngine.Physics.Raycast( ray, out hitInfo );
   }
}
~~~

**Comment by CGWang** [comment]
Got it.
One more word: any plan for solving this in wrapper classes ?

**Comment by chexiongsheng** [comment]
This problem is essentially caused by the different types of richness of the two languages, which cannot be solved by wrapper classes change, for example: 
~~~csharp
//csharp
class A
{
    void Foo(short a) {}
    void Foo(int a) {} 
}
~~~

~~~lua
--lua
local obj = CS.A()
obj:Foo(1)  -- which one?
~~~

**Comment by CGWang** [comment]
yeah, it's a language level problem, lua could not fit all the variable types for cs function signature.

I will try the workround you suggested. 
Thx so much.
