### ISSUE TITLE
Unity2019.2.11 上CSharpCallLua标签对interface不生效

### ISSUE THREAD

**Issue by boswelyu** [Tencent/xLua#689]
使用Unity2019.2.11f版本运行Lua Tutorial中的CSharpCallLua 脚本，运行到 
ItfD d3 = luaenv.Global.Get<ItfD>("d"); 
时，会报错：
InvalidCastException: This type must add to CSharpCallLua: LuaDemo+ItfD
XLua.LuaTable.Get[TKey,TValue] (TKey key, TValue& value) (at Assets/XLua/Src/LuaTable.cs:65)
XLua.LuaTable.Get[TValue] (System.String key) (at Assets/XLua/Src/LuaTable.cs:333)
LuaDemo.Start () (at Assets/Scripts/LuaDemo.cs:77)

interface的定义上已经添加了CSharpCallLua标签。
    [CSharpCallLua]
    public interface ItfD
    {
        int f1 { get; set; }
        int f2 { get; set; }
        
        int add(int a, int b);
    }

**Comment by boswelyu** [comment]
环境问题，可以了

**Comment by sbfkcel** [comment]
是什么环境问题？
