### ISSUE TITLE
选型疑问

### ISSUE THREAD

**Issue by hsl4125** [Tencent/xLua#69]
利用xlua可以大部分逻辑用lua写，也可以只是利用hotfix。这两种做法个有各的优势。腾讯内部应该有一些项目用上xlua了吧。这些项目是怎么用的？可以介绍一下经验吗？

**Comment by chexiongsheng** [comment]
如果你只是fix下bug，选hotfix是最好的。
如果有某个系统，比如活动系统，要经常更新，那用lua来实现更划算。

hotfix是新开发的功能，你看相关文章介绍也知道了，是12月末才开发完成，这功能还没发正式版本（预计这种发）。所以内部项目之前肯定都是用lua来写逻辑。但这个功能公布后，有一些项目感兴趣，向我要正式版。

**Comment by chexiongsheng** [comment]
还有要考虑你的团队，有很多人就不喜欢lua或者很喜欢lua。
另外，两语言混合编程，很多时候开发效率不高。
