### ISSUE TITLE
2019.2.17f1打包无法被正常注入

### ISSUE THREAD

**Issue by leechking1987** [Tencent/xLua#691]
测试了一下用master分支上的最新版在2019.2.17f1上面Editor下面能正常hotfix，但是打Windows和安卓包均无法hotfix，提示类似于“xlua.access, no field __Hitfix0_Update”，就像是打的包没有被注入一样。同的项目在2019.1.14f1和2018.4.14f1上面出包均没有问题，怀疑是2019.2版本修改了什么导致打包时的注入无效

**Comment by chexiongsheng** [comment]
新版本Unity把编译后dll放置的目录更改了
这有人解决了：https://github.com/Tencent/InjectFix/issues/66

**Comment by leechking1987** [comment]
我自己尝试解决了一下，修改了Hotfix中HotfixInject函数中injectAssemblyPaths里面injectAssemblyPath的值，把ScriptAssemblies修改成了PlayerScriptAssemblies，工具最后打印也是成功inject了PlayerScriptAssemblies中的dll，但是最后打出来的包表现还是注入失败，不知道能否指点下还需要修改什么地方？官方对这个版本的支持有计划吗？

**Comment by chexiongsheng** [comment]
你可能改错地方了，改这里：https://github.com/Tencent/xLua/blob/master/Assets/XLua/Src/Editor/Hotfix.cs#L1631

**Comment by leechking1987** [comment]
啊，不好意思我忘记说明了，我最开始就是改的这里，发现无效才去改了其他地方的。因为我看这个assembly_csharp_path被赋值到了args的第一个参数，而后面arg[0]又被赋值成了injectAssemblyPath，所以才去改了那边。我打包的过程中观察到确实有PlayerScriptAssemblies这个临时文件夹生成，注入工具打印的日志也确实是这个路径，不过最终表现就是没有注入成功

**Comment by chexiongsheng** [comment]
哦，应该是改这个函数的实现：https://github.com/Tencent/xLua/blob/master/Assets/XLua/Src/Editor/Hotfix.cs#L1669

**Comment by chexiongsheng** [comment]
你是咋改的？

**Comment by leechking1987** [comment]
https://github.com/Tencent/xLua/blob/452c99149668d6eb13198dd5d1a4e2488e6badc7/Assets/XLua/Src/Editor/Hotfix.cs#L1631
修改为了
var assembly_csharp_path = "./Library/PlayerScriptAssemblies/Assembly-CSharp.dll";
https://github.com/Tencent/xLua/blob/452c99149668d6eb13198dd5d1a4e2488e6badc7/Assets/XLua/Src/Editor/Hotfix.cs#L1673
修改为了
string realPath = injectAssemblyPath.Replace("ScriptAssemblies", "PlayerScriptAssemblies");
args[0] = realPath.Replace('\\', '/');
此外https://github.com/Tencent/xLua/blob/452c99149668d6eb13198dd5d1a4e2488e6badc7/Assets/XLua/Src/Editor/Hotfix.cs#L1681
修改为了
var injectAssemblyFileName = Path.GetFileName(realPath);
感觉是应该有某些东西漏了

**Comment by chexiongsheng** [comment]
1631行那赋值是没用的，赋值成啥都不影响。
这是当年只支持Assembly-CSharp.dll时的代码，后面加上了Assembly-CSharp.dll之外的dll的支持，实际起作用的是args[0]，你可以在赋值给args[0]前，把injectAssemblyPath改了。

**Comment by leechking1987** [comment]
是的，我就是这么改的，我在1673赋值给args[0]之前就把injectAssemblyPath里面的ScriptAssemblies给替换成PlayerScriptAssemblies了（见我之前的回复），实际输出的log也显示注入的是这个目录下的代码，不过实际打包出来就是不生效，是不是还有什么顺序上的问题？

**Comment by leechking1987** [comment]
问题解决了，仅仅修改args[0]还不够，将args里面所有的ScriptAssemblies替换成PlayerScriptAssemblies注入就成功了

**Comment by chexiongsheng** [comment]
> 问题解决了，仅仅修改args[0]还不够，将args里面所有的ScriptAssemblies替换成PlayerScriptAssemblies注入就成功了

好的

**Comment by lanyantao** [comment]
> 问题解决了，仅仅修改args[0]还不够，将args里面所有的ScriptAssemblies替换成PlayerScriptAssemblies注入就成功了

你好，打扰一下，我现在使用unity2019.4.0f1也出现了电脑上可以hotfix成功，打包出来apk就提示：xlua.access, no field __Hitfix0_Update，可以告知一下需要修改哪些地方吗，xlua版本我已经使用的最新的了。谢谢啦

**Comment by YangPeng124** [comment]
https://wjrsbu.smartapps.cn/zhihu/article?id=380745695&isShared=1&_swebfr=1&_swebFromHost=baiduboxapp我看这里解决了问题
