### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by datgamedev** [Tencent/xLua#693]
I have a simple Unity project using xLua, after exporting to Xcode and building, I got this error:

Undefined symbols for architecture arm64:
  "_xlua_is_eq_str", referenced from:
      _Lua_xlua_is_eq_str_m520195630AD5C7372F8C4DBB3115D76BD9195DE1 in Bulk_Assembly-CSharp_0

**Comment by datgamedev** [comment]
Never mind, it's because my libxlua was corrupted

**Comment by lulukdog** [comment]
> Never mind, it's because my libxlua was corrupted

how do u resolve it? can u show the screenshot step to add xlua.a?
