### ISSUE TITLE
luajit加密解密

### ISSUE THREAD

**Issue by zhaoyibo2014** [Tencent/xLua#698]
更新了xlua版本到xlua_v2.1.14_luajit.zip，用LuaJIT-2.1.0-beta3加密后报error loading module test.lua from CustomLoader, test.lua: cannot load incompatible bytecode 是xlua不能用luajit加密吗

**Comment by chexiongsheng** [comment]
那不叫加密，叫字节码。
支不支持字节码是luajit的事情，和xlua没关。
报这个错要么是你用的编译字节码程序不对（luajit的字节码是分32位和64位的，你要用对应，而且，版本号要一致），要么是你CustomLoader写得不对。

**Comment by zhaoyibo2014** [comment]
好的谢谢，我试试compatible_bytecode.md说的，先编成字节码，再用AES加密看看

**Comment by chexiongsheng** [comment]
compatible_bytecode.md只支持lua53版本的xlua

**Comment by zhaoyibo2014** [comment]
谢谢提醒，我目前用的就是lua5.3

**Comment by lihualinUnity** [comment]
你好，想请教一下。这个问题是怎么解决的呢。我这边也遇到了这个问题

**Comment by zhaoyibo2014** [comment]
你先看下大佬给我的回复，然后看下项目里的文档，按步骤来。要有一点是vs的版本注意下，我记得当时我用的vs2017不行，换了个低版本的就成了。重点是看文档

**Comment by lihualinUnity** [comment]
好的，谢啦
