### ISSUE TITLE
“某次性能测试” 的疑惑

### ISSUE THREAD

**Issue by HellGame** [Tencent/xLua#7]
Doc里的XLua介绍.ppt的倒数第二页 “附录：某次性能测试”，有些疑惑。
比如：
max              xlua    slua   ulua
6249375         1     0.15   0.21
是说执行6249375次，xlua用了一秒，slua和ulua分别用了0.15秒和0.21秒吗？
这样的话 XLua 岂不是要慢很多？

**Comment by chexiongsheng** [comment]
max是三者最高值，然后每个下面跟的数字代表的是到达最高的百分比。
比如1代表就是最高，0.15是最高的15%。

**Comment by chexiongsheng** [comment]
6249375是每秒调用次数。
1代表就是6249375
0.15代表6249375 * 0.15

**Comment by HellGame** [comment]
厉害了

**Comment by staare-zx** [comment]
所以性能上xlua是slua的2到10+倍？
