### ISSUE TITLE
新手学习xlua的疑惑

### ISSUE THREAD

**Issue by dingxiaowei** [Tencent/xLua#71]
新手学习了一下框架感觉很赞，但还是有两点小疑惑，希望老大解答一下：
1.关于为啥lua文件都是.txt后缀是出于什么样的考虑，因为这会影响到开发效率低问题，要手动改后缀，这样设计是不是出于安全性考虑？还是其他？。
2.看了例子知道lua调用C#脚本通过特性即可访问，那如果我想lua使用第三方插件，比如NGUI，有没有不在源码上添加特性更加快捷的方法，还是用CSObjectWrapEditor.GenCodeMenu这样生成Wrap？
希望老大抽空解答，感谢！

**Comment by chexiongsheng** [comment]
如果你放Resources下，不认.lua后缀，这是unity的规则，，只支持特定几个后缀，我选了个比较接近的，就txt了。
如果你用lua默认的加载器或者用Customloader是不受限制的，但unity不会帮你打包。我之前为了演示方便用Resources 比较多。
不用改源码都可以生成代码，请看Doc下关于配置的介绍，Example下也有例子。而且也不一定要生成代码才能调，还是看配置那篇文档

**Comment by dingxiaowei** [comment]
尝试了下是可以的，可以支持NGUI，感谢老大！但又碰到一个新的问题再请教，就是关于C#中带有ref参数的方法lua如何处理？我测试过貌似不是想要的结果
C#方法:
public void SayHelloWithRefParam(ref string s)
	{
		Debug.Log("传入的参数是:" + s);
		s = "Hello 我是C#";
	}

lua调用：
local inputValue = '你好，我是lua'
luaO2:SayHelloWithRefParam(inputValue)
print(inputValue)                          --这里还是原来的lua字符串
结果:
打印的结果还是“你好，我是lua”  并不是预期的“你好，我是C#”，这个怎么处理呢

**Comment by chexiongsheng** [comment]
ref修改后的值是通过返回值返回。
local r = uaO2:SayHelloWithRefParam(inputValue)
print(r)

这个打印就是你的预期

**Comment by dingxiaowei** [comment]
测试了下ref out都是通过字符串返回，并且测试了如果C#方法本身就有返回，那么lua是返回两个值，第一个值是C#的返回值，第二个值是ref的返回值！感谢老大热心解答！

**Comment by chexiongsheng** [comment]
还是建议仔细先看一遍教程以及配套的例子，这些都有。
