### ISSUE TITLE
luatable 如何转换为C#端的IList对象？

### ISSUE THREAD

**Issue by tenvick** [Tencent/xLua#710]
我用luatable实现了IList接口，但是在设置给C#端的时候还是table. 
lua代码
---设置子对象的context
---@overload fun(context:any)
---@param context any
local function set_children_context(self, context)
    local children = self._children
    local target_unity
    for k, child in ipairs(children) do
        child.context = context
    end
end

child为C#对象，context有可能是IList对象也有可能是普通luatable.

**Comment by chexiongsheng** [comment]
lua的table可以直接赋值给IList对象，会自动转换。
“设置给C#端的时候还是table”是什么意思？

**Comment by chexiongsheng** [comment]
> lua的table可以直接赋值给IList对象，会自动转换。
> “设置给C#端的时候还是table”是什么意思？

还有个前提，那个实现了IList接口的类必须是泛型。
