### ISSUE TITLE
构造函数，在特定指令数下，Hotfix之后，会提示指令目标无效

### ISSUE THREAD

**Issue by wuxiongbin** [Tencent/xLua#711]
VerificationException: Error in XLuaTest.TestHotfix:XLuaTest.TestHotfix:.ctor (int,int,long) Invalid instruction target fffffff5

测试代码如下,Hotfix之后，newTestHotfix对象，必定出现,经调试发现，特定指令长度下必出现,
构造函数在Hotfix之后，需要对指令重新计算下偏移再进行长度处理
在此行数上重新计算下指令偏移量，即可修复，
![image](https://user-images.githubusercontent.com/15257441/75946638-98ef7c00-5ed8-11ea-902b-3d2a008f799b.png)

[InstructionHelp.txt](https://github.com/Tencent/xLua/files/4290930/InstructionHelp.txt)
    [Hotfix]
    public class TestHotfix
    {
        static int Test(int type)
        {
            return 0;
        }

        int index = 0;
        int currencyType = 0;
        int currencyConfigLO = 0;

        public TestHotfix(int type, int code, long amount)
        {
            currencyType = code;

            switch (currencyType)
            {
            case 0:
                currencyConfigLO = Test(1);
                break;
            case 1:
                currencyConfigLO = Test(2);
                break;
            case 2:
                currencyConfigLO = Test(3);
                break;
            case 3:
                currencyConfigLO = Test(4);
                break;
            case 4:
                currencyConfigLO = Test(5);
                break;
            case 5:
                currencyConfigLO = Test(9);
                break;
            case 6:
                currencyConfigLO = Test(7);
                break;
            case 7:
                currencyConfigLO = Test(10);
                break;
            case 8:
                currencyConfigLO = Test(11);
                break;
            default:
                break;
            }
        }
    }

**Comment by chexiongsheng** [comment]
好的，我抽时间看看，谢谢

**Comment by chexiongsheng** [comment]
什么版本的unity呢？
我在unity5.6.6试了没报错，我把TestHotfix拷贝进来，new一个实例，注入后运行没问题。

**Comment by chexiongsheng** [comment]
new的参数是这样的：
new TestHotfix(1, 1, 1);

**Comment by wuxiongbin** [comment]
用Unity2019.2.21f1或Unity2019.3.2f1两个版本试试，
应该2019版本都会有这问题，这两个版本我试过有问题

**Comment by chexiongsheng** [comment]
我重现并修复了，你更新下试试
