### ISSUE TITLE
父类是泛型类时改如何hotfix类中的方法

### ISSUE THREAD

**Issue by oldLetter** [Tencent/xLua#716]
请问下类似这样的类，我想热更新其中的方法，该如何做呢
public class BlockManager : ManagerBase\<BlockManager\>
我试过hotfix.md里的方法都失败了

**Comment by chexiongsheng** [comment]
例子就有啊：https://github.com/Tencent/xLua/blob/master/Assets/XLua/Examples/08_Hotfix/HotfixTest2.cs

**Comment by oldLetter** [comment]
找到替换报错原因了，原来只是统一对Assembly-CSharp打了标签，没有给单独给BlockManager打，
 xlua.hotfix(CS.Game.Block.BlockManager, 'Test', function(self, a)
                    print('lua BlockManager', a)
                end)
            "
报错LuaException: xlua.access, no field __Hotfix0_Test，
暂时无法换包，请问有什么补救方法吗

**Comment by chexiongsheng** [comment]
上线前没注入就没救了。如果不注入也可以修复的话，我为啥还要搞这步呢？

**Comment by oldLetter** [comment]
好吧 ，麻烦了
