### ISSUE TITLE
类修复中LuaEnv的问题

### ISSUE THREAD

**Issue by davyxu** [Tencent/xLua#72]
请问xlua中的类修复方式, 为每个修复类都创建一个LuaEnv的实例, 这样会造成多个修复类跨LuaEnv访问共享数据造成巨大麻烦

试想:  如果要将C#共享数据给多个LuaEnv访问, 就要为每个LuaEnv注册一大堆的C#相同的访问器, 内存不说, 速度也是很慢的

如果要将lua共享给修复LuaEnv, 这个需要将数据通过C#转换到另外一个LuaEnv, 非常的麻烦

请问这样设计的目的是什么?
跨LuaEnv的数据共享如何处理?

谢谢

**Comment by chexiongsheng** [comment]
建议一个进程一个luaenv实例

**Comment by chexiongsheng** [comment]
如果是类修复，整个进程一个实例，在启动时加载一次lua脚本就可以了

**Comment by davyxu** [comment]
问题是: 生成的代码中是每个类一个LuaEnv

**Comment by chexiongsheng** [comment]
生成代码不new luaenv

**Comment by chexiongsheng** [comment]
你看那个是luaenv的引用而已，是你new的

**Comment by davyxu** [comment]
LuaEnv的构造函数里有做了new LuaState, 还做了很多的注册函数的操作. 我感觉这个并不是对C层做的引用吧?

**Comment by chexiongsheng** [comment]
你都说是构造函数了。构造函数是你new对象是调用的。
一个luaenv实例对应的是一个lua虚拟机实例

**Comment by davyxu** [comment]
1个LuaEnv=1个Lua虚拟机=1个LuaState+注册函数  是这个意思吧?

那我可以理解的是, 所有的LuaEnv里的lua代码可以互相访问对方的变量? 还是通过lua5.2之后的_ENV进行访问?

**Comment by chexiongsheng** [comment]
就一个lua虚拟机。你说的lua state对应的是协程。一个虚拟机有一个main state，就是主协程。
Lua的实现或者c#的语法就不讨论了。
重申下，你new一个luaenv，就是一个lua虚拟机(相当于你启动的一次lua命令)，里头的lua代码的交互就和你一次lua命令加载的脚本间交互一样

**Comment by davyxu** [comment]
ok, thanks
