### ISSUE TITLE
多个xlua间的数据通信

### ISSUE THREAD

**Issue by yysijie** [Tencent/xLua#720]
两个不同线程的xlua应该怎么互相访问数据。目前采用的方式是把table转换成json string，这个table比较大，转换的代价很高，想找到可以直接访问的方式，有没有什么建议呢？

**Comment by chexiongsheng** [comment]
没有直接访问的方式。
建议通过减少数据量，提高数据打解包效率的方式来提高性能。

**Comment by chexiongsheng** [comment]
还有一种方式，数据不要放table，而是放在和lua无关的数据结构，比如C结构体，两个虚拟机间传指针即可。又比如C#的class，两边都通过个C#对象来交换数据。

**Comment by yysijie** [comment]
多谢！
