### ISSUE TITLE
怎样导出泛型容器Dictionary<string, object>？

### ISSUE THREAD

**Issue by jerry-zeng** [Tencent/xLua#721]
看FAQ，这类容器是用反射的方式调用，代码量不多。
我想把使用频率最高的几个容器提前导出，是不是就不用反射调用了？
把它配到LuaCallCSharp，但是生成的wrap类，其中构造函数有非常多的重载，而且还报错。其实只用无参的构造函数就够了，需要剔除，但是这个泛型类的名字很长，不知道怎么剔除，要怎么加到[BlackList]列表呢？

**Comment by chexiongsheng** [comment]
“把它配到LuaCallCSharp，但是生成的wrap类，其中构造函数有非常多的重载，而且还报错。其实只用无参的构造函数就够了，需要剔除，但是这个泛型类的名字很长，不知道怎么剔除”
--这个看faq的“Unity 2018兼容性问题解决”

**Comment by jerry-zeng** [comment]
谢谢雄哥，解决了。那个配置好久没看过了，不知道还加了这个。
