### ISSUE TITLE
能不能把byte[]对应string的设定去掉?

### ISSUE THREAD

**Issue by sFisherE** [Tencent/xLua#723]

**Comment by sFisherE** [comment]
这个设计对我目前的项目很不适合，有什么简单的改法去掉？

**Comment by chexiongsheng** [comment]
没有太简单的方式，要把三种实现，生成代码，反射，和emit都分别改掉。不过貌似也没太复杂。

**Comment by sFisherE** [comment]
> 没有太简单的方式，要把三种实现，生成代码，反射，和emit都分别改掉。不过貌似也没太复杂。

哇，大佬的回复速度值得点赞！
我们项目是ulua升级过来的。所以非常需要这个功能，能不能支持下。

**Comment by sFisherE** [comment]
改了改，看起来可以用了。
