### ISSUE TITLE
为什么不提供dofile方法？

### ISSUE THREAD

**Issue by sFisherE** [Tencent/xLua#724]
比如我在编辑器下面dofile的话，如果脚本出错，可以按脚本路径来输出信息，但是dostring的话就不行。或者有别的更好的方式？

**Comment by chexiongsheng** [comment]
dostring里头不是可以require么？甚至不用用dostring。require可以直接映射到一个C#的delegate里头，就像首页演示的math.max函数一样。

**Comment by sFisherE** [comment]
> dostring里头不是可以require么？甚至不用用dostring。require可以直接映射到一个C#的delegate里头，就像首页演示的math.max函数一样。

require不是reload，调试的过程会经常要reload一个脚本

**Comment by chexiongsheng** [comment]
清下缓存就是reload。
