### ISSUE TITLE
文档是不是有问题，delegate在lua侧是userdata，文档写的是function

### ISSUE THREAD

**Issue by sFisherE** [Tencent/xLua#726]

**Comment by chexiongsheng** [comment]
userdata和function吧。一个function也可以直接赋值给delegate，这是大多数的场景。delegate传入lua是userdata。

**Comment by chexiongsheng** [comment]
你们不是在搞tolua换xlua么？刚好有另外一个项目也计划换，我帮那项目问下工作量有多大。

**Comment by sFisherE** [comment]
> 你们不是在搞tolua换xlua么？刚好有另外一个项目也计划换，我帮那项目问下工作量有多大。

大致已经替换完成了，工作量其实还好，主要是qa测试覆盖度还不够全，偶尔有一些遗漏的地方需要处理。
