### ISSUE TITLE
lua继承使用问题

### ISSUE THREAD

**Issue by hsl4125** [Tencent/xLua#73]
现在有一个关于lua继承使用的问题，标记导出MeshRender类，然后想再lua代码访问父类Render的Materials属性，但是无法获取父类的该属性，该功能应该如何实现？？

**Comment by chexiongsheng** [comment]
支持的，子类实例直接可以访问父类的东西。
检查是不是大小写错误，或者那个属性不是public的，或者贴下你代码。

**Comment by dongxue** [comment]
子类可以直接访问父类的public属性和方法？protected可以访问吗？

**Comment by chexiongsheng** [comment]
@dongxue 子类实例上，C#在外部也是调用不了protected方法的，protected是子类本身的实现可以使用。

如果你用lua方法替换c#方法的时候，想访问父类protected的东东，可以通过xlua.private_accessible实现。

**Comment by dongxue** [comment]
protected override void sayHi()
{
     base.sayHi();
     Debug.log("hi in child");
}
用lua来hotFix这个方法的话，如果调用父类的sayHi呢？

**Comment by chexiongsheng** [comment]
这种的话目前不支持，你调用父类的sayHi还是通过虚表引用到子类的方法。
而base.sayHi();是编译器帮你通过call指令去指定调用父类方法（一般是callvirt），目前没想到用比较常规的方法去实现。
你把父类的sayHi也在lua那实现一遍好了。

**Comment by dongxue** [comment]
这个后续有优化的可能么？

**Comment by chexiongsheng** [comment]
目前看不会，到时有方案支持，但会进一步增加注入的代码，进而增加安装包大小。而打补丁也不是很频繁的行为，碰到这种实现一遍问题不大。。为这增加安装包大小得不偿失。

**Comment by dongxue** [comment]
嗯，现在我在写可能需要hotfix的C#的时候都尽量规避需要重写父类的情况
