### ISSUE TITLE
HotfixTest场景在Unity2019.2.18f1打出的Android包上运行报错，报xlua.access, no field __Hotfix0_Update。在Unity2018上打出来的Android包是好的。打Android包前确定加了HOTFIX_ENABLE定义和执行了Generate Code。

### ISSUE THREAD

**Issue by lisiliang** [Tencent/xLua#732]

**Comment by chexiongsheng** [comment]
应该是新版本unity把dll换了个放置目录导致，在injectfix那已经有人改了，可以参考改下：https://github.com/Tencent/InjectFix/pull/68

**Comment by lisiliang** [comment]
好的，非常感谢车大大百忙之中抽时间回复。😀

chexiongsheng <notifications@github.com> 于2020年4月21日周二 下午5:36写道：

**Comment by sowyer888** [comment]
15085-15104/? E/Unity: LuaException: xlua.access, no field __Hotfix0_Update
    stack traceback:
    	[C]: in field 'access'
    	[string "Init"]:101: in field 'hotfix'
    	[string "chunk"]:2: in main chunk
      at XLua.LuaEnv.ThrowExceptionFromError (System.Int32 oldTop) [0x00050] in <d5639ea731764915b3c6f9bd7e864862>:0 
      at XLua.LuaEnv.DoString (System.Byte[] chunk, System.String chunkName, XLua.LuaTable env) [0x00072] in <d5639ea731764915b3c6f9bd7e864862>:0 
      at XLua.LuaEnv.DoString (System.String chunk, System.String chunkName, XLua.LuaTable env) [0x0000c] in <d5639ea731764915b3c6f9bd7e864862>:0 
      at XLuaTest.HotfixTest.OnGUI () [0x00025] in <d5639ea731764915b3c6f9bd7e864862>:0 
     
    (Filename: <d5639ea731764915b3c6f9bd7e864862> Line: 0)


----------------------------
在Unity2019.3.10f1同样出现这个问题， 改过目录后仍不起效，请问您解决了吗？
解决方案能否共享一下，谢谢！！

**Comment by mansamtsui** [comment]
> 应该是新版本unity把dll换了个放置目录导致，在injectfix那已经有人改了，可以参考改下：[Tencent/InjectFix#68](https://github.com/Tencent/InjectFix/pull/68)

查了一下发现2019.2.后dll路径需要到Temp/StagingArea/Data/Managed/Assembly-CSharp.dll这里进行inject。需要在IPostBuildPlayerScriptDLLs这个时机，BuildReport report里的files列表寻找dll，希望能修改下兼容2019的情况。谢谢

**Comment by mansamtsui** [comment]
另外还建议下能考虑使用upm后的分dll情况，注入il的时候Assembly-CSharp.dll是依赖xlua的dll，需要ImportReference方式返回注入MethodReference才行。谢谢楼主

**Comment by chexiongsheng** [comment]
> 另外还建议下能考虑使用upm后的分dll情况，注入il的时候Assembly-CSharp.dll是依赖xlua的dll，需要ImportReference方式返回注入MethodReference才行。谢谢楼主

如果分dll，用injectfix会支持得比较好。2019的兼容，如果你可以尝试修改下，提个PR过来。

**Comment by mansamtsui** [comment]
> > 另外还建议下能考虑使用upm后的分dll情况，注入il的时候Assembly-CSharp.dll是依赖xlua的dll，需要ImportReference方式返回注入MethodReference才行。谢谢楼主
> 
> 如果分dll，用injectfix会支持得比较好。2019的兼容，如果你可以尝试修改下，提个PR过来。

哦哦。其实我们是需要70%的lua开发业务的，明白了，谢谢楼主回复。

**Comment by chexiongsheng** [comment]
> > > 另外还建议下能考虑使用upm后的分dll情况，注入il的时候Assembly-CSharp.dll是依赖xlua的dll，需要ImportReference方式返回注入MethodReference才行。谢谢楼主
> > 
> > 
> > 如果分dll，用injectfix会支持得比较好。2019的兼容，如果你可以尝试修改下，提个PR过来。
> 
> 哦哦。其实我们是需要70%的lua开发业务的，明白了，谢谢楼主回复。

可以关闭xlua的hotfix特性，然后用injectfix做修复，两者可以共存

**Comment by mansamtsui** [comment]
> > > > 另外还建议下能考虑使用upm后的分dll情况，注入il的时候Assembly-CSharp.dll是依赖xlua的dll，需要ImportReference方式返回注入MethodReference才行。谢谢楼主
> > > 
> > > 
> > > 如果分dll，用injectfix会支持得比较好。2019的兼容，如果你可以尝试修改下，提个PR过来。
> > 
> > 
> > 哦哦。其实我们是需要70%的lua开发业务的，明白了，谢谢楼主回复。
> 
> 可以关闭xlua的hotfix特性，然后用injectfix做修复，两者可以共存

了解谢谢楼主回复

**Comment by chexiongsheng** [comment]
> > 应该是新版本unity把dll换了个放置目录导致，在injectfix那已经有人改了，可以参考改下：[Tencent/InjectFix#68](https://github.com/Tencent/InjectFix/pull/68)
> 
> 查了一下发现2019.2.后dll路径需要到Temp/StagingArea/Data/Managed/Assembly-CSharp.dll这里进行inject。需要在IPostBuildPlayerScriptDLLs这个时机，BuildReport report里的files列表寻找dll，希望能修改下兼容2019的情况。谢谢

你都研究到这程度了，就改下，提个PR过来吧。我主要是手头没有现成的环境，要搭建也比较费时间。

**Comment by heyChenfu** [comment]
请问这个问题解决了吗?看了下injectfix那里改的意思是Assembly-CSharp.dll不是放在./Library/ScriptAssemblies这个路径了, 但是我看了下我的2019.2.9这个目录还是有的。。。那我和楼主遇到的一样的问题要咋解决求助

**Comment by heyChenfu** [comment]
> 
> 
> 15085-15104/? E/Unity: LuaException: xlua.access, no field __Hotfix0_Update
> stack traceback:
> [C]: in field 'access'
> [string "Init"]:101: in field 'hotfix'
> [string "chunk"]:2: in main chunk
> at XLua.LuaEnv.ThrowExceptionFromError (System.Int32 oldTop) [0x00050] in :0
> at XLua.LuaEnv.DoString (System.Byte[] chunk, System.String chunkName, XLua.LuaTable env) [0x00072] in :0
> at XLua.LuaEnv.DoString (System.String chunk, System.String chunkName, XLua.LuaTable env) [0x0000c] in :0
> at XLuaTest.HotfixTest.OnGUI () [0x00025] in :0
> 
> ```
> (Filename: <d5639ea731764915b3c6f9bd7e864862> Line: 0)
> ```
> 
> 在Unity2019.3.10f1同样出现这个问题， 改过目录后仍不起效，请问您解决了吗？
> 解决方案能否共享一下，谢谢！！

老哥你这个问题后来怎么办。。。难道2019.2之后的版本就都用不了xlua了吗

**Comment by heyChenfu** [comment]
> 
> 
> > 应该是新版本unity把dll换了个放置目录导致，在injectfix那已经有人改了，可以参考改下：[Tencent/InjectFix#68](https://github.com/Tencent/InjectFix/pull/68)
> 
> 查了一下发现2019.2.后dll路径需要到Temp/StagingArea/Data/Managed/Assembly-CSharp.dll这里进行inject。需要在IPostBuildPlayerScriptDLLs这个时机，BuildReport report里的files列表寻找dll，希望能修改下兼容2019的情况。谢谢

大佬能不能贡献下你的修改, 我照着你的方案做真机上还是没有注入成功, 不知道哪里有遗漏

**Comment by heyChenfu** [comment]
> 
> 
> > > 应该是新版本unity把dll换了个放置目录导致，在injectfix那已经有人改了，可以参考改下：[Tencent/InjectFix#68](https://github.com/Tencent/InjectFix/pull/68)
> > 
> > 
> > 查了一下发现2019.2.后dll路径需要到Temp/StagingArea/Data/Managed/Assembly-CSharp.dll这里进行inject。需要在IPostBuildPlayerScriptDLLs这个时机，BuildReport report里的files列表寻找dll，希望能修改下兼容2019的情况。谢谢
> 
> 你都研究到这程度了，就改下，提个PR过来吧。我主要是手头没有现成的环境，要搭建也比较费时间。

大佬能不能解决下这个问题。。不然2019.2和以上的版本相当于没法用XLua了

**Comment by heyChenfu** [comment]
> 
> 
> > 应该是新版本unity把dll换了个放置目录导致，在injectfix那已经有人改了，可以参考改下：[Tencent/InjectFix#68](https://github.com/Tencent/InjectFix/pull/68)
> 
> 查了一下发现2019.2.后dll路径需要到Temp/StagingArea/Data/Managed/Assembly-CSharp.dll这里进行inject。需要在IPostBuildPlayerScriptDLLs这个时机，BuildReport report里的files列表寻找dll，希望能修改下兼容2019的情况。谢谢

多谢老哥的解决方案! 已经用你说的方法成功解决
首先根据https://docs.unity3d.com/2018.3/Documentation/ScriptReference/Build.IPostBuildPlayerScriptDLLs.OnPostBuildPlayerScriptDLLs.html官方文档上的做法写一个一模一样的Editor下的类, 里面的方法会在打包生成dll后触发, 然后从这个BuildReport中获取"Assembly-CSharp.dll"的路径交给Hotfix.HotfixInject, 用这个路径取代HotfixConfig.GetHotfixAssemblyPaths()给出的路径就行了

**Comment by lanyantao** [comment]
> > > 应该是新版本unity把dll换了个放置目录导致，在injectfix那已经有人改了，可以参考改下：[Tencent/InjectFix#68](https://github.com/Tencent/InjectFix/pull/68)
> > 
> > 
> > 查了一下发现2019.2.后dll路径需要到Temp/StagingArea/Data/Managed/Assembly-CSharp.dll这里进行inject。需要在IPostBuildPlayerScriptDLLs这个时机，BuildReport report里的files列表寻找dll，希望能修改下兼容2019的情况。谢谢
> 
> 多谢老哥的解决方案! 已经用你说的方法成功解决
> 首先根据[https://docs.unity3d.com/2018.3/Documentation/ScriptReference/Build.IPostBuildPlayerScriptDLLs.OnPostBuildPlayerScriptDLLs.html官方文档上的做法写一个一模一样的Editor下的类](https://docs.unity3d.com/2018.3/Documentation/ScriptReference/Build.IPostBuildPlayerScriptDLLs.OnPostBuildPlayerScriptDLLs.html%E5%AE%98%E6%96%B9%E6%96%87%E6%A1%A3%E4%B8%8A%E7%9A%84%E5%81%9A%E6%B3%95%E5%86%99%E4%B8%80%E4%B8%AA%E4%B8%80%E6%A8%A1%E4%B8%80%E6%A0%B7%E7%9A%84Editor%E4%B8%8B%E7%9A%84%E7%B1%BB), 里面的方法会在打包生成dll后触发, 然后从这个BuildReport中获取"Assembly-CSharp.dll"的路径交给Hotfix.HotfixInject, 用这个路径取代HotfixConfig.GetHotfixAssemblyPaths()给出的路径就行了

hello，打扰了，我目前用unity2019.4.0f1也遇到了相同的问题，找了很多办法都未成功，可以将您的方案告知一下么，谢谢啦。
