### ISSUE TITLE
CS.System.Text.Encoding.ASCII:GetBytes这个方法会执行失败

### ISSUE THREAD

**Issue by sFisherE** [Tencent/xLua#734]
测试代码：
print(CS.System.Text.Encoding.ASCII:GetBytes("xxx"))
报错：
LuaException: invalid arguments to GetBytes
stack traceback:
	[C]: in method 'GetBytes'
	[string "LuaTestScript"]:11: in main chunk

**Comment by caihan** [comment]
这不是个static的方法嘛？ 怎么用":"访问？

**Comment by chexiongsheng** [comment]
调用前加上这句试试
cast(CS.System.Text.Encoding.ASCII, typeof(CS.System.Text.Encoding))

**Comment by sFisherE** [comment]
原来如此，多谢指点！
