### ISSUE TITLE
使用最新版xlua，发布wengl报错，还请作者看下，谢谢

### ISSUE THREAD

**Issue by Destiny198523** [Tencent/xLua#735]
Failed running "E:\Program Files\Unity2018.2.8\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten_Win\python\2.7.5.3_64bit\python.exe" "E:\Program Files\Unity2018.2.8\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten\emcc" @"C:\Users\Administrator\Desktop\XLuaStudy\XLuaStudy\Assets\..\Temp\emcc_arguments.resp"

stdout:
stderr:WARNING:root:--separate-asm works best when compiling to HTML. Otherwise, you must yourself load the '.asm.js' file that is emitted separately, and must do so before loading the main '.js' file. [-Wseparate-asm]
C:\Users\Administrator\Desktop\XLuaStudy\XLuaStudy\Assets\Plugins\WebGL\xlua_webgl.cpp:2:10: fatal error: '../../../WebGLPlugins/lapi.c' file not found
#include "../../../WebGLPlugins/lapi.c"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by Destiny198523** [comment]
window10系统，64位。xlua使用的是2.1.13.在unity运行模式没问题，发布报以上错误，项目中的eplugins文件夹下也有webgl文件夹，下游xlua_webgl文件

**Comment by chexiongsheng** [comment]
fatal error: '../../../WebGLPlugins/lapi.c' file not found

你的包没带这目录。

**Comment by Destiny198523** [comment]
原来如此，忘了把WebGLPlugins放进项目了，完美解决，感谢
