### ISSUE TITLE
包含枚举的结构体不视为纯值类型么

### ISSUE THREAD

**Issue by snuc** [Tencent/xLua#737]
Cinemachine.AxisState因为包含枚举项m_SpeedMode，执行SizeOf总是返回-1（因为CopyByValue.IsStruct(Cinemachine.AxisState.SpeedMode)返回-1）。导致生成Wrap函数都是会装箱的版本。
是我什么地方操作有问题么，感谢！

**Comment by chexiongsheng** [comment]
https://docs.microsoft.com/en-us/dotnet/framework/interop/blittable-and-non-blittable-types

**Comment by snuc** [comment]
Cinemachine.AxisState 还有一个string的成员，放弃。
不过对于仅包含枚举项和Blittable Type的struct，虽然Enum不是Blittable，通过特殊处理应该可以支持吧
