### ISSUE TITLE
xLua是否支持c#和lua混合编程

### ISSUE THREAD

**Issue by chenqiu1988** [Tencent/xLua#76]
之前用c#做的项目，现在想接入xlua,想一些经常变化的逻辑直接用lua写，可否支持呢？

**Comment by chexiongsheng** [comment]
当然支持，可以认为现在主流lua方案支持的，xlua都支持，多加上了些自己的东西，比如热补丁。

**Comment by chenqiu1988** [comment]
之前一直纠结于c#项目的热更新，正好你出了xlua，一些插件和关键模块沿用c#代码，后续代码部分用lua，万一c#出了问题，还可以用lua热更新挽救一下，功德无量，10086个赞
