### ISSUE TITLE
为啥我在lua中无法使用C#中string的StartsWith方法？

### ISSUE THREAD

**Issue by Emerson92** [Tencent/xLua#762]
我在lua脚本中调用C#string的StartsWith方法，我在luaCallCSharp静态表中已经添加了string了，但是在lua脚本中调用StartsWith方法还是会报异常，请问一下有什么解决办法么。如图示
![~F1WTKD@4SWI62XP3{X2P9I](https://user-images.githubusercontent.com/13955075/85355005-56f94d00-b53e-11ea-8bed-71de6fd0bfb5.png)
![DVI28VZ47H)VC%IH}4_K4QB](https://user-images.githubusercontent.com/13955075/85355011-595ba700-b53e-11ea-9eab-4ab89ed84002.png)
![2PC1CU3I6)X@{NH`AQ2M7AW](https://user-images.githubusercontent.com/13955075/85355099-7d1eed00-b53e-11ea-9831-b00220555dd4.png)

**Comment by chexiongsheng** [comment]
已经转为lua的字符串了

**Comment by Emerson92** [comment]
但是我在Lua调用C#类的StartsWith方法时候，Lua这边抛出了一个nil value的异常？这是啥问题导致的呢

**Comment by Emerson92** [comment]
![image](https://user-images.githubusercontent.com/13955075/85935672-1dea1f80-b926-11ea-8612-ef112eb4b156.png)
但是我在Lua调用C#类的StartsWith方法时候，Lua这边抛出了一个nil value的异常？这是啥问题导致的呢

**Comment by chexiongsheng** [comment]
不是说已经转成lua的string了么？任意c#的函数都用不了
