### ISSUE TITLE
unity2019.4打包xcode工程时报错

### ISSUE THREAD

**Issue by happy253650035** [Tencent/xLua#765]
报错内容如下
NullReferenceException: Object reference not set to an instance of an object
CSObjectWrapEditor.Generator..cctor () (at Assets/ThirdCode/XLua/Src/Editor/Generator.cs:119)

**Comment by chexiongsheng** [comment]
漏了meta文件

**Comment by happy253650035** [comment]
没太明白大佬的意思，是哪里漏了meta文件？

**Comment by chexiongsheng** [comment]
xlua包里头每个文件都有用，包括每个文件配套的meta文件

**Comment by zhihexiao** [comment]
你好，请问这个问题解决了吗，是怎么解决的呢

**Comment by zhihexiao** [comment]
检查了xlua包里对应meta文件都在
