### ISSUE TITLE
LuaFunction泄露问题?

### ISSUE THREAD

**Issue by yhnu** [Tencent/xLua#769]
在调用次函数之前之后都做了SystemGC和LuaGC
![image](https://user-images.githubusercontent.com/23090916/87222354-9250a400-c3a5-11ea-9c5f-65f7013b8f02.png)

测试结果是匿名函数Lua并没有被回收:
![image](https://user-images.githubusercontent.com/23090916/87222383-c330d900-c3a5-11ea-943e-d7ab8d98c89a.png)

想知道问题原因,以及如何能够避免此类现象,能否抽空解答下?

**Comment by chexiongsheng** [comment]
你这不都注册到C#里头了么？C#没反注册都还引用着。
ps一下，你这段代码，直接在lua那调用AddListener，传lua函数即可，不需要通过LuaFunction中转，lua函数可以映射到delegate。不过这建议和你的问题无关。

**Comment by yhnu** [comment]
你说的反注册是指RemoveAllListeners么?我这边界面关闭后会进行Remove操作的.
`function UIPanel:UnInitButtonEvent()
    if not self.tbOnClick then
        return
    end
    for key, _ in pairs(self.tbOnClick) do
        if self[key] then
            local btn = self.pPanel:GetButton(self[key])
            if btn then
                btn.onClick:RemoveAllListeners()
            else
                LogErr(string.format("UnInitButtonEvent Error! Wnd=%s, key=%s not exist !", self.ClassName, self[key]))
            end
        else
            LogErr(string.format("UnInitButtonEvent Error! Wnd=%s, key=%s not exist !", self.ClassName, key))
        end
    end
end`

**Comment by chexiongsheng** [comment]
可能删的不干净吧，另外ugui有缓存，你可以看下之前的issues，而且网上也有人就这问题写过博客

**Comment by yhnu** [comment]
好的,我看一下相关情况
