### ISSUE TITLE
C#类导出的lua table，是否rawset无效

### ISSUE THREAD

**Issue by lixiuzhi** [Tencent/xLua#77]

**Comment by chexiongsheng** [comment]
不太明白“C#导出 lua table”是什么意思。

C#对象是映射到lua的userdata。

**Comment by lixiuzhi** [comment]
就是一个C#类导出过后，然后通过getmetatable 和 rawset在lua里重设某个函数，木有效果，此段代码在ulua tolua中是可以的

**Comment by chexiongsheng** [comment]
实现不一样的。
你为什么要重设呢？描述下你们的场景？

**Comment by lixiuzhi** [comment]
我现在做简单测试，目前应用场景就是fairygui提供的事件注册方式
https://github.com/fairygui/FairyGUI-unity/blob/master/LuaSupport/uLua/FairyGUI.lua

**Comment by chexiongsheng** [comment]
“是为了支持self参数，和方便地进行remove操作”
self你用闭包bind一下就可以了。
至于remove，本来xlua就支持，同一个function实例和delegate在xlua是一一对应的，你直接传入到remove是可以删除的。可以看下教程。

**Comment by lixiuzhi** [comment]
好的 3ks

**Comment by lixiuzhi** [comment]
也就是说xlua 目前暂不支持rawset这种操作么

**Comment by chexiongsheng** [comment]
rawset支持啊，但我们的方法不是像其它方案那样，放metatable而已，你rawset错地方而已。

**Comment by chexiongsheng** [comment]
你真的有这方面需求，我再告诉你，但目前看你们那需求在xlua有更简单的解法。

**Comment by lixiuzhi** [comment]
求告知,我现在是想尽可能多的了解xlua

**Comment by chexiongsheng** [comment]
xlua是放在__index函数的upvalue上。

**Comment by chexiongsheng** [comment]
凡事先别想太hacker的方法，即使是ulua，万一它某天方案变了，你们就悲剧了。

**Comment by lixiuzhi** [comment]
没办法 统一嘛  我这边先保证xlua tolua切换 不影响我已写的功能先 ...

**Comment by Garretthh07** [comment]
借楼问个问题：
我在 C# 这边接入 FGUI， 添加界面资源并且添加监听这么写的， 没有问题
```
 void OnClick(EventContext context)
 {
        Debug.Log("== OnClick ==");
 }
```
```
// Use this for initialization
void Start () {
        UIPackage.AddPackage("UI/FairyGUI/UILogin");
        GComponent com = UIPackage.CreateObject("UILogin", "Login").asCom;
        com.onClick.Add(OnClick);
}
```
我按照 **Doc/XLua的配置** 中静态列表的方式把 FGUI 的一些接口导出到 Lua 来使用。Lua 中的写法是这样的：

```
local function OnClick0()
        print('you click')
end

UIPackage.AddPackage('UI/FairyGUI/UILogin')
local view = UIPackage.CreateObject('UILogin', 'Login')
GRoot.inst:AddChild(view)

print("==== Lua ===", view.onClick, view.onClick.Add, FairyGUI.EventCallback1)
view.onClick:Add(OnClick0)
```
然而 **FairyGUI.EventCallback1** 答应出来的类型是个 table, 完整：
`LUA: ==== Lua ===	FairyGUI.EventListener: -2045534976	function: 0000000069A8CCE0	table: 0000000069D0A740`

EventCallback1 原始的类型是这样的：
```
namespace FairyGUI
{
    public delegate void EventCallback1(EventContext context);
}
```
参考 **Doc/XLua教程/delegate使用（调用，+，-）** 没有得到启发

最后导致的结果就是， 我在 C# 点击回调是可以触发的， 但是导出到 Lua 点击没有任何反应。
报告的错误：

```
XLua.StaticLuaCallbacks:Print(IntPtr) (at Assets/XLua/Src/StaticLuaCallbacks.cs:625)
XLua.LuaDLL.Lua:lua_pcall(IntPtr, Int32, Int32, Int32)
XLua.DelegateBridge:__Gen_Delegate_Imp1() (at Assets/XLua/Gen/DelegatesGensBridge.cs:60)
GameApp.Xlua.LuaBehaviour:Awake() (at E:/DFWorkSpace/Program/ProgramUnity/GameApp/Xlua/LuaBehaviour.cs:97)
Main:Awake() (at E:/DFWorkSpace/Program/ProgramUnity/GameApp/Main/Main.cs:36)
```

请问是哪里设置不对？
