### ISSUE TITLE
内嵌的代理类型总是被反射

### ISSUE THREAD

**Issue by phenixxy** [Tencent/xLua#778]
临时解决方法，在TryDelayWrapLoader方法内跳过内嵌的代理类型：
foreach (var nested_type in type.GetNestedTypes(BindingFlags.Public))
{
	if (nested_type.IsGenericTypeDefinition())
	{
		continue;
	}
	**if (typeof(MulticastDelegate).IsAssignableFrom(nested_type))
	{
		continue;
	}**
	TryDelayWrapLoader(L, nested_type);
}

**Comment by chexiongsheng** [comment]
反射带来什么问题呢？

**Comment by phenixxy** [comment]
性能问题，代理类型一般都是内嵌的，有很多这种反射的话还是不太好。

**Comment by chexiongsheng** [comment]
你这么去掉的话，需要用到这些内嵌delegate的类型信息的时候就有问题了。比如faq这种场景：
https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/faq.md#%E6%80%8E%E4%B9%88%E6%8A%8Ac%E7%9A%84%E5%87%BD%E6%95%B0%E8%B5%8B%E5%80%BC%E7%BB%99%E4%B8%80%E4%B8%AA%E5%A7%94%E6%89%98%E5%AD%97%E6%AE%B5

**Comment by phenixxy** [comment]
我试了没有问题，内嵌的delegate类型在被lua用到的时候还是会再去反射的。如果数量不多的话，提前都反射生成好也没太大问题。

**Comment by chexiongsheng** [comment]
> 我试了没有问题，内嵌的delegate类型在被lua用到的时候还是会再去反射的。如果数量不多的话，提前都反射生成好也没太大问题。

内嵌的如果不提前生成，lua访问的时候不会触发生成的。
