### ISSUE TITLE
关于out关键字

### ISSUE THREAD

**Issue by ArchieKing** [Tencent/xLua#78]
类里面有2个方法，第一个是普通的方法，第二个是out关键字的方法；
在没有普通方法的时候，lua里能够执行带有out关键字的方法
加入普通方法的时候，lua里就只会重载到普通方法，并不会执行带有out关键字的方法
![_ mruvbrbs xa mq 13i2](https://cloud.githubusercontent.com/assets/19188981/21924128/a04d7866-d9b2-11e6-9b7b-f0192d0bf5aa.png)

**Comment by ArchieKing** [comment]
请问要怎么操作才能执行普通方法和带有out关键字的方法？

**Comment by chexiongsheng** [comment]
是这样的，lua由于类型系统和C#不对等，重载是无论如何都无法完备的。比如void foo(int a) 和void foo(double b)，输入1是没法判断你调哪个。因为lua只有一种数字类型。
你可以通过Extension method来为out的那个起个别名

publci static void TestMethodOut(this LuaHelper self, out int a)
{
 self.TestMethod(out a)
}

然后把TestMethodOut的那个类加到生成代码
然后lua里头
local r1, r2 = luaHelper:TestMethodOut()

**Comment by ArchieKing** [comment]
谢谢，给函数起一个别名确实是一个办法；
但现在需要使用UnityEngine.Physics.Raycast发射射线来做三维物体的点击事件检测，里面就会涉及这个普通方法和带有out关键字方法的重载，按你的思路，这样就不能使用了吗？

**Comment by chexiongsheng** [comment]
可以呀，如果是静态方法，直接分别封装成不同名的。

如果是成员方法，就用Extension method起别名，Extension method对于所有类都能起作用的，当然也包括UnityEngine下的。

**Comment by ArchieKing** [comment]
好的，明白了，谢谢蛤
