### ISSUE TITLE
Webgl平台Build出错

### ISSUE THREAD

**Issue by chaoslife** [Tencent/xLua#780]
使用Unity2019.4.2f1打包，返回错误：

stdout:
stderr:In file included from C:\Chaos\SVN\Test\TF\Framework\Assets\com.onesight.xframework\Assets\Lua\Plugins\WebGL\xlua_webgl.cpp:35:C:\Chaos\SVN\Test\TF\Framework\Assets\com.onesight.xframework\Assets\Lua\Plugins\WebGL/../../../WebGLPlugins/i64lib.c:409:34: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]        snprintf(temp, sizeof(temp), "%"PRIu64, n);                                        ^                                         1 error generated.ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

错误位置在
static int uint64_tostring(lua_State* L) {
	char temp[72];
	uint64_t n = lua_touint64(L, 1);
#if ( defined (_WIN32) ||  defined (_WIN64) ) && !defined (__MINGW32__) && !defined (__MINGW64__)
	sprintf_s(temp, sizeof(temp), "%"PRIu64, n); <------------
#else
	snprintf(temp, sizeof(temp), "%"PRIu64, n);   <------------
#endif

请问应该怎么解决

**Comment by zhaozilie12** [comment]
我也遇到了，同问怎么解决的啊

**Comment by zhaozilie12** [comment]
问题解决了
1.检查WebGLPlugins文件夹不要放在Assets目录下面，Unity会修改文本格式
2.放在Assets同级目录后，检查xlua_webgl文件里面的的路径索引是否正确
