### ISSUE TITLE
win64 Luac 编译字节码，CustomLoader报错 format mismatch in precompiled chunk

### ISSUE THREAD

**Issue by fantasia-gotchas** [Tencent/xLua#785]
1，windows 10平台下，先进行Luac的win64的编译，再对make_win64_lua53.bat 添加了 -DLUAC_COMPATIBLE_FORMAT=ON 项。 编译两者都编译成功。 
2，用luac\build64\Release的luac.exe对教程例子的byfile.lua.txt进行编译输出为byfile.lua.bytes ,用目录下的lua.exe执行byfile.lua.bytes能正常输出hello world。
3，把编译好的x86_64的xlua.dll 以及 byfile.lua.bytes文件放置到Unity工程相应的目录位置。
4，byfile.lua.bytes在Resources目录用Resources进行CustomLoader加载或者放在SreamingAssets直接用File进行CumstomLoader加载，均出现**format mismatch in precompiled chunk**. 错误。

**Comment by fantasia-gotchas** [comment]
解决了

**Comment by lihualinUnity** [comment]
你好，想咨询一下是怎么解决的呢？
