### ISSUE TITLE
生成的wrap类中的函数重复定义问题

### ISSUE THREAD

**Issue by mydodolookdo** [Tencent/xLua#79]
public class MyTest
{
    public int num;
    public void set_num(int v)   {    }
}

生成出来的wrap类
public class MyTestWrap    {
        public static void __Register(RealStatePtr L)        {		
			Utils.RegisterFunc(L, Utils.METHOD_IDX, "set_num", set_num);
			Utils.RegisterFunc(L, Utils.GETTER_IDX, "num", get_num);
			Utils.RegisterFunc(L, Utils.SETTER_IDX, "num", set_num);
       }
}

两个set_num函数，重复定义了

**Comment by chexiongsheng** [comment]
谢谢反馈，已经修改。
