### ISSUE TITLE
不能正确获取到transform了。

### ISSUE THREAD

**Issue by LetGo** [Tencent/xLua#792]
有个问题，这边获取到transform保存到table中，在Update里面去获取transform的position 正常执行几次后就报transform被删除了（实际未删） 的异常

**Comment by Jayatubi** [comment]
code please

**Comment by LetGo** [comment]
来了!!!
下面的函数在Update执行
for index, value in ipairs(table) do
        if value then
            if value.build then
                Log.Error(value.name..value.id)
                 --build 是场景中的一个对象 就是此处获取transom pos异常
                local buildPos = value.build.position
                local pos = mainCamera:WorldToViewportPoint(buildPos)
                pos = uiCamera:ViewportToWorldPoint(pos)
                pos.z = 0
                value.lab.transform.position = pos
            else
                
            end
        end
   end
