### ISSUE TITLE
lua中通过loadFile加载文件，不会调用customLoader，导致文件加载失败

### ISSUE THREAD

**Issue by cc198911** [Tencent/xLua#798]
--lua
local ret, msg = loadfile("main.lua") -- 没有调用到loader
local ret, msg = require("main.lua") -- 正常调用到loader

--C#
_luaEnv.AddLoader((ref string filePath) =>{
       Debug.LogWarning(filePath);
});

**Comment by chexiongsheng** [comment]
本来这两个就不一样
require的参数是“模块”，loadfile的参数是“路径”
“模块”是可以没有后缀，可以用xx.yy.aa来代表xx/yy/aa.lua，可以自动加上so，lua，等后缀；
loadfile可以么？

**Comment by cc198911** [comment]
通过自己实现了一个loadfile方法替换掉默认的loadfile解决这个问题
