### ISSUE TITLE
xlua.access, no field __Hitfix0_Update

### ISSUE THREAD

**Issue by hellosssssssssssssss** [Tencent/xLua#8]
您好，在运行demo hotfix的时候报错xlua.access, no field __Hitfix0_Update是什么原因造成的？

**Comment by chexiongsheng** [comment]
要等打印了hotfix inject finish!才点击运行

**Comment by Ollydbg** [comment]
首先 
 osx上的命令行 cp /Applications/Unity/Unity.app/Contents/Managed/Mono.Cecil.* Project/Assets/XLua/Src/Editor/
Win命令行 copy UnityPath\Editor\Data\Managed\Mono.Cecil.*  Project\Assets\XLua\Src\Editor\


其次打开宏HOTFIX_ENABLE

然后等待出现hotfix inject finish!

**Comment by hellosssssssssssssss** [comment]
我手动找到Mono.Cecil.dll 拷贝进去的，没有出现hotfix inject finish.... 确定宏开了

**Comment by Ollydbg** [comment]
那你就reimport一个脚本

**Comment by chexiongsheng** [comment]
@hellosssssssssssssss  可能你没注意到就清屏了，你试试再运行一下，应该可以了的。
或者你试试改一行代码，触发下编译

**Comment by hellosssssssssssssss** [comment]
@chexiongsheng  @Ollydbg找到问题了，原来Unity目录下有好几个Mono.Cecil.*，我拷贝错了，然后编译的时候有一个报错method.ContainsGenericParameter，我给注释掉了，重新拷贝managed下的Mono.Cecil.*就好啦，感谢两位的帮助!

**Comment by chexiongsheng** [comment]
@hellosssssssssssssss @Ollydbg  谢谢反馈，参考命令我已经更新到文档里头。
