### ISSUE TITLE
数组注册到lua报错

### ISSUE THREAD

**Issue by zyq20130111** [Tencent/xLua#800]
[LuaCallCSharp]
    public static List<Type> List_LuaCallCS = new List<Type>()
    {
        typeof(int[]),
    };
   生成代码时会提示
Array creation must have array size or array initializer

**Comment by chexiongsheng** [comment]
数组不用加

**Comment by zyq20130111** [comment]
熊哥，数组为啥不用加，而dictionary,list需要加吗？

**Comment by chexiongsheng** [comment]
你可以理解为数组统一加了。

**Comment by zyq20130111** [comment]
好的，多谢
