### ISSUE TITLE
How to use external DLL in Hotfix?

### ISSUE THREAD

**Issue by buihuuloc** [Tencent/xLua#81]
Hi there,

Could you let me know how could I use external DLL in Hotfix (i.e DOTween) ?
Thanks!

**Comment by chexiongsheng** [comment]
Just add types that you want to use in lua to LuaCallCSharp list or ReflectionUse list.

**Comment by chexiongsheng** [comment]
The type and its extension method must add to the same list.
LuaCallCSharp list will generate wrap class for the type, it faster but more code. Lua access types in ReflectionUse list by Reflection, it slower but less impact to the ipa/apk.

**Comment by buihuuloc** [comment]
Hi @chexiongsheng 

Here is what I did for external DLL
```C#
public static class DotweenHotfix
{
	[LuaCallCSharp]
	public static List<Type> LuaCallCSharp
	{
		get
		{
			var luaTypeWrap = new List<Type>();
			var assem = Assembly.Load("DOTween");
			var types = assem.GetExportedTypes();
			luaTypeWrap.AddRange(types);
			return luaTypeWrap;
		}
	}
}
```
And here is the hotfix string
```
xlua.hotfix(CS.HotFixSubClass,{
    Awake = function(self)
        self.transform:DOMoveX(10,22):SetLoops(-1)
    end
})
```
It works without SetLoops(-1), with SetLoops(-1) I got this error message
```
LuaException: [string "chunk"]:6: attempt to call method 'SetLoops' (a nil value)
stack traceback:
	[string "chunk"]:6: in function <[string "chunk"]:2>
XLua.LuaEnv.ThrowExceptionFromError (Int32 oldTop) (at Assets/XLua/Src/LuaEnv.cs:366)
XLua.DelegateBridge.SystemVoid (System.Object self) (at Assets/XLua/Gen/DelegatesGensBridge.cs:143)
HotFixSubClass.Awake ()

```

**Comment by chexiongsheng** [comment]
SetLoops is generic method. xLua do not support direct.
You can write anthor extentsion method to instance the generic parameter and and add to LuaCallCSharp list.

[XLua.LuaCallCSharp]
public static class GenericMethodWrap
{
    public static Tweener SetLoopsOfTweener(this Tweener t, int loops)
    {
        return t.SetLoops(loops);
    }
}

Call SetLoopsOfTweener in lua:

xlua.hotfix(CS.HotFixSubClass,{
    Awake = function(self)
        self.transform:DOMoveX(10,22):SetLoopsOfTweener(-1)
    end
})

**Comment by buihuuloc** [comment]
I just got another error message

```
BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
Mono.Cecil.PE.ImageReader.ReadImage ()
Mono.Cecil.PE.ImageReader.ReadImageFrom (System.IO.Stream stream)
Mono.Cecil.ModuleDefinition.ReadModule (System.IO.Stream stream, Mono.Cecil.ReaderParameters parameters)
Mono.Cecil.ModuleDefinition.ReadModule (System.String fileName, Mono.Cecil.ReaderParameters parameters)
Mono.Cecil.AssemblyDefinition.ReadAssembly (System.String fileName, Mono.Cecil.ReaderParameters parameters)
XLua.Hotfix.HotfixInject () (at Assets/XLua/Src/Editor/Hotfix.cs:254)
```
I don't know why it happens
Here is the demo project
https://www.dropbox.com/s/zdmhtn5690ozba8/Example.zip?dl=0

**Comment by chexiongsheng** [comment]
It is a bug.
The path of third path dll must add to the cecil search path. i fix it and test in my project.
Pls update code and check if the problem had solved!

**Comment by buihuuloc** [comment]
Awesome
Thanks @chexiongsheng

**Comment by chexiongsheng** [comment]
xLua added generic method support partially， you can call SetLoops without extentsion method now.
there is the excample:
https://github.com/Tencent/xLua/tree/master/Assets/XLua/Examples/09_GenericMethod

**Comment by cn00** [comment]
my error log
[Editor.log.zip](https://github.com/Tencent/xLua/files/3580146/Editor.log.zip)


I had stuck at the same problem for a week, and found an ugly bypass to skip it.

XLua/Generate code
delete XLuaGenConfig.cs
build
revert XLuaGenConfig.cs
