### ISSUE TITLE
怎么屏蔽UnityEngine中部分属性的set方法

### ISSUE THREAD

**Issue by leohawke** [Tencent/xLua#811]
xlua是用的编辑器引用下的UnityEngine.dll？

**Comment by leohawke** [comment]
public static class DefaultControls
    {
        static IFactoryControls m_CurrentFactory = DefaultRuntimeFactory.Default;
        public static IFactoryControls factory
        {
            get { return m_CurrentFactory; }
#if UNITY_EDITOR
            set { m_CurrentFactory = value; }
#endif
        }

**Comment by chexiongsheng** [comment]
黑名单啊，看faq

**Comment by leohawke** [comment]
我是找了半天文档也没看到黑名单的文档在哪

**Comment by chexiongsheng** [comment]
https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/configure.md
为啥会找半天找不到呢？google以下就有了

**Comment by leohawke** [comment]
首先这个文档里面只描述了屏蔽属性与方法，并没有描述怎么屏蔽属性的set/get方法。
换句话说，这个文档并没有说明get_XXX能否匹配，不过我也懒得尝试了。
其次，将整个UnityEngine.dll都加入代码生成的情况下，使用的UnityEngine.dll是Editor所使用的dll。不过目测你们这个也不会支持了。

**Comment by chexiongsheng** [comment]
get_XXX就是一个方法，为啥需要特别说明呢？
整个加就一个个api的排除。

**Comment by chexiongsheng** [comment]
条件编译宏是代码层面的东西，编译后是没法判断某api是在条件编译宏下
