### ISSUE TITLE
如何在blacklist里加入一个struct

### ISSUE THREAD

**Issue by xianwx** [Tencent/xLua#829]
![image](https://user-images.githubusercontent.com/10540608/98081033-635cc180-1eb1-11eb-87ae-3b4eabd93013.png)
请问一下，我有这个报错，我想要把
![image](https://user-images.githubusercontent.com/10540608/98080773-ed585a80-1eb0-11eb-9620-64c881babdea.png)
这个struct加入黑名单，怎么样才能让黑名单里加入一个struct呢？

**Comment by chexiongsheng** [comment]
对哪些类生成代码，是根据一个白名单，那白名单是你提供的，你只要在你那白名单那去掉该类即可。

**Comment by xianwx** [comment]
哦哦哦，也行，我本来是只想剔除那个struct，但是想了想整个剔除也问题不大。谢谢。

**Comment by xianwx** [comment]
嗷嗷，我错了，原来可以精准打击，不需要整个都剔除。
