### ISSUE TITLE
两个类名 字母相同大小写不同 只会生成一个wrap类

### ISSUE THREAD

**Issue by mydodolookdo** [Tencent/xLua#83]
public class MyTest
{
    public int num;
}
public class myTest
{
    public int id;
}
只生成了一个wrap类, 然后就会报错
public class myTestWrap
{}

**Comment by chexiongsheng** [comment]
window下文件不区分大小写导致的，不是不生成，是后面的覆盖了前面的。
我想想看有没办法。
但是同一个namespace下有两个这样的类的代码也是不合理的。

**Comment by chexiongsheng** [comment]
业务同一个namespace下有同名，但大小写不一样的类是不合理的，所以我也不打算修改到能支持这种不合理的情况，业务调整下代码来规避。
