### ISSUE TITLE
泛型委托的参数如何在lua侧调用

### ISSUE THREAD

**Issue by lanyantao** [Tencent/xLua#831]
打扰，问个问题哈：
void Function 《T》 (Action 《T》 action, int index) where T : GameObject
这种参数是泛型委托的方法在lua中怎么调用，看FAQ也只有参数本身是T类型的使用方式，也没有能够在网上找到泛型委托的使用，是否是不支持这种调用？
ps：<显示有问题，有《代替

**Comment by chexiongsheng** [comment]
FAQ那说的（怎么调用，有什么限制）也适用这种情况。FAQ只针对泛型参数，也就是你例子里头的T，这个T怎么组成参数是一样的。
举例不可能穷尽所有情况，比如例子里头用int作为参数来演示函数调用，你应该得出其它数字也是类似的结论。

**Comment by lanyantao** [comment]
> FAQ那说的（怎么调用，有什么限制）也适用这种情况。FAQ只针对泛型参数，也就是你例子里头的T，这个T怎么组成参数是一样的。
> 举例不可能穷尽所有情况，比如例子里头用int作为参数来演示函数调用，你应该得出其它数字也是类似的结论。

谢谢车大的回复，我有看泛型的例子使用，比如：
local foo_generic = xlua.get_generic_method(CS.GetGenericMethodTest, 'Foo')
local foo = foo_generic(CS.System.Int32, CS.System.Double)
Foo是一个int与double的泛型，
但是我的问题是我想要获得一个泛型委托Action《T》，但是貌似并没有找到类似xlua.get_generic_delegate的方法，不知我是否有表述清楚？

**Comment by chexiongsheng** [comment]
是你理解错什么叫泛型参数。
泛型参数是那个T，你指定了那个就可以了，后面那个是函数形参，你指定了T后面那个就自然定了
