### ISSUE TITLE
error with unity2020.1.6

### ISSUE THREAD

**Issue by unitymatrix** [Tencent/xLua#833]
`LuaException: error loading module message_box from resource, message_box.lua:1: unexpected symbol near '<\239>'
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	async_test.lua:8: in main chunk
	[C]: in function 'require'
	[string "chunk"]:1: in main chunk
XLua.LuaEnv.ThrowExceptionFromError (System.Int32 oldTop) (at Assets/XLua/Src/LuaEnv.cs:441)
XLua.LuaEnv.DoString (System.Byte[] chunk, System.String chunkName, XLua.LuaTable env) (at Assets/XLua/Src/LuaEnv.cs:274)
XLua.LuaEnv.DoString (System.String chunk, System.String chunkName, XLua.LuaTable env) (at Assets/XLua/Src/LuaEnv.cs:288)
XLuaTest.AsyncTest.Start () (at Assets/XLua/Examples/07_AsyncTest/AsyncTest.cs:23)`
运行第七个demo 07_AsyncTest 报上述错误
Unity2017.1.3未见报错
xlua版本2.1.15

**Comment by chexiongsheng** [comment]
看上去是async_test.lua是UTF8带Bom格式导致的，但我查看了下，xlua例子附带的这个文件是UTF8不带Bom的格式，可能是你用某个编辑器打开，帮你转了

**Comment by unitymatrix** [comment]
> 看上去是async_test.lua是UTF8带Bom格式导致的，但我查看了下，xlua例子附带的这个文件是UTF8不带Bom的格式，可能是你用某个编辑器打开，帮你转了

确实~  我用notepad++ 转了之后就可以了
