### ISSUE TITLE
自己编译的win32版本的xlua.dll，一初始化LuaEnv就崩溃

### ISSUE THREAD

**Issue by s635438255** [Tencent/xLua#835]
用工程自带的bat文件编译的，64位的dll可以正常运行，32位的直接就奔溃了。
[output_log.txt](https://github.com/Tencent/xLua/files/5614095/output_log.txt)

**Comment by chexiongsheng** [comment]
用官方的呢？

**Comment by s635438255** [comment]
用官方的是可以的

**Comment by chexiongsheng** [comment]
那可能你的编译环境有问题吧

**Comment by chexiongsheng** [comment]
另外，现在做了基于actions的自动编译，在github提供的虚拟机上编译，你即使要修改代码也不用本地编译

**Comment by chexiongsheng** [comment]
https://github.com/Tencent/xLua/actions/runs/390972732，你下载自动编译的结果看看

**Comment by s635438255** [comment]
好的我试试，我特地重装了一个32位的win10系统编译也不行。。。

**Comment by s635438255** [comment]
我用actions编译了一遍也不行，还是会奔溃，然后我去试了一下Release里的2.1.15包里的32位dll，发现也会奔溃了。。。。

**Comment by chexiongsheng** [comment]
4.24的不会？

**Comment by s635438255** [comment]
问题原因好像是因为我修改的C#部分的xlua代码导致的32位的会奔溃，我把C#部分的代码还原之后就可以正常使用了。应该是我自己的问题Orz，打扰了

**Comment by s635438255** [comment]
问题解决了，原因是我将C#部分的代码编译到了一个dll里面，但是没有设置对应的宏，导致生成的dll与32位平台的代码不匹配。
