### ISSUE TITLE
无法在他人写好的事件中添加[CSharpCallLua]，如何解决这种情况？

### ISSUE THREAD

**Issue by dreamCirno** [Tencent/xLua#849]
我使用 Addressables 异步生成预制体

`AsyncOperationHandle<GameObject> handle = Addressables.InstantiateAsync("Prefab");`
`handle.Completed += (p) => { // Do my operation ... };`

以上是 C# 的实现方式，想将其转为 Lua 实现
`function Test(p)
    print(p)
end
`
`local handle = Addressables.InstantiateAsync("Prefab")`
`handle:Completed('+', Test)`

报的是如下错误：
LuaException: c# exception:System.InvalidCastException: This type must add to CSharpCallLua:

该如何去实现它？

**Comment by chexiongsheng** [comment]
看配置文档

**Comment by dreamCirno** [comment]
感谢引导
