### ISSUE TITLE
什么时候支持Windows10（UWP）平台呢？

### ISSUE THREAD

**Issue by FlameskyDexive** [Tencent/xLua#85]
什么时候支持Windows10（UWP）平台呢？ 作为微软主打的Win10（UWP）平台，，如果能增加对Win10的支持，，就完美了，，UWP包括Win10 Mobile、Win10 PC、Xbox one、 HoloLens等多平台，，而HoloLens是MR发展趋势，，期待UWP版

**Comment by chexiongsheng** [comment]
xLua本身是用C#和纯C编写，如果是lua53版本的话，lua53也是纯C，C#和C能支持到的平台都好办。

你说的UWP版是指脱离Unity独立运行的xLua么？如果不是的话，还得看Unity的支持，Unity不支持xLua支持了也没用。

**Comment by FlameskyDexive** [comment]
Unity现在是原声支持UWP的，但其他的采用luajit 的lua热更新框架如tolua跟slua没有对UWP做适配，也没生成对应的库文件，所以，如果xlua采用lua53，按理应该是可以编译UWP的库文件然后对UWP进行适配的，希望你们能帮忙解决下适配问题，谢谢

**Comment by chexiongsheng** [comment]
可以啊，xlua的plugins是用cmake编译的，支持uwp估计比较简单。
我找了下网上资料试了下，报我没安装sdk，如果你机器有装，帮忙试试？我最近比较忙，没时间折腾。
你在build目录新建一个make_uwp.bat，加入如下内容，运行一下：
~~~bat
mkdir build_uwp & pushd build_uwp
cmake -G "Visual Studio 14 2015" -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION=10.0 ..
popd
cmake --build build_uwp --config Release
pause
~~~

**Comment by chexiongsheng** [comment]
你调通了可以提个push request给我

**Comment by FlameskyDexive** [comment]
好的，，等我周末放假，，我就去试试编译UWP看看，，谢谢

**Comment by gitlsl** [comment]
能不能给个 xlua 在 winform 或者  wpf 上的 例子 呢

**Comment by chexiongsheng** [comment]
@gitlsl 暂时还没剥离到Unity之外哦。等我忙完这一段时间可以规划下。
楼主说的还是Unity下的windows10支持。

**Comment by chexiongsheng** [comment]
@FlameskyDexive 你后来试了没？

**Comment by FlameskyDexive** [comment]
还没，还没去上班，电脑没带回来

Sent from my iPhone

On 6 Feb 2017, at 1:56 PM, chexiongsheng <notifications@github.com<mailto:notifications@github.com>> wrote:


@FlameskyDexive<https://github.com/FlameskyDexive> 你后来试了没？

―

**Comment by chexiongsheng** [comment]
@FlameskyDexive 
master上已经有uwp的支持了
@gitlsl 
2.1.6以上已经支持非unity环境
