### ISSUE TITLE
rapidjson有bug哦

### ISSUE THREAD

**Issue by zjytra** [Tencent/xLua#858]
不是按1索引的table转出json有问题

**Comment by chexiongsheng** [comment]
xlua没带rapidjson

**Comment by WuHaoShuang** [comment]
这个不是rapidjson的问题，不是1开始的表示不是数组，而是json的key value中的key不能是数字。建议自己改下rapidjson的源码，不是1开始的table，索引导出为string

**Comment by zjytra** [comment]
已经在lua层处理，将encoding时不是number的key转为string,decoding时反向转回来
