### ISSUE TITLE
Google.Protobuf生成的Message代码代码后 使用xlua 生成代码 DelegatesGensBridge.cs报错

### ISSUE THREAD

**Issue by zjytra** [Tencent/xLua#859]
报错代码如下：
public void __Gen_Delegate_Imp147(object p0, ref Google.Protobuf.WriteContext p1)
		{
#if THREAD_SAFE || HOTFIX_ENABLE
            lock (luaEnv.luaEnvLock)
            {
#endif
                RealStatePtr L = luaEnv.rawL;
                int errFunc = LuaAPI.pcall_prepare(L, errorFuncRef, luaReference);
                ObjectTranslator translator = luaEnv.translator;
                translator.PushAny(L, p0);
                translator.Push(L, p1);
                
                PCall(L, 2, 1, errFunc);
                
                translator.Get(L, errFunc + 1, out p1);
                
                
                LuaAPI.lua_settop(L, errFunc - 1);
                
#if THREAD_SAFE || HOTFIX_ENABLE
            }
#endif
		}
我看WriteContext参数只有protobuf 生成的消息文件 只有这个 void pb::IBufferMessage.InternalWriteTo方法用到而这个方法加了global::System.Diagnostics.DebuggerNonUserCodeAttribute 属性  我在
#if UNITY_2018_1_OR_NEWER
    [BlackList]标签 MethodFilter 中过滤不了

**Comment by zjytra** [comment]
生成的类都过滤了

**Comment by chexiongsheng** [comment]
DelegatesGensBridge的代码BlackList过滤不了。
DelegatesGensBridge是在Hotfix或者CSharpCallLua的生成代码，要在这两者里头过滤。

**Comment by zjytra** [comment]
public void __Gen_Delegate_Imp161(UnityEditor.PlayModeStateChange p0) 这个怎么过滤呢？
拿参数类型拿不到，我开了 HOTFIX_ENABLE

**Comment by zjytra** [comment]
过滤DOTweenModuleUtils 这个类ok了
