### ISSUE TITLE
请问下要热更tdr通信协议, 该如何入手?

### ISSUE THREAD

**Issue by zhangdage** [Tencent/xLua#87]
这边游戏客户端是想实现大部分的逻辑支持玩家按需求动态下载, 请问下大神 xlua是否支持tdr协议,  该如何实现?

**Comment by chexiongsheng** [comment]
内网版本有发预集成了tdr扩展的版本。
你是tx的么？是的话直接到code平台下载。如果不是，请联系你的接口人。

**Comment by zhangdage** [comment]
thx
