### ISSUE TITLE
有没有标签或者列表的方式，表明只导出部分wrap

### ISSUE THREAD

**Issue by zhaogd233** [Tencent/xLua#882]
项目开发过程中，可能类里面有需要导出的和lua侧不用的。正常的流程可能是需要对不导出的加blocklist。
但是如果一个类基本就需要导出一个函数，可不可以有个只打的 [白名单] 的标签。或者是白名单列表。
举个例子：lua侧用的image。基本就需要一个基础sprite的wrap（抛弃继承之后导出继承类这种方式，毕竟系统类型还是很多的），这种的可以做成一个白名单列表 导出部分属性|函数。

**Comment by chexiongsheng** [comment]
类本来就是白名单，你不配置就不生成。
而白名单里头，如果某个类需要排除函数或者属性，这时才用blacklist。

**Comment by zhaogd233** [comment]
嗯，这种设计我是理解的。
我是想只对白名单类中，只导出白名单函数/属性。如果用blacklist的话，可能需要写一大堆代码。
如果能增加一个标签过滤下只导出白名单类的函数/属性就 挺好的。

**Comment by chexiongsheng** [comment]
blacklist是个getter，是可以通过些代码返回的。
你很容易扩展成白名单。
白名单反转就是黑名单。
