### ISSUE TITLE
android Luac 编译字节码，CustomLoader报错 format mismatch in precompiled chunk

### ISSUE THREAD

**Issue by byteker** [Tencent/xLua#884]
使用build_xlua_with_libs的Actions编译直接改的CMakeLists.txt里LUAC_COMPATIBLE_FORMAT为ON

在window上是没问题了， android上LUAC_COMPATIBLE_FORMAT没生效（用原版的luac能正常运行）

**Comment by byteker** [comment]
是那个步骤有问题吗？

**Comment by chexiongsheng** [comment]
可能你android没处理。
每个平台都要按文档处理

**Comment by lihualiy** [comment]
你好，我也遇到了这个问题。请问是怎么解决的呢
