### ISSUE TITLE
请教，如果在lua中引用了C#对象，有没有什么通用的方法可以一劳永逸地清理这块引用，最终c#和lua端都GC干净呢

### ISSUE THREAD

**Issue by Laughing111** [Tencent/xLua#885]
1.在a.lua中 引用了c#的对象，`self.csharp_obj = obj`
2.在c#中，也通过Alua_Interface.cs，在调用a.lua  ==>  'Alua_Interface callLua;'
3.这时候如果只执行了c#中的 `callLua?.Dispose() `,那么csharp_obj将还存在于ObjectTranlator的reverseMap和objects中。
4.在c#或者lua端有没有什么通用的接口或处理方式，可以解决这块内存的泄露呢。（因为a.lua 作为基类，内部对c#对象的引用内容实在太多了T T，实在不太想一个个去`self.csharp_obj = nil` 处理）

**Comment by Laughing111** [comment]
@chexiongsheng 救救孩子吧

**Comment by Laughing111** [comment]
有没有可能，在C#GC的时候，通过ObjectTranslator获取存放的lua引用，1.先把对应的lua引用置空，然后再进行正常GC呢

**Comment by Laughing111** [comment]
> 把对应的lua引用置空 2.然后再进行正常GC呢

忽略忽略

**Comment by chexiongsheng** [comment]
最简单莫过于重启程序

**Comment by Laughing111** [comment]
che神，请教

**Comment by Laughing111** [comment]
如果项目维护过程中 不得不在lua脚本里 xlua.privae_accessible(CS.A) 
1.这样的情况下，是不是会在xlua的CS的缓存表(ObjectTranlator)中 自动缓存这个CS.A对象的引用

如果 1 满足
2.这个CS.A在整体架构中并非全局唯一的，会Dispose，会在外部置为空以供GC
3.那这样的情况下，岂不是这个A对象就泄露了，请问该如何清空xlua CS缓存表中的引用呢

**Comment by chexiongsheng** [comment]
> 如果项目维护过程中 不得不在lua脚本里 xlua.privae_accessible(CS.A)
> 1.这样的情况下，是不是会在xlua的CS的缓存表(ObjectTranlator)中 自动缓存这个CS.A对象的引用
> 
> 如果 1 满足
> 2.这个CS.A在整体架构中并非全局唯一的，会Dispose，会在外部置为空以供GC
> 3.那这样的情况下，岂不是这个A对象就泄露了，请问该如何清空xlua CS缓存表中的引用呢

每个字我都看得懂，连一起就看不懂了

**Comment by chexiongsheng** [comment]
比如CS的缓存表是什么，那括号里ObjectTranlator和CS的缓存表又有啥关系？

**Comment by Laughing111** [comment]
![0Z%43P($14 EMRK5VU1R}R5](https://user-images.githubusercontent.com/39397262/127597665-b6cca1fa-4c47-43a7-aad3-860e7195e1db.jpg)

**Comment by Laughing111** [comment]
che神 我指这个哈，如果在lua脚本里， xlua.privae_accessible(CS.A)

**Comment by Laughing111** [comment]
> 比如CS的缓存表是什么，那括号里ObjectTranlator和CS的缓存表又有啥关系？

想请教，如果我通过xlua.private_accessible(CS.A),是不是这个A对象 就会存在ObejectTranslator的ObjectPool中

**Comment by chexiongsheng** [comment]
CS.A，A不是一个类么？
ObjectPool是为所有lua引用的c#对象保存引用，如果lua不引用了，就自动释放。如果有什么泄漏早完蛋了。
或者你直接说你发现什么现象就行，别自己乱猜原因。比如你电脑开不了机，你和师傅说电脑开不了机就行，别瞎猜是“CPU坏了”，然后和师傅说我电脑CPU坏了。

**Comment by Laughing111** [comment]
好的，其实我上面有保守的提问哈【如果1满足】

**Comment by chexiongsheng** [comment]
所有CS.XX都会缓存和这个类调用有关的信息。这种缓存只有一次，不会释放。

**Comment by Laughing111** [comment]
che神，还是想确认一遍哈，如果我只执行xlua.private_accessible(CS.A)
剩余的lua脚本逻辑里，没有其他和CS.A相关的调用逻辑，也没有对CS.A进行引用存储
这个时候，xlua会在ObjectPool中塞一份CS.A吗

**Comment by chexiongsheng** [comment]
感觉你编程没学好啊。。
CS.A作为参数传递，不就相当于访问了CS.A了么。。

**Comment by Laughing111** [comment]
che神那这个时候，怎样才能清除ObjectPool中塞的这份CS.A呢
`
比如
b.lua 中 只有 xlua.private_accessible(CS.A)
然后CS侧
class A
{
    blua_interface b;
    void clear()
    {
          //这样应该也清不掉吧？
          b?.Dispose();
          b = null;
    }
}
`

**Comment by Laughing111** [comment]
che神那这个时候，怎样才能清除ObjectPool中塞的这份CS.A呢
比如 b.lua 中 只有 xlua.private_accessible(CS.A) 
然后CS侧 
class A 
{ 
      blua_interface b; 
      void clear() 
     { 
         //这样应该也清不掉吧？ 
         b?.Dispose(); 
         b = null; 
      } 
}

**Comment by chexiongsheng** [comment]
我觉得对你来说，唯一可操作的释放方式，就是关闭整个虚拟机，或者程序重启。
