### ISSUE TITLE
batchmode时如何generate code生成对应平台的代码

### ISSUE THREAD

**Issue by nxlwnm** [Tencent/xLua#890]
RT
通过batchmode构建版本时，对于wwise这种不同平台有不同实现的库，xlua生成的代码依然是UNITY_EDITOR_WIN或UNITY_EDITOR_OSX版本的，无法生成对应的iOS Android，这种情况应该如何处理？有办法识别并正确生成，或者添加黑名单来阻止生成这部分的代码(上层有封装平台差异，应该是可以不生成这部分代码的)？

**Comment by rhy2020** [comment]
你可以通过过滤命名空间和过滤类的方式来做

**Comment by nxlwnm** [comment]
> 你可以通过过滤命名空间和过滤类的方式来做
