### ISSUE TITLE
Debug.Log的行数错误

### ISSUE THREAD

**Issue by Ollydbg** [Tencent/xLua#9]
非常棒的想法！
我在测试过程中发现了一个问题，一旦开启了HOTFIX_ENABLE宏编译之后，Demo中的HotfixTest里面打印的LOG的函数会定位到HotfixTest2的102行，关闭这个宏之后重新编译就好了。

> ^>>>>>>>>Update in C#, tick = 50
UnityEngine.Debug:Log(Object)
HotfixTest:Update() (at Assets/XLua/Examples/08_Hotfix/HotfixTest2.cs:102)

Unity版本5.3.5f1

**Comment by chexiongsheng** [comment]
文档已经有说明了，打开HOTFIX_DEBUG_SYMBOLS就可以解决这问题，但带来的新问题是只能运行一次，Unity运行过一次后会持有Assembly-CSharp.dll.mdb文件的句柄，这时改代码后会导致重新编译，xLua要写Assembly-CSharp.dll.mdb的时候会报写冲突。详细情况及使用建议看Assets/XLua/Doc/hotfix.md

**Comment by Ollydbg** [comment]
谢谢 @chexiongsheng 我没注意到...
