### ISSUE TITLE
集成protobuffer -lua协议

### ISSUE THREAD

**Issue by LazyPlanet** [Tencent/xLua#90]
问个非框架性问题，lua5.3 是不是删除了module关键字，对于protobuffer -lua楼主知道什么好的解决方案吗？

另外，这个里面对int64_t 是怎么处理呢？

非常感谢。

**Comment by chexiongsheng** [comment]
xlua同时支持lua53和luajit版本的。
其实pb我不熟悉，我以前用msgpack居多。
如果pb那用了module，你又要用lua53版本的话，要么你看看有没支持lua53的pb，或者你自己动手改造下pb的让他支持lua53，或者可以加个兼容，让lua53支持module。

pb的int64_t，我印象中是转字符串。。当然，你也可以改掉，include i64lib.h后，有对应的64位api可以调用。

**Comment by LazyPlanet** [comment]
好的，多谢啦。
