### ISSUE TITLE
unity2020 Windows环境 ios平台 

### ISSUE THREAD

**Issue by bushbxj** [Tencent/xLua#907]
当我切换到ios的时候，即使在playersetting里面设置api compatibility level 为.net 4.x也还是会报下面的错
The type or namespace name 'ILGenerator' could not be found (are you missing a using directive or an assembly reference?)

**Comment by bushbxj** [comment]
是因为Windows切换ios的原因么？
同时我比较疑惑一个地方就是mac上面安装不了.net 4.x的吧，那如果在mac开发的话是否就用不了这个了（还是我理解错误0.0）

**Comment by chexiongsheng** [comment]
window切ios平台有啥用呢？

**Comment by bushbxj** [comment]
懂了
