### ISSUE TITLE
请问xLua是否支持多线程以及多虚拟机（非Unity环境）

### ISSUE THREAD

**Issue by Magicqy** [Tencent/xLua#913]
各位好，

已知xLua可以在非Unity环境运行，例如net core 写的console程序

最近有需求想使用xLua来制作一个独立程序，可以运行Lua脚本，并且使用C#代码编写扩展模块

这个程序想要能够同时创建并运行多个独立的Lua虚拟机环境，并且可在多线程中并发执行

想确认一下xLua官方版本是否已经支持了？
@chexiongsheng 

程序运行过程伪代码示意如下：
```
for i= 1, 100 do
  ls[i] = new LuaState()
end

for i = 1, 10 do
  new thread(function()
    while true do
      var i = random(1, 100)
      ls[i].tick()
    end
  end)
end
```

**Comment by chexiongsheng** [comment]
多虚拟机肯定支持，多线程加THREAD_SAFE宏编译，不过加了THREAD_SAFE后，同一个虚拟机多个线程会串行访问

**Comment by Magicqy** [comment]
明白了， 多线程串行访问也是一个比较合理的限制，感谢。
