### ISSUE TITLE
lua_newthread 对应的功能

### ISSUE THREAD

**Issue by jagt** [Tencent/xLua#92]
Hi.

感觉好像 xLua 没有封装 lua_newthread 以及其对应的功能，我们的用例里面这个用的比较多，老的 LuaInterface 也有 `LuaThread` 来对应这个 (刚刚特地看了下 nLua 好像也把这个去掉了)。

请问有考虑过实现这方面的功能吗？谢谢！

**Comment by chexiongsheng** [comment]
你们什么场景下需要用到这呢？

**Comment by chexiongsheng** [comment]
童鞋不回应我就close了啊？

我个人觉得在C#那直接new协程是一种错误的引导，貌似有用，其实容易用错，也没啥必要。
还记得LuaInterface的封装是不合理的，但怎么不合理就忘了，既然同一个作者的后续作品NLua去掉了，应该也是觉得不好。

**Comment by jagt** [comment]
@chexiongsheng 

不好意思之前过年去了...

我们的用例里面这个用的比较多，大概情况就是创建新的有自己栈的 thread，比如直接用 `coroutine.yield(xxx)` 把 `xxx` 传给 C# 然后做阻塞，满足条件的话再 resume 这个 thread。可能的确这个用的人比较少如果你这边短期没有做这个的打算可以先关掉了。后面如果真的要用到的话我会试试发一个 pr。

感谢回复！

**Comment by chexiongsheng** [comment]
你这也不需要通过C#层面开放协程相关接口就可以实现了。你在lua那封装好给C#使用就可以了
~~~lua
return  {
      co = coroutine.create(func);
      Resume = function(self, ...)
         local succ, ret = coroutine.resume(self.co, ...)
         if succ then return ret end
         error(ret)
    end
}
~~~
然后在C#那定义个接口来适配这个table
~~~csharp
public interface
{
    int Resume(int i};
}
~~~

**Comment by jagt** [comment]
我大概知道什么意思了，谢谢了。
