### ISSUE TITLE
Undefined symbols for architecture arm64: "_xlua_is_eq_str"

### ISSUE THREAD

**Issue by lulukdog** [Tencent/xLua#923]

**Comment by lulukdog** [comment]
I've met 111 errors about lua_xxx after exporting to Xcode and building.Xlua version is v2.1.15 
errors like bellow

Undefined symbols for architecture arm64:
  "_xlua_is_eq_str", referenced from:
      _Lua_xlua_is_eq_str_m6990D89A2872CFAA070684738360A43F4A4244FD in Assembly-CSharp5.o
      _Lua_xlua_is_eq_str_m7FCEA3805288EB6E8616D080D09F43D2F1003A12 in Assembly-CSharp5.o
     (maybe you meant: _Lua_xlua_is_eq_str_m7FCEA3805288EB6E8616D080D09F43D2F1003A12, _Lua_xlua_is_eq_str_m6990D89A2872CFAA070684738360A43F4A4244FD )

**Comment by chexiongsheng** [comment]
打包环境漏了xlua的库
