### ISSUE TITLE
你好，DoTween有些方法不能用，DOScale可以，DOAnchorPosX不可以，要报错，请问如何解决

### ISSUE THREAD

**Issue by a405457747** [Tencent/xLua#925]
环境：unity2019.4.1     xlua2.1.15     doTween1.2.632

报错信息： 
LuaException: C:/Users/SkyAllen/Desktop/YaoTianNeng/Framework3/Assets/Game/LuaFiles/ui/tipPanel.lua:17: attempt to call method 'DOAnchorPosX' (a nil value)
stack traceback:
	C:/Users/SkyAllen/Desktop/YaoTianNeng/Framework3/Assets/Game/LuaFiles/ui/tipPanel.lua:17: in function 'createTip'
	C:/Users/SkyAllen/Desktop/YaoTianNeng/Framework3/Assets/Game/LuaFiles/ui/tipPanel.lua:27: in function 'v'
	C:/Users/SkyAllen/Desktop/YaoTianNeng/Framework3/Assets/Game/LuaFiles/functions/event2.lua:50: in function 'sendEvent'
	C:/Users/SkyAllen/Desktop/YaoTianNeng/Framework3/Assets/Game/LuaFiles/root.lua:58: in function <C:/Users/SkyAllen/Desktop/YaoTianNeng/Framework3/Assets/Game/LuaFiles/root.lua:55>
XLua.LuaEnv.ThrowExceptionFromError (System.Int32 oldTop) (at Assets/XLua/Src/LuaEnv.cs:441)
XLua.DelegateBridge.Action[T1] (T1 p1) (at Assets/XLua/Src/GenericDelegateBridge.cs:43)
LuaMono.Update () (at Assets/Game/Scripts/LuaAbout/LuaMono.cs:111)

**Comment by a405457747** [comment]
已经解决了，在配置文件 [LuaCallCSharp] public static List<Type> LuaCallCSharp = new List<Type>()里面加入这些，具体是哪个我暂时也不清楚，反正乱加了很多，就可以了    


   typeof(DG.Tweening.Core.TweenerCore<Vector2, Vector2, DG.Tweening.Plugins.Options.VectorOptions>),
        typeof(DG.Tweening.Core.DOGetter<Vector2>),
        typeof(DG.Tweening.Core.DOSetter<Vector2>),
        typeof(DG.Tweening.Core.DOTweenComponent),
        typeof(DG.Tweening.Core.DOTweenUtils),
        typeof(DG.Tweening.Core.DOTweenExternalCommand),
        typeof(DG.Tweening.DOTweenModuleUI),
        typeof(DG.Tweening.Core.TweenerCore<float,float,DG.Tweening.Plugins.Options.VectorOptions>),

**Comment by Aersiterliu** [comment]
谢了兄弟 今天也碰到这个问题
