### ISSUE TITLE
怎么在多个LuaEnv之间获取table类型的全局变量

### ISSUE THREAD

**Issue by Domain** [Tencent/xLua#926]
我现在需要同时存在多个LuaEnv，还需要在lua代码中通过C#中转，相互获取对方的全局变量，现在发现通过LuaEnv.Global.Get获取全局变量时，如果是数字等简单类型时，看起来没问题，但是如果是lua的table，获取出来就无法使用了，有办法做到吗？
例如lua
a = 1
b = { a = 1 }
获取a没问题，获取b时，返回的可能时nil，或者b.a是nil

**Comment by chexiongsheng** [comment]
你从LuaEnv A获取到的LuaTable，然后在LuaEnv B那new一个LuaTable，一对对key value拷贝过去
