### ISSUE TITLE
打包时遇到Error:can not find delegate for XXXXX! try re-genertate code.

### ISSUE THREAD

**Issue by rhy2020** [Tencent/xLua#933]
使用目前最新的版本，
复现步骤
1、新建一个脚本目录，创建一个cs脚本和一个自定义程序集
测试代码
		using System.Collections;
		using System.Collections.Generic;
		using UnityEngine;
		using System.Net.Sockets;
		public class NewBehaviourScript : MonoBehaviour
		{
		    private void GateWayConnectCallBack(SocketError code)
		    {
		    }
		}
2、在hotfix中加标签
		    static List<string> Assemblys = new List<string>()
		    {
		        "Assembly-CSharp",
		        "TestAs"
		    };
		    [Hotfix]
		    public static List<Type> by_property
		    {
 		       get
		        {
    		        List<Type> result = new List<Type>();
  		          foreach (var assembly in Assemblys)
     		       {
       		         var types = Assembly.Load(assembly).GetTypes().ToList<Type>();
       		         result.AddRange(types);
     		       }
   		         return result;
  		      }
		    }
3、使用菜单 XLua->Examples->13_BuildFromCLI 进行打包
4、编辑器会报
Error:can not find delegate for NewBehaviourScript.GateWayConnectCallBack! try re-genertate code.
UnityEngine.Debug:Log(Object)
XLua.Hotfix:HotfixInject(String) (at Assets/XLua/Src/Editor/Hotfix.cs:1737)
XLua.MyCustomBuildProcessor:OnPostBuildPlayerScriptDLLs(BuildReport) (at Assets/XLua/Src/Editor/Hotfix.cs:1607)
UnityEditor.BuildPipeline:BuildPlayer(String[], String, BuildTarget, BuildOptions)
XLuaTest.BuildFromCLI:build(String, String) (at Assets/XLua/Examples/13_BuildFromCLI/Editor/BuildFromCLI.cs:43)
XLuaTest.BuildFromCLI:BuildFromUnityMenu() (at Assets/XLua/Examples/13_BuildFromCLI/Editor/BuildFromCLI.cs:19)

疑惑的地方:
1.编辑器中使用菜单的XLua->Hotfix Inject In Editor 时注入是成功的 使用ILSpy也可以看到dll中有注入，打包时缺报这个错误，并且打出的包中dll是没有注入的，只有Assembly-CSharp注入成功
2.XLua/Gen/DelegatesGensBridge.cs 中 也有适配的代码
        
		public void __Gen_Delegate_Imp54(object p0, System.Net.Sockets.SocketError p1)
		{
		#if THREAD_SAFE || HOTFIX_ENABLE
           		 lock (luaEnv.luaEnvLock)
           		 {
		#endif
                		RealStatePtr L = luaEnv.rawL;
                		int errFunc = LuaAPI.pcall_prepare(L, errorFuncRef, luaReference);
                		ObjectTranslator translator = luaEnv.translator;
               		       translator.PushAny(L, p0);
                		translator.Push(L, p1);
                		PCall(L, 2, 0, errFunc);
                		LuaAPI.lua_settop(L, errFunc - 1);
		#if THREAD_SAFE || HOTFIX_ENABLE
            }
		#endif
		}

**Comment by rhy2020** [comment]
问题找到了 Hotfix.cs 注入的时候 在调用 isSameType(TypeReference left, TypeReference right) 程序集的PublicKeyToken不一致导致
lr.Module.Assembly.FullName   "System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"
rr.Module.Assembly.FullName   "System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"

**Comment by rhy2020** [comment]
@chexiongsheng  查到问题了，luaevn的程序集与打包时的程序集不一致导致的，发了一个pull 
 https://github.com/Tencent/xLua/pull/934

**Comment by zahiwonder** [comment]
给力，碰到了类似的问题，你的解决方案给了我启发
