### ISSUE TITLE
最新android的so文件还是debug的

### ISSUE THREAD

**Issue by liuyi-13** [Tencent/xLua#935]
麻烦确认下
![image](https://user-images.githubusercontent.com/80743243/141425584-2065ac14-0313-426d-98e6-7f8b48a36c5f.png)

**Comment by chexiongsheng** [comment]
https://github.com/Tencent/xLua/releases/tag/v2.1.16_android_release_lib
这么？

**Comment by liuyi-13** [comment]
这个里面也不是release的
readelf -S  
出来有  .debug的字段

**Comment by chexiongsheng** [comment]
看大小是和之前没啥区别，可能还是debug版本
但问题所有已知的设置都设置成release了

**Comment by chexiongsheng** [comment]
ndk官网也是这么设置

**Comment by liuyi-13** [comment]
CMAKE_TOOLCHAIN_FILE用的是NDK目录的文件，
![image](https://user-images.githubusercontent.com/80743243/141440845-27200b76-5b60-493c-a7c3-b54f708fc244.png)
r15c的toolchain.cmake中默认带有debug用的-g
去掉-g后so文件大小能小不少，但是readelf还是有.debug

参考
https://zhuanlan.zhihu.com/p/72475595

**Comment by liuyi-13** [comment]
修改NDK目录 android-ndk-r15c/build/cmake/android.toolchain.cmake 415行
把-g换成-s   -把编译选项-g【调试】换成-s【裁剪符号文件】
![image](https://user-images.githubusercontent.com/80743243/141450048-944d6d9f-8562-4d30-b170-9c12f60b2e9c.png)

so文件大小能小不少，readelf也没有.debug
![image](https://user-images.githubusercontent.com/80743243/141450103-6d607dfb-d428-4686-880c-b63e4796cdbf.png)

**性能对比**
真机测试过，基本性能没有影响，只是so文件的大小区别，多了.debug的调试信息
