### ISSUE TITLE
能在同一个项目中使用多个xlua的实例么？且他们之间完全独立

### ISSUE THREAD

**Issue by remember-mo** [Tencent/xLua#939]
项目中想使用多个，但是发现第二个new的时候，会和前面创建的luaEnv有共享的内容

**Comment by chexiongsheng** [comment]
不会有共享内容。

**Comment by MoonSKTY** [comment]
> 

大佬你好，这里能麻烦解释下吗？我理解中，即使是不同的lua state，e默认不是共享global table的？

**Comment by MoonSKTY** [comment]
> 不会有共享内容。
大佬你好，这里能麻烦解释下吗？我理解中，即使是不同的lua state，e默认不是共享global table的？

**Comment by MoonSKTY** [comment]
> 不会有共享内容。


大佬你好，这里能麻烦解释下吗？我理解中，即使是不同的lua state，默认不是共享global table的么？

**Comment by chexiongsheng** [comment]
> > 不会有共享内容。
> 
> 大佬你好，这里能麻烦解释下吗？我理解中，即使是不同的lua state，默认不是共享global table的么？

一个lua虚拟机不等于一个lua state，lua state其实对应的是一个协程（一个虚拟机可有有很多协程，或者说lua state）。协程间是共享一些全局数据。
但xlua的实例对应的不是lua state，是lua虚拟机，他们间不共享全局数据。
