### ISSUE TITLE
是否可以丰富一下print的输出格式 

### ISSUE THREAD

**Issue by daaoling** [Tencent/xLua#94]
比如  2017-2-2-0:47 : [main.lua:1] helloworld  带错误的时候也可以提示在第几行，那个我是不是要求太多了。。。

**Comment by chexiongsheng** [comment]
Lua的原生print就没这东东，没必要改lua默认的东西。你需要这功能自己扩展一下就可以了，几行代码，查询下debug库的文档。

**Comment by daaoling** [comment]
好吧
