### ISSUE TITLE
关于在linux下编译lua问题

### ISSUE THREAD

**Issue by RainStar1989511** [Tencent/xLua#95]
你好：
我在linux下配置好了jdk和ndk后，然后想测试编译一下make_android_lua53.sh文件
结果出现了找不到cmake的文件夹，如下图
![image](https://cloud.githubusercontent.com/assets/17958662/22585694/03f6db32-ea34-11e6-9383-825acd14848b.png)
这个是我修改该文件的配置
![image](https://cloud.githubusercontent.com/assets/17958662/22585731/31adb2f8-ea34-11e6-91b3-9762f622e763.png)
我只修改了NDK的路径，其余的都没有作改动，请问这个是怎么回事呢?

**Comment by chexiongsheng** [comment]
你没安装cmake
