### ISSUE TITLE
考虑支持teal语言吗？

### ISSUE THREAD

**Issue by uniqss** [Tencent/xLua#958]
https://github.com/teal-language/tl
强类型lua，测了一下内嵌方式运行，基本可用，不过还有很多周边工作要完善。xlua有考虑过支持teal语言不？强类型对大项目的益处是非常明显的

**Comment by chexiongsheng** [comment]
语言的选择要考虑其生态。
个人觉得这还不如一些typescript 转lua的方案呢。

**Comment by uniqss** [comment]
好吧，ts的话就不用转了，直接puerts了，，，哎，国内前端啥时候才能广泛应用强类型啊，哪怕不是ts是其他语言
