### ISSUE TITLE
LuaException: c# exception:error loading module 'emmy_core' from file '/Users/username/Library/Application Support/JetBrains/Rider2021.2/plugins/EmmyLua/classes/debugger/emmy/mac/emmy_core.dylib':

### ISSUE THREAD

**Issue by BillScott1024** [Tencent/xLua#960]
xLua: v2.1.15
Mac: 11.4
Unity：2019.4.26f1

使用 Emmy Debugger(NEW) 调试吗，Lua 文件头引入

```

package.cpath = package.cpath .. ';/Users/username/Library/Application Support/JetBrains/Rider2021.2/plugins/EmmyLua/classes/debugger/emmy/mac/?.dylib'
local dbg = require('emmy_core')
dbg.tcpConnect('localhost', 9966)

```

开启调试报错，无法进入断点，界面报错逻辑无法继续运行：
```

LuaException: c# exception:error loading module 'emmy_core' from file '/Users/username/Library/Application Support/JetBrains/Rider2021.2/plugins/EmmyLua/classes/debugger/emmy/mac/emmy_core.dylib':
	dynamic libraries not enabled; check your Lua installation
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	[string "UIPageNew"]:2: in main chunk
	[C]: in method 'PushPage'

```

报错截图

![image](https://user-images.githubusercontent.com/22955480/150717723-5d3a6d92-c4aa-43a7-8ac0-dea773a88ca3.png)

emmy_core文件路径正确：

![image](https://user-images.githubusercontent.com/22955480/150717946-fad27e14-32d3-4275-b0e5-3b2279c7fc10.png)

**Comment by chexiongsheng** [comment]
？
不是应该找Emmy插件维护者么？

**Comment by BillScott1024** [comment]
> ？ 不是应该找Emmy插件维护者么？

因为我在这个项目的 issue 里面找到的 closed 的类似的问题，你提供了解决方案，但是还是会出现相同的问题，我就在这里提了：
![20220128153343](https://user-images.githubusercontent.com/22955480/151505983-8f7a1fa1-3f3b-4639-b0f0-261f1ef49181.jpg)
![20220128153353](https://user-images.githubusercontent.com/22955480/151505999-c503edf8-cab6-4e36-a30f-0f293e087114.jpg)

**Comment by chexiongsheng** [comment]
同一原因直接按那个issue不就可以了么？

**Comment by BillScott1024** [comment]
> 同一原因直接按那个issue不就可以了么？

就是无法解决问题，才提新的 issue 的。。那个 issue 后面也都是反馈了无法解决
