### ISSUE TITLE
unity for m1 版 dll注册失败

### ISSUE THREAD

**Issue by mtmtraveler** [Tencent/xLua#966]
在unity 2021.2.11 m1 版不支持
xlua assembly:<unknown assembly> type:<unknown type> member:(null)

**Comment by DZRgogogo** [comment]
同样啊，是不支持吗

**Comment by chexiongsheng** [comment]
需要自己在M1上编译库，然后放特定的位置。你翻翻之前，有issue提到怎么弄

**Comment by DZRgogogo** [comment]
经过测试，用在2019.4.17正常，在2021以后版本的就会出现这个问题

**Comment by DZRgogogo** [comment]
> 需要自己在M1上编译库，然后放特定的位置。你翻翻之前，有issue提到怎么弄

谢谢啦
