### ISSUE TITLE
C# 调用require后，竟然获取不到脚本中return的对象？？？

### ISSUE THREAD

**Issue by JiekeZhu** [Tencent/xLua#974]
// TestObject.lua.txt 中 return {}
var results = _lua.DoString(@"require 'TestObject'");
结果，results为null，这是怎么回事？走require流程，获取组件，这不是正常流程么？

**Comment by throw-out** [comment]
> // TestObject.lua.txt 中 return {} var results = _lua.DoString(@"require 'TestObject'"); 结果，results为null，这是怎么回事？走require流程，获取组件，这不是正常流程么？

var results = _lua.DoString(@"return require 'TestObject'");
