### ISSUE TITLE
Hotfix Demo Exception in Unity 5.5.0p3 64bit 

### ISSUE THREAD

**Issue by xbhuang1994** [Tencent/xLua#98]
我运行HotfixTest Examples场景，出现以下错误：
![image](https://cloud.githubusercontent.com/assets/6432896/22771252/946a363c-eed0-11e6-9d2d-f4f24b97e3a3.png)

**Comment by chexiongsheng** [comment]
看下FAQ

**Comment by xbhuang1994** [comment]
thinks，问题已解决
建议在提示错误处加入一条链接：https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/hotfix.md
